BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "{CHN}训练家需要什么……\p"
	.string "知识……\n"
	.string "策略……\l"
	.string "运气……\l"
	.string "胆量……\l"
	.string "精神……\l"
	.string "勇气……\l"
	.string "还有实力……\p"
	.string "嗯，我每样都具备了！\n"
	.string "我在每座设施都将所向披靡！\p"
	.string "啊？宝可梦？\n"
	.string "那是什么？$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "{CHN}你知道开拓区首领吗？\p"
	.string "那是亚希达对运行对战开拓区\n"
	.string "七座设施的七位特别训练家\l"
	.string "的称呼。$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "{CHN}在对战塔，一位大姐姐\n"
	.string "告诉我我在对战方面\l"
	.string "很有天赋！\p"
	.string "但我更喜欢宝可梦华丽大赛！\p"
	.string "可是我在华丽大赛上又不行！\p"
	.string "我想，有天赋和喜欢某件事\n"
	.string "并不是一回事吧。$"

