SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "{CHN}琉璃市和送神山之间\n"
	.string "似乎有某种联系。\p"
	.string "我和朋友们以前在工作的\n"
	.string "实验室里研究过这个。$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "{CHN}我哥哥以前研究过海洋。$"

