RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "{CHN}训练家学校非常优秀.\p"
	.string "如果你在那里学习，甚至\n"
	.string "可以成为道馆馆主.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "{CHN}杜娟，道馆馆主，真的非常\n"
	.string "了解宝可梦.\p"
	.string "她也真的很强！$"

