gText_ApprenticeChallenge0::
	.string "{CHN}嗯，我是{STR_VAR_1}的第{STR_VAR_2}号学徒。\n"
	.string "抽噎……这种紧张感真让人受不了……$"

gText_ApprenticeChallenge1::
	.string "{CHN}我是{STR_VAR_1}的第{STR_VAR_2}号学徒！\n"
	.string "我们开始吧！$"

gText_ApprenticeChallenge2::
	.string "{CHN}我是{STR_VAR_1}的第{STR_VAR_2}号学徒！\n"
	.string "请接受我的挑战！$"

gText_ApprenticeChallenge3::
	.string "{CHN}嗯……我是{STR_VAR_1}的第{STR_VAR_2}号学徒……\n"
	.string "您觉得像我这样的人能赢吗？$"

gText_ApprenticeChallenge4::
	.string "{CHN}我是{STR_VAR_1}的第{STR_VAR_2}号学徒！\n"
	.string "就让我来挑战您吧！$"

gText_ApprenticeChallenge5::
	.string "{CHN}我忙得要命，不过我恰好也是\n"
	.string "{STR_VAR_1}的第{STR_VAR_2}号学徒。$"

gText_ApprenticeChallenge6::
	.string "{CHN}我是{STR_VAR_1}的第{STR_VAR_2}号学徒。\n"
	.string "很高兴见到您！$"

gText_ApprenticeChallenge7::
	.string "{CHN}我担任{STR_VAR_1}的第{STR_VAR_2}号学徒。\n"
	.string "可以开始了吗？$"

gText_ApprenticeChallenge8::
	.string "{CHN}呀！我是{STR_VAR_1}的第{STR_VAR_2}号学徒！\n"
	.string "我会加油的！$"

gText_ApprenticeChallenge9::
	.string "{CHN}嘿咻！我是{STR_VAR_1}的第{STR_VAR_2}号学徒！\n"
	.string "放马过来吧！$"

gText_ApprenticeChallenge10::
	.string "{CHN}我是{STR_VAR_1}的第一千号学徒！\n"
	.string "其实，我是第{STR_VAR_2}号！开始吧！$"

gText_ApprenticeChallenge11::
	.string "{CHN}没错，我是{STR_VAR_1}的第{STR_VAR_2}号学徒！\n"
	.string "让我们热闹起来吧！$"

gText_ApprenticeChallenge12::
	.string "{CHN}好耶！我就是所谓的\n"
	.string "{STR_VAR_1}的第{STR_VAR_2}号学徒！$"

gText_ApprenticeChallenge13::
	.string "{CHN}咳咳！我是{STR_VAR_1}的第{STR_VAR_2}号学徒。\n"
	.string "见到您很高兴！咳咳！$"

gText_ApprenticeChallenge14::
	.string "{CHN}真让人紧张……\n"
	.string "我是{STR_VAR_1}的第{STR_VAR_2}号学徒。$"

gText_ApprenticeChallenge15::
	.string "{CHN}我是{STR_VAR_1}的第{STR_VAR_2}号学徒，\n"
	.string "这可不是说谎。$"

gText_ApprenticePleaseTeach0::
	.string "{CHN}您是……{PLAYER}吗？\n"
	.string "啊！抽泣……呜呜……\p"
	.string "啊！对、对不起……\n"
	.string "我太紧张了，忍不住哭了起来……\p"
	.string "我是{STR_VAR_1}，我真的非常\n"
	.string "崇拜您，{PLAYER}。\p"
	.string "我……我一直梦想着有朝一日能见到\n"
	.string "您，向您请教关于宝可梦的事。\p"
	.string "求求您，求求您，{PLAYER}！\n"
	.string "请教教我关于宝可梦的事吧！$"

gText_ApprenticeRejectTeaching0::
	.string "{CHN}啊……可、可是……\n"
	.string "抽噎……呜哇啊啊啊！\p"
	.string "求求您！\n"
	.string "我求您了，拜托！$"

gText_ApprenticeWhichLevelMode0::
	.string "{CHN}哦，真的吗？您愿意？\n"
	.string "太棒了！太厉害了！呜吼！\p"
	.string "啊……对不起……\n"
	.string "我太高兴了，又哭了起来……\p"
	.string "嗯……那就请您告诉我！\n"
	.string "是关于对战塔的事。\p"
	.string "对我来说哪个更好：50级\n"
	.string "还是开放等级？$"

gText_ApprenticeLevelModeThanks0::
	.string "{CHN}{STR_VAR_1}吗？\n"
	.string "呜哇啊啊啊！\p"
	.string "啊！真对不起！\n"
	.string "您帮我选了等级，我高兴得\l"
	.string "又哭了起来……\p"
	.string "抽噎……\n"
	.string "太感谢您了！\l"
	.string "请再和我聊聊吧！$"

gText_ApprenticePleaseTeach1::
	.string "{CHN}哇！您是{PLAYER}，对吧？\n"
	.string "您超级厉害，对不对？\p"
	.string "我是{STR_VAR_1}！\n"
	.string "我刚成为训练家！\p"
	.string "拜托了，{PLAYER}！\n"
	.string "您能当我的老师，告诉我\l"
	.string "好多关于当训练家的事吗？$"

gText_ApprenticeRejectTeaching1::
	.string "{CHN}哎呀，为什么？\n"
	.string "哦，拜托嘛？求求您了？\l"
	.string "请当我的老师吧，求您了！$"

gText_ApprenticeWhichLevelMode1::
	.string "{CHN}好耶！太棒了！\p"
	.string "我想问您的第一件事\n"
	.string "是关于对战塔的！\p"
	.string "50级和开放等级房间……\n"
	.string "哪个最适合我呢？$"

gText_ApprenticeLevelModeThanks1::
	.string "{CHN}{STR_VAR_1}啊，没错！\n"
	.string "我会加油的！\p"
	.string "如果我们再在这里见面，请再教\n"
	.string "我点别的吧，老师！$"

gText_ApprenticePleaseTeach2::
	.string "{CHN}嗯……您是{PLAYER}吗？\n"
	.string "我叫{STR_VAR_1}。\p"
	.string "我想成为一名宝可梦训练家，\n"
	.string "但我不知道该怎么做……\p"
	.string "所以我想也许可以向您请教，\n"
	.string "因为您那么有名。\p"
	.string "{PLAYER}，您能给我一些建议吗？$"

gText_ApprenticeRejectTeaching2::
	.string "{CHN}哦，可是……\p"
	.string "我真心想成为一名宝可梦\n"
	.string "训练家！\p"
	.string "求求您，能回答我的问题吗？$"

gText_ApprenticeWhichLevelMode2::
	.string "{CHN}谢谢您！\n"
	.string "我马上就有第一个问题了！\p"
	.string "对战塔有两个等级，\n"
	.string "50级和开放等级，对吧？\p"
	.string "您觉得哪个等级\n"
	.string "更适合我呢？$"

gText_ApprenticeLevelModeThanks2::
	.string "{CHN}哦，挑战{STR_VAR_1}吗？\n"
	.string "明白了！\p"
	.string "如果我有其他问题，我会\n"
	.string "再回来向您请教的！$"

gText_ApprenticePleaseTeach3::
	.string "{CHN}哦？咦？您是……\n"
	.string "不，那不可能是真的。\p"
	.string "像我这样的人\n"
	.string "怎么可能遇到{PLAYER}。\p"
	.string "……您真的是{PLAYER}？\n"
	.string "我不敢相信在和您说话！\p"
	.string "当这种好事发生时，\n"
	.string "接下来一定会有可怕的事降临\l"
	.string "到我身上，我就知道……\p"
	.string "……对不起……\n"
	.string "我是……{STR_VAR_1}……\p"
	.string "我没有什么特别的\n"
	.string "值得骄傲的地方……\p"
	.string "我甚至不该说关于\n"
	.string "自己的事，因为您会忘记的……\p"
	.string "我曾梦想着如果有一天能遇见\n"
	.string "您，{PLAYER}，也许我可以请您\l"
	.string "作为训练家给我一些建议。\p"
	.string "但我觉得您不会\n"
	.string "答应的。\p"
	.string "……还是说，您愿意好心\n"
	.string "给我建议呢？$"

gText_ApprenticeRejectTeaching3::
	.string "{CHN}我就知道……\p"
	.string "一定会的，因为我就是\n"
	.string "这么一个无聊的无名小卒……\p"
	.string "但我还是想着也许……\n"
	.string "您不会再考虑一下吗？\p"
	.string "但我不能就这样放弃。\n"
	.string "趁着我还有运气，我要再问您一次！\p"
	.string "求求您，您愿意好心\n"
	.string "给我建议吗？$"

gText_ApprenticeWhichLevelMode3::
	.string "{CHN}真的吗？我不敢相信！\n"
	.string "不敢相信您会指导我！\l"
	.string "我……我好高兴……\p"
	.string "我想问您的其实\n"
	.string "是件小事，但我决定不了……\p"
	.string "在对战塔，他们让您\n"
	.string "选择50级或开放等级。\p"
	.string "您觉得哪种级别连我\n"
	.string "也有机会呢？$"

gText_ApprenticeLevelModeThanks3::
	.string "{CHN}{STR_VAR_1}吗？好的！\n"
	.string "但您真的觉得像我\l"
	.string "这样的人会有机会吗？\p"
	.string "我会加油的，虽然我觉得\n"
	.string "不会有什么用。\p"
	.string "非常感谢您花时间\n"
	.string "陪像我这样的人。$"

gText_ApprenticePleaseTeach4::
	.string "{CHN}哦！您是{PLAYER}{KUN}，对吧？\p"
	.string "我听说您在\n"
	.string "宝可梦方面很厉害！\p"
	.string "我是{STR_VAR_1}！\n"
	.string "我们交个朋友吧！\p"
	.string "您知道吗？\p"
	.string "如果只懂训练家学校教的那些，\n"
	.string "是无法在对战开拓区\l"
	.string "获胜的。\p"
	.string "我愿意听您的建议。\n"
	.string "您当然会答应吧？$"

gText_ApprenticeRejectTeaching4::
	.string "{CHN}咦？您为什么要拒绝我？\n"
	.string "是我在求您啊！\l"
	.string "您得再考虑一下！$"

gText_ApprenticeWhichLevelMode4::
	.string "{CHN}好，有这么一件事。\n"
	.string "我想让您替我决定。\p"
	.string "您知道对战塔有\n"
	.string "50级和开放等级房间吗？\p"
	.string "您觉得哪个对我\n"
	.string "比较合适，{PLAYER}{KUN}？$"

gText_ApprenticeLevelModeThanks4::
	.string "{CHN}好的，{STR_VAR_1}对我合适？\n"
	.string "谢谢！\p"
	.string "知道是您做的决定，\n"
	.string "{PLAYER}{KUN}，即使输了\l"
	.string "我也不会那么难过。\p"
	.string "好，我会再向您请教的。\n"
	.string "再见！$"

gText_ApprenticePleaseTeach5::
	.string "{CHN}哦，嗨！{PLAYER}{KUN}！\n"
	.string "我知道您，因为您很有名！\l"
	.string "叫我{STR_VAR_1}吧！很高兴见到您！\p"
	.string "我是个铁人三项运动员，所以即使\n"
	.string "培育宝可梦，我也保持健身。\p"
	.string "我还忙着其他事，\n"
	.string "比如工作、打盹、交际舞……\p"
	.string "这么忙，要成为一名\n"
	.string "出色的训练家可不容易。\p"
	.string "所以，我有个提议！\p"
	.string "我们相遇一定有原因。\n"
	.string "所以，{PLAYER}{KUN}，您看每隔一阵\l"
	.string "和我分享您的智慧如何？$"

gText_ApprenticeRejectTeaching5::
	.string "{CHN}哦，可是，拜托嘛？\n"
	.string "像我这样的家伙需要\l"
	.string "您这样的人，{PLAYER}{KUN}！\p"
	.string "说真的，我需要您的建议！$"

gText_ApprenticeWhichLevelMode5::
	.string "{CHN}谢谢！这才像话！\n"
	.string "那，先来个简单的！\p"
	.string "您知道对战塔的\n"
	.string "两个级别吧？\l"
	.string "就是50级和开放等级。\p"
	.string "我这个大忙人，应该\n"
	.string "为哪个做准备呢？$"

gText_ApprenticeLevelModeThanks5::
	.string "{CHN}{STR_VAR_1}啊，好的，明白。\n"
	.string "我会想办法抽空去试试！\p"
	.string "……哎呀，我得去上班了！\n"
	.string "谢谢！回头见！$"

gText_ApprenticePleaseTeach6::
	.string "{CHN}不会吧！不会吧！\n"
	.string "您也许就是真正的{PLAYER}？\p"
	.string "啊哈！太棒了！我是{STR_VAR_1}，\n"
	.string "很高兴见到您！\p"
	.string "{PLAYER}，您非常强，\n"
	.string "对吧？\p"
	.string "大家都在谈论您！\p"
	.string "哦！我刚有个绝妙的主意！\n"
	.string "我要向您请教，{PLAYER}！\l"
	.string "我相信这会让我变得更强！\p"
	.string "这不是个好主意吗？\n"
	.string "拜托，我想要您的建议！$"

gText_ApprenticeRejectTeaching6::
	.string "{CHN}啊哈哈，您可以装作很凶，\n"
	.string "但您骗不了我！\l"
	.string "您其实是说好的，对吧？$"

gText_ApprenticeWhichLevelMode6::
	.string "{CHN}好耶！我就知道您心胸宽广，\n"
	.string "{PLAYER}！\p"
	.string "我该先问您什么呢？\n"
	.string "……哦，我想到了！\p"
	.string "请敲鼓伴奏！\n"
	.string "我的问题是……\p"
	.string "如果我要挑战对战塔，\n"
	.string "我该走哪条路？\p"
	.string "50级还是开放等级？\n"
	.string "哪个更适合我？$"

gText_ApprenticeLevelModeThanks6::
	.string "{CHN}哦哦哦！\n"
	.string "您说是{STR_VAR_1}！\l"
	.string "谢谢您超酷的回答！\p"
	.string "我想今天我想问\n"
	.string "您的就这些了。\p"
	.string "我们再在这里见面吧，好吗？\n"
	.string "谢谢！$"

gText_ApprenticePleaseTeach7::
	.string "{CHN}打扰了，请问……\n"
	.string "您是{PLAYER}吗？\p"
	.string "我是{STR_VAR_1}，很高兴\n"
	.string "能认识您。\p"
	.string "我长久以来\n"
	.string "一直是您的崇拜者……\p"
	.string "…… …… …… …… …… ……\p"
	.string "嗯……希望您不觉得\n"
	.string "这个请求太过唐突，但是……\p"
	.string "我可以成为您的学徒吗，\n"
	.string "{PLAYER}？$"

gText_ApprenticeRejectTeaching7::
	.string "{CHN}啊……！\p"
	.string "…… …… …… …… …… ……\n"
	.string "…… …… …… …… …… ……\p"
	.string "……我一定是震惊得晕过去了。\n"
	.string "对不起，我一定是听错了。\p"
	.string "求求您！请您说您愿意\n"
	.string "收我做学徒吧！$"

gText_ApprenticeWhichLevelMode7::
	.string "{CHN}啊……我太高兴了！\p"
	.string "我不想浪费您的时间，\n"
	.string "所以请就这件事给我建议。\p"
	.string "我打算不久后\n"
	.string "挑战对战塔。\p"
	.string "然而，有两个等级……\p"
	.string "哪个最适合我呢？\n"
	.string "50级还是开放等级？$"

gText_ApprenticeLevelModeThanks7::
	.string "{CHN}您选的是{STR_VAR_1}！\n"
	.string "我明白了。我会尽力的！\p"
	.string "谢谢您，{PLAYER}。\n"
	.string "希望还能继续依靠您。\l"
	.string "请多保重！$"

gText_ApprenticePleaseTeach8::
	.string "{CHN}呀！呀！{PLAYER}！\n"
	.string "您和我说话了！\l"
	.string "我……我太高兴了！\p"
	.string "我！我叫{STR_VAR_1}！\n"
	.string "我刚成为训练家！\p"
	.string "能遇见您真是太好了，{PLAYER}，\n"
	.string "宝可梦界的大名人！\p"
	.string "哦哦哦，我知道了！\n"
	.string "我可以请您帮个大忙吗，{PLAYER}？\p"
	.string "请收我做您的学徒吧！\n"
	.string "我想向您学习！$"

gText_ApprenticeRejectTeaching8::
	.string "{CHN}呜哇啊啊！\n"
	.string "{PLAYER}拒绝了我……\l"
	.string "这……这是宝贵的经验！\p"
	.string "{PLAYER}，求求您！这次\n"
	.string "我想听到肯定的回答！\p"
	.string "求您指导我！$"

gText_ApprenticeWhichLevelMode8::
	.string "{CHN}嘿咿咿！{PLAYER}答应了！\n"
	.string "{PLAYER}答应了！\p"
	.string "我今晚都睡不着了……\n"
	.string "实在太感谢您了！\p"
	.string "那么，这是我的问题！\p"
	.string "在对战塔，对我来说\n"
	.string "哪个合适，50级还是开放等级？$"

gText_ApprenticeLevelModeThanks8::
	.string "{CHN}{STR_VAR_1}！完全明白！\n"
	.string "我完全明白了！\l"
	.string "我高兴得不得了！\p"
	.string "希望您以后还愿意\n"
	.string "再教我一些。$"

gText_ApprenticePleaseTeach9::
	.string "{CHN}哇哦！您该不会是……\n"
	.string "您莫非是……{PLAYER}{KUN}？！\l"
	.string "那位又强又出名的训练家？\l"
	.string "哎呀，您好，我可真幸运！\p"
	.string "您好，我叫{STR_VAR_1}！\p"
	.string "我一直在\n"
	.string "寻找宝可梦老师。\p"
	.string "而您恰好在这时出现了，\n"
	.string "{PLAYER}{KUN}！\p"
	.string "所以，就这么定了，{PLAYER}{KUN}！\n"
	.string "让我做您的学徒吧！$"

gText_ApprenticeRejectTeaching9::
	.string "{CHN}哇啊啊啊！\n"
	.string "您可真酷、真硬派……\p"
	.string "别这样嘛，拜托了。\n"
	.string "我在求您啊！$"

gText_ApprenticeWhichLevelMode9::
	.string "{CHN}哦，对！这回答真干脆！\n"
	.string "出色，我得说！\p"
	.string "那关于对战塔，\n"
	.string "给我第一份建议如何？\p"
	.string "如果我去的话，哪个更好？\n"
	.string "50级还是开放等级？$"

gText_ApprenticeLevelModeThanks9::
	.string "{CHN}嗯哼，就{STR_VAR_1}了！\n"
	.string "好，很好！\l"
	.string "我会去露一手的，砰！\p"
	.string "好，我会把您当作我的导师！\n"
	.string "再见！$"

gText_ApprenticePleaseTeach10::
	.string "{CHN}哦，嘿，您是{PLAYER}{KUN}吧？\n"
	.string "警察在找您呢！\p"
	.string "…… …… ……\n"
	.string "我当然在撒谎！\p"
	.string "我是{STR_VAR_1}。别看我这样，\n"
	.string "我可是宝可梦冠军！\l"
	.string "……那也是撒谎！\p"
	.string "不过，这不是谎言。\n"
	.string "我不太擅长对战。\p"
	.string "所以，您来当我的师傅，\n"
	.string "教我关于宝可梦的一切如何？$"

gText_ApprenticeRejectTeaching10::
	.string "{CHN}如果您要这么冷淡的话，\n"
	.string "我给您看看我会怎么做！\p"
	.string "哇啊！哇啊！哇啊！\n"
	.string "打嗝！\p"
	.string "哈哈哈，那是我的假哭！\p"
	.string "拜托嘛，您就当我的\n"
	.string "宝可梦师傅吧？$"

gText_ApprenticeWhichLevelMode10::
	.string "{CHN}好耶！\n"
	.string "为此我要给您买艘游艇！\p"
	.string "我当然又在撒谎啦！\n"
	.string "不过……谢谢您，师傅！\p"
	.string "您知道对战塔有50级和\n"
	.string "开放等级吧？\p"
	.string "我正为该挑战哪个\n"
	.string "等级而烦恼……\p"
	.string "您能替我决定吗，师傅？$"

gText_ApprenticeLevelModeThanks10::
	.string "{CHN}好的，{STR_VAR_1}更好！\n"
	.string "那我去另一个等级！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "谢谢，师傅！\n"
	.string "希望您继续教我！$"

gText_ApprenticePleaseTeach11::
	.string "{CHN}A-H-O-Y！\n"
	.string "这拼起来就是ahoy，意思就是你好！\p"
	.string "我是{STR_VAR_1}，是说唱水手，\n"
	.string "就是我！\p"
	.string "现在轮到您，告诉我一点关于\n"
	.string "您自己的事，试试看！\p"
	.string "嗯哼，嗯哼！\n"
	.string "{PLAYER}{KUN}是您的名，\l"
	.string "宝可梦是您的戏！\p"
	.string "您正处于微妙的年纪，\n"
	.string "全世界都是您的舞台！\p"
	.string "总之，我只想说，\n"
	.string "您是我今天说话的\l"
	.string "第十位训练家。\p"
	.string "让我们庆祝一番！\n"
	.string "为了纪念，做我的导师吧！$"

gText_ApprenticeRejectTeaching11::
	.string "{CHN}可是！\n"
	.string "您得配合我呀！\p"
	.string "别这么捉弄人！\n"
	.string "做我的导师吧，拜托！$"

gText_ApprenticeWhichLevelMode11::
	.string "{CHN}就是这个！\n"
	.string "{PLAYER}，您真有精神！\p"
	.string "那这是我的第一个问题，\n"
	.string "正等着您的建议！\p"
	.string "是关于对战塔的，\n"
	.string "取决于我的力量！\p"
	.string "那里有50级和开放等级，\n"
	.string "哪个对我才合适？$"

gText_ApprenticeLevelModeThanks11::
	.string "{CHN}好的，您说就是{STR_VAR_1}！\n"
	.string "我这就上路去挑战！\p"
	.string "如果我需要建议，\n"
	.string "{PLAYER}，我会一直听您的话！$"

gText_ApprenticePleaseTeach12::
	.string "{CHN}嘿，您不是{PLAYER}吗？\n"
	.string "我该怎么办？和您说话？\l"
	.string "有何不可？我都在和您说话了！\p"
	.string "{PLAYER}，您对我感到惊讶吗？\n"
	.string "我最好告诉您我是谁！\p"
	.string "{STR_VAR_1}是您可以叫我的名字。\n"
	.string "吉他界最闪亮的明星，\l"
	.string "就是我！\p"
	.string "您听明白了吗？\n"
	.string "您听明白了！\p"
	.string "我的运气到了顶峰，\n"
	.string "我要向您提个请求！\p"
	.string "{PLAYER}，让我做您的小弟吧！\n"
	.string "我想让您教我一切！$"

gText_ApprenticeRejectTeaching12::
	.string "{CHN}那您是拒绝我了？\n"
	.string "我只好再问您一次！\p"
	.string "{PLAYER}，我求您让我做小弟！\n"
	.string "我需要您教我一切！$"

gText_ApprenticeWhichLevelMode12::
	.string "{CHN}幸运，耶，呜呼！\n"
	.string "我该向您抛个问题吗？\p"
	.string "既然我们在对战塔附近，\n"
	.string "就问个关于它的问题如何？\p"
	.string "在您看到的选项中，\n"
	.string "哪个对我才合适？$"

gText_ApprenticeLevelModeThanks12::
	.string "{CHN}如果您建议的是{STR_VAR_1}，\n"
	.string "那一定是最好的！\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticePleaseTeach13::
	.string "{CHN}哦，嗨！您那边！\n"
	.string "能帮我按按肩膀吗？\p"
	.string "……对，就那里！就是那里！\n"
	.string "哎哟，哎哟！哦哦，好舒服！\p"
	.string "我叫{STR_VAR_1}。\n"
	.string "我在练空手道，但我的身体\l"
	.string "经不起那种折腾……\p"
	.string "我决定要和宝可梦对战，\n"
	.string "让自己变强壮。\p"
	.string "您是{PLAYER}{KUN}，对吧？\n"
	.string "宝可梦联盟冠军？\p"
	.string "听着，您能给我\n"
	.string "一些建议吗？$"

gText_ApprenticeRejectTeaching13::
	.string "{CHN}哦，为什么？\p"
	.string "我不会太添麻烦的，我保证！\n"
	.string "拜托嘛？$"

gText_ApprenticeWhichLevelMode13::
	.string "{CHN}谢谢。您真好！\n"
	.string "……咳咳！咳咳！\p"
	.string "呜，我得快点变强壮……\p"
	.string "我马上就去对战塔，\n"
	.string "但哪个对我更合适\l"
	.string "呢？50级还是开放等级？$"

gText_ApprenticeLevelModeThanks13::
	.string "{CHN}嗯，好的。就是{STR_VAR_1}。\n"
	.string "我马上就去那里。\p"
	.string "希望我能继续\n"
	.string "找您帮忙——毕竟，您是我的导师！$"

gText_ApprenticePleaseTeach14::
	.string "{CHN}呃……嗯……\n"
	.string "{PLAYER}{KUN}……？\p"
	.string "请不要那样看我。\n"
	.string "您让我都不好意思了。\p"
	.string "我……我是{STR_VAR_1}。\p"
	.string "说起来真不好意思，\n"
	.string "我探索古代遗迹之类的。\p"
	.string "更不好意思承认的是\n"
	.string "我对对战开拓区感兴趣。\p"
	.string "{PLAYER}{KUN}，您有\n"
	.string "强悍训练家的名声……\p"
	.string "这话难以启齿，\n"
	.string "但我想拜托您一件事。\p"
	.string "您能当我的老师，\n"
	.string "给我建议吗？$"

gText_ApprenticeRejectTeaching14::
	.string "{CHN}请您别这样打发我！\n"
	.string "我受不了这种羞辱。\p"
	.string "请当我的老师吧！\n"
	.string "我需要您的建议！$"

gText_ApprenticeWhichLevelMode14::
	.string "{CHN}谢、谢谢……\p"
	.string "但请不要那样看我。\n"
	.string "那会让我心慌意乱。\p"
	.string "请您不要看着我的眼睛，\n"
	.string "回答我吧。\p"
	.string "在对战塔……\n"
	.string "我该挑战哪个等级？$"

gText_ApprenticeLevelModeThanks14::
	.string "{CHN}哦……好的！\n"
	.string "我会试试那个。\p"
	.string "希望我能从容地挑战，\n"
	.string "不会心慌意乱……\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "如果我们再见面，希望您\l"
	.string "还能这么帮忙。$"

gText_ApprenticePleaseTeach15::
	.string "{CHN}嗯？您似乎是{PLAYER}{KUN}……\n"
	.string "但您是真的吗？\p"
	.string "您可以叫我{STR_VAR_1}。\p"
	.string "我一直在考虑\n"
	.string "拜一位强悍的训练家为师。\p"
	.string "所以，您出现得真是幸运！\n"
	.string "……您真的是{PLAYER}{KUN}吧？\p"
	.string "不，不，如果您是真的，那没问题。\n"
	.string "我只是希望您能认可我\l"
	.string "作为您的学徒。$"

gText_ApprenticeRejectTeaching15::
	.string "{CHN}哦？\n"
	.string "可您为什么要拒绝呢？\p"
	.string "我对您的身份\n"
	.string "表示怀疑，为此我道歉。\p"
	.string "请接受我的道歉，\n"
	.string "并收我做学徒吧。$"

gText_ApprenticeWhichLevelMode15::
	.string "{CHN}您真的要收我？\n"
	.string "我不愿过早庆祝。\p"
	.string "如果这是真的，我道歉。\n"
	.string "不过，我需要您的建议。\p"
	.string "如果我要进入对战塔，\n"
	.string "什么才配得上我？\l"
	.string "50级还是开放等级？$"

gText_ApprenticeLevelModeThanks15::
	.string "{CHN}{STR_VAR_1}吗？\n"
	.string "您确定吗？\p"
	.string "我明白了。既然如此，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我知道我可能让人烦，但您\n"
	.string "收下我，让我很高兴。\p"
	.string "我们再见吧！$"

gText_ApprenticeWhatHeldItem0::
	.string "{CHN}唉……呜呜……\n"
	.string "哦，{PLAYER}！\p"
	.string "我陷入了一个\n"
	.string "无法决定的两难。\p"
	.string "我决定不了该让\n"
	.string "我的{STR_VAR_1}携带什么。\p"
	.string "请告诉我，{PLAYER}。\n"
	.string "我该让它携带什么道具？$"

gText_ApprenticeHoldNothing0::
	.string "{CHN}哦，真的吗？我不该让\n"
	.string "我的{STR_VAR_1}携带任何东西吗？$"

gText_ApprenticeThanksNoHeldItem0::
	.string "{CHN}哦，好的！解决了，我太高兴了！\n"
	.string "太棒了！太厉害了！呜吼！\p"
	.string "太感谢您了！$"

gText_ApprenticeThanksHeldItem0::
	.string "{CHN}哦，太好了……\n"
	.string "我想我也有那个{STR_VAR_1}。\p"
	.string "解决了，我太高兴了！\n"
	.string "太棒了！太厉害了！呜吼！\p"
	.string "太感谢您了！$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "{CHN}呜哇啊啊！请别这么坏！\p"
	.string "那个{STR_VAR_1}之前\n"
	.string "已经有人推荐给我了，呜呜……\p"
	.string "还是说您的意思是我不该让\n"
	.string "我的{STR_VAR_2}携带任何东西吗？$"

gText_ApprenticeWhatHeldItem1::
	.string "{CHN}好耶！是{PLAYER}！\n"
	.string "太好了！我正想问您点事！\p"
	.string "您会让您的宝可梦携带道具吗？\n"
	.string "我想让我的宝可梦携带道具，可是……\p"
	.string "什么道具对\n"
	.string "{STR_VAR_1}比较合适呢？\p"
	.string "您觉得呢？$"

gText_ApprenticeHoldNothing1::
	.string "{CHN}咦？您是说我的{STR_VAR_1}\n"
	.string "不必携带任何东西吗？$"

gText_ApprenticeThanksNoHeldItem1::
	.string "{CHN}哦，我懂了！我会照做的！\n"
	.string "谢谢您教我！$"

gText_ApprenticeThanksHeldItem1::
	.string "{CHN}哦，哇！一个{STR_VAR_1}啊？\n"
	.string "好的，我会照做的！\p"
	.string "谢谢您教我！$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "{CHN}哦，呃，不，我不是那个意思。\n"
	.string "我想了解一个不同的道具，\l"
	.string "和我已经知道的不同。\p"
	.string "还是说您的意思是这次我的宝可梦\n"
	.string "不必携带任何东西了？$"

gText_ApprenticeWhatHeldItem2::
	.string "{CHN}{PLAYER}，您好！\n"
	.string "是关于我的{STR_VAR_1}的事……\p"
	.string "我想让它携带一个好道具。\n"
	.string "什么对它比较合适呢？$"

gText_ApprenticeHoldNothing2::
	.string "{CHN}哦，那我的{STR_VAR_1}不必\n"
	.string "携带任何东西吗？$"

gText_ApprenticeThanksNoHeldItem2::
	.string "{CHN}好的，我明白了！\n"
	.string "再见！$"

gText_ApprenticeThanksHeldItem2::
	.string "{CHN}哦，{STR_VAR_1}这个道具吗？\n"
	.string "明白了！\p"
	.string "我会尽力去找到一个的！\n"
	.string "再见！$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "{CHN}有人已经教过\n"
	.string "我关于{STR_VAR_1}的事了。\p"
	.string "我想让我的宝可梦携带一种\n"
	.string "不同的道具。\p"
	.string "还是说您觉得{STR_VAR_2}不必\n"
	.string "携带任何东西吗？$"

gText_ApprenticeWhatHeldItem3::
	.string "{CHN}您好，{PLAYER}……\n"
	.string "抱歉打扰您，我还有\l"
	.string "其他事想问您。\p"
	.string "我觉得凭自己赢不了比赛，\n"
	.string "所以我在想让\l"
	.string "我的{STR_VAR_1}携带一个道具。\p"
	.string "但我不知道什么比较好。\p"
	.string "{PLAYER}，求求您，您能\n"
	.string "替我决定吗？$"

gText_ApprenticeHoldNothing3::
	.string "{CHN}像我这样的人的宝可梦，\n"
	.string "不带道具反而更好吗？$"

gText_ApprenticeThanksNoHeldItem3::
	.string "{CHN}我明白了……\n"
	.string "您是说我不该依赖道具。\l"
	.string "我会尽量不依赖的！\p"
	.string "非常感谢！$"

gText_ApprenticeThanksHeldItem3::
	.string "{CHN}{STR_VAR_1}这个道具，好的。\n"
	.string "我不确定能不能弄到……\l"
	.string "不！我会尽力去弄的。\p"
	.string "非常感谢！$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "{CHN}哦，可是……\n"
	.string "我好像听说过那个……\p"
	.string "是因为我没能很好地\n"
	.string "使用{STR_VAR_1}这个道具吗？\p"
	.string "还是说您的意思是我不该让\n"
	.string "我的{STR_VAR_2}携带任何东西吗？$"

gText_ApprenticeWhatHeldItem4::
	.string "{CHN}哦，{PLAYER}{KUN}。\n"
	.string "我有件事想问您。\p"
	.string "您记得您决定了我\n"
	.string "该有哪些宝可梦吗？\p"
	.string "但我从没问过您它\n"
	.string "该携带什么道具。\p"
	.string "既然您已经给了我建议，\n"
	.string "不如把这件事也一起解决？\p"
	.string "什么比较好？我想让\n"
	.string "我的{STR_VAR_1}携带点什么。$"

gText_ApprenticeHoldNothing4::
	.string "{CHN}哦！所以我的{STR_VAR_1}应该\n"
	.string "空着手尽力去战吗？$"

gText_ApprenticeThanksNoHeldItem4::
	.string "{CHN}如果您觉得那样最好，我就照做。\p"
	.string "知道是您做的决定，\n"
	.string "{PLAYER}{KUN}，即使输了\l"
	.string "我也不会那么难过。\p"
	.string "好，我会再向您请教的。\n"
	.string "再见！$"

gText_ApprenticeThanksHeldItem4::
	.string "{CHN}{STR_VAR_1}这个道具啊？\n"
	.string "不错。我会用的！\p"
	.string "知道是您做的决定，\n"
	.string "{PLAYER}{KUN}，即使输了\l"
	.string "我也不会那么难过。\p"
	.string "好，我会再向您请教的。\n"
	.string "再见！$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "{CHN}咦？您在说什么？\n"
	.string "您之前已经告诉过我\l"
	.string "关于{STR_VAR_1}的事了。\p"
	.string "还是说您的意思是我的{STR_VAR_2}应该\n"
	.string "空着手尽力去战吗？$"

gText_ApprenticeWhatHeldItem5::
	.string "{CHN}哟，{PLAYER}{KUN}！\p"
	.string "我们都忙，但似乎还是经常\n"
	.string "碰到一起！\p"
	.string "今天我得走路、\n"
	.string "打扫、还要刷洗。\p"
	.string "我甚至没时间\n"
	.string "给宝贝{STR_VAR_1}买点什么。\p"
	.string "我没时间，所以不如\n"
	.string "给我点建议，我该让\l"
	.string "我的{STR_VAR_1}携带什么？$"

gText_ApprenticeHoldNothing5::
	.string "{CHN}哦，所以我这个大忙人，\n"
	.string "您是说我的{STR_VAR_1}不需要任何东西吗？$"

gText_ApprenticeThanksNoHeldItem5::
	.string "{CHN}好的，明白。\n"
	.string "那我就不需要花时间了。\p"
	.string "今天谢谢您！\n"
	.string "回头见！$"

gText_ApprenticeThanksHeldItem5::
	.string "{CHN}好的，明白。\n"
	.string "我会想办法抽时间去\l"
	.string "找您推荐的{STR_VAR_1}。\p"
	.string "很高兴遇到了您这位好导师。\n"
	.string "谢谢！回头见！$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "{CHN}咦？我已经知道\n"
	.string "那个{STR_VAR_1}了。\p"
	.string "哦，对，我明白了。\n"
	.string "所以我这个大忙人，您是说\l"
	.string "我的{STR_VAR_2}不需要任何东西吗？$"

gText_ApprenticeWhatHeldItem6::
	.string "{CHN}嗨呀，{PLAYER}！是我！\n"
	.string "今天我又得向您请教了。\l"
	.string "拜托，我需要您的建议！\p"
	.string "请敲鼓伴奏！\n"
	.string "我的问题是……\p"
	.string "如果我想让我的{STR_VAR_1}\n"
	.string "携带一个道具，该是什么呢？$"

gText_ApprenticeHoldNothing6::
	.string "{CHN}是这样吗？您是说\n"
	.string "我的{STR_VAR_1}不需要携带道具。$"

gText_ApprenticeThanksNoHeldItem6::
	.string "{CHN}好的，我就照做！\p"
	.string "我想今天我想问\n"
	.string "您的就这些了。\p"
	.string "我们再在这里见面吧，好吗？\n"
	.string "谢谢！$"

gText_ApprenticeThanksHeldItem6::
	.string "{CHN}嗯哼！一个{STR_VAR_1}。\n"
	.string "多酷的选择！\l"
	.string "我一定要试试！\p"
	.string "我想今天我想问\n"
	.string "您的就这些了。\p"
	.string "我们再在这里见面吧，好吗？\n"
	.string "谢谢！$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "{CHN}啊哈哈！太傻了！\n"
	.string "您之前已经告诉过我\l"
	.string "那个{STR_VAR_1}了！\p"
	.string "您还好吗，{PLAYER}？\p"
	.string "哦，等等！您是说\n"
	.string "我的{STR_VAR_2}不需要携带道具。$"

gText_ApprenticeWhatHeldItem7::
	.string "{CHN}您好，{PLAYER}。希望您\n"
	.string "一切安好。\p"
	.string "我可以向您请教吗？\p"
	.string "在最近的一场对战中，我的对手\n"
	.string "似乎给他的宝可梦\l"
	.string "携带了道具。\p"
	.string "结果，我输了……\p"
	.string "我不想被甩在后面。\n"
	.string "我也想让我的{STR_VAR_1}\l"
	.string "携带一个道具。\p"
	.string "如果您能决定什么\n"
	.string "对我的宝可梦合适，我会很高兴……$"

gText_ApprenticeHoldNothing7::
	.string "{CHN}换言之……我的宝可梦\n"
	.string "不需要携带道具吗？$"

gText_ApprenticeThanksNoHeldItem7::
	.string "{CHN}现在我完全明白了！\n"
	.string "我会继续保持这样的。\p"
	.string "谢谢您，{PLAYER}。\n"
	.string "希望还能继续依靠您。\l"
	.string "请多保重！$"

gText_ApprenticeThanksHeldItem7::
	.string "{CHN}一个{STR_VAR_1}！\n"
	.string "我马上就去订购。\p"
	.string "谢谢您，{PLAYER}。\n"
	.string "希望还能继续依靠您。\l"
	.string "请多保重！$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "{CHN}那个您已经告诉我了，\n"
	.string "我已经有了。\p"
	.string "还是说您的意思是……\n"
	.string "我的宝可梦不需要携带道具吗？$"

gText_ApprenticeWhatHeldItem8::
	.string "{CHN}呀！{PLAYER}！\n"
	.string "我……我又见到您了，太高兴了！\p"
	.string "哦哦哦！我有件事\n"
	.string "非问您不可，{PLAYER}！\p"
	.string "请决定我的{STR_VAR_1}\n"
	.string "该携带什么吧！$"

gText_ApprenticeHoldNothing8::
	.string "{CHN}哦，哇！没想到会是这个回答！\n"
	.string "所以，携带道具不是必需的？$"

gText_ApprenticeThanksNoHeldItem8::
	.string "{CHN}完全明白！\n"
	.string "我会不带道具继续努力！\p"
	.string "希望您以后还愿意\n"
	.string "再教我一些。$"

gText_ApprenticeThanksHeldItem8::
	.string "{CHN}{STR_VAR_1}！我会用那个！\p"
	.string "嗯……莫非，{PLAYER}，您也\n"
	.string "让您的宝可梦携带那个道具吗？\p"
	.string "我一定会弄到的！\n"
	.string "希望您以后还愿意\l"
	.string "再教我一些。$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "{CHN}哦？您之前也推荐过\n"
	.string "那个{STR_VAR_1}。\p"
	.string "还是说那是最好的携带道具？\n"
	.string "还是说您的意思是我的{STR_VAR_2}\l"
	.string "不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem9::
	.string "{CHN}您好！\n"
	.string "我的大师，{PLAYER}{KUN}！\p"
	.string "我想向您请教关于\n"
	.string "宝可梦道具的事。\p"
	.string "您觉得什么对\n"
	.string "我的{STR_VAR_1}携带比较合适？\p"
	.string "别害羞嘛。\n"
	.string "直接说出来吧！$"

gText_ApprenticeHoldNothing9::
	.string "{CHN}哦？所以您是说我的{STR_VAR_1}\n"
	.string "不携带任何道具也能赢吗？$"

gText_ApprenticeThanksNoHeldItem9::
	.string "{CHN}好，好的！\n"
	.string "我会全力以赴，砰！\p"
	.string "好，一如既往地感谢！\n"
	.string "再见！$"

gText_ApprenticeThanksHeldItem9::
	.string "{CHN}嗯哼，就是一个{STR_VAR_1}吗？\n"
	.string "好，好的！\l"
	.string "我会去找一个，嘭！\p"
	.string "好，一如既往地感谢！\n"
	.string "再见！$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "{CHN}不，不！您之前已经告诉过我\n"
	.string "关于那个{STR_VAR_1}的事了。\p"
	.string "哦，等等，等一下……\n"
	.string "所以您是说我的{STR_VAR_2}\l"
	.string "不携带任何道具也能赢吗？$"

gText_ApprenticeWhatHeldItem10::
	.string "{CHN}{PLAYER}{KUN}，发生了一件\n"
	.string "难以置信的事！\p"
	.string "我今天早上醒来，我的宝可梦\n"
	.string "有了10个金珠！\p"
	.string "我当然在撒谎！\n"
	.string "哇哈哈！\p"
	.string "不过，这不是谎言。\n"
	.string "我不太擅长思考\l"
	.string "宝可梦该携带什么道具。\p"
	.string "所以，不如替我决定\n"
	.string "我的{STR_VAR_1}该携带什么吧，师傅？$"

gText_ApprenticeHoldNothing10::
	.string "{CHN}那是什么意思？\n"
	.string "不让它携带任何东西吗？$"

gText_ApprenticeThanksNoHeldItem10::
	.string "{CHN}好的，那它就不携带任何东西。\n"
	.string "那我还是给它弄点什么吧！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "谢谢，师傅！\n"
	.string "希望您继续教我！$"

gText_ApprenticeThanksHeldItem10::
	.string "{CHN}好的，就是一个{STR_VAR_1}！\n"
	.string "我会让它携带别的，不携那个！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "谢谢，师傅！\n"
	.string "希望您继续教我！$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "{CHN}嗯，您之前告诉过我那个，\n"
	.string "对吧？\p"
	.string "没有别的了吗？\p"
	.string "还是说您的意思是，不让\n"
	.string "我的{STR_VAR_2}携带任何东西吗？$"

gText_ApprenticeWhatHeldItem11::
	.string "{CHN}A-H-O-Y！\n"
	.string "这拼起来就是ahoy！\p"
	.string "我是说唱水手！\n"
	.string "我向您提出一个问题，\l"
	.string "挺不错的吧！\p"
	.string "是一个道具问题，\n"
	.string "正等着您的建议！\p"
	.string "我的{STR_VAR_1}需要携带一个道具，\n"
	.string "该是什么呢，如果我大胆的话？$"

gText_ApprenticeHoldNothing11::
	.string "{CHN}是这样吗？\n"
	.string "我的{STR_VAR_1}不需要\l"
	.string "紧紧携带任何东西吗？$"

gText_ApprenticeThanksNoHeldItem11::
	.string "{CHN}好的，我听到了，确实！\n"
	.string "我的宝可梦也会空着手去！\p"
	.string "如果我需要建议，\n"
	.string "{PLAYER}，我会一直听您的话！$"

gText_ApprenticeThanksHeldItem11::
	.string "{CHN}好的，一个{STR_VAR_1}，\n"
	.string "我就用那个。\l"
	.string "让您选果然没错！\p"
	.string "如果我需要建议，\n"
	.string "{PLAYER}，我会一直听您的话！$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{CHN}好的，您说一个{STR_VAR_1}吗？\n"
	.string "那天您告诉过我。\l"
	.string "我需要新主意，新方法。\p"
	.string "还是说，对吗？\n"
	.string "我的宝可梦不需要\l"
	.string "紧紧携带任何东西吗？$"

gText_ApprenticeWhatHeldItem12::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "今天又找到您了！\p"
	.string "我该怎么办？向您请教？\n"
	.string "有何不可？我都在和您说话了！\p"
	.string "{PLAYER}，您对我厌烦了吗？\n"
	.string "不，不，不会的，不可能。\p"
	.string "您愿意听我说吗？\n"
	.string "我在寻求建议——这就是\l"
	.string "我要说的。\p"
	.string "是关于我的{STR_VAR_1}\n"
	.string "该携带什么道具比较好。\l"
	.string "我的犹豫让我犯愁。$"

gText_ApprenticeHoldNothing12::
	.string "{CHN}我的{STR_VAR_1}什么都不需要？\n"
	.string "不需要携带任何东西吗？$"

gText_ApprenticeThanksNoHeldItem12::
	.string "{CHN}如果什么都不携带最好，\n"
	.string "我会照您的建议做！\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeThanksHeldItem12::
	.string "{CHN}如果携带那个{STR_VAR_1}\n"
	.string "最好，我会照您的建议做！\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "{CHN}我之前不是听说过\n"
	.string "那个{STR_VAR_1}吗？\l"
	.string "我确定我听过，肯定的！\p"
	.string "我需要新的东西！\n"
	.string "还是说，我的{STR_VAR_2}什么都不需要？\l"
	.string "不需要携带任何东西吗？$"

gText_ApprenticeWhatHeldItem13::
	.string "{CHN}哇啊！哎哟！{PLAYER}{KUN}，我的手臂断了！\n"
	.string "请别碰它！\p"
	.string "一定是我在和宝可梦伙伴们\n"
	.string "试用各种携带道具时\l"
	.string "弄断的。\p"
	.string "所以，事已至此，\n"
	.string "我需要您替我决定。\p"
	.string "{PLAYER}{KUN}，您觉得什么\n"
	.string "对我的{STR_VAR_1}携带比较合适？$"

gText_ApprenticeHoldNothing13::
	.string "{CHN}哎哟……\p"
	.string "所以您的建议是\n"
	.string "我的{STR_VAR_1}不必携带任何东西？$"

gText_ApprenticeThanksNoHeldItem13::
	.string "{CHN}嗯，好的。那样\n"
	.string "对现在的我来说更轻松。\p"
	.string "希望我能继续像这样\n"
	.string "找您帮忙。$"

gText_ApprenticeThanksHeldItem13::
	.string "{CHN}嗯，好的。一个{STR_VAR_1}。\n"
	.string "我的宝可梦手臂没事，我马上\l"
	.string "让它携带那个道具。\p"
	.string "希望我能继续像这样\n"
	.string "找您帮忙。$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "{CHN}不，不，您之前告诉过我\n"
	.string "那个{STR_VAR_1}了，记得吗？\p"
	.string "不如告诉我一些\n"
	.string "更好的东西？\p"
	.string "哦，等一下。\n"
	.string "所以您的建议是\l"
	.string "我的{STR_VAR_2}不必携带任何东西？$"

gText_ApprenticeWhatHeldItem14::
	.string "{CHN}呃……嗯……\n"
	.string "{PLAYER}{KUN}……\p"
	.string "请不要那样看我。\n"
	.string "我的宝可梦什么都没有。\p"
	.string "我……说起来真不好意思，\n"
	.string "但我真的需要您的建议。\p"
	.string "我决定不了什么携带道具能让\n"
	.string "我的{STR_VAR_1}变强。\p"
	.string "{PLAYER}{KUN}，您觉得什么\n"
	.string "比较好？$"

gText_ApprenticeHoldNothing14::
	.string "{CHN}哦……那么，您觉得如果\n"
	.string "我的{STR_VAR_1}不带道具会更好吗？$"

gText_ApprenticeThanksNoHeldItem14::
	.string "{CHN}哦……好的！\n"
	.string "我会不带道具上场。\p"
	.string "不过这真让人紧张。\n"
	.string "会不会太酷了？\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "如果我们再见面，希望您\l"
	.string "还能这么帮忙。$"

gText_ApprenticeThanksHeldItem14::
	.string "{CHN}哦……好的！\n"
	.string "我会用那个{STR_VAR_1}。\p"
	.string "不过这真让人紧张。\n"
	.string "会不会太酷了？\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "如果我们再见面，希望您\l"
	.string "还能这么帮忙。$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "{CHN}可、可是我已经听说过那个了。\p"
	.string "请您别这样打发我！\n"
	.string "我受不了这种羞辱。\p"
	.string "哦……是我妄下结论了吗？\n"
	.string "您是觉得如果\l"
	.string "我的{STR_VAR_2}不带道具会更好吗？$"

gText_ApprenticeWhatHeldItem15::
	.string "{CHN}嗯？您似乎是{PLAYER}{KUN}……\n"
	.string "但您是真的吗？\l"
	.string "或许您是双胞胎？\p"
	.string "哦，不，不，不，别担心！\n"
	.string "如果您真的是{PLAYER}，请\l"
	.string "原谅我的无礼。\p"
	.string "我想要的是再多一些\n"
	.string "您的好建议。\p"
	.string "我这里有我的{STR_VAR_1}，我想\n"
	.string "让它携带一个便利的道具。\p"
	.string "什么才配得上它呢？$"

gText_ApprenticeHoldNothing15::
	.string "{CHN}什么都不携带更好吗？\n"
	.string "您确定吗？$"

gText_ApprenticeThanksNoHeldItem15::
	.string "{CHN}我明白了。既然如此，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我们再见吧！$"

gText_ApprenticeThanksHeldItem15::
	.string "{CHN}一个{STR_VAR_1}吗？\n"
	.string "您确定吗？\p"
	.string "我明白了。既然如此，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我真希望我的宝可梦能\n"
	.string "好好使用它。\p"
	.string "我们再见吧！$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "{CHN}不，不，等一下。\n"
	.string "我相信您之前教过我那个。\p"
	.string "希望您这次\n"
	.string "推荐点不同的东西。\p"
	.string "或许您的意思是\n"
	.string "我的{STR_VAR_2}不该携带任何东西？\l"
	.string "您确定吗？$"

gText_ApprenticeWhichMonFirst0::
	.string "{CHN}呜哇，{PLAYER}！\n"
	.string "我有两难，呜呜……\p"
	.string "我想开始和其他人对战，\n"
	.string "但我不知道该怎么办。\p"
	.string "我该怎么安排我的宝可梦\n"
	.string "才能让它们发挥最强？\p"
	.string "请告诉我，{PLAYER}。\n"
	.string "如果是您，这些宝可梦中\l"
	.string "您会先派出哪一只？$"

gText_ApprenticeMonFirstThanks0::
	.string "{CHN}我的{STR_VAR_1}应该先上吗？\n"
	.string "呜哇啊啊啊！\p"
	.string "啊！真对不起！\n"
	.string "您帮我选了\l"
	.string "第一只宝可梦，我高兴得又哭了……\p"
	.string "太感谢您了！$"

gText_ApprenticeWhichMonFirst1::
	.string "{CHN}好耶！是{PLAYER}！\n"
	.string "太好了！我正想问您点事！\p"
	.string "嗯，我的宝可梦中，\n"
	.string "您觉得哪只应该先上？$"

gText_ApprenticeMonFirstThanks1::
	.string "{CHN}我的{STR_VAR_1}吗？没错。\n"
	.string "好的，我会照做！\p"
	.string "谢谢您教我！$"

gText_ApprenticeWhichMonFirst2::
	.string "{CHN}{PLAYER}，您好！\p"
	.string "我觉得，在对战中，哪只宝可梦\n"
	.string "先上场非常重要。\p"
	.string "在我有的宝可梦中，\n"
	.string "哪只先上比较好呢？$"

gText_ApprenticeMonFirstThanks2::
	.string "{CHN}我的{STR_VAR_1}先上吗？\n"
	.string "好的，我明白了！\p"
	.string "再见！$"

gText_ApprenticeWhichMonFirst3::
	.string "{CHN}您好，{PLAYER}……\n"
	.string "抱歉又来打扰您，\l"
	.string "又有一个问题。\p"
	.string "我太没自信了，不知道\n"
	.string "没有您我该怎么办，{PLAYER}。\p"
	.string "也许我连担心都是浪费时间，\n"
	.string "但我就是决定\l"
	.string "不了……\p"
	.string "我该让哪只宝可梦\n"
	.string "在对战中先上场呢？$"

gText_ApprenticeMonFirstThanks3::
	.string "{CHN}我的{STR_VAR_1}吗？\n"
	.string "明白了！\p"
	.string "我不敢相信您竟然愿意\n"
	.string "这么多次回答我的问题！\p"
	.string "我太感激了，您甚至\n"
	.string "愿意和我说话……谢谢您！$"

gText_ApprenticeWhichMonFirst4::
	.string "{CHN}哦，{PLAYER}{KUN}！是我！\n"
	.string "我很高兴见到您，因为我有\l"
	.string "这个小问题。\p"
	.string "我决定不了我的宝可梦该怎么\n"
	.string "排列。您能替我决定吗？\p"
	.string "哦，您现在不必决定整个\n"
	.string "队伍。\p"
	.string "不如先替我决定\n"
	.string "第一只宝可梦？$"

gText_ApprenticeMonFirstThanks4::
	.string "{CHN}我的{STR_VAR_1}吗？太棒了！\p"
	.string "知道是您做的决定，\n"
	.string "{PLAYER}{KUN}，即使输了\l"
	.string "我也不会那么难过。\p"
	.string "好，我会再向您请教的。\n"
	.string "再见！$"

gText_ApprenticeWhichMonFirst5::
	.string "{CHN}嗨，我的老师{PLAYER}{KUN}！\n"
	.string "我今天又忙了！\p"
	.string "我得骑车、购物、\n"
	.string "还要哼歌。\p"
	.string "我甚至没时间决定\n"
	.string "怎么排列我的宝可梦队伍。\p"
	.string "所以，不如看看我的队伍？\n"
	.string "哪只该先上？$"

gText_ApprenticeMonFirstThanks5::
	.string "{CHN}好的，明白。\n"
	.string "我至少还有时间把\l"
	.string "我的{STR_VAR_1}排在最前面！\p"
	.string "哎呀，我女朋友在等我！\n"
	.string "谢谢！回头见！$"

gText_ApprenticeWhichMonFirst6::
	.string "{CHN}哟呼！嗨呀，{PLAYER}！\n"
	.string "您走路的样子总是那么神气！\p"
	.string "听着，我又需要您帮忙了！\n"
	.string "还是老样子！\p"
	.string "请敲鼓伴奏！\n"
	.string "我的问题是关于我的队伍的。\p"
	.string "我的哪只宝可梦应该\n"
	.string "在对战中先上场？$"

gText_ApprenticeMonFirstThanks6::
	.string "{CHN}嗯哼！\n"
	.string "您说是我的{STR_VAR_1}！\l"
	.string "谢谢您超酷的回答！\p"
	.string "我想今天我想问\n"
	.string "您的就这些了。\p"
	.string "我们再在这里见面吧，好吗？\n"
	.string "谢谢！$"

gText_ApprenticeWhichMonFirst7::
	.string "{CHN}非常感谢您停下脚步\n"
	.string "和我聊天，{PLAYER}。\p"
	.string "我知道我在利用您的\n"
	.string "好意，但我可以请教吗？\p"
	.string "我希望您能决定\n"
	.string "我的宝可梦队伍的顺序。\p"
	.string "如果您能决定哪只宝可梦\n"
	.string "该先上，我会很高兴。$"

gText_ApprenticeMonFirstThanks7::
	.string "{CHN}我的{STR_VAR_1}！\n"
	.string "我马上就把它放第一个！\p"
	.string "谢谢您，{PLAYER}。\n"
	.string "希望还能继续依靠您。\l"
	.string "请多保重！$"

gText_ApprenticeWhichMonFirst8::
	.string "{CHN}呀！{PLAYER}！\n"
	.string "我……我又见到您了，太高兴了！\p"
	.string "我的宝可梦变得\n"
	.string "更强了！\p"
	.string "但我并不总是赢。这似乎\n"
	.string "取决于哪只宝可梦先上场。\p"
	.string "{PLAYER}，求求您，我需要您的帮助！\p"
	.string "请决定我的哪只宝可梦\n"
	.string "该先上场！$"

gText_ApprenticeMonFirstThanks8::
	.string "{CHN}啊……我幸福得不知所措……\p"
	.string "让您为我决定\n"
	.string "就像做梦一样，{PLAYER}。\p"
	.string "完全明白！\n"
	.string "我会让我的{STR_VAR_1}先上！\p"
	.string "希望您以后还愿意\n"
	.string "再教我一些。$"

gText_ApprenticeWhichMonFirst9::
	.string "{CHN}您好，您好！\n"
	.string "我的导师，{PLAYER}{KUN}！\l"
	.string "今天请赐予我高明的建议！\p"
	.string "您看，我组建了一支\n"
	.string "三只宝可梦的队伍。目前还不错。\p"
	.string "但队伍的对战顺序\n"
	.string "还没定下来。\p"
	.string "这就轮到您了，{PLAYER}{KUN}！\n"
	.string "您来决定哪只宝可梦先上！\p"
	.string "别害羞嘛。\n"
	.string "直接说出来吧！$"

gText_ApprenticeMonFirstThanks9::
	.string "{CHN}嗯哼，我的{STR_VAR_1}先上！\n"
	.string "好，很好！\l"
	.string "我会重新排列队伍，砰！\p"
	.string "好，一如既往地感谢！\n"
	.string "再见！$"

gText_ApprenticeWhichMonFirst10::
	.string "{CHN}{PLAYER}{KUN}，听我说！\n"
	.string "出大事了！\p"
	.string "我的宝可梦，三只全都\n"
	.string "一起上阵了！\p"
	.string "当然那是不可能的！\n"
	.string "哇哈哈！\p"
	.string "不过，这不是谎言。\n"
	.string "我不太擅长思考\l"
	.string "该怎么排列我的宝可梦。\p"
	.string "所以，不如替我决定哪只\n"
	.string "宝可梦该先上吧，师傅？$"

gText_ApprenticeMonFirstThanks10::
	.string "{CHN}好的，您选的是我的{STR_VAR_1}吗？\n"
	.string "我会让别的任何一只先上！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "谢谢，师傅！\n"
	.string "希望您继续教我！$"

gText_ApprenticeWhichMonFirst11::
	.string "{CHN}A-H-O-Y！\n"
	.string "这拼起来就是ahoy！\p"
	.string "我是说唱水手！\n"
	.string "我向您提出一个问题，\l"
	.string "挺不错的吧！\p"
	.string "是一个队伍排列问题，\n"
	.string "正等着您的建议！\p"
	.string "在这群之中，哪只该先上，\n"
	.string "成为先发的那个？$"

gText_ApprenticeMonFirstThanks11::
	.string "{CHN}好的，我听到了，确实！\n"
	.string "我会调整顺序，我一定做！\p"
	.string "如果我需要建议，\n"
	.string "{PLAYER}，我会一直听您的话！$"

gText_ApprenticeWhichMonFirst12::
	.string "{CHN}呀呼，{PLAYER}！\n"
	.string "您好吗？\p"
	.string "我该怎么办？直接问？\n"
	.string "嗯哼，我有事要问！\l"
	.string "您听明白了吗？\l"
	.string "您听明白了！\p"
	.string "您得决定，我的哪只\n"
	.string "宝可梦第一个上场！\l"
	.string "我的意思是说，上战场。$"

gText_ApprenticeMonFirstThanks12::
	.string "{CHN}我的{STR_VAR_1}吗？好！\n"
	.string "那就行了，没问题！\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMonFirst13::
	.string "{CHN}……哎……哎哟……{PLAYER}{KUN}……\n"
	.string "我的肚子突然疼起来了……\p"
	.string "……现在好点了……\p"
	.string "我一定是为如何排列\n"
	.string "我的宝可梦伙伴\l"
	.string "伤透了脑筋而病倒了。\p"
	.string "所以，事已至此，\n"
	.string "我需要您替我决定。\p"
	.string "{PLAYER}{KUN}，我的哪只宝可梦应该\n"
	.string "先上？我的意思是，为了赢。$"

gText_ApprenticeMonFirstThanks13::
	.string "{CHN}嗯，好的。\n"
	.string "我的{STR_VAR_1}先上。\p"
	.string "我吃完晚饭后\n"
	.string "就按那样调整顺序。\p"
	.string "希望我能继续像这样\n"
	.string "找您帮忙。$"

gText_ApprenticeWhichMonFirst14::
	.string "{CHN}呃……嗯……\n"
	.string "{PLAYER}{KUN}……？\p"
	.string "请不要那样看我。\n"
	.string "您让我心慌意乱。\p"
	.string "嗯……\n"
	.string "我真的需要您的建议。\p"
	.string "说起来真不好意思，\n"
	.string "我选好了我的三只宝可梦队伍。\l"
	.string "但我决定不了顺序。\p"
	.string "我该先派哪只宝可梦上场\n"
	.string "才看起来至少有点本事？$"

gText_ApprenticeMonFirstThanks14::
	.string "{CHN}哦……好的！\n"
	.string "我会让我的{STR_VAR_1}打头。\p"
	.string "希望我能尽力而为，\n"
	.string "不会心慌意乱。\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "如果我们再见面，希望您\l"
	.string "还能这么帮忙。$"

gText_ApprenticeWhichMonFirst15::
	.string "{CHN}嗯？您似乎是{PLAYER}{KUN}……\n"
	.string "但您是真的吗？\l"
	.string "或许您是个聪明的替身？\p"
	.string "哦，不，不，不，别担心！\n"
	.string "如果您真的是{PLAYER}，请\l"
	.string "原谅我的无礼。\p"
	.string "我想要的是您的好建议。\p"
	.string "我这里有我的宝可梦队伍。\n"
	.string "我希望您告诉我\l"
	.string "哪只该在对战中先上。$"

gText_ApprenticeMonFirstThanks15::
	.string "{CHN}我的{STR_VAR_1}吗……\n"
	.string "您不是在耍我吧？\p"
	.string "我明白了。既然如此，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我如您所见，但我会\n"
	.string "尽力而为。\p"
	.string "我们再见吧！$"

gText_ApprenticeWhichMon0::
	.string "{CHN}抽噎……\n"
	.string "哦，{PLAYER}！\p"
	.string "来得正好！\n"
	.string "有件事我决定不了……\p"
	.string "我决定不了该用\n"
	.string "哪只宝可梦。\p"
	.string "我在宝可梦{STR_VAR_1}\n"
	.string "和{STR_VAR_2}之间犹豫……\p"
	.string "{PLAYER}，您觉得哪只\n"
	.string "连我也有机会赢？$"

gText_ApprenticeMonThanks0::
	.string "{CHN}抽噎……我……我明白了！\n"
	.string "啊！真对不起！\l"
	.string "您让我太高兴了，我哭了……\p"
	.string "我会尽力去\n"
	.string "抓一只{STR_VAR_1}！\p"
	.string "太感谢您了！$"

gText_ApprenticeWhichMon1::
	.string "{CHN}好耶！是{PLAYER}！\n"
	.string "好耶，您来得正好！\l"
	.string "我又需要您的建议了！\p"
	.string "嗯，我犯愁了——我该用\n"
	.string "我的{STR_VAR_1}还是{STR_VAR_2}……\p"
	.string "您觉得我该培育哪只，\n"
	.string "{PLAYER}？$"

gText_ApprenticeMonThanks1::
	.string "{CHN}哦，所以我的{STR_VAR_1}更好！\n"
	.string "好的，我会照做！\p"
	.string "谢谢您教我！$"

gText_ApprenticeWhichMon2::
	.string "{CHN}{PLAYER}，您好！\n"
	.string "我有个问题想问。\p"
	.string "我在纠结是该培育\n"
	.string "一只{STR_VAR_1}还是{STR_VAR_2}。\p"
	.string "您觉得哪只宝可梦\n"
	.string "会更强？$"

gText_ApprenticeMonThanks2::
	.string "{CHN}您选{STR_VAR_1}吗？\n"
	.string "好的，我明白了！\p"
	.string "我马上去抓一只\n"
	.string "强壮的{STR_VAR_1}！\p"
	.string "再见！$"

gText_ApprenticeWhichMon3::
	.string "{CHN}您好，{PLAYER}……\p"
	.string "嗯，您可能已经忘了\n"
	.string "像我这样的人了……\p"
	.string "……不过那不重要，\n"
	.string "如果您能给我建议的话……\p"
	.string "我决定不了该培育\n"
	.string "哪种宝可梦……\p"
	.string "我把范围缩小到了宝可梦\n"
	.string "{STR_VAR_1}和{STR_VAR_2}，但\l"
	.string "就在那时我卡住了……\p"
	.string "{PLAYER}，您可能不想\n"
	.string "费心，但请替我决定吧。$"

gText_ApprenticeMonThanks3::
	.string "{CHN}但野生的{STR_VAR_1}\n"
	.string "会理我吗？\p"
	.string "我会试试的！\p"
	.string "但我连能不能抓到一只都……\n"
	.string "不！我会加油的！\p"
	.string "谢谢您！$"

gText_ApprenticeWhichMon4::
	.string "{CHN}哦，{PLAYER}{KUN}！很高兴见到您！\n"
	.string "我正要去找您！\p"
	.string "您能决定我该用\n"
	.string "哪种宝可梦吗？\p"
	.string "比如……\n"
	.string "宝可梦{STR_VAR_1}\l"
	.string "和{STR_VAR_2}如何？\p"
	.string "您觉得哪个\n"
	.string "更好？$"

gText_ApprenticeMonThanks4::
	.string "{CHN}{STR_VAR_1}吗？太棒了！\p"
	.string "知道是您做的决定，\n"
	.string "{PLAYER}{KUN}，即使输了\l"
	.string "我也不会那么难过。\p"
	.string "好，我会再向您请教的。\n"
	.string "再见！$"

gText_ApprenticeWhichMon5::
	.string "{CHN}这不是{PLAYER}{KUN}嘛！最近如何？\n"
	.string "我又像往常一样忙了！\p"
	.string "我也想在宝可梦方面做好，\n"
	.string "但我一直决定不了\l"
	.string "该用哪只宝可梦。\p"
	.string "您知道{STR_VAR_1}看起来很强吧？\n"
	.string "但{STR_VAR_2}也不容小觑。\p"
	.string "{PLAYER}{KUN}，给我点好\n"
	.string "建议吧！哪个对我合适？$"

gText_ApprenticeMonThanks5::
	.string "{CHN}好的，明白。\n"
	.string "我会想办法抽时间去\l"
	.string "抓您推荐的{STR_VAR_1}。\p"
	.string "很高兴遇到了您这位好导师。\n"
	.string "谢谢！回头见！$"

gText_ApprenticeWhichMon6::
	.string "{CHN}哦！\n"
	.string "好耶，是{PLAYER}！\p"
	.string "我迫不及待地向\n"
	.string "朋友们吹嘘遇见您的事！\p"
	.string "今天我又得向您请教了。\n"
	.string "对您来说很简单！\p"
	.string "请敲鼓伴奏！\n"
	.string "我的问题是……\p"
	.string "如果我要培育一只宝可梦，\n"
	.string "选择是一只{STR_VAR_1}\l"
	.string "或{STR_VAR_2}，该选哪个？$"

gText_ApprenticeMonThanks6::
	.string "{CHN}啊啊啊！\n"
	.string "您说是{STR_VAR_1}！\l"
	.string "谢谢您超酷的回答！\p"
	.string "我想今天我想问\n"
	.string "您的就这些了。\p"
	.string "我们再在这里见面吧，好吗？\n"
	.string "谢谢！$"

gText_ApprenticeWhichMon7::
	.string "{CHN}哦，是您吗，{PLAYER}？\n"
	.string "很高兴再次见到您！\p"
	.string "自从成为您的学徒以来，\n"
	.string "我的自信心一直在绽放。\p"
	.string "我想我已经准备好培育\n"
	.string "自己的宝可梦了！\p"
	.string "{PLAYER}，我可以麻烦您选择\n"
	.string "我该培育哪只宝可梦吗？\p"
	.string "选择是宝可梦\n"
	.string "{STR_VAR_1}或{STR_VAR_2}……\l"
	.string "哪只宝可梦适合我？$"

gText_ApprenticeMonThanks7::
	.string "{CHN}一只{STR_VAR_1}！\n"
	.string "我马上就去找一只！\p"
	.string "谢谢您，{PLAYER}。\n"
	.string "希望还能继续依靠您。\l"
	.string "请多保重！$"

gText_ApprenticeWhichMon8::
	.string "{CHN}呀！{PLAYER}！我又遇见您了！\n"
	.string "我……我太高兴了！\p"
	.string "哦哦哦，我知道了！\n"
	.string "我不能错过这个机会！\p"
	.string "我可以请您帮个大忙吗，{PLAYER}？\n"
	.string "请为我选一只宝可梦吧！\p"
	.string "请决定哪个更好，\n"
	.string "{STR_VAR_1}还是{STR_VAR_2}！$"

gText_ApprenticeMonThanks8::
	.string "{CHN}哇！您替我决定了！\n"
	.string "我会尽力培育一只\l"
	.string "{STR_VAR_1}。\p"
	.string "希望您以后还愿意\n"
	.string "再教我一些。$"

gText_ApprenticeWhichMon9::
	.string "{CHN}嘿，嘿！\n"
	.string "我的导师，{PLAYER}{KUN}！\p"
	.string "您好，我一直在找您，\n"
	.string "想再听听您的高见！\p"
	.string "哪种宝可梦对我合适，\n"
	.string "一只{STR_VAR_1}还是{STR_VAR_2}？\p"
	.string "别害羞嘛。\n"
	.string "直接说出来吧！$"

gText_ApprenticeMonThanks9::
	.string "{CHN}嗯哼，就一只{STR_VAR_1}了！\n"
	.string "好，很好！\l"
	.string "我会用精灵球抓一只，咔嚓！\p"
	.string "好，一如既往地感谢！\n"
	.string "再见！$"

gText_ApprenticeWhichMon10::
	.string "{CHN}{PLAYER}{KUN}，听我说！大事！\n"
	.string "我抓到了一只幻之宝可梦！\p"
	.string "我当然在撒谎！\n"
	.string "哇哈哈！\p"
	.string "不过，这不是谎言。\n"
	.string "我不太擅长抓\l"
	.string "宝可梦。\p"
	.string "所以，不如替我决定\n"
	.string "我该抓哪种宝可梦，\l"
	.string "师傅？\p"
	.string "哪个更好？\n"
	.string "{STR_VAR_1}还是{STR_VAR_2}？$"

gText_ApprenticeMonThanks10::
	.string "{CHN}好的，您选的是{STR_VAR_1}吗？\n"
	.string "那我就抓另一种！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "谢谢，师傅！\n"
	.string "希望您继续教我！$"

gText_ApprenticeWhichMon11::
	.string "{CHN}A-H-O-Y！\n"
	.string "这拼起来就是ahoy！\p"
	.string "我是说唱水手！\n"
	.string "您肯定还记得我是谁吧？\p"
	.string "今天，我有一个宝可梦问题，\n"
	.string "正等着您的建议！\p"
	.string "我可以选择这只\n"
	.string "{STR_VAR_1}或{STR_VAR_2}，您看。\l"
	.string "哪只该我去抓？$"

gText_ApprenticeMonThanks11::
	.string "{CHN}{STR_VAR_1}，您说的，嘿嘿！\n"
	.string "我马上就去抓一只！\p"
	.string "如果我需要建议，\n"
	.string "{PLAYER}，我会一直听您的话！$"

gText_ApprenticeWhichMon12::
	.string "{CHN}哦，哇，这不是{PLAYER}嘛！\p"
	.string "我该怎么办？向您请教？\n"
	.string "有何不可？我都在和您说话了！\p"
	.string "好久不见。让我\n"
	.string "打开话题。我也在寻求建议！\l"
	.string "您听明白了吗？\l"
	.string "您听明白了！\p"
	.string "我的宝可梦——我该用哪只？\n"
	.string "是{STR_VAR_1}还是{STR_VAR_2}。\l"
	.string "您选哪个？$"

gText_ApprenticeMonThanks12::
	.string "{CHN}如果那个{STR_VAR_1}最好，\n"
	.string "我会照您的建议做！\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMon13::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}……\n"
	.string "我头疼得厉害……\p"
	.string "我一定是太担心\n"
	.string "该培育哪种宝可梦了。\p"
	.string "所以，事已至此，\n"
	.string "我需要您替我决定。\p"
	.string "{PLAYER}{KUN}，如果我必须在\n"
	.string "宝可梦{STR_VAR_1}和\l"
	.string "{STR_VAR_2}之间选，该选哪个？$"

gText_ApprenticeMonThanks13::
	.string "{CHN}嗯，一只{STR_VAR_1}，好的。\n"
	.string "我好点就去寻找一只。\p"
	.string "希望我能继续像这样\n"
	.string "找您帮忙。$"

gText_ApprenticeWhichMon14::
	.string "{CHN}呃……嗯……\n"
	.string "{PLAYER}{KUN}……？\p"
	.string "请不要那样看我。\n"
	.string "我心慌意乱了……\l"
	.string "我……我需要您的建议。\p"
	.string "我……说起来真不好意思，但我\n"
	.string "决定不了该用哪只宝可梦。\p"
	.string "如果选择是{STR_VAR_1}或\n"
	.string "{STR_VAR_2}，哪个更好？$"

gText_ApprenticeMonThanks14::
	.string "{CHN}哦……好的！\n"
	.string "我会尽力和一只{STR_VAR_1}培育好。\p"
	.string "希望我能尽力而为，\n"
	.string "不会心慌意乱。\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "如果我们再见面，希望您\l"
	.string "还能这么帮忙。$"

gText_ApprenticeWhichMon15::
	.string "{CHN}嗯？您似乎是{PLAYER}{KUN}……\n"
	.string "但您是真的吗？\p"
	.string "不，不，如果您是真的，那没问题。\n"
	.string "顺带一提，我希望获得\l"
	.string "您的建议。\p"
	.string "是关于我该用的宝可梦的。\p"
	.string "如果选择是宝可梦\n"
	.string "{STR_VAR_1}和{STR_VAR_2}，哪个更\l"
	.string "配得上我？$"

gText_ApprenticeMonThanks15::
	.string "{CHN}{STR_VAR_1}吗？\n"
	.string "您确定吗？\p"
	.string "我明白了。既然如此，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我真希望那是连我\n"
	.string "也能从容应对的事。\p"
	.string "我们再见吧！$"

gText_ApprenticeWhichMove0::
	.string "{CHN}呜哇！哦，{PLAYER}！\n"
	.string "抽噎……打嗝……\p"
	.string "我有两难！\n"
	.string "我决定不了\l"
	.string "我的{STR_VAR_1}的招式……\p"
	.string "求求您，求求您，{PLAYER}。\n"
	.string "您能替我决定吗？\p"
	.string "对于我的{STR_VAR_1}，哪个招式\n"
	.string "更好：{STR_VAR_2}\l"
	.string "还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks0::
	.string "{CHN}{STR_VAR_1}吗？\n"
	.string "呜哇啊啊啊！\p"
	.string "啊！真对不起，{PLAYER}！\n"
	.string "您帮我决定了\l"
	.string "招式，我高兴得哭了……\p"
	.string "抽噎……\n"
	.string "太感谢您了！$"

gText_ApprenticeWhichMove1::
	.string "{CHN}好耶！嗨，{PLAYER}！\n"
	.string "我又需要您的建议了！\p"
	.string "我想教我的{STR_VAR_1}\n"
	.string "一个酷招式。\p"
	.string "我喜欢{STR_VAR_2}\n"
	.string "或{STR_VAR_3}这两个招式。\l"
	.string "您推荐哪个？$"

gText_ApprenticeMoveThanks1::
	.string "{CHN}{STR_VAR_1}更好吗？我想也是！\n"
	.string "好的，我就用那个！\p"
	.string "如果我们再在这里见面，请再教\n"
	.string "我点别的吧，老师！$"

gText_ApprenticeWhichMove2::
	.string "{CHN}{PLAYER}，您好！\n"
	.string "是关于我的{STR_VAR_1}的事，\l"
	.string "我在为它的招式发愁。\p"
	.string "是这样的，是招式{STR_VAR_2}\n"
	.string "和{STR_VAR_3}。\p"
	.string "哪个更强、对\n"
	.string "我的{STR_VAR_1}更好？$"

gText_ApprenticeMoveThanks2::
	.string "{CHN}您选{STR_VAR_1}吗？\n"
	.string "好的，我明白了！\p"
	.string "我马上去教\n"
	.string "我的宝可梦{STR_VAR_1}！\p"
	.string "再见！$"

gText_ApprenticeWhichMove3::
	.string "{CHN}哦哦，{PLAYER}……\n"
	.string "我无药可救了，不，真的！\p"
	.string "我决定培育一只宝可梦，\n"
	.string "但现在我连该让它学\l"
	.string "什么招式都决定不了……\p"
	.string "我知道这对您\n"
	.string "没什么意义，{PLAYER}。\p"
	.string "但对我意义非凡……\p"
	.string "求求您，{PLAYER}，您能为\n"
	.string "我的{STR_VAR_1}选个招式吗？\p"
	.string "如果您能在\n"
	.string "{STR_VAR_2}和{STR_VAR_3}之间选……$"

gText_ApprenticeMoveThanks3::
	.string "{CHN}我明白了！\p"
	.string "但它会愿意为\n"
	.string "我学{STR_VAR_1}吗……\l"
	.string "不！我会加油的！\p"
	.string "谢谢您！$"

gText_ApprenticeWhichMove4::
	.string "{CHN}哦，{PLAYER}{KUN}！\n"
	.string "我也正想着能见到您！\p"
	.string "我在想什么招式\n"
	.string "适合我的{STR_VAR_1}。\p"
	.string "我决定不了，您能替我\n"
	.string "决定吗？\p"
	.string "比如……招式\n"
	.string "{STR_VAR_2}和{STR_VAR_3}如何？\l"
	.string "哪个更好？$"

gText_ApprenticeMoveThanks4::
	.string "{CHN}{STR_VAR_1}吗？太棒了！\p"
	.string "知道是您做的决定，\n"
	.string "{PLAYER}{KUN}，即使输了\l"
	.string "我也不会那么难过。\p"
	.string "好，我会再向您请教的。\n"
	.string "再见！$"

gText_ApprenticeWhichMove5::
	.string "{CHN}怎么会这么忙？\n"
	.string "嘿，这不是{PLAYER}{KUN}嘛！\l"
	.string "最近如何？\p"
	.string "我从今早起就在慢跑、\n"
	.string "游泳、做饭了！\p"
	.string "您想不到我有多忙！\p"
	.string "我连我的{STR_VAR_1}该学\n"
	.string "什么招式都决定不了！\p"
	.string "{STR_VAR_2}看起来不错吧？\n"
	.string "但{STR_VAR_3}也不赖。\p"
	.string "{PLAYER}{KUN}，给我点好\n"
	.string "建议吧！哪个招式对我合适？$"

gText_ApprenticeMoveThanks5::
	.string "{CHN}好的，明白。\n"
	.string "我会在日程里腾出时间\l"
	.string "教那个招式。\p"
	.string "很高兴遇到了您这位好导师。\n"
	.string "谢谢！回头见！$"

gText_ApprenticeWhichMove6::
	.string "{CHN}哦！幸运！\n"
	.string "我又遇见您了，{PLAYER}！\l"
	.string "今天我又得向您请教了。\p"
	.string "请敲鼓伴奏！\n"
	.string "我的问题是……\p"
	.string "对于我的{STR_VAR_1}，哪个招式\n"
	.string "最合适，{STR_VAR_2}还是\l"
	.string "{STR_VAR_3}？$"

gText_ApprenticeMoveThanks6::
	.string "{CHN}啊啊啊！\n"
	.string "您说是{STR_VAR_1}！\l"
	.string "谢谢您超酷的回答！\p"
	.string "我想今天我想问\n"
	.string "您的就这些了。\p"
	.string "我们再在这里见面吧，好吗？\n"
	.string "谢谢！$"

gText_ApprenticeWhichMove7::
	.string "{CHN}哦，您好，{PLAYER}。\n"
	.string "您近来可好？\p"
	.string "我又得向您请教了。\n"
	.string "是关于我最心爱的{STR_VAR_1}的事。\p"
	.string "什么才是我的\n"
	.string "可爱{STR_VAR_1}的理想招式？\l"
	.string "{STR_VAR_2}还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks7::
	.string "{CHN}就{STR_VAR_1}了！\n"
	.string "我马上就教它！\p"
	.string "谢谢您，{PLAYER}。\n"
	.string "希望还能继续依靠您。\l"
	.string "请多保重！$"

gText_ApprenticeWhichMove8::
	.string "{CHN}呀！{PLAYER}！我又遇见您了！\n"
	.string "我……我太高兴了！\p"
	.string "每当我有需要，您总是\n"
	.string "在我身边，{PLAYER}！\p"
	.string "今天，我想请您推荐\n"
	.string "一个招式！\p"
	.string "请为\n"
	.string "我的{STR_VAR_1}选个招式吧！\p"
	.string "哪个招式更好，\n"
	.string "{STR_VAR_2}还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks8::
	.string "{CHN}哦哦哦！谢谢您！\n"
	.string "就是{STR_VAR_1}！\l"
	.string "完全明白！\p"
	.string "希望您以后还愿意\n"
	.string "再教我一些。$"

gText_ApprenticeWhichMove9::
	.string "{CHN}您好，{PLAYER}{KUN}，好的！\n"
	.string "我希望今天\l"
	.string "能再听听您的高见！\p"
	.string "什么才是\n"
	.string "我的{STR_VAR_1}的最佳招式？\p"
	.string "应该是那种能让我\n"
	.string "一下子就获胜的招式！\p"
	.string "是{STR_VAR_2}吗？\n"
	.string "还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks9::
	.string "{CHN}嗯哼，就{STR_VAR_1}了！\n"
	.string "好，好的！\l"
	.string "我会去教它，咔嚓！\p"
	.string "好，一如既往地感谢！\n"
	.string "再见！$"

gText_ApprenticeWhichMove10::
	.string "{CHN}{PLAYER}{KUN}，太疯狂了！\p"
	.string "我的宝可梦！\n"
	.string "它学了六个招式！\p"
	.string "我当然在撒谎！\n"
	.string "哇哈哈！\p"
	.string "不过，这不是谎言。\n"
	.string "我不太擅长为\l"
	.string "我的宝可梦选招式。\p"
	.string "所以，不如替我决定\n"
	.string "我该教哪种招式？\p"
	.string "{STR_VAR_2}还是{STR_VAR_3}——哪个\n"
	.string "和我的{STR_VAR_1}最配？$"

gText_ApprenticeMoveThanks10::
	.string "{CHN}好的，您选的是{STR_VAR_1}吗？\n"
	.string "那我就选另一个招式！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "谢谢，师傅！\n"
	.string "希望您继续教我！$"

gText_ApprenticeWhichMove11::
	.string "{CHN}A-H-O-Y！\n"
	.string "这拼起来就是ahoy！\p"
	.string "我是说唱水手！\n"
	.string "我总是这么在行，别问我为什么。\p"
	.string "今天，我有个招式问题，\n"
	.string "正等着您的建议！\p"
	.string "{STR_VAR_2}和{STR_VAR_3}是\n"
	.string "候选的招式。哪个对我的\l"
	.string "{STR_VAR_1}最佳，让它出彩？$"

gText_ApprenticeMoveThanks11::
	.string "{CHN}{STR_VAR_1}，您说的，嘿嘿！\n"
	.string "我马上就去教它！\p"
	.string "如果我需要建议，\n"
	.string "{PLAYER}，我会一直听您的话！$"

gText_ApprenticeWhichMove12::
	.string "{CHN}哦，耶啊，这不是{PLAYER}嘛！\p"
	.string "我该怎么办？向您请教？\n"
	.string "有何不可？我都在和您说话了！\p"
	.string "{PLAYER}，您对我感到惊讶吗？\n"
	.string "我想要您的建议，您看不出吗？\p"
	.string "您听明白了吗？\n"
	.string "您听明白了！\p"
	.string "我的{STR_VAR_1}——该用什么？\n"
	.string "是{STR_VAR_2}还是{STR_VAR_3}，\l"
	.string "您选哪个？$"

gText_ApprenticeMoveThanks12::
	.string "{CHN}如果那个{STR_VAR_1}最好，\n"
	.string "我会照您的建议做！\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMove13::
	.string "{CHN}咳咳！啊啊！哦，{PLAYER}{KUN}……\n"
	.string "我感冒了，真糟糕……\p"
	.string "我想为我的宝可梦选个招式，\n"
	.string "但我没那个精神……\p"
	.string "所以，事已至此，\n"
	.string "我需要您替我决定。\p"
	.string "{PLAYER}{KUN}，如果我必须在\n"
	.string "{STR_VAR_2}和{STR_VAR_3}之间为\l"
	.string "我的{STR_VAR_1}选一个，该选哪个？$"

gText_ApprenticeMoveThanks13::
	.string "{CHN}嗯，{STR_VAR_1}，好的。咳咳！\n"
	.string "我好点就去教它。\p"
	.string "希望我能继续像这样\n"
	.string "找您帮忙。$"

gText_ApprenticeWhichMove14::
	.string "{CHN}呃……嗯……\n"
	.string "{PLAYER}{KUN}……？\p"
	.string "请不要那样看我。\n"
	.string "我心慌意乱了……\l"
	.string "我……我需要您的建议。\p"
	.string "我……说起来真不好意思，但我\n"
	.string "决定不了该教\l"
	.string "我的宝可梦什么招式。\p"
	.string "是为我的{STR_VAR_1}。\n"
	.string "如果选择是{STR_VAR_2}或\l"
	.string "{STR_VAR_3}，哪个更好？$"

gText_ApprenticeMoveThanks14::
	.string "{CHN}哦……好的！\n"
	.string "我会试试那个{STR_VAR_1}。\p"
	.string "希望我能教那个招式……\n"
	.string "这真让人紧张……\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "如果我们再见面，希望您\l"
	.string "还能这么帮忙。$"

gText_ApprenticeWhichMove15::
	.string "{CHN}嗯？您似乎是{PLAYER}{KUN}……\n"
	.string "但您是真的吗？\p"
	.string "或许您是那种流行的\n"
	.string "拟态宝可梦？\p"
	.string "不，不，如果您是真的，那没问题。\n"
	.string "不必动怒，我保证！\p"
	.string "顺带一提，我希望获得\n"
	.string "您的建议。\p"
	.string "是关于我的{STR_VAR_1}的事。\p"
	.string "它该用哪个招式更好，\n"
	.string "{STR_VAR_2}还是{STR_VAR_3}？$"

gText_ApprenticeMoveThanks15::
	.string "{CHN}{STR_VAR_1}吗？\n"
	.string "这没什么疑问吗？\p"
	.string "我明白了。既然如此，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我真希望那是连\n"
	.string "我的宝可梦也能学会的招式。\p"
	.string "我们再见吧！$"

gText_ApprenticePickWinSpeech0::
	.string "{CHN}哦……{PLAYER}吗？\n"
	.string "是{PLAYER}！\l"
	.string "啊！抽泣……呜呜…… 请听我说！\p"
	.string "我……我对战时太紧张了，\n"
	.string "即使赢了也会忍不住哭……\p"
	.string "真希望赢了的时候\n"
	.string "能说句酷话……\p"
	.string "求求您，求求您，{PLAYER}！\n"
	.string "您能不能教我一句\l"
	.string "赢了时说的酷话，让我不哭？$"

gText_ApprenticeWinSpeechThanks0::
	.string "{CHN}{STR_VAR_1}\p"
	.string "太棒了！太厉害了！呜吼！\n"
	.string "真的好酷！\p"
	.string "啊……对不起……\n"
	.string "我太高兴了，又哭了……\p"
	.string "抽噎……{PLAYER}！\n"
	.string "太感谢您的一切了！\p"
	.string "我会为了\n"
	.string "您尽力而战，{PLAYER}！\p"
	.string "{PLAYER}……\n"
	.string "下次……我们应该对战！$"

gText_ApprenticePickWinSpeech1::
	.string "{CHN}好耶！是{PLAYER}！您好！\n"
	.string "我正想问您点事！\p"
	.string "我想在赢得比赛时\n"
	.string "说句酷话。\p"
	.string "您有没有什么\n"
	.string "酷话可以推荐？$"

gText_ApprenticeWinSpeechThanks1::
	.string "{CHN}{STR_VAR_1}\p"
	.string "哦，哇！太酷了！\n"
	.string "好的，我就说那个！\p"
	.string "谢谢您这段时间的教导！\n"
	.string "从今往后无论去哪，\l"
	.string "我都会尽力而为！\p"
	.string "当我们再见面时，\n"
	.string "就是对战了！$"

gText_ApprenticePickWinSpeech2::
	.string "{CHN}{PLAYER}，您好！\p"
	.string "我的宝可梦和我\n"
	.string "准备好了一切，除了一件事。\p"
	.string "我想如果我赢了有\n"
	.string "什么可以喊的就好了。\p"
	.string "您能想句\n"
	.string "好话吗？$"

gText_ApprenticeWinSpeechThanks2::
	.string "{CHN}{STR_VAR_1}\p"
	.string "……酷！\n"
	.string "我会用那个！\p"
	.string "我要去\n"
	.string "到处对战了。\p"
	.string "谁知道呢，也许有一天\n"
	.string "我会和您对战，{PLAYER}。\p"
	.string "下次，让我们在\n"
	.string "战场相见！$"

gText_ApprenticePickWinSpeech3::
	.string "{CHN}您好，{PLAYER}……\n"
	.string "抱歉打扰您，但我无药可救了……\p"
	.string "即使……\n"
	.string "即使我赢了，我也没什么\l"
	.string "特别的话可说……\p"
	.string "我知道这对您\n"
	.string "没什么意义，{PLAYER}。\p"
	.string "但对我意义非凡……\p"
	.string "求求您，{PLAYER}，如果我赢了\n"
	.string "我该说什么？$"

gText_ApprenticeWinSpeechThanks3::
	.string "{CHN}{STR_VAR_1}\p"
	.string "真有灵感……\p"
	.string "呃……像我这样的人\n"
	.string "说那种话真的合适吗？\p"
	.string "不！我会加油的！\p"
	.string "{PLAYER}，太感谢您\n"
	.string "这么久以来对我的包容……\p"
	.string "我保证从今往后尽力而为。\p"
	.string "我相信您很快就会忘记\n"
	.string "像我这样的人，但我们\l"
	.string "在某个地方再见吧！$"

gText_ApprenticePickWinSpeech4::
	.string "{CHN}哦，{PLAYER}{KUN}。\n"
	.string "我有件事想让您听听。\p"
	.string "我知道我说话\n"
	.string "不总是好听或礼貌……\p"
	.string "当我赢得对战时，我想我\n"
	.string "显得很傲慢。\p"
	.string "我不想让人讨厌我，\n"
	.string "所以我想对\l"
	.string "被我打败的人说点好话。\p"
	.string "但我想不出什么好的！\n"
	.string "您能替我想想吗？$"

gText_ApprenticeWinSpeechThanks4::
	.string "{CHN}{STR_VAR_1}\p"
	.string "不错！\n"
	.string "对，我就用那个！\p"
	.string "我要上路了，把您教我的\n"
	.string "东西记在\l"
	.string "脑海里和心里去闯荡。\p"
	.string "对不起我一直\n"
	.string "这么纠缠您！\p"
	.string "下次，我们对战吧，好吗？\n"
	.string "再见！$"

gText_ApprenticePickWinSpeech5::
	.string "{CHN}哦，我忙得不可开交！\n"
	.string "哦，嘿，我正找您呢，{PLAYER}{KUN}。\p"
	.string "您像往常一样好吗？\n"
	.string "我这边一点没变。\p"
	.string "我有跑步、格斗、还有测绘\n"
	.string "要做。我怎么这么忙？\p"
	.string "但即使我忙，赢了之后\n"
	.string "转身就走\l"
	.string "一句话也不说也太失礼了。\p"
	.string "所以，什么样的酷话能\n"
	.string "在我结束\l"
	.string "转身离开时彰显我的酷？{PLAYER}{KUN}，帮帮我！$"

gText_ApprenticeWinSpeechThanks5::
	.string "{CHN}{STR_VAR_1}\p"
	.string "好的，明白。\n"
	.string "我能抽时间说那个！\p"
	.string "说真的，很高兴遇到了您\n"
	.string "这样的好导师。\p"
	.string "我会想办法腾出时间\n"
	.string "去对战。\p"
	.string "感谢一切，{PLAYER}{KUN}！\n"
	.string "总有一天我们要对战，您和我！$"

gText_ApprenticePickWinSpeech6::
	.string "{CHN}我又走运了！\n"
	.string "{PLAYER}！见到您真高兴！\l"
	.string "像往常一样，我需要您的建议！\p"
	.string "请敲鼓伴奏！\n"
	.string "我最后的问题是……\p"
	.string "如果我赢得对战，想以\n"
	.string "酷炫的方式结束，\l"
	.string "我该说什么？$"

gText_ApprenticeWinSpeechThanks6::
	.string "{CHN}{STR_VAR_1}\p"
	.string "那……那太棒了！\n"
	.string "又庄重又酷！我选它了！\p"
	.string "……听着，我觉得我在这方面\n"
	.string "变得不错了吧？\p"
	.string "所以，我打算从现在起\n"
	.string "挑战其他训练家。\p"
	.string "{PLAYER}，您的建议真的帮了我。\p"
	.string "也许有一天，会有\n"
	.string "我们对战的时候！\p"
	.string "感谢您的一切！$"

gText_ApprenticePickWinSpeech7::
	.string "{CHN}哦，{PLAYER}。\n"
	.string "我太高兴能遇到您！\p"
	.string "关于我的宝可梦，\n"
	.string "我不再有任何顾虑了。\p"
	.string "让我担心的是我自己……\p"
	.string "您知道训练家在赢得对战后\n"
	.string "会说几句话吗？\p"
	.string "我当然希望我也能\n"
	.string "那样！\p"
	.string "求求您，我赢了\n"
	.string "对战时该说什么？$"

gText_ApprenticeWinSpeechThanks7::
	.string "{CHN}{STR_VAR_1}\p"
	.string "啊！那句话！它让我神清气爽，\n"
	.string "感觉焕然一新！\p"
	.string "我必须马上用上它！\p"
	.string "那么，我必须告辞了，\n"
	.string "{PLAYER}……\p"
	.string "我会去和许多其他人对战，\n"
	.string "但我永远不会忘记您的教导。\p"
	.string "也许有一天……\n"
	.string "再会！$"

gText_ApprenticePickWinSpeech8::
	.string "{CHN}呀！我发现{PLAYER}了！\n"
	.string "我……我见到您太高兴了！\p"
	.string "哦哦哦！我有件事\n"
	.string "非问您不可！\p"
	.string "不久前，我赢了一场对战。\n"
	.string "那部分让我头晕目眩！\p"
	.string "但我太高兴了，\n"
	.string "喉咙哽住，一句话都说不出来！\p"
	.string "所以现在，{PLAYER}，求求您，\n"
	.string "我想请您想一句我赢时的结束语！$"

gText_ApprenticeWinSpeechThanks8::
	.string "{CHN}{STR_VAR_1}\p"
	.string "呜哇啊啊！\n"
	.string "我要说那个？！\l"
	.string "我……我高兴得要疯了！\p"
	.string "谢、谢、谢谢您！\n"
	.string "我现在没什么可遗憾的了！\p"
	.string "我现在要去旅行，\n"
	.string "和各种人对战了。\p"
	.string "这一切都要归功于您，{PLAYER}。\n"
	.string "真的，真的，谢谢您！\p"
	.string "我得走了，但让我们\n"
	.string "有一天在战场上见！$"

gText_ApprenticePickWinSpeech9::
	.string "{CHN}您好，好的！\n"
	.string "{PLAYER}{KUN}！\p"
	.string "您知道，我开始有四处闯荡\n"
	.string "对战的冲动了。\p"
	.string "但在此之前，我想再\n"
	.string "请教您一次，拜托！\p"
	.string "如果我赢了对战，\n"
	.string "什么是我可以对\l"
	.string "战败的训练家说的得意话？$"

gText_ApprenticeWinSpeechThanks9::
	.string "{CHN}{STR_VAR_1}\p"
	.string "嗯哼，太妙了！\n"
	.string "好，好的！\l"
	.string "我会试着说那个，哈！\p"
	.string "那么，是时候说再见了！\n"
	.string "感谢您的一切！\p"
	.string "改天和我对战吧，好吗？\n"
	.string "再见！$"

gText_ApprenticePickWinSpeech10::
	.string "{CHN}{PLAYER}{KUN}，出大事了！\p"
	.string "我赢了对战时，会 brag\n"
	.string "至少一个小时！\p"
	.string "我当然在撒谎！\n"
	.string "哇哈哈！\p"
	.string "不过，这不是谎言。\n"
	.string "我不太擅长聊天。\p"
	.string "所以，不如替我决定\n"
	.string "我赢得对战后该说什么，\l"
	.string "师傅？$"

gText_ApprenticeWinSpeechThanks10::
	.string "{CHN}{STR_VAR_1}\p"
	.string "那就是我该说的吗？\n"
	.string "那我就不说那个！\p"
	.string "开玩笑的！\n"
	.string "我会听从您的教导，师傅！\p"
	.string "感谢您这段时间的教导，\n"
	.string "师傅！\p"
	.string "我终于明白当训练家\n"
	.string "是怎么回事了。\p"
	.string "我要去和\n"
	.string "任何训练家对战并获胜。\p"
	.string "也许有一天就是您，师傅！\p"
	.string "就这样了！\n"
	.string "再会，我的师傅！$"

gText_ApprenticePickWinSpeech11::
	.string "{CHN}A-H-O-Y！\n"
	.string "这拼起来就是ahoy！\p"
	.string "我是说唱水手！\n"
	.string "这是我最后一个问题，\l"
	.string "您别哭！\p"
	.string "是一个台词问题，\n"
	.string "正等着您的建议！\p"
	.string "如果我赢了比赛，我能\n"
	.string "用什么酷酷的话来说？$"

gText_ApprenticeWinSpeechThanks11::
	.string "{CHN}{STR_VAR_1}\p"
	.string "完美！我就用那个。\n"
	.string "让您选果然没错！\p"
	.string "那么，我想最好是\n"
	.string "我离巢高飞！\p"
	.string "感谢您教我的一切。\n"
	.string "我要去大闹对战一场！\p"
	.string "B-O-N-V-O-Y-A-G-E！\n"
	.string "这拼起来就是bon voyage，\l"
	.string "这是我对您的敬意！$"

gText_ApprenticePickWinSpeech12::
	.string "{CHN}哦，耶啊，{PLAYER}！\n"
	.string "今天又找到您了！\p"
	.string "我该怎么办？再问您？\n"
	.string "有何不可？我都在问了！\p"
	.string "总之，{PLAYER}……\n"
	.string "您听明白了吗？\l"
	.string "您听明白了！\l"
	.string "我需要再给我一些建议！\p"
	.string "是关于我该喊什么。\n"
	.string "一些酷酷的话，\l"
	.string "当对战顺利结束时喊。\p"
	.string "来嘛，我想听您说！$"

gText_ApprenticeWinSpeechThanks12::
	.string "{CHN}{STR_VAR_1}\p"
	.string "好，好！\n"
	.string "我就用那个，因为它太棒了！\p"
	.string "我没有别的问题要问了。\n"
	.string "只剩下挥手告别了。\p"
	.string "但也许有一天我们会相见，\n"
	.string "其中一个注定要落败。\p"
	.string "不过，真的是时候说再见了。\p"
	.string "那么，{PLAYER}，我得自由翱翔了，\n"
	.string "但您可别忘了我！\p"
	.string "保重，{PLAYER}！\n"
	.string "爱你！$"

gText_ApprenticePickWinSpeech13::
	.string "{CHN}{PLAYER}{KUN}，我完了……\n"
	.string "我的鼻涕流个不停……\p"
	.string "我在想一句\n"
	.string "我赢得对战时说的酷话。\p"
	.string "它太启发我了，让我哭了，\n"
	.string "现在我的鼻涕流个不停……\p"
	.string "所以，事已至此，\n"
	.string "我需要您替我决定，{PLAYER}{KUN}。\p"
	.string "我赢得对战时，\n"
	.string "该说什么？$"

gText_ApprenticeWinSpeechThanks13::
	.string "{CHN}{STR_VAR_1}\p"
	.string "…… …… ……好。\n"
	.string "不，是令人敬畏！\l"
	.string "它让我又流下新的眼泪！\p"
	.string "尽管我眼泪鼻涕直流，\n"
	.string "我也要用那句话！\p"
	.string "我已经没什么要问\n"
	.string "您的了，{PLAYER}{KUN}。\p"
	.string "从现在起，我们是劲敌了！\n"
	.string "感谢您的一切！$"

gText_ApprenticePickWinSpeech14::
	.string "{CHN}呃……嗯……\n"
	.string "{PLAYER}{KUN}……\p"
	.string "请不要那样看我。\n"
	.string "您让我紧张了。\p"
	.string "我……我又需要您的建议了。\n"
	.string "不过这是我最后一次了……\p"
	.string "问起来真不好意思，\n"
	.string "但如果我赢了对战呢？\l"
	.string "我该说什么？$"

gText_ApprenticeWinSpeechThanks14::
	.string "{CHN}{STR_VAR_1}\p"
	.string "哦……好的！\n"
	.string "我会试着说那个！\l"
	.string "我可能太紧张说不出来……\p"
	.string "谢谢您，{PLAYER}{KUN}。\n"
	.string "我得说再见了。\p"
	.string "我会遵从您教的一切，\n"
	.string "{PLAYER}{KUN}，尽力而为。$"

gText_ApprenticePickWinSpeech15::
	.string "{CHN}嗯？您似乎是{PLAYER}{KUN}……\n"
	.string "但您是真的吗？\l"
	.string "或许是个聪明的{PLAYER}玩偶？\p"
	.string "哦，不，不，不，别担心！\n"
	.string "如果您真的是真的，请\l"
	.string "原谅我的无礼。\p"
	.string "不必这么生气。我只\n"
	.string "希望再多一些您的好建议。\p"
	.string "是关于一句话的。\p"
	.string "更确切地说，如果我赢了\n"
	.string "对战，我该说什么？$"

gText_ApprenticeWinSpeechThanks15::
	.string "{CHN}{STR_VAR_1}\p"
	.string "…… …… …… …… …… ……\n"
	.string "当我赢得比赛时……\p"
	.string "{STR_VAR_1}\p"
	.string "……您是认真的吗？\p"
	.string "我明白了。如果您是认真的，那就好。\n"
	.string "感谢您的时间。\p"
	.string "我真希望连我\n"
	.string "也能好好使用那句话。\p"
	.string "我似乎已经没有\n"
	.string "需要的建议了。\p"
	.string "我相信是时候向您\n"
	.string "告别，独自闯荡了。\p"
	.string "谢谢您，我的导师！\n"
	.string "我为我的怀疑道歉！$"
