FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{CHN}欢迎来到对战帐篷\n"
	.string "烟尘山会场！\p"
	.string "我是固定KO锦标赛的向导！$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "{CHN}那么，你想挑战\n"
	.string "固定KO锦标赛吗？$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "{CHN}我们期待你下次再来\n"
	.string "挑战！$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "{CHN}在烟尘山对战帐篷，\n"
	.string "我们举办固定KO锦标赛。\p"
	.string "所有参赛者要以三只\n"
	.string "宝可梦组队入场。\p"
	.string "三只宝可梦必须按照\n"
	.string "出场的顺序排列。\p"
	.string "对战中，宝可梦会按照预设的顺序\n"
	.string "一只一只地出场。\p"
	.string "一旦宝可梦出场，就必须\n"
	.string "留在场上直到比赛决出胜负。\p"
	.string "如果比赛在三回合内\n"
	.string "未决出胜负，将进入评审。\p"
	.string "如果想中断挑战，\n"
	.string "请保存游戏。\p"
	.string "如果不保存，你将无法\n"
	.string "继续挑战。\p"
	.string "如果你能达成连续击败\n"
	.string "三位训练家的壮举，\l"
	.string "我们将赠予你一份精美的奖品。$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{CHN}在带你去对战帐篷之前，\n"
	.string "我必须保存游戏。可以吗？$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{CHN}我们提供两种难度的挑战，\n"
	.string "50级和开放等级。\l"
	.string "你选择哪一个？$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{CHN}好的，请选择你的\n"
	.string "三只宝可梦。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{CHN}亲爱的挑战者！\p"
	.string "你没有参赛所需的\n"
	.string "三只宝可梦。\p"
	.string "它们也不能持有\n"
	.string "相同种类的道具。\p"
	.string "蛋{STR_VAR_1}不合格。\p"
	.string "等你做好准备，\n"
	.string "请再来。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{CHN}亲爱的挑战者！\p"
	.string "你没有参赛所需的\n"
	.string "三只宝可梦。\p"
	.string "要符合资格，你必须带三只\n"
	.string "不同种类的宝可梦。\p"
	.string "它们也不能持有\n"
	.string "相同种类的道具。\p"
	.string "蛋{STR_VAR_1}不合格。\p"
	.string "等你做好准备，\n"
	.string "请再来。$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "{CHN}我现在带你\n"
	.string "去对战帐篷。$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{CHN}亲爱的挑战者！\p"
	.string "你在关机之前\n"
	.string "没有保存游戏，是吧？\p"
	.string "很遗憾，这导致了你\n"
	.string "被取消挑战资格，\l"
	.string "无法继续挑战。\p"
	.string "当然，你可以开始一次\n"
	.string "全新的挑战。$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "{CHN}太棒了！你连续击败了\n"
	.string "三位训练家！$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "{CHN}请稍候，我正在保存游戏。$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{CHN}为纪念你的三连胜，\n"
	.string "我们向你赠送这份奖品。$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{CHN}{PLAYER}收到了奖品\n"
	.string "{STR_VAR_1}。$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "{CHN}哦？\n"
	.string "你的包似乎满了。\p"
	.string "我劝你腾出空间\n"
	.string "再来领取奖品。$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "{CHN}非常感谢你的参与！\p"
	.string "请稍候，我正在保存游戏。$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "{CHN}我们期待你下次再来\n"
	.string "挑战！$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "{CHN}我们一直期待着\n"
	.string "你的到来。\p"
	.string "在带你去对战帐篷之前，\n"
	.string "我必须保存游戏。请稍候。$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{CHN}欢迎来到对战帐篷\n"
	.string "茵郁市会场！\p"
	.string "这里将测试训练家\n"
	.string "对宝可梦的信任。$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "{CHN}你想挑战茵郁市\n"
	.string "对战帐篷吗？$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "{CHN}在茵郁市对战帐篷，\n"
	.string "有一条必须遵守的\l"
	.string "关键规则。\p"
	.string "训练家只允许\n"
	.string "替换宝可梦。\p"
	.string "训练家除此之外\n"
	.string "不得命令宝可梦。\p"
	.string "宝可梦要根据自身性格\n"
	.string "自主行动和战斗。\p"
	.string "你必须信任你的宝可梦\n"
	.string "并照看它们。\p"
	.string "如果你能达成连续击败\n"
	.string "三位训练家的荣誉，\l"
	.string "我们将赠予你一份奖品。\p"
	.string "如果想中断挑战，\n"
	.string "请保存游戏。\p"
	.string "如果中断前不保存，\n"
	.string "你将被取消资格。$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "{CHN}等你强化了内心\n"
	.string "和宝可梦之后，你必须回来。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{CHN}有两种难度，\n"
	.string "50级和开放等级。\l"
	.string "你想选择哪种挑战？$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{CHN}唉……\p"
	.string "你没有挑战所需的\n"
	.string "三只宝可梦。\p"
	.string "要参赛，你必须提供三只\n"
	.string "不同种类的宝可梦。\p"
	.string "它们也不能持有\n"
	.string "相同种类的道具。\p"
	.string "蛋{STR_VAR_1}不合格。\p"
	.string "等你做好准备\n"
	.string "再来吧。$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{CHN}唉……\p"
	.string "你没有挑战所需的\n"
	.string "三只宝可梦。\p"
	.string "要参赛，你必须提供三只\n"
	.string "不同种类的宝可梦。\p"
	.string "它们也不能持有\n"
	.string "相同种类的道具。\p"
	.string "蛋{STR_VAR_1}不合格。\p"
	.string "等你做好准备\n"
	.string "再来吧。$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{CHN}好。现在，你必须选择你的\n"
	.string "三只宝可梦。$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{CHN}在带你去对战帐篷之前，\n"
	.string "我必须保存。可以吗？$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "{CHN}好。\n"
	.string "那么，跟我来。$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "{CHN}能见证你的宝可梦的\n"
	.string "英勇表现，我深感荣幸。\p"
	.string "结果将被记录。\n"
	.string "我得请你稍等一下。$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "{CHN}达成了三连胜……\p"
	.string "连接你心灵与宝可梦的\n"
	.string "纽带似乎坚固而真挚。$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "{CHN}你的壮举将被记录。\n"
	.string "我得请你稍等一下。$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{CHN}为纪念你的三连胜壮举，\n"
	.string "我们向你赠送这份奖品。$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{CHN}欢迎来到对战帐篷\n"
	.string "凯那市会场！\p"
	.string "我是战斗交换锦标赛的\n"
	.string "向导。$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "{CHN}你想挑战战斗\n"
	.string "交换赛吗？$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "{CHN}在凯那市对战帐篷，\n"
	.string "我们使用租借宝可梦\l"
	.string "举办战斗交换赛。\p"
	.string "首先，我们会借给你三只\n"
	.string "专为本次活动准备的宝可梦。\p"
	.string "使用提供的租借宝可梦，\n"
	.string "你必须进行单打对战。\p"
	.string "如果你赢了，你可以交换\n"
	.string "你的一只租借宝可梦。\p"
	.string "重复这个对战和交换的循环——\n"
	.string "如果你连续赢三次，\l"
	.string "你将获得一份精美的奖品。\p"
	.string "如果想中断挑战，\n"
	.string "请保存游戏。\p"
	.string "如果中断前不保存，\n"
	.string "你将被取消资格。$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "{CHN}期待你的下次光临。$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "{CHN}你想挑战哪个等级？\n"
	.string "50级还是100级？$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{CHN}在你开始挑战之前，\n"
	.string "我需要保存数据。可以吗？$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "{CHN}好的，在你比赛期间，\n"
	.string "我会替你保管你的宝可梦。$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "{CHN}请这边走。$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "{CHN}感谢你的参与！\p"
	.string "我会用我们的租借宝可梦换回\n"
	.string "你的宝可梦。\p"
	.string "我也必须保存你的活动成绩。\n"
	.string "请稍候。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "{CHN}我会用我们的租借宝可梦换回\n"
	.string "你的宝可梦。$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "{CHN}恭喜你！\n"
	.string "你连续赢了三场！\p"
	.string "我会用我们的租借宝可梦换回\n"
	.string "你的宝可梦。\p"
	.string "我也必须保存你的活动成绩。\n"
	.string "请稍候。$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "{CHN}为表彰你的三连胜，\n"
	.string "我们向你颁发这份奖品。$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "{CHN}哦？\n"
	.string "你似乎没有空间放这个。\p"
	.string "请在包里腾出空间\n"
	.string "再告诉我。$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "{CHN}我们一直在等你！\p"
	.string "在你继续挑战之前，\n"
	.string "我必须保存游戏。$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{CHN}很抱歉这么说，但你上次\n"
	.string "退出前没有保存。\p"
	.string "因此，你已被取消\n"
	.string "挑战资格。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "{CHN}我们会归还你的个人宝可梦。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{CHN}{PLAYER}收到了奖品\n"
	.string "{STR_VAR_1}。$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "{CHN}战斗交换赛的规则如下。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "{CHN}你想阅读哪个标题？$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "{CHN}在战斗交换赛中，你只能\n"
	.string "使用三只宝可梦。\p"
	.string "无论是租借还是交换，\n"
	.string "你的队伍不能有两只或更多\l"
	.string "相同的宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "{CHN}你只能与你刚刚击败的\n"
	.string "训练家交换宝可梦。\p"
	.string "你只能交换被击败的\n"
	.string "训练家所使用的宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "{CHN}在你每次获胜后，\n"
	.string "你可以交换一只被击败的\l"
	.string "对手的宝可梦。\p"
	.string "你不能与活动中的\n"
	.string "第三位训练家交换宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "{CHN}交换宝可梦时，\n"
	.string "有两个要点需要注意。\p"
	.string "首先，交换时，你无法查看\n"
	.string "你即将得到的\l"
	.string "宝可梦的能力值。\p"
	.string "其次，你的队伍中的宝可梦\n"
	.string "会按照你租借它们的顺序\l"
	.string "依次排列。\p"
	.string "即使进行交换，\n"
	.string "这个顺序也不会改变。$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "{CHN}凯那市对战帐篷的\n"
	.string "宝可梦全是租借的。\p"
	.string "所有租借宝可梦都保持在\n"
	.string "30级。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "{CHN}茵郁市对战帐篷\n"
	.string "的规则如下。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "{CHN}你想阅读哪个标题？$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "{CHN}在茵郁市对战帐篷，\n"
	.string "宝可梦需要自己思考\l"
	.string "并自己战斗。\p"
	.string "与野生环境不同，与人\n"
	.string "一起生活的宝可梦会根据\l"
	.string "它们的性格表现不同。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "{CHN}根据性格不同，宝可梦\n"
	.string "可能无论如何都喜欢攻击。\p"
	.string "另一只宝可梦可能\n"
	.string "喜欢保护自己不受伤害。\p"
	.string "还有的可能喜欢\n"
	.string "困扰或迷惑对手。\p"
	.string "根据性格不同，宝可梦\n"
	.string "会有它擅长使用的\l"
	.string "喜爱招式。\p"
	.string "它也可能不喜欢某些\n"
	.string "它难以使用的招式。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "{CHN}有直接对对手造成伤害的\n"
	.string "攻击招式。\p"
	.string "有为敌人攻击做准备，\n"
	.string "或用于恢复HP等的\l"
	.string "防御招式。\p"
	.string "还有一些奇怪的招式，\n"
	.string "可以通过中毒和麻痹等\l"
	.string "状态问题来削弱对手。\p"
	.string "宝可梦会考虑使用\n"
	.string "这三类招式。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "{CHN}当不被训练家指挥时，\n"
	.string "宝可梦可能无法有效地\l"
	.string "使用某些招式。\p"
	.string "宝可梦不擅长使用\n"
	.string "它不喜欢的招式。\p"
	.string "如果宝可梦只懂得\n"
	.string "不符合它性格的招式，\l"
	.string "它往往无法发挥潜力。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "{CHN}根据性格不同，宝可梦在\n"
	.string "陷入困境时，可能开始使用\l"
	.string "不符合它性格的招式。\p"
	.string "如果宝可梦在危难时\n"
	.string "表现异常，请仔细观察。$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "{CHN}在这个对战帐篷，\n"
	.string "对手的等级将被调整以\l"
	.string "匹配你的宝可梦等级。\p"
	.string "但是，你面对的训练家\n"
	.string "不会有任何低于30级的宝可梦。$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "{CHN}茵郁市对战帐篷\n"
	.string "的规则如下。$"
