PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "{CHN}爸爸：嗨，{PLAYER}！\p"
	.string "我刚收到一颗非常稀有的树果。\n"
	.string "我想把它给您。$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "{CHN}如果您看到树果长在松软的\n"
	.string "土壤里，请随便摘取。\p"
	.string "但请务必在同一位置\n"
	.string "种下一颗树果。这是基本的礼貌。\p"
	.string "来，我把这个分给您。$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "{CHN}看您的样子，您一定是\n"
	.string "训练家吧？\p"
	.string "训练家经常让宝可梦\n"
	.string "携带树果。\p"
	.string "种植树果还是使用树果，\n"
	.string "由您自己决定。$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "{CHN}我每天给植物浇水。\n"
	.string "它们开了很多花。\p"
	.string "也给了我很多树果。\p"
	.string "给您！\n"
	.string "您可以拿去！$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "{CHN}我要努力尝试\n"
	.string "种出不同颜色的树果。\p"
	.string "希望您也加油！$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "{CHN}我想知道今天要找\n"
	.string "什么颜色的树果呢？$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "{CHN}我喜欢用树果粉碎机，\n"
	.string "所以我在收集树果。\p"
	.string "如果您愿意，我分一个给您。$"

Route114_Text_TryBerryCrushWithFriends:
	.string "{CHN}您应该和朋友一起\n"
	.string "试试树果粉碎机。$"

Route114_Text_FunToThinkAboutBerries:
	.string "{CHN}应该种哪种树果呢？\n"
	.string "树果该用还是该攒着？\p"
	.string "想想就觉得有趣。$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "{CHN}树果通过吸收阳光生长。\p"
	.string "我们定期浇水\n"
	.string "帮助树果生长。\p"
	.string "这是一种爱的表达，不是吗？$"

Route120_Text_YesYouUnderstand:
	.string "{CHN}是，是。\n"
	.string "您明白我的意思。\p"
	.string "您应该收下这个。$"

Route120_Text_MakeYourOwnImpressions:
	.string "{CHN}哦……但有自己的\n"
	.string "感想也很重要吧……\p"
	.string "这个给您。$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "{CHN}我觉得那颗树果很稀有。\n"
	.string "希望您用心培育它。$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "{CHN}我会从树果大师那里\n"
	.string "拿到更多树果。$"

LilycoveCity_Text_BerrySuitsYou:
	.string "{CHN}说到底……\p"
	.string "就像西装最适合我，\n"
	.string "清爽的微风最适合大海。\p"
	.string "而您，树果最适合您……\p"
	.string "为什么会这样呢？$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "{CHN}说到底……\p"
	.string "因为您是训练家！$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "{CHN}说到底……\p"
	.string "就像端庄简约最适合我，\n"
	.string "{POKEBLOCK}S最适合宝可梦。$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "{CHN}您可以叫我树果大师。\p"
	.string "我梦想让世界开满\n"
	.string "美丽的花朵，所以我培育树果\l"
	.string "并分发给每个人。\p"
	.string "您值得一颗！$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "{CHN}何必小气呢？\n"
	.string "再拿一颗吧！$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "{CHN}一定要去卡那兹市附近的\n"
	.string "漂亮花瓣花店看看。\p"
	.string "让鲜花开满世界！$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "{CHN}今天就到此为止了。\n"
	.string "改天再来吧。\p"
	.string "让鲜花开满世界！$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "{CHN}我丈夫种树果的方式，\n"
	.string "哦，他是世界第一。\p"
	.string "他让我感到骄傲，确实如此。\p"
	.string "顺便问一下，孩子，您最近\n"
	.string "听过什么好格言吗？$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "{CHN}啊！多么了不起的格言！\n"
	.string "真让人振奋！\p"
	.string "我希望您收下这个。$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "{CHN}哦！真是好格言。\n"
	.string "您相当了不起。\p"
	.string "我希望您收下这个。$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "{CHN}我们的四个孙子孙女应该会比\n"
	.string "我丈夫更有成就。\p"
	.string "我的生活永远充满欢乐！$"

Route123_BerryMastersHouse_Text_Ah:
	.string "{CHN}啊……$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "{CHN}您好！\p"
	.string "这里是漂亮花瓣花店。\n"
	.string "让鲜花传遍全世界！$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{CHN}{PLAYER}{KUN}，您想了解\n"
	.string "树果吗？$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "{CHN}您叫什么名字？\p"
	.string "{PLAYER}{KUN}。\n"
	.string "真是个好名字。\p"
	.string "{PLAYER}{KUN}，您想了解\n"
	.string "树果吗？$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "{CHN}树果生长在只适于\n"
	.string "松软肥沃土壤的树上。\p"
	.string "如果您摘了一些树果，请务必\n"
	.string "在松软的土壤里再种一颗。\p"
	.string "种下的树果很快会发芽，\n"
	.string "长成植物，开出美丽的花，\l"
	.string "然后再次结出树果。\p"
	.string "我希望看到全世界\n"
	.string "开满美丽的花朵。\l"
	.string "那是我的梦想。\p"
	.string "请帮帮我，{PLAYER}{KUN}。种下树果\n"
	.string "让世界开满更多的花。$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "{CHN}鲜花给人们带来\n"
	.string "很多快乐，不是吗？$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "{CHN}您好！\p"
	.string "您越用心照顾花朵，\n"
	.string "它们就开得越美丽。\p"
	.string "您会喜欢照料花朵的。我确信\n"
	.string "这一点。这个给您。$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "{CHN}树果植物生长时，\n"
	.string "用吼吼鲸喷壶浇水。\p"
	.string "哦，还有一件事。\p"
	.string "如果一段时间不摘树果，\n"
	.string "它们就会掉到地上。\l"
	.string "但它们会再次发芽。\p"
	.string "是不是很厉害？\n"
	.string "就像它们有生存的意志一样。$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "{CHN}我想学我的姐姐们。\n"
	.string "我也在种花！\p"
	.string "给您！\n"
	.string "这是给您的！$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "{CHN}您可以种下树果让它长大，\n"
	.string "也可以让宝可梦携带它。\p"
	.string "但现在他们有了一台机器，可以\n"
	.string "混合不同的树果，做成\l"
	.string "给宝可梦的糖果。\p"
	.string "我也想要糖果。$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "{CHN}嗨，您叫什么名字？\p"
	.string "… … …  … … …  … … …\n"
	.string "好的。真不错！\p"
	.string "我叫小桐。\p"
	.string "爸爸妈妈给我起这个名字，是希望\n"
	.string "我健康、心地善良地长大。\l"
	.string "那是他们的愿望。\p"
	.string "您可以拿一个这个。$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "{CHN}小桐也把这颗树果给您！\n"
	.string "我真的好喜欢它！$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "{CHN}我想知道您的名字里\n"
	.string "包含了什么样的愿望。$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "{CHN}春、夏、秋、冬。\p"
	.string "如果您出生在春天，您喜欢\n"
	.string "春天吗？如果出生在\l"
	.string "夏天，您喜欢夏天吗？$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "{CHN}那小桐就是出生在秋天，\n"
	.string "所以我喜欢秋天！\p"
	.string "您喜欢哪个季节？$"

SootopolisCity_Text_OhDoesntMatter:
	.string "{CHN}哦……\n"
	.string "没关系……\p"
	.string "我有好多想知道的事……$"
