gText_Birch_Welcome::
	.string "{CHN}嗨！让你久等了！\p"
	.string "欢迎来到宝可梦的世界！\p"
	.string "我叫小田卷。\p"
	.string "大家都叫我宝可梦\n"
	.string "博士。\p"
	.string "$"

gText_Birch_Pokemon::
	.string "{CHN}这就是我们所说的“宝可梦”。\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "{CHN}这个世界里广泛栖息着\n"
	.string "被称为宝可梦的生物。\p"
	.string "我们人类与宝可梦一起生活，\n"
	.string "有时是友好的玩伴，\l"
	.string "有时是合作的伙伴。\p"
	.string "有时候，我们会结伴\n"
	.string "与其他人进行战斗。\p"
	.string "但尽管如此亲密，我们并不\n"
	.string "了解宝可梦的一切。\p"
	.string "事实上，关于宝可梦\n"
	.string "还有很多很多秘密。\p"
	.string "为了解开宝可梦的谜团，\n"
	.string "我一直在进行研究。\l"
	.string "这就是我的工作。\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "{CHN}你是谁？$"

gText_Birch_BoyOrGirl::
	.string "{CHN}你是男孩？\n"
	.string "还是女孩？$"

gText_Birch_WhatsYourName::
	.string "{CHN}好的。\n"
	.string "你叫什么名字？$"

gText_Birch_SoItsPlayer::
	.string "{CHN}所以你是{PLAYER}{KUN}？$"

gText_Birch_YourePlayer::
	.string "{CHN}啊，好的！\p"
	.string "你是{PLAYER}{KUN}，要搬到我的\n"
	.string "故乡未白镇。\l"
	.string "我明白了！\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{CHN}好了，你准备好了吗？\p"
	.string "你的冒险即将\n"
	.string "展开。\p"
	.string "拿出勇气，跳入\n"
	.string "宝可梦的世界吧，那里有\l"
	.string "梦想、冒险和友谊在等着你！\p"
	.string "那么，我期待着以后见到你。\n"
	.string "来我的宝可梦研究所找我吧。\p"
	.string "$"
