BerryBlender_Text_BlendWithTheBlendMaster:
	.string "{CHN}搅拌大师：没错就是我！\n"
	.string "我正是搅拌大师！\p"
	.string "与我一起搅拌，你将见证\n"
	.string "我搅拌技艺的精髓！$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "{CHN}搅拌大师：嗯！那么，你想\n"
	.string "亲眼见识我的技艺？$"

BerryBlender_Text_TooBusyNowIsee:
	.string "{CHN}嗯！\p"
	.string "原来如此，你现在很忙啊！\p"
	.string "但不要紧！\n"
	.string "我会在这里待一整天！\l"
	.string "忙完你的事就快来吧！$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "{CHN}嗯！\p"
	.string "你连一颗树果都没有！\p"
	.string "我会在这里待一整天！\n"
	.string "带着树果快回来吧！$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "{CHN}当然！\n"
	.string "当然！\p"
	.string "顺便说一句……\n"
	.string "你知道如何用树果\l"
	.string "搅拌出方块糖吗？$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "{CHN}嗯！\p"
	.string "啊，这其实很简单！\p"
	.string "当搅拌机的指针转到\n"
	.string "你的标记时，按下A键即可。\p"
	.string "你要做的就只有这些。\p"
	.string "当你看到我精确地按下\n"
	.string "A键时，你就会明白了。$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "{CHN}好！\p"
	.string "那就开始吧！\p"
	.string "与搅拌大师一起，\n"
	.string "来树果搅拌吧！$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "{CHN}嗯！\p"
	.string "你似乎还没有\n"
	.string "拿到方块糖盒！\p"
	.string "我会在这里待一整天！\n"
	.string "拿到方块糖盒后快回来吧！$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "{CHN}嗯！\p"
	.string "你的方块糖盒似乎已经满了！\p"
	.string "我会在这里待一整天！\n"
	.string "用掉一些方块糖后快回来吧！$"

BerryBlender_Text_WhoaAwesome:
	.string "{CHN}哇！\n"
	.string "太厉害了！$"

BerryBlender_Text_WickedlyFast:
	.string "{CHN}快得离谱！$"

BerryBlender_Text_WhatAnExpert:
	.string "{CHN}真是专家！$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "{CHN}当我和大师一起搅拌时，\n"
	.string "我们做出了惊人的方块糖！$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "{CHN}以机械般的专注\n"
	.string "追踪指针的双眼……\p"
	.string "以钟表般的精确\n"
	.string "敲击A键的手……\p"
	.string "拥有这些品质\n"
	.string "才使搅拌大师真正伟大。$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "{CHN}据说搅拌大师会在\n"
	.string "深山里磨练自己的技艺。\p"
	.string "有时，他会来水静市\n"
	.string "搅拌一整天的树果。$"
