CableClub_Text_WelcomeWhichCableClubService:
	.string "{CHN}欢迎来到宝可梦\n"
	.string "联线俱乐部。\p"
	.string "您想使用\n"
	.string "我们的哪项服务？$"

CableClub_Text_WhichService:
	.string "{CHN}您想使用\n"
	.string "我们的哪项服务？$"

CableClub_Text_TradeUsingLinkCable::
	.string "{CHN}使用GBA联机线与另一名玩家\n"
	.string "交换宝可梦。$"

CableClub_Text_BattleUsingLinkCable::
	.string "{CHN}你可以使用GBA联机线\n"
	.string "与另一名训练家对战。$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "{CHN}你可以使用GBA联机线\n"
	.string "与他人一起使用记录角。$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "{CHN}关闭此菜单。$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "{CHN}要进行双打对战，\n"
	.string "你必须至少有两只宝可梦。$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "{CHN}要交换，你必须\n"
	.string "至少带着两只宝可梦。$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "{CHN}携带着{STR_VAR_1}\n"
	.string "树果的宝可梦无法交换。$"

gText_PleaseWaitForLink::
	.string "{CHN}请稍候。\n"
	.string "…… …… B键：取消$"

gText_ConfirmLinkWhenPlayersReady::
	.string "{CHN}当所有玩家都准备好时……\n"
	.string "A键：确认\l"
	.string "B键：取消$"

gText_ConfirmStartLinkWithXPlayers::
	.string "{CHN}与{STR_VAR_1}名玩家开始联机。\n"
	.string "A键：确认\l"
	.string "B键：取消$"

gText_AwaitingLinkup::
	.string "{CHN}等待联机中……\n"
	.string "…… …… B键：取消$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "{CHN}联机前必须保存进度。\n"
	.string "可以保存吗？$"

CableClub_Text_PleaseEnter:
	.string "{CHN}请进入。$"

CableClub_Text_DirectYouToYourRoom:
	.string "{CHN}我现在带你去你的房间。$"

Text_SomeoneIsNotReadyToLink:
	.string "{CHN}有人还没准备好联机。\p"
	.string "请等大家\n"
	.string "都准备好后再来。$"

Text_LinkErrorPleaseReset:
	.string "{CHN}抱歉，出现联机错误……\n"
	.string "请重置后再试一次。$"

Text_PlayersMadeDifferentSelections:
	.string "{CHN}联机伙伴似乎\n"
	.string "做出了不同的选择。$"

CableClub_Text_PleaseVisitAgain:
	.string "{CHN}欢迎再次光临。$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "{CHN}参加人数\n"
	.string "不正确。$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "{CHN}单打对战模式\n"
	.string "无法由{STR_VAR_1}名玩家进行。$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "{CHN}双打对战模式\n"
	.string "无法由{STR_VAR_1}名玩家进行。$"

CableClub_Text_NeedFourPlayers:
	.string "{CHN}必须有四名玩家\n"
	.string "才能进行此对战模式。$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "{CHN}请确认玩家人数\n"
	.string "后重新开始。$"

Text_TerminateLinkConfirmation:
	.string "{CHN}如果你离开房间，\n"
	.string "联机将被终止。可以吗？$"

Text_TerminateLinkPleaseWait:
	.string "{CHN}正在终止联机……\n"
	.string "我们将带你离开\l"
	.string "房间。请稍候。$"

CableClub_Text_TooBusyToNotice:
	.string "{CHN}这位训练家忙得\n"
	.string "没空理会……$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "{CHN}太棒了！看到了{STR_VAR_1}的\n"
	.string "训练家卡片！$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "{CHN}太棒了！看到了{STR_VAR_1}的\n"
	.string "训练家卡片！\p"
	.string "是一张{STR_VAR_2}卡片！$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "{CHN}请就位并开始\n"
	.string "你的对战。$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "{CHN}请就座并开始\n"
	.string "你的交换。$"

RecordCorner_Text_ThanksForComing:
	.string "{CHN}感谢光临。$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "{CHN}训练家卡片数据\n"
	.string "将被覆盖。$"

CableClub_Text_HopeToSeeYouAgain:
	.string "{CHN}希望能再见到你！$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "{CHN}非常抱歉。\p"
	.string "我们还没有准备好\n"
	.string "与远方其他地区的\l"
	.string "训练家进行交换……$"

CableClub_Text_OtherTrainerNotReady:
	.string "{CHN}另一位训练家还没准备好。$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "{CHN}你至少有一只宝可梦\n"
	.string "无法被带走。$"

RecordCorner_Text_TakeSeatAndWait:
	.string "{CHN}请就座并等待。$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{CHN}{STR_VAR_1}送来了一个\n"
	.string "{STR_VAR_2}。$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "{CHN}抱歉，出现传输错误。\p"
	.string "你不能与日文版\n"
	.string "红宝石或蓝宝石游戏混合记录。\p"
	.string "此外，你也不能同时与日文版\n"
	.string "绿宝石和海外版红宝石\l"
	.string "或蓝宝石游戏混合记录。$"

CableClub_Text_AdapterNotConnected:
	.string "{CHN}无线适配器\n"
	.string "未正确连接。$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "{CHN}请参加者\n"
	.string "到接待柜台前来。$"

@ Unused
CableClub_Text_Hello:
	.string "{CHN}你好！$"

@ Unused
CableClub_Text_PleaseWait:
	.string "{CHN}请稍候。$"

CableClub_Text_YouMayTradeHere::
	.string "{CHN}你可以在这里与\n"
	.string "另一位训练家交换宝可梦。$"

CableClub_Text_YouMayBattleHere::
	.string "{CHN}你可以在这里与\n"
	.string "你的朋友们对战。$"

CableClub_Text_CanMakeBerryPowder::
	.string "{CHN}两到五名训练家可以\n"
	.string "一起制作树果粉末。$"

CableClub_Text_CanMixRecords::
	.string "{CHN}两到四名玩家的记录\n"
	.string "可以混合在一起。$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "{CHN}无线俱乐部\n"
	.string "各项服务的指南。$"

CableClub_Text_CancelSelectedItem::
	.string "{CHN}取消所选的菜单项。$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "{CHN}你想要哪种对战模式？$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "{CHN}返回上一步。$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "{CHN}要使用树果粉碎服务，\n"
	.string "你必须至少有一颗树果。$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "{CHN}要进入联谊室，你必须\n"
	.string "至少有两只宝可梦。$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "{CHN}携带着{STR_VAR_1}\n"
	.string "树果的宝可梦不得进入联谊室。$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "{CHN}这里是宝可梦无线俱乐部\n"
	.string "联谊室。\p"
	.string "很遗憾，你的无线\n"
	.string "适配器未正确连接。\p"
	.string "欢迎再次光临。$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "{CHN}哦……\n"
	.string "失陪！$"

CableClub_Text_PlayerIsWaiting:
	.string "{CHN}看来{STR_VAR_1}现在\n"
	.string "正在游玩。\l"
	.string "上吧！$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "{CHN}如果你愿意，我可以向你\n"
	.string "说明游戏规则。\p"
	.string "你想了解哪个游戏？$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "{CHN}“宝可梦跳绳”\p"
	.string "用A键让你的宝可梦跳过\n"
	.string "藤鞭绳子。\p"
	.string "只有28英寸左右的\n"
	.string "小型宝可梦才能参加。\p"
	.string "只会游泳、挖洞\n"
	.string "或飞行的宝可梦不擅长跳跃。\p"
	.string "因此，这些宝可梦\n"
	.string "不能参加。\p"
	.string "如果大家都能合拍跳跃，\n"
	.string "就会有好事发生。$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "{CHN}“嘟嘟利采果”\p"
	.string "指挥嘟嘟利的三个头\n"
	.string "接住掉落的树果。\p"
	.string "按{PLUS}控制板的右、上、左键\n"
	.string "来移动头部。\p"
	.string "要玩这个游戏，\n"
	.string "你必须有一只嘟嘟利。$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "{CHN}如果你想玩游戏，\n"
	.string "请告诉我旁边的老爷爷。$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "{CHN}嗨，欢迎！\n"
	.string "你是来玩使用\l"
	.string "无线通信的游戏吗？\p"
	.string "你能稍等一下吗？$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "{CHN}好的，再来啊！$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "{CHN}无线适配器未连接。\n"
	.string "连接好后再来吧！$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "{CHN}好的，你想\n"
	.string "玩哪个游戏？$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "{CHN}你想让哪只\n"
	.string "宝可梦参加？$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "{CHN}好了，一切就绪。\n"
	.string "别让其他人打败你！$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "{CHN}你现在要走了吗？\n"
	.string "一定要再来啊！$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "{CHN}看起来你没有任何\n"
	.string "可以参加的宝可梦……\p"
	.string "要我说明一下什么样的\n"
	.string "宝可梦可以参加吗？$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "{CHN}“宝可梦跳绳”面向28英寸\n"
	.string "左右的宝可梦。\p"
	.string "不能参加的是那些\n"
	.string "不会跳跃的宝可梦。\p"
	.string "你知道的，比如只会游泳、\n"
	.string "挖洞或飞行的宝可梦。\p"
	.string "你需要知道的就这些。$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "{CHN}嘟嘟利采果是一个\n"
	.string "只有嘟嘟利才能参加的游戏。$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "{CHN}能不能请你\n"
	.string "从头再试一次？$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "{CHN}欢迎来到宝可梦无线\n"
	.string "俱乐部直连角。\p"
	.string "你可以在这里与\n"
	.string "你的朋友们直接互动。\p"
	.string "你想进入\n"
	.string "哪个房间？$"

CableClub_Text_TradePokemon:
	.string "{CHN}你想交换宝可梦吗？$"

CableClub_Text_PlayWhichBattleMode:
	.string "{CHN}你想玩\n"
	.string "哪种对战模式？$"

CableClub_Text_AccessRecordCorner:
	.string "{CHN}你想使用\n"
	.string "记录角吗？$"

CableClub_Text_UseBerryCrush:
	.string "{CHN}你想使用\n"
	.string "树果粉碎系统吗？$"

CableClub_Text_ExplainBattleModes:
	.string "{CHN}共有三种对战模式。\p"
	.string "单打对战需要两名训练家，\n"
	.string "每人至少一只宝可梦。\p"
	.string "每名训练家一次只能\n"
	.string "派一只宝可梦上场。\p"
	.string "双打对战需要两名训练家，\n"
	.string "每人至少两只宝可梦。\p"
	.string "每名训练家一次\n"
	.string "派两只宝可梦上场。\p"
	.string "多人对战需要四名训练家，\n"
	.string "每人至少一只宝可梦。\p"
	.string "每名训练家一次只能\n"
	.string "派一只宝可梦上场。$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "{CHN}请决定你们两个中\n"
	.string "谁当队长。\p"
	.string "另一名玩家然后必须选择\n"
	.string "“加入队伍”。$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "{CHN}请决定你们四个中\n"
	.string "谁当队伍队长。\p"
	.string "其他玩家然后必须选择\n"
	.string "“加入队伍”。$"

CableClub_Text_ChooseGroupLeader:
	.string "{CHN}请决定你们中谁\n"
	.string "当队伍队长。\p"
	.string "其他玩家然后必须选择\n"
	.string "“加入队伍”。$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "{CHN}欢迎来到宝可梦无线\n"
	.string "俱乐部联谊室。\p"
	.string "你可以在这里与其他\n"
	.string "训练家直接互动，其中\l"
	.string "有些人你可能甚至不认识。\p"
	.string "你想进入联谊室吗？$"

CableClub_Text_UnionRoomInfo:
	.string "{CHN}联谊室里的训练家\n"
	.string "将是周围也进入了\l"
	.string "联谊室的玩家。\p"
	.string "你可以在这里做各种事情，\n"
	.string "比如互相问候。\p"
	.string "你可以带两只等级不超过\n"
	.string "30级的宝可梦进行一对一对战。\p"
	.string "你可以参加两到五人\n"
	.string "的聊天。\p"
	.string "或者，你可以登记\n"
	.string "一只宝可梦用于交换。\p"
	.string "你想进入联谊室吗？$"

CableClub_Text_EnjoyUnionRoom:
	.string "{CHN}希望你在联谊室\n"
	.string "度过愉快的时光。$"

CableClub_Text_FirstTimeRightThisWay:
	.string "{CHN}你好！\n"
	.string "我叫蒂拉。\p"
	.string "这一定是\n"
	.string "你第一次上来。\p"
	.string "我会向你介绍无线\n"
	.string "通信系统的运作方式。\p"
	.string "首先，我需要带你看看\n"
	.string "宝可梦中心的这一层。\p"
	.string "请这边走。$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "{CHN}顶层有两个\n"
	.string "房间。\p"
	.string "首先是左边的房间。\n"
	.string "那是联谊室。\p"
	.string "你可以与周围也进入了\n"
	.string "联谊室的\l"
	.string "训练家联机。\p"
	.string "你可以和他们聊天、\n"
	.string "对战和交换等。\p"
	.string "其次是右边的房间，\n"
	.string "那是直连角。\p"
	.string "你可以在这个房间与\n"
	.string "朋友交换或对战宝可梦。\p"
	.string "如果无线适配器未\n"
	.string "连接，你仍可以使用\l"
	.string "GBA联机线进行联机。\p"
	.string "如果是这种情况，你必须\n"
	.string "去直连角。\p"
	.string "希望你享受无线\n"
	.string "通信系统。$"

CableClub_Text_AskAboutLinking:
	.string "{CHN}你好，{PLAYER}！\p"
	.string "是我，蒂拉，宝可梦\n"
	.string "中心二楼的接待员。\p"
	.string "关于联机，你\n"
	.string "有什么要问我的吗？$"

CableClub_Text_ExplainWirelessClub:
	.string "{CHN}让我说明一下宝可梦\n"
	.string "无线俱乐部的运作方式。\p"
	.string "在顶层，有\n"
	.string "两个房间。\p"
	.string "首先是左边的房间。\n"
	.string "那是联谊室。\p"
	.string "你可以与周围也进入了\n"
	.string "联谊室的\l"
	.string "训练家联机。\p"
	.string "你可以和他们聊天、\n"
	.string "对战和交换等。\p"
	.string "其次是右边的房间，\n"
	.string "那是直连角。\p"
	.string "你可以在这个房间与\n"
	.string "朋友交换或对战宝可梦。\p"
	.string "有时，你可能无法\n"
	.string "在联谊室\l"
	.string "或直连角找到你的朋友。\p"
	.string "在这种情况下，请\n"
	.string "靠近你的朋友。\p"
	.string "如果无线适配器未\n"
	.string "连接，你仍可以使用\l"
	.string "GBA联机线进行联机。\p"
	.string "如果是这种情况，你必须\n"
	.string "去直连角。\p"
	.string "希望你享受无线\n"
	.string "通信系统。$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "{CHN}希望你享受无线\n"
	.string "通信系统。$"
