Text_PictureBookShelf:
	.string "{CHN}这里有一套宝可梦图画书。$"

Text_BookShelf:
	.string "{CHN}摆满了各种各样的书。$"

Text_PokemonCenterBookShelf:
	.string "{CHN}宝可梦杂志！\n"
	.string "宝可梦之友…\p"
	.string "宝可梦手册…\n"
	.string "可爱的宝可梦…$"

Text_Vase:
	.string "{CHN}这个花瓶看起来很昂贵…\n"
	.string "往里面看了看…\p"
	.string "但是，里面是空的。$"

Text_EmptyTrashCan:
	.string "{CHN}里面是空的。$"

Text_ShopShelf:
	.string "{CHN}货架上摆满了各种\n"
	.string "宝可梦商品。$"

Text_Blueprint:
	.string "{CHN}这是什么蓝图？\n"
	.string "太复杂了！$"
