gContestHallPaintingCaption::
	.string "{CHN}{STR_VAR_1}\n"
	.string "{STR_VAR_2}的{STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "{CHN}选拔赛$"

gContestRankNormal::
	.string "{CHN}普通级$"

gContestRankSuper::
	.string "{CHN}超级级$"

gContestRankHyper::
	.string "{CHN}高级$"

gContestRankMaster::
	.string "{CHN}大师级$"

gContestLink::
	.string "{CHN}联机$"

gContestCoolness::
	.string "{CHN}帅气$"

gContestBeauty::
	.string "{CHN}美丽$"

gContestCuteness::
	.string "{CHN}可爱$"

gContestSmartness::
	.string "{CHN}聪明$"

gContestToughness::
	.string "{CHN}强壮$"

gContestPaintingCool1::
	.string "{CHN}不停歇的超级酷——\n"
	.string "无可估量的{STR_VAR_1}$"

gContestPaintingCool2::
	.string "{CHN}嘿，这边！\n"
	.string "英俊的宝可梦{STR_VAR_1}$"

gContestPaintingCool3::
	.string "{CHN}奇迹般、精彩且\n"
	.string "非常了不起的{STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "{CHN}本世纪最后的维纳斯——\n"
	.string "美丽的{STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{CHN}{STR_VAR_1}那耀眼\n"
	.string "闪光的笑容$"

gContestPaintingBeauty3::
	.string "{CHN}宝可梦中心的超级偶像——\n"
	.string "无与伦比的{STR_VAR_1}$"

gContestPaintingCute1::
	.string "{CHN}可爱又甜美的{STR_VAR_1}$"

gContestPaintingCute2::
	.string "{CHN}漂亮的{STR_VAR_1}的\n"
	.string "获奖肖像$"

gContestPaintingCute3::
	.string "{CHN}给我们眨眨眼！\n"
	.string "可爱的宝可梦{STR_VAR_1}$"

gContestPaintingSmart1::
	.string "{CHN}聪明的大师——\n"
	.string "睿智的宝可梦{STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{CHN}{STR_VAR_1}——那只\n"
	.string "在所有宝可梦中被选中的$"

gContestPaintingSmart3::
	.string "{CHN}出色的{STR_VAR_1}的\n"
	.string "优雅时刻$"

gContestPaintingTough1::
	.string "{CHN}肌肉发达的\n"
	.string "速度之星{STR_VAR_1}$"

gContestPaintingTough2::
	.string "{CHN}强大、更强、\n"
	.string "最强的{STR_VAR_1}$"

gContestPaintingTough3::
	.string "{CHN}威猛强悍的\n"
	.string "超级宝可梦{STR_VAR_1}$"
