/* Contest move effect descriptions*/

gText_HighlyAppealingMove::
	.string "{CHN}极具魅力的招式。$"

gText_UserMoreEasilyStartled::
	.string "{CHN}使用此招式后，使用者\n"
	.string "会更容易被吓到。$"

gText_GreatAppealButNoMoreToEnd::
	.string "{CHN}能造成极佳的表演，\n"
	.string "但之后无法再进行表演。$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "{CHN}可以重复使用\n"
	.string "而不会让评审感到厌倦。$"

gText_AvoidStartledByOthersOnce::
	.string "{CHN}可以一次避免\n"
	.string "被其他人吓到。$"

gText_AvoidStartledByOthers::
	.string "{CHN}可以避免\n"
	.string "被其他人吓到。$"

gText_AvoidStartledByOthersLittle::
	.string "{CHN}可以稍微避免\n"
	.string "被其他人吓到。$"

gText_UserLessLikelyStartled::
	.string "{CHN}使用此招式后，使用者\n"
	.string "不容易被吓到。$"

gText_SlightlyStartleFrontMon::
	.string "{CHN}稍微吓到\n"
	.string "前方的宝可梦。$"

gText_SlightlyStartleAppealed::
	.string "{CHN}稍微吓到\n"
	.string "已经表演过的宝可梦。$"

gText_StartleAppealedBeforeUser::
	.string "{CHN}吓到在使用者之前\n"
	.string "表演的宝可梦。$"

gText_StartleAllAppealed::
	.string "{CHN}吓到所有已经\n"
	.string "表演过的宝可梦。$"

gText_BadlyStartleFrontMon::
	.string "{CHN}严重吓到\n"
	.string "前方的宝可梦。$"

gText_BadlyStartleAppealed::
	.string "{CHN}严重吓到已经\n"
	.string "表演过的宝可梦。$"

gText_StartleAppealedBeforeUser2::
	.string "{CHN}吓到在使用者之前\n"
	.string "表演的宝可梦。$"

gText_StartleAllAppealed2::
	.string "{CHN}吓到所有已经\n"
	.string "表演过的宝可梦。$"

gText_ShiftJudgesAttentionFromOthers::
	.string "{CHN}将评审的注意力\n"
	.string "从其他人身上转移。$"

gText_StartleMonHasJudgesAttention::
	.string "{CHN}吓到吸引了\n"
	.string "评审注意力的宝可梦。$"

gText_JamOthersMissesTurn::
	.string "{CHN}干扰其他人，并\n"
	.string "错过一轮表演。$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "{CHN}吓到进行了\n"
	.string "同属性表演的宝可梦。$"

gText_BadlyStartleCoolAppeals::
	.string "{CHN}严重吓到进行了\n"
	.string "帅气表演的宝可梦。$"

gText_BadlyStartleBeautyAppeals::
	.string "{CHN}严重吓到进行了\n"
	.string "美丽表演的宝可梦。$"

gText_BadlyStartleCuteAppeals::
	.string "{CHN}严重吓到进行了\n"
	.string "可爱表演的宝可梦。$"

gText_BadlyStartleSmartAppeals::
	.string "{CHN}严重吓到进行了\n"
	.string "聪明表演的宝可梦。$"

gText_BadlyStartleToughAppeals::
	.string "{CHN}严重吓到进行了\n"
	.string "强壮表演的宝可梦。$"

gText_MakeMonAfterUserNervous::
	.string "{CHN}让在使用者之后的\n"
	.string "一只宝可梦紧张。$"

gText_MakeAllMonsAfterUserNervous::
	.string "{CHN}让在使用者之后的\n"
	.string "所有宝可梦紧张。$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "{CHN}恶化已经表演过的\n"
	.string "宝可梦的状态。$"

gText_BadlyStartleMonsGoodCondition::
	.string "{CHN}严重吓到处于\n"
	.string "良好状态的宝可梦。$"

gText_AppealGreatIfPerformedFirst::
	.string "{CHN}如果第一个表演，\n"
	.string "效果会很棒。$"

gText_AppealGreatIfPerformedLast::
	.string "{CHN}如果最后一个表演，\n"
	.string "效果会很棒。$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "{CHN}使表演变得和\n"
	.string "之前的表演一样好。$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "{CHN}使表演变得和\n"
	.string "前一个一样好。$"

gText_AppealBetterLaterItsPerformed::
	.string "{CHN}越晚表演，\n"
	.string "效果越好。$"

gText_AppealVariesDependingOnTiming::
	.string "{CHN}表演的质量\n"
	.string "会因时机而异。$"

gText_WorksWellIfSameTypeAsBefore::
	.string "{CHN}如果与前一个表演\n"
	.string "同属性，效果会很好。$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "{CHN}如果与前一个表演\n"
	.string "属性不同，效果会很好。$"

gText_AffectedByAppealInFront::
	.string "{CHN}受前方表演的\n"
	.string "好坏影响。$"

gText_UpsConditionHelpsPreventNervousness::
	.string "{CHN}提升使用者的状态。\n"
	.string "有助于防止紧张。$"

gText_AppealWorksWellIfConditionGood::
	.string "{CHN}如果使用者的状态良好，\n"
	.string "表演效果会很好。$"

gText_NextAppealMadeEarlier::
	.string "{CHN}下一轮的表演可以\n"
	.string "提前进行。$"

gText_NextAppealMadeLater::
	.string "{CHN}下一轮的表演会\n"
	.string "延后进行。$"

gText_TurnOrderMoreEasilyScrambled::
	.string "{CHN}使下一轮的顺序\n"
	.string "更容易被打乱。$"

gText_ScrambleOrderOfNextAppeals::
	.string "{CHN}打乱下一轮\n"
	.string "表演的顺序。$"

gText_AppealExcitesAudienceInAnyContest::
	.string "{CHN}在任何选拔赛中\n"
	.string "都能让观众兴奋的表演。$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "{CHN}严重吓到所有\n"
	.string "表演得好的宝可梦。$"

gText_AppealBestMoreCrowdExcited::
	.string "{CHN}观众越兴奋，\n"
	.string "表演效果就越好。$"

gText_TemporarilyStopCrowdExcited::
	.string "{CHN}暂时阻止\n"
	.string "观众变得兴奋。$"

/* Unused move names*/

gText_RainDance::
	.string "{CHN}求雨$"

gText_Rage::
	.string "{CHN}愤怒$"

gText_FocusEnergy::
	.string "{CHN}聚气$"

gText_Hypnosis::
	.string "{CHN}催眠术$"

gText_Softboiled::
	.string "{CHN}生蛋$"

gText_HornAttack::
	.string "{CHN}角撞$"

gText_SwordsDance::
	.string "{CHN}剑舞$"

gText_Conversion::
	.string "{CHN}转换$"

gText_SunnyDay::
	.string "{CHN}大晴天$"

gText_Rest2::
	.string "{CHN}睡觉$"

gText_Vicegrip::
	.string "{CHN}夹住$"

gText_DefenseCurl::
	.string "{CHN}变圆$"

gText_LockOn::
	.string "{CHN}锁定$"

/* Contest type names*/

gContestMoveTypeCoolText::
	.string "{CHN}帅气$"

gContestMoveTypeBeautyText::
	.string "{CHN}美丽$"

gContestMoveTypeCuteText::
	.string "{CHN}可爱$"

gContestMoveTypeSmartText::
	.string "{CHN}聪明$"

gContestMoveTypeToughText::
	.string "{CHN}强壮$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "{CHN}第{STR_VAR_1}次表演！\n"
	.string "要使用哪个招式？$"

gText_AppealNumButItCantParticipate::
	.string "{CHN}第{STR_VAR_1}次表演！\n"
	.string "但它无法参加！$"

gText_MonAppealedWithMove::
	.string "{CHN}{STR_VAR_1}使用了\n"
	.string "{STR_VAR_2}！$"

gText_MonWasWatchingOthers::
	.string "{CHN}{STR_VAR_1}在观察\n"
	.string "其他人。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "{CHN}表演时间\n"
	.string "全部结束了！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

/* Unused appeal result texts*/

gText_ButAppealWasJammed::
	.string "{CHN}但表演被\n"
	.string "干扰了。$"

gText_FollowedAnotherMonsLead::
	.string "{CHN}它模仿了其他\n"
	.string "宝可梦的样子。$"

gText_ButItMessedUp::
	.string "{CHN}但它搞砸了。$"

gText_WentBetterThanUsual::
	.string "{CHN}比平时\n"
	.string "进行得更顺利。$"

gText_JudgeLookedAwayForSomeReason::
	.string "{CHN}评审不知为何\n"
	.string "看向了别处。$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "{CHN}它努力从过去的\n"
	.string "错误中吸取教训。$"

gText_CantMakeAnyMoreMoves::
	.string "{CHN}它无法再\n"
	.string "使用招式了。$"

gText_WorkedFrighteninglyWell::
	.string "{CHN}它表现得惊人地\n"
	.string "出色。$"

gText_WorkedHardAsStandoutMon::
	.string "{CHN}它和那只引人注目的\n"
	.string "宝可梦一样努力。$"

gText_JudgedLookedOnExpectantly::
	.string "{CHN}评审期待地\n"
	.string "注视着。$"

gText_WorkedRatherWell::
	.string "{CHN}它表现得相当不错。$"

gText_WorkedLittleBetterThanUsual::
	.string "{CHN}它比平时\n"
	.string "表现稍好一些。$"

/* Round result texts*/

gText_MonFailedToStandOutAtAll::
	.string "{CHN}{STR_VAR_1}完全没有\n"
	.string "引人注目……{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{CHN}{STR_VAR_1}不太\n"
	.string "引人注目……{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{CHN}{STR_VAR_1}引起了\n"
	.string "一点注意。{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{CHN}{STR_VAR_1}吸引了\n"
	.string "很多注意。{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{CHN}{STR_VAR_1}完全\n"
	.string "吸引了观众的目光。{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{CHN}{STR_VAR_1}还没\n"
	.string "进行表演。{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "{CHN}对{STR_VAR_1}的下一个\n"
	.string "表演充满了期待。$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "{CHN}评审对{STR_VAR_1}\n"
	.string "的看法保持不变。$"

gText_MonsXChangedPerceptions::
	.string "{CHN}{STR_VAR_1}的{STR_VAR_3}\n"
	.string "改变了观感。$"

gText_MonsAppealEffectWoreOff::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "效果消失了。$"

gText_SpecialAppealsEffectWoreOff::
	.string "{CHN}特殊表演的\n"
	.string "效果消失了。$"

gText_EveryonesAppealsMadeToLookSame::
	.string "{CHN}所有人的表演\n"
	.string "都被弄得看起来一样。$"

gText_CheapenedMonsAppeal::
	.string "{CHN}它贬低了\n"
	.string "{STR_VAR_2}的表演。$"

gText_CheapenedAppealOfThoseAhead::
	.string "{CHN}它贬低了前面那些\n"
	.string "宝可梦的表演。$"

gText_StoleAttentionAwayFromMon::
	.string "{CHN}它从{STR_VAR_2}那里\n"
	.string "抢走了注意力。$"

gText_CheapenedMonsAppeal2::
	.string "{CHN}它贬低了\n"
	.string "{STR_VAR_2}的表演。$"

gText_SeverelyCheapenedOtherAppeals::
	.string "{CHN}它严重贬低了\n"
	.string "其他表演。$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "{CHN}对{STR_VAR_1}的下一个\n"
	.string "表演充满了期待。$"

gText_CheapenedAppealOfThoseAhead2::
	.string "{CHN}它贬低了前面那些\n"
	.string "宝可梦的表演。$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "{CHN}它贬低了评审\n"
	.string "最喜爱的表演。$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "{CHN}其他人的表演\n"
	.string "被贬低了一半。$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "{CHN}它引人注目，\n"
	.string "弥补了被干扰的损失。$"

gText_CantParticipateInAppealsAnyMore::
	.string "{CHN}它无法再\n"
	.string "参加表演了。$"

gText_TouchedJudgeForFantasticAppeal::
	.string "{CHN}它打动了评审，\n"
	.string "呈现了精彩的表演。$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "{CHN}对接下来表演的\n"
	.string "期待提升了。$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "{CHN}它和特殊表演\n"
	.string "一样引人注目。$"

gText_StoodOutAsMuchAsMon::
	.string "{CHN}它和{STR_VAR_1}\n"
	.string "一样引人注目。$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "{CHN}被干扰的表演变得\n"
	.string "更加不显眼了。$"

gText_EveryonesAppealsMadeSame::
	.string "{CHN}所有人的表演\n"
	.string "都被弄得相同了。$"

/* Appeal result texts*/

gText_BecameMoreConsciousOfOtherMons::
	.string "{CHN}它变得更在意\n"
	.string "其他宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{CHN}{STR_VAR_1}在这之后\n"
	.string "无法再进行表演了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "{CHN}它稍微\n"
	.string "冷静了一些。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "{CHN}它变得对其他\n"
	.string "宝可梦视而不见了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "{CHN}它变得更不在意\n"
	.string "其他宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "{CHN}它不再那么在意\n"
	.string "其他宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "{CHN}它试图吓到\n"
	.string "其他宝可梦。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "{CHN}它试图让别人\n"
	.string "目眩。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "{CHN}评审不再看\n"
	.string "{STR_VAR_1}了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "{CHN}它试图让下一只\n"
	.string "宝可梦紧张。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{CHN}{STR_VAR_1}变得\n"
	.string "紧张了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "{CHN}表演试图让等待中的\n"
	.string "宝可梦紧张。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "{CHN}它嘲弄了表现\n"
	.string "良好的宝可梦。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{CHN}{STR_VAR_1}恢复了\n"
	.string "状态。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "{CHN}它试图干扰表现\n"
	.string "良好的宝可梦。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{CHN}引人注目的{STR_VAR_1}\n"
	.string "更加卖力了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "{CHN}不太引人注目的\n"
	.string "{STR_VAR_1}努力了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "{CHN}它和前面的\n"
	.string "宝可梦一样努力。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "不太顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "{CHN}它和前面的\n"
	.string "宝可梦一样努力。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "不太顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "不太顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "还算顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "进行得相当顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "进行得非常出色。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "毫无效果。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "效果不太好。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "还算顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "进行得相当顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "进行得非常顺利。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{CHN}{STR_VAR_1}的表演\n"
	.string "进行得非常出色。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "{CHN}与前一只宝可梦同属性——\n"
	.string "太棒了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "{CHN}与前一个不同属性——\n"
	.string "太棒了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "{CHN}它比前面的\n"
	.string "宝可梦更引人注目。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "{CHN}它没有前面的\n"
	.string "宝可梦表现得好。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{CHN}{STR_VAR_1}的状态\n"
	.string "提升到了平常之上。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{CHN}{STR_VAR_1}的火热状态\n"
	.string "成就了精彩的表演！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "{CHN}它在下次表演的\n"
	.string "顺序中前移了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "{CHN}它在下次表演的\n"
	.string "顺序中后移了一次。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "{CHN}它打乱了下一轮\n"
	.string "的表演顺序。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "{CHN}评审期待地\n"
	.string "看着{STR_VAR_1}。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "{CHN}表演连击\n"
	.string "效果不错。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "{CHN}表演连击\n"
	.string "效果非常好。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "{CHN}表演连击\n"
	.string "效果非常出色。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{CHN}{STR_VAR_1}成功地\n"
	.string "移开了视线。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{CHN}{STR_VAR_1}成功地\n"
	.string "避免了看到它。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{CHN}{STR_VAR_1}不会被\n"
	.string "那种事情吓到。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{CHN}{STR_VAR_1}变得\n"
	.string "有点分心了。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "{CHN}它试图吓到\n"
	.string "其他宝可梦。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{CHN}{STR_VAR_1}因为分心\n"
	.string "低下了头。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{CHN}{STR_VAR_1}因为分心\n"
	.string "回过头去。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{CHN}{STR_VAR_1}忍不住\n"
	.string "发出了叫声。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{CHN}{STR_VAR_1}忍不住\n"
	.string "跳了起来。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{CHN}{STR_VAR_1}因为分心\n"
	.string "绊了一跤。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{CHN}{STR_VAR_1}紧张得\n"
	.string "无法动弹。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "{CHN}但它搞砸了。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "{CHN}但它没能让\n"
	.string "目标紧张。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "{CHN}但它没能让\n"
	.string "任何人紧张。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "{CHN}但它被忽视了……{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "{CHN}但它无法提升\n"
	.string "自己的状态……{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "{CHN}它糟糕的状态\n"
	.string "导致了无力的表演。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{CHN}{STR_VAR_1}没有\n"
	.string "受到影响。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{CHN}{STR_VAR_1}因重复表演\n"
	.string "而令人失望。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{CHN}{STR_VAR_1}的{STR_VAR_3}\n"
	.string "效果非常好。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{CHN}{STR_VAR_1}的{STR_VAR_3}\n"
	.string "在这里效果不好……{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{CHN}{STR_VAR_1}的{STR_VAR_3}\n"
	.string "让观众兴奋起来。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{CHN}{STR_VAR_1}下一轮\n"
	.string "无法表演……{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "{CHN}它吸引了\n"
	.string "观众的注意。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "{CHN}观众继续\n"
	.string "观看{STR_VAR_3}。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{CHN}{STR_VAR_1}的\n"
	.string "{STR_VAR_2}被忽视了。{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "{CHN}羞怯$"

gText_Contest_Anxiety::
	.string "{CHN}焦虑$"

gText_Contest_Laziness::
	.string "{CHN}懒惰$"

gText_Contest_Hesitancy::
	.string "{CHN}犹豫$"

gText_Contest_Fear::
	.string "{CHN}恐惧$"

gText_Contest_Coolness::
	.string "{CHN}帅气$"

gText_Contest_Beauty::
	.string "{CHN}美丽$"

gText_Contest_Cuteness::
	.string "{CHN}可爱$"

gText_Contest_Smartness::
	.string "{CHN}聪明$"

gText_Contest_Toughness::
	.string "{CHN}强壮$"

@ Unused
gText_Tension::
	.string "{CHN}紧张$"

gText_CoolMove::
	.string "{CHN}帅气招式$"

gText_BeautyMove::
	.string "{CHN}美丽招式$"

gText_CuteMove::
	.string "{CHN}可爱招式$"

gText_SmartMove::
	.string "{CHN}聪明招式$"

gText_ToughMove::
	.string "{CHN}强壮招式$"

gText_3QuestionMarks::
	.string "{CHN}？？？$"
