/* With the exception of Link standby, none of the below texts are used*/

gTest_MissedTurn::
	.string "{CHN}错过回合$"

gText_LinkStandby4::
	.string "{CHN}联机待机！$"

gText_WinnerIsPlayersMonCongrats::
	.string "{CHN}获胜者是{STR_VAR_1}的{STR_VAR_2}！\n"
	.string "恭喜！$"

gText_WinnerIsPlayersMon::
	.string "{CHN}获胜者是{STR_VAR_1}的{STR_VAR_2}！{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "{CHN}第一次评审：第{STR_VAR_1}号{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "{CHN}第二次评审：第{STR_VAR_1}号{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "{CHN}设定事件：第{STR_VAR_1}号{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "{CHN}最常使用的招式：\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "{CHN}最令人印象深刻的宝可梦：\n"
	.string "{STR_VAR_1}的{STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "{CHN}设定事件：第{STR_VAR_1}号{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "{CHN}由于训练家输了，\n"
	.string "将不会制作联机电视节目。{PAUSE_UNTIL_PRESS}$"
