EventTicket_Text_ShowOldSeaMap:
	.string "{CHN}前往凯那市的渡轮……\p"
	.string "您说什么？\n"
	.string "我们可以航行到地图上的这个地方吗？\p"
	.string "我知道有谁能更好地帮助您。\n"
	.string "请稍等。$"

EventTicket_Text_ThatPass:
	.string "{CHN}前往凯那市的渡轮……\p"
	.string "哦？\n"
	.string "那张通行证……$"

EventTicket_Text_ShowEonTicket:
	.string "{CHN}哎，伙计，是你带了那张\n"
	.string "古怪无比的通行证吗？\p"
	.string "我告诉你，你要去的是\n"
	.string "南方远方的一座小岛。\p"
	.string "谁也不知道我们到达那里\n"
	.string "后会遇到什么，哎。\l"
	.string "真叫我毛骨悚然！\p"
	.string "全员上船！$"

EventTicket_Text_SouthernIslandSailBack:
	.string "{CHN}哎，伙计，这座不起眼的小岛\n"
	.string "上没什么可看可玩的。\p"
	.string "我们还是回水静市怎么样？$"

EventTicket_Text_SailHome:
	.string "{CHN}哎，好吧，那就！\n"
	.string "我们就启程回家！$"

EventTicket_Text_AsYouLike:
	.string "{CHN}哎，好吧，随您喜欢吧。$"

SouthernIsland_Interior_Text_Sign:
	.string "{CHN}“所有的梦境不过是另一种现实。\n"
	.string "永远不要忘记……”$"

SouthernIsland_Exterior_Text_Sign:
	.string "{CHN}“记忆消逝之人试图将\n"
	.string "它们铭刻于心……”$"
