EventTicket_Text_OldSeaMapTooFar:
	.string "{CHN}怎么了，小家伙？\p"
	.string "什么，你说你有一张\n"
	.string "破旧的地图？\p"
	.string "让我看看。\n"
	.string "…… …… …… …… …… ……\p"
	.string "天哪，这可相当远啊。\n"
	.string "恐怕我帮不了你……$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "{CHN}布里内：等一下！\p"
	.string "你怎么能拒绝\n"
	.string "一个我欠他人情的人？$"

EventTicket_Text_BrineyLetsSail:
	.string "{CHN}{PLAYER}{KUN}，真是对不起。\p"
	.string "你来找我寻求帮助，\n"
	.string "我们却差点把你拒之门外。\p"
	.string "好吧，让我弥补这一切。\p"
	.string "我们当然马上启程！\p"
	.string "让我们用这张\n"
	.string "古老海图找到这座岛吧！$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "{CHN}是你带了那张奇怪的\n"
	.string "船票吗？\p"
	.string "你要去的是一座\n"
	.string "遥远无比的岛屿。\p"
	.string "没人知道那里等待着什么……\p"
	.string "一想到这些，作为\n"
	.string "航海人的我就热血沸腾！\p"
	.string "上船吧，小家伙！$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "{CHN}布里内船长有时真是\n"
	.string "喜怒无常得让人抓狂……\p"
	.string "你想返回水静市吗？$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "{CHN}这岛形状真怪，是吧？\n"
	.string "你想返回水静市吗？$"

EventTicket_Text_OddTicketsWhereTo:
	.string "{CHN}是你带了那些\n"
	.string "奇怪的船票吗？\p"
	.string "…… …… ……嗯。\p"
	.string "这些船票能带你去\n"
	.string "遥远无比的岛屿。\p"
	.string "没人知道那里等待着什么，\n"
	.string "也不知道那里会发生什么。\p"
	.string "一想到这些，作为\n"
	.string "航海人的我就热血沸腾！\p"
	.string "上船吧，小家伙！\n"
	.string "我们先航行到哪里？$"

NavelRock_Harbor_Text_SailorReturn:
	.string "{CHN}你……你听到了吗？\n"
	.string "从深处传来的低沉咆哮声。\p"
	.string "你确定这里安全吗？\n"
	.string "我们是不是该离开了？$"

FarawayIsland_Entrance_Text_Sign:
	.string "{CHN}字迹逐渐褪去，\n"
	.string "仿佛是很久以前写的……\p"
	.string "“……月，第6天\n"
	.string "如果有人类……再次\l"
	.string "踏上这里……愿他是个善良的……\l"
	.string "……怀着这份希望，我离……”$"

FarawayIsland_Interior_Text_Mew:
	.string "{CHN}梦幻……$"
