@ Battle Tower
gText_AnabelWonSilver::
	.string "{CHN}真让人失望……$"

gText_AnabelDefeatSilver::
	.string "{CHN}好吧，我明白了……$"

gText_AnabelWonGold::
	.string "{CHN}非常抱歉……$"

gText_AnabelDefeatGold::
	.string "{CHN}谢谢你……$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "{CHN}啊哈哈！你不觉得难为情吗？\n"
	.string "大家都在看着呢！$"

gText_TuckerDefeatSilver::
	.string "{CHN}呃……\n"
	.string "怎么会……$"

gText_TuckerWonGold::
	.string "{CHN}我的巨蛋王牌称号可不是浪得虚名！$"

gText_TuckerDefeatGold::
	.string "{CHN}啊哈哈！\n"
	.string "你真令人振奋！$"

@ Battle Factory
gText_NolandWonSilver::
	.string "{CHN}干得好！\n"
	.string "这可是堂好课，是吧？$"

gText_NolandDefeatSilver::
	.string "{CHN}做得好！\n"
	.string "你很清楚自己在做什么！$"

gText_NolandWonGold::
	.string "{CHN}嘿，嘿，嘿！\n"
	.string "你已经结束了吗？$"

gText_NolandDefeatGold::
	.string "{CHN}这里发生了什么？$"

@ Battle Pike
gText_LucyWonSilver::
	.string "{CHN}哼……$"

gText_LucyDefeatSilver::
	.string "{CHN}呃……$"

gText_LucyWonGold::
	.string "{CHN}哈！$"

gText_LucyDefeatGold::
	.string "{CHN}可恶！$"

@ Battle Arena
gText_GretaWonSilver::
	.string "{CHN}哎呀，得了吧！\n"
	.string "你得更加努力才行！$"

gText_GretaDefeatSilver::
	.string "{CHN}不可能！\n"
	.string "干得不错！$"

gText_GretaWonGold::
	.string "{CHN}嘿嘿！\n"
	.string "你还指望什么？$"

gText_GretaDefeatGold::
	.string "{CHN}啊？\n"
	.string "你认真的吗？！$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "{CHN}你的宝可梦之所以软弱，\n"
	.string "是因为作为训练家的你太软弱了！$"

gText_SpenserDefeatSilver::
	.string "{CHN}啊……\n"
	.string "这可真是与众不同……$"

gText_SpenserWonGold::
	.string "{CHN}哇哈哈哈！\n"
	.string "我的同胞们，我们无所畏惧！$"

gText_SpenserDefeatGold::
	.string "{CHN}哇哈！\n"
	.string "哈哈哈哈！$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "{CHN}嘿！你怎么了！\n"
	.string "拿出点干劲来！站起来！$"

gText_BrandonDefeatSilver::
	.string "{CHN}就是这样！你做得太棒了！\n"
	.string "你为这一刻付出了努力！$"

gText_BrandonWonGold::
	.string "{CHN}嘿！你别放弃啊！\n"
	.string "站起来！不要对自己失去信心！$"

gText_BrandonDefeatGold::
	.string "{CHN}就是这样！你做到了！\n"
	.string "你一直为此努力着！$"
