LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "{CHN}这里是宝可梦抽奖角落。\p"
	.string "在我们百货商店购物的所有顾客\n"
	.string "都可以抽取一张宝可梦抽奖券。\p"
	.string "如果抽奖券的号码与您任何一只\n"
	.string "宝可梦的ID号码一致，\l"
	.string "您将获得一份精美礼物。\p"
	.string "您想抽取一张宝可梦\n"
	.string "抽奖券吗？$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "{CHN}请明天再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "{CHN}请再次光临。$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "{CHN}请抽取一张抽奖券。\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "{CHN}抽奖券号码是{STR_VAR_1}。\p"
	.string "我需要核对一下这个号码\n"
	.string "看看是否与您任何一只\l"
	.string "宝可梦的ID号码一致。请稍候。$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "{CHN}恭喜您！\p"
	.string "您队伍中\n"
	.string "{STR_VAR_1}的ID号码与您的\l"
	.string "抽奖券号码一致！$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "{CHN}恭喜您！\p"
	.string "您电脑盒子里的\n"
	.string "{STR_VAR_1}的ID号码与您的\l"
	.string "抽奖券号码一致！$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "{CHN}很抱歉。\n"
	.string "没有一个号码匹配。$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "{CHN}有两位数字匹配，所以您获得了\n"
	.string "三等奖！\l"
	.string "您赢得了{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "{CHN}有三位数字匹配，所以您获得了\n"
	.string "二等奖！\l"
	.string "您赢得了{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "{CHN}有四位数字匹配，所以您获得了\n"
	.string "一等奖！\l"
	.string "您赢得了{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "{CHN}天哪，五位数字\n"
	.string "全部匹配！\p"
	.string "您赢得了头奖！\n"
	.string "您赢得了{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "{CHN}哦？\n"
	.string "您似乎没有空间放这个。\p"
	.string "请在您的背包里腾出空间\n"
	.string "然后告诉我。$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{CHN}{PLAYER}？\n"
	.string "是的，我一直在等您。\p"
	.string "这是我们一直为您保留的\n"
	.string "奖品。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "{CHN}请再次光临。$"
