MatchCall_WildBattleText1::
	.string "{CHN}嗨！{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "不久前我看到了这只{STR_VAR_2}\n"
	.string "但是没能捉住它。\p"
	.string "就差那么一点点！\n"
	.string "那么，再见啦！$"

MatchCall_WildBattleText2::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "刚才我试着去捉一只\n"
	.string "不错的{STR_VAR_2}。\p"
	.string "但是，它跑掉了。\n"
	.string "我真是大失所望！\p"
	.string "好，拜拜！$"

MatchCall_WildBattleText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "我刚试着去捉\n"
	.string "这只{STR_VAR_2}，但它溜走了。\p"
	.string "就差那么一点点！\p"
	.string "我今天真倒霉…\n"
	.string "好啦，再见！$"

MatchCall_WildBattleText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你知道宝可梦{STR_VAR_2}吗？\n"
	.string "我差一点就捉到一只了。\p"
	.string "就在不久前的事。\n"
	.string "我以为抓住了它，但它逃跑了。\p"
	.string "如果我再看到它，我一定会\n"
	.string "捉住它的。\p"
	.string "好，回头见。$"

MatchCall_WildBattleText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\l"
	.string "最近有捉到宝可梦吗？\p"
	.string "不久前我差一点就捉到了一只，\n"
	.string "但它跑掉了。\p"
	.string "好，保重！$"

MatchCall_WildBattleText6::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "最近有捉到宝可梦吗？\p"
	.string "前几天我差一点就捉到了一只。\n"
	.string "但不知怎么被它逃了。\p"
	.string "保重啊。$"

MatchCall_WildBattleText7::
	.string "{CHN}…呃，{PLAYER}{KUN}？\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "哦，等等！等等！\n"
	.string "我能捉到这只{STR_VAR_2}…\p"
	.string "啊啊啊！它跑掉了！\n"
	.string "就差那么一点点！$"

MatchCall_WildBattleText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近捉宝可梦\n"
	.string "还顺利吗？\p"
	.string "不久前我差一点就捉到了，\n"
	.string "但目标逃走了。\p"
	.string "我还得再努力！\n"
	.string "再见啦！$"

MatchCall_WildBattleText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "怎么样？你有没有收集到\n"
	.string "更多宝可梦？\p"
	.string "我真是倒霉透顶！\n"
	.string "它们全跑掉了！\p"
	.string "再见！$"

MatchCall_WildBattleText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听着，我差一点点就捉到了\n"
	.string "这只{STR_VAR_2}…\p"
	.string "但是，它溜走了…\p"
	.string "我需要再努力一些。\n"
	.string "回见。$"

MatchCall_WildBattleText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "你最近怎么样？\p"
	.string "我刚才试着捉一只野生的{STR_VAR_2}，\n"
	.string "但它逃掉了。\p"
	.string "我好沮丧…$"

MatchCall_WildBattleText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还在捉宝可梦吗？\p"
	.string "我也一直在试着捉它们，\n"
	.string "但不太容易。\p"
	.string "宝可梦的世界真是深奥！$"

MatchCall_WildBattleText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "你有在捉宝可梦吗？\p"
	.string "我也一直在试着捉它们，\n"
	.string "但没什么成果。\p"
	.string "宝可梦的世界真是深奥！$"

MatchCall_WildBattleText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "就在刚才，我试着去捉一只可爱的\n"
	.string "{STR_VAR_2}。\p"
	.string "不过它跑掉了！\n"
	.string "哦，你不知道我有多失望！\p"
	.string "拜拜！$"

MatchCall_WildBattleText15::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "我一直在想试着去\n"
	.string "捉些宝可梦。\p"
	.string "但我一只也找不到。\n"
	.string "真是让我百思不解！\p"
	.string "我都束手无策了！\n"
	.string "回见！$"

MatchCall_NegativeBattleText1::
	.string "{CHN}嗨！{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我试着和另一个训练家对战，\n"
	.string "但我输了。\p"
	.string "真是令人失望。\n"
	.string "好，再见啦！$"

MatchCall_NegativeBattleText2::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "在我们对战之后，\n"
	.string "我又挑战了别人。\p"
	.string "差一点就赢了，但最后\n"
	.string "还是输了。哎，算了！$"

MatchCall_NegativeBattleText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "我刚在对战中被虐了。\p"
	.string "看来我需要再好好培育\n"
	.string "我的队伍！$"

MatchCall_NegativeBattleText4::
	.string "{CHN}嘿，{PLAYER}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "昨天我又打了一场对战，\n"
	.string "但没能赢下来。\p"
	.string "我的队伍还需要多加培育。\n"
	.string "好，回头见。$"

MatchCall_NegativeBattleText5::
	.string "{CHN}嗨呀，{PLAYER}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近怎么样？\p"
	.string "我一直在对战，\n"
	.string "但没赢过几次。\p"
	.string "我状态不太好。\n"
	.string "好，保重！$"

MatchCall_NegativeBattleText6::
	.string "{CHN}嘿，{PLAYER}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近怎么样？\p"
	.string "我最近对战很努力，\n"
	.string "但战果不佳。\p"
	.string "我找不到感觉。\n"
	.string "保重啊。$"

MatchCall_NegativeBattleText7::
	.string "{CHN}我是{STR_VAR_1}。\n"
	.string "最近怎么样？\p"
	.string "昨天我输了一场对战，\n"
	.string "满脑子都在想这件事。\p"
	.string "我得想个办法…\n"
	.string "再见。$"

MatchCall_NegativeBattleText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你的宝可梦怎么样？\n"
	.string "前几天我输了一场对战。\p"
	.string "我需要再努力一些！\n"
	.string "再见啦！$"

MatchCall_NegativeBattleText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "听着听着，你一定要听听\n"
	.string "这个！\p"
	.string "我刚才打了一场宝可梦对战，\n"
	.string "但在最后一秒输了。\p"
	.string "哦，气死我了！$"

MatchCall_NegativeBattleText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\p"
	.string "刚才我打了一场对战。\n"
	.string "不过我输了。\p"
	.string "我需要再好好培育宝可梦。\n"
	.string "回见。$"

MatchCall_NegativeBattleText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "你的宝可梦怎么样？\p"
	.string "我又输了一场对战。\p"
	.string "好，再见！$"

MatchCall_NegativeBattleText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还在努力对战吗？\p"
	.string "至于我，最近输了，所以我\n"
	.string "正在重新训练队伍。\p"
	.string "下次再见。$"

MatchCall_NegativeBattleText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "希望你一切都好。\p"
	.string "就在刚才\n"
	.string "我打了一场对战。\p"
	.string "{PLAYER}{KUN}，要像我一样积极活动哦。\n"
	.string "再见啦！$"

MatchCall_NegativeBattleText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你还好吗？\p"
	.string "不过你应该偶尔回家\n"
	.string "看看。\p"
	.string "拜拜！$"

MatchCall_PositiveBattleText1::
	.string "{CHN}嗨！{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "刚才我和另一个训练家对战了。\n"
	.string "我赢了！我赢了！\p"
	.string "我的{STR_VAR_2}真的很努力\n"
	.string "为我拼搏。太棒了！$"

MatchCall_PositiveBattleText2::
	.string "{CHN}你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "昨天我打了一场对战，\n"
	.string "我赢了！太棒了！$"

MatchCall_PositiveBattleText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}！\l"
	.string "你的对战怎么样？\p"
	.string "我前几天打了一场对战，\n"
	.string "我的{STR_VAR_2}大显神威！\p"
	.string "下次我和你对战时，\n"
	.string "{PLAYER}，输的绝不会是我！$"

MatchCall_PositiveBattleText4::
	.string "{CHN}嘿，{PLAYER}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我刚才打了一场对战。\n"
	.string "我赢了，但很惊险。\p"
	.string "我的{STR_VAR_2}表现\n"
	.string "非常出色。$"

MatchCall_PositiveBattleText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近怎么样？\n"
	.string "有在对战吗？\p"
	.string "我刚才赢了！\n"
	.string "我的{STR_VAR_2}太厉害了！\p"
	.string "你等着。下次我一定会打败你！\n"
	.string "好，保重！$"

MatchCall_PositiveBattleText6::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近怎么样？\p"
	.string "我最近运气很好。\n"
	.string "嘿，我刚赢了一场对战。\p"
	.string "下次我们对战时，\n"
	.string "我一定不会输！$"

MatchCall_PositiveBattleText7::
	.string "{CHN}{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我的{STR_VAR_2}太强了！\n"
	.string "它刚帮我赢了一场对战！\p"
	.string "我等不及要和你\n"
	.string "再战一场了。$"

MatchCall_PositiveBattleText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "希望你一切都好。\n"
	.string "我要告诉你我刚才赢了。\p"
	.string "我的{STR_VAR_2}特别\n"
	.string "努力地拿下了胜利。\p"
	.string "再见啦！$"

MatchCall_PositiveBattleText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "你的宝可梦怎么样？\n"
	.string "我的刚赢了一场对战！\p"
	.string "我的{STR_VAR_2}表现精彩，\n"
	.string "我必须说！\p"
	.string "真希望你能看到！\n"
	.string "再见啦！$"

MatchCall_PositiveBattleText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近过得怎么样？\p"
	.string "我的宝可梦似乎\n"
	.string "充满了能量。\p"
	.string "我刚和它们赢了一场对战。\n"
	.string "回见。$"

MatchCall_PositiveBattleText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "最近有对战吗？\n"
	.string "我今天又赢了一场！\p"
	.string "我势如破竹！嘎哈哈哈！\n"
	.string "好，再见！$"

MatchCall_PositiveBattleText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "你一切都好吧？\n"
	.string "我仍然精神矍铄！\p"
	.string "嘿，就在刚才，我又赢了一场对战。\n"
	.string "我可不会把位置让给\l"
	.string "你们这些年轻人！$"

MatchCall_PositiveBattleText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "希望你一切都好。\n"
	.string "我仍然健步如飞！\p"
	.string "嘿，我又赢了一场对战。\n"
	.string "哦，我可不会轻易\n"
	.string "输给年轻人！\p"
	.string "再见啦！$"

MatchCall_PositiveBattleText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我最近打了一场对战，我的\n"
	.string "{STR_VAR_2}表现异常出色！\p"
	.string "真希望你能看到，\n"
	.string "{PLAYER}{KUN}。拜拜！$"

MatchCall_SameRouteBattleRequestText1::
	.string "{CHN}嗨！{PLAYER}，你好啊！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "嗯？等等，你在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "哦，哇，那我们一定要对战！\n"
	.string "我会等你的！再见！$"

MatchCall_SameRouteBattleRequestText2::
	.string "{CHN}你好，{PLAYER}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "哦？你现在正好在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "现在要不要对战一场？\n"
	.string "我会等你的！再见！$"

MatchCall_SameRouteBattleRequestText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "哦，嘿，你现在在\n"
	.string "{STR_VAR_2}附近吗？\p"
	.string "现在要不要和我\n"
	.string "对战一场？\p"
	.string "我不会再输了！\n"
	.string "我会等你的！回头见！$"

MatchCall_SameRouteBattleRequestText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你现在在哪里？\n"
	.string "嗯？{STR_VAR_2}？\p"
	.string "现在要不要对战？\n"
	.string "我会等你的。再见！$"

MatchCall_SameRouteBattleRequestText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\l"
	.string "你最近怎么样？\p"
	.string "你在哪里？\n"
	.string "{STR_VAR_2}？\p"
	.string "那，要不要马上\n"
	.string "来一场再战？\p"
	.string "我会留意你的。\n"
	.string "回头见！$"

MatchCall_SameRouteBattleRequestText6::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "你的宝可梦还好吗？\p"
	.string "哦，是吗？你在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "那，我们最好来一场\n"
	.string "再战。\p"
	.string "我可以等。\n"
	.string "再见！$"

MatchCall_SameRouteBattleRequestText7::
	.string "{CHN}…呃，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}…\p"
	.string "哦，你正好在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "那么，我们对战吧。\n"
	.string "马上开始。\p"
	.string "我会让你看看我的宝可梦。\n"
	.string "我会等你的。$"

MatchCall_SameRouteBattleRequestText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "希望你一切都好。\n"
	.string "哦，你在{STR_VAR_2}附近。\p"
	.string "那要不要和我\n"
	.string "来一场对战？\p"
	.string "我会等你的。\n"
	.string "回头见！$"

MatchCall_SameRouteBattleRequestText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "你最近还跟得上吗？\n"
	.string "哦，你在{STR_VAR_2}附近？\p"
	.string "哦，那你不觉得我们\n"
	.string "应该对战吗？\p"
	.string "别让我等太久！$"

MatchCall_SameRouteBattleRequestText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你最近怎么样？\n"
	.string "哦，你在{STR_VAR_2}附近。\p"
	.string "那我们现在应该对战一场。\p"
	.string "我准备好了，等着你。\n"
	.string "快来！$"

MatchCall_SameRouteBattleRequestText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "啊，你现在所在的地方\n"
	.string "是{STR_VAR_2}？\p"
	.string "那，我们非得来一场\n"
	.string "对战不可，你觉得呢？\p"
	.string "我会在这里等你！\n"
	.string "马上见！$"

MatchCall_SameRouteBattleRequestText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你现在在哪里？\p"
	.string "{STR_VAR_2}？\n"
	.string "那相当近！\p"
	.string "你说我们现在来一场对战\n"
	.string "怎么样？\p"
	.string "我可以等。\n"
	.string "再见！$"

MatchCall_SameRouteBattleRequestText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "希望你一切都好。\n"
	.string "哦，你在{STR_VAR_2}附近？\p"
	.string "既然不远，\n"
	.string "就来找我对战吧。\p"
	.string "我会等你的。\n"
	.string "先再见了。$"

MatchCall_SameRouteBattleRequestText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你说什么？…{STR_VAR_2}？\n"
	.string "那非常近。\p"
	.string "你不觉得我们应该来一场\n"
	.string "对战吗？\p"
	.string "我会去找你的！\n"
	.string "拜拜！$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "{CHN}嗨！{PLAYER}，你好啊！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "要不要和我对战一场？\p"
	.string "我会在{STR_VAR_2}\n"
	.string "附近等你！$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "{CHN}你好，{PLAYER}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "要不要再和我\n"
	.string "对战一场？\p"
	.string "你可以在{STR_VAR_2}\n"
	.string "附近找到我。我会等你的！$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "自从上次见面，我的宝可梦\n"
	.string "变得更强大了。\p"
	.string "我想看看它们和你的宝可梦相比\n"
	.string "有多强，{PLAYER}。\p"
	.string "所以，我们对战吧！\p"
	.string "我会在{STR_VAR_2}\n"
	.string "附近等你。$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "你最近怎么样？\p"
	.string "我的宝可梦最近变得\n"
	.string "相当强了。\p"
	.string "嘿，要不要再和我\n"
	.string "对战一场？\p"
	.string "我们在{STR_VAR_2}\n"
	.string "附近见，好吗？$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我的宝可梦正在\n"
	.string "茁壮成长。\p"
	.string "我真的很想再和你\n"
	.string "对战一场。\p"
	.string "我会在{STR_VAR_2}附近留意你。\n"
	.string "回头见！$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切顺利。\p"
	.string "我在想我想再和你\n"
	.string "对战一场。你觉得呢？\p"
	.string "如果你想对战，\n"
	.string "就来{STR_VAR_2}吧。\p"
	.string "再见！$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "{CHN}…呃，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}…\l"
	.string "怎么样？你的宝可梦在成长吗？\p"
	.string "我的肯定变强了。\n"
	.string "我想给你看看。\p"
	.string "我会在{STR_VAR_2}附近。\n"
	.string "来找我对战吧。\p"
	.string "回见。$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "希望你一切都好。\n"
	.string "我的宝可梦非常活泼。\p"
	.string "如果你有机会到附近来，请\n"
	.string "和我再战一场。\p"
	.string "我会在{STR_VAR_2}附近。\n"
	.string "到时候见，再见！$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "你的宝可梦怎么样？\p"
	.string "我的宝可梦越来越厉害了。\n"
	.string "我想给你看看，{PLAYER}{KUN}。\p"
	.string "我现在在{STR_VAR_2}附近，\n"
	.string "所以如果你在附近，就对战吧。\p"
	.string "希望能很快见到你！$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\l"
	.string "那么，你最近怎么样？\p"
	.string "我的宝可梦比以前\n"
	.string "强多了。\p"
	.string "我很想再和你对战一场，\n"
	.string "{PLAYER}{KUN}。\p"
	.string "我会在{STR_VAR_2}附近。\n"
	.string "如果在附近就来看看我吧。$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "你现在在哪里？\p"
	.string "我的宝可梦充满活力。\n"
	.string "它们似乎很期待\l"
	.string "见到你的宝可梦，{PLAYER}{KUN}。\p"
	.string "我现在在{STR_VAR_2}附近。\n"
	.string "希望你能来找我们。$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "我应该告诉你，我的宝可梦\n"
	.string "最近变得相当强壮了。\p"
	.string "我想看它们和\n"
	.string "你对战，{PLAYER}{KUN}。\p"
	.string "我们会在{STR_VAR_2}附近。\n"
	.string "随时来看看我们！$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "你的宝可梦还好吗？\p"
	.string "我的宝可梦非常健康，\n"
	.string "看起来不会输！\p"
	.string "我当然很愿意再和你\n"
	.string "对战一场。\p"
	.string "如果你在{STR_VAR_2}附近，\n"
	.string "就来看看我们吧。$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切都好。\p"
	.string "哦，对！我的宝可梦\n"
	.string "比以前强多了。\p"
	.string "你不觉得我们应该来一场\n"
	.string "对战吗，{PLAYER}{KUN}？\p"
	.string "我们会在{STR_VAR_2}\n"
	.string "附近等你。\p"
	.string "随时来看看我们，好吗？$"

MatchCall_PersonalizedText1::
	.string "{CHN}是我，热爱大山的\n"
	.string "{STR_VAR_1}！\p"
	.string "嘿，自从我们相遇后，你有没有\n"
	.string "更欣赏大山了？\p"
	.string "我很少在山里看到你…\p"
	.string "下次，我们在\n"
	.string "{STR_VAR_2}附近见吧。$"

MatchCall_PersonalizedText2::
	.string "{CHN}我是{STR_VAR_1}。\n"
	.string "你好。\p"
	.string "我刚才在跟一个新的训练家\n"
	.string "说起你。\p"
	.string "我告诉她有一位强大的训练家\n"
	.string "用心培育宝可梦的故事。\p"
	.string "我希望你能成为一位\n"
	.string "人人都钦佩的训练家。\p"
	.string "希望我们能再见！$"

MatchCall_PersonalizedText3::
	.string "{CHN}你好！我是{STR_VAR_1}。\p"
	.string "我喜欢我现在所在的地方。\n"
	.string "这里很惬意，香气甜美！\p"
	.string "我想有人种了树果，\n"
	.string "它们开满了花。\p"
	.string "改天再见！$"

MatchCall_PersonalizedText4::
	.string "{CHN}你好！探索三十年，\n"
	.string "{STR_VAR_1}为你效劳！\p"
	.string "看来你正精力充沛地\n"
	.string "到处旅行。\p"
	.string "你有没有发现什么新遗迹？\n"
	.string "如果有的话请告诉我！\p"
	.string "那么，失陪了，\n"
	.string "我还有遗迹要探索。$"

MatchCall_PersonalizedText5::
	.string "{CHN}我是{STR_VAR_1}！\p"
	.string "知道我今天在做什么吗？\n"
	.string "在海滩上看海浪！\p"
	.string "唉…海浪闪闪发光。\n"
	.string "从这儿看海最美了。\l"
	.string "我饿了，拜拜！$"

MatchCall_PersonalizedText6::
	.string "{CHN}嚼嚼嚼…\n"
	.string "哦，嗨，我是{STR_VAR_1}。\l"
	.string "我喜欢在海滩上吃东西。\p"
	.string "我和我的宝可梦过得\n"
	.string "很好。我们能量满满！\l"
	.string "我要去游泳了。拜拜！$"

MatchCall_PersonalizedText7::
	.string "{CHN}你好，我是{STR_VAR_1}…\p"
	.string "我对这整个酷酷训练家\n"
	.string "的事有点厌倦了…\p"
	.string "每个人都觉得我是个完美的\n"
	.string "训练家，这让我努力\l"
	.string "去达到那种期望。\p"
	.string "但我想这就是成为\n"
	.string "酷酷训练家的代价吧。\p"
	.string "我只能咬牙坚持…\n"
	.string "笑着承受。\p"
	.string "你是我唯一能这样\n"
	.string "倾诉的人。\p"
	.string "但下次见到你时，\n"
	.string "别担心，我不会发牢骚！$"

MatchCall_PersonalizedText8::
	.string "{CHN}呀呼，我是{STR_VAR_1}！\n"
	.string "你好吗？\p"
	.string "我一直在以你为目标\n"
	.string "培育我的宝可梦。\p"
	.string "当我们再次对战时，\n"
	.string "我不打算输。\p"
	.string "有训练家朋友\n"
	.string "不是很好吗？再见！$"

MatchCall_PersonalizedText9::
	.string "{CHN}我是{STR_VAR_1}…\n"
	.string "现在，在你身后…\l"
	.string "是不是有什么东西…？\p"
	.string "在送火山沉睡的\n"
	.string "宝可梦的力量…\p"
	.string "它在向我诉说关于你的事…\p"
	.string "你应该快步离开，\n"
	.string "并且永远不要回头…\p"
	.string "咯咯咯…\n"
	.string "再会…$"

MatchCall_PersonalizedText10::
	.string "{CHN}我是{STR_VAR_1}。\n"
	.string "你好吗？\p"
	.string "我们能这样远距离聊天\n"
	.string "不是很方便吗？\p"
	.string "以前，如果我想和\n"
	.string "任何人说话，都得让我爸爸\l"
	.string "开车送我…\p"
	.string "我得走了。\n"
	.string "很高兴能和你聊天。$"

MatchCall_PersonalizedText11::
	.string "{CHN}我是{STR_VAR_1}！\n"
	.string "你听听这个！\p"
	.string "我很喜欢野生原野区，\n"
	.string "但每次去，我都会迷路！\p"
	.string "全是高高的草丛！\n"
	.string "而且地方太大了！\p"
	.string "把这话吐出来\n"
	.string "感觉好多了！\p"
	.string "我又要去野生原野区了！\n"
	.string "回头见！$"

MatchCall_PersonalizedText12::
	.string "{CHN}你好，我是{STR_VAR_1}。\n"
	.string "是的，没错，我很富有，是的。\p"
	.string "我得告诉你，自从我们上次见面，\n"
	.string "我的财富又增长了。\p"
	.string "而且，我的宝可梦也\n"
	.string "变得更强了。\p"
	.string "我总觉得\n"
	.string "这个世界是为我而存在的！\p"
	.string "哦，不用你说！\n"
	.string "大家都知道这是真的！\p"
	.string "哦，抱歉，我有个\n"
	.string "正式晚宴要参加。$"

MatchCall_PersonalizedText13::
	.string "{CHN}呜呼呼呼…\n"
	.string "是我，{STR_VAR_1}…\p"
	.string "你能猜到我在看什么吗？\n"
	.string "一对{STR_VAR_2}在对战。\p"
	.string "也许我会试着捉住胜者…\n"
	.string "呜呼呼呼呼…\p"
	.string "我…我现在有点忙。\n"
	.string "我得走了。$"

MatchCall_PersonalizedText14::
	.string "{CHN}哦，是{STR_VAR_1}！\p"
	.string "我刚才在想我已经对废弃船\n"
	.string "感到厌倦了。\p"
	.string "但既然我已经在这里了，\n"
	.string "而且我想打败你一次，\l"
	.string "我会再待一段时间。\p"
	.string "如果你有兴致，何不\n"
	.string "来看看我？\p"
	.string "我觉得今天就是我终于挑战\n"
	.string "隔壁那个家伙的日子。\p"
	.string "回见！$"

MatchCall_PersonalizedText15::
	.string "{CHN}我是{STR_VAR_1}！\n"
	.string "大海的男人！\p"
	.string "你知道我怎么想吗？\p"
	.string "海上的训练家\n"
	.string "是强者中的强者！\p"
	.string "你应该向我学习，在\n"
	.string "海里训练…\p"
	.string "哎呀，大浪来了！\p"
	.string "这是绝佳的训练机会！\n"
	.string "抱歉，我得走了！$"

MatchCall_PersonalizedText16::
	.string "{CHN}我是{STR_VAR_1}！听着，我一直在\n"
	.string "教我的宝可梦空手道。\p"
	.string "但现在它们比我厉害了！\n"
	.string "我一直在输给它们！\p"
	.string "但即使我可能输给\n"
	.string "宝可梦，我也不会输给另一个\l"
	.string "训练家，绝不！\p"
	.string "我们一定要再战一场！\n"
	.string "呜哇！$"

MatchCall_PersonalizedText17::
	.string "{CHN}是我，{STR_VAR_1}。\n"
	.string "你的旅途怎么样？\p"
	.string "…哇，真的吗？\n"
	.string "听起来真刺激！\p"
	.string "我觉得我可以为你的一段\n"
	.string "经历写首歌。\p"
	.string "…哦，嘿，我有感觉了。\n"
	.string "我脑子里响起了吉他声。\p"
	.string "我得赶紧把这首曲子好好\n"
	.string "写下来，所以我得走了！回头见！$"

MatchCall_PersonalizedText18::
	.string "{CHN}我是{STR_VAR_1}…\n"
	.string "听听我的新歌。\p"
	.string "啦啦啦，{STR_VAR_2}，{STR_VAR_2}！\n"
	.string "你为什么那么{STR_VAR_2}？\l"
	.string "为什么我不能成为你，{STR_VAR_2}？\l"
	.string "啦啦，{STR_VAR_2}和{STR_VAR_1}，\l"
	.string "{STR_VAR_1}和{STR_VAR_2}…\p"
	.string "重复副歌，渐弱…$"

MatchCall_PersonalizedText19::
	.string "{CHN}我是{STR_VAR_1}，你知道的，\n"
	.string "那个露营专家！\p"
	.string "我们对战时，我\n"
	.string "忍不住输给了你。\p"
	.string "毕竟，我的专长是\n"
	.string "露营。\p"
	.string "但无论输赢，我露营时\n"
	.string "都喜欢对战。\p"
	.string "再和我们战一场吧，好吗？\n"
	.string "哦，也一起去露营吧！$"

MatchCall_PersonalizedText20::
	.string "{CHN}是我，是我，{STR_VAR_1}！\p"
	.string "老实说，我想爬爬\n"
	.string "这座山以外的其他山。\p"
	.string "但我不确定其他山上\n"
	.string "会不会有像烟囱山上的女士。\p"
	.string "如果你知道其他有女士的\n"
	.string "山，告诉我！\p"
	.string "嘿嘿嘿，回见！$"

MatchCall_PersonalizedText21::
	.string "{CHN}… … … … … …\n"
	.string "… … … … … …\l"
	.string "我是{STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "今天就到这里…$"

MatchCall_PersonalizedText22::
	.string "{CHN}我是{STR_VAR_1}。今天，我有\n"
	.string "一种会和你聊天预感。\p"
	.string "我打败你的欲望日以继夜\n"
	.string "地膨胀。\p"
	.string "你有一位这样的对手，对吧？\n"
	.string "我希望那是我…\p"
	.string "很高兴你听我说完。\n"
	.string "再见！$"

MatchCall_PersonalizedText23::
	.string "{CHN}我是{STR_VAR_1}。\p"
	.string "当附近有一位强大的训练家时，\n"
	.string "我有时能感应\l"
	.string "到。\p"
	.string "你刚从附近经过吗，{PLAYER}{KUN}？\n"
	.string "也许那就是你。\p"
	.string "我会等你的造访。\n"
	.string "拜拜！$"

MatchCall_PersonalizedText24::
	.string "{CHN}你好，我是{STR_VAR_1}。\n"
	.string "你听起来不错，{PLAYER}{KUN}。\p"
	.string "我周游过世界，\n"
	.string "但我得说我非常喜欢\l"
	.string "这个地区。\p"
	.string "我打算在这里待一段时间。\n"
	.string "也许我们能再见？\p"
	.string "我没有忘记你那些\n"
	.string "耀眼的技巧。\p"
	.string "我确实希望能再战一场。$"

MatchCall_PersonalizedText25::
	.string "{CHN}抽泣…是…{STR_VAR_1}…\n"
	.string "…呜呜…\p"
	.string "杜鹃今天在课堂上\n"
	.string "狠狠训了我一顿。\p"
	.string "但我并不讨厌她。\p"
	.string "杜鹃确切地告诉我哪里\n"
	.string "做错了，这样我就能从中学习。\p"
	.string "我当然明天还要去\n"
	.string "训练家学校！\p"
	.string "回头见！$"

MatchCall_PersonalizedText26::
	.string "{CHN}我是{STR_VAR_1}！\p"
	.string "杜鹃昨天让我和她\n"
	.string "对战了。\p"
	.string "结果…\n"
	.string "很惨，不用说也知道。\p"
	.string "但我很高兴杜鹃\n"
	.string "愿意让我挑战她！\p"
	.string "你不会相信我\n"
	.string "有多崇拜她！\p"
	.string "我要真的集中精力努力！\n"
	.string "我得走了！$"

MatchCall_PersonalizedText27::
	.string "{CHN}嗨，我是安娜！今天我又和\n"
	.string "我的搭档梅格在一起。\p"
	.string "我真的很喜欢照顾梅格和\n"
	.string "宝可梦。它们太可爱了！\p"
	.string "我真希望能像照顾\n"
	.string "弟妹一样照顾它们！\p"
	.string "哦，嗨，梅格！\n"
	.string "你买到面包了吗？\p"
	.string "嗯？不，不，我没有把你\n"
	.string "当我的私人仆人！\p"
	.string "你输了那场对战，所以你\n"
	.string "得去面包作为惩罚！\p"
	.string "我不会把你当仆人的，\n"
	.string "梅格！你对我来说太特别了！\p"
	.string "我得走了。\n"
	.string "吃点心的时间到了！$"

MatchCall_PersonalizedText28::
	.string "{CHN}我爱宝可梦！\n"
	.string "我是粉丝俱乐部的{STR_VAR_1}！\p"
	.string "你一定要听听这个！\n"
	.string "我可爱的宝可梦…\p"
	.string "哼哼！哇哈哈！\n"
	.string "我不能再说了！这是秘密！\l"
	.string "它简直可爱得无法形容！\p"
	.string "哦，我可爱的{STR_VAR_2}在讨\n"
	.string "宝可方块了！\p"
	.string "那画面太可爱了！\p"
	.string "抱歉，我现在不能聊了！\n"
	.string "下次再听吧！$"

MatchCall_PersonalizedText29::
	.string "{CHN}哦呵呵！\p"
	.string "我是{STR_VAR_1}！我等不及要\n"
	.string "告诉你我亲爱的宝可梦！\p"
	.string "请务必听听这个。\n"
	.string "是关于我亲爱的{STR_VAR_2}。\p"
	.string "每当有人把它拿起来，\n"
	.string "它就直跳进我怀里！\p"
	.string "哦…哦…还有比这\n"
	.string "更幸福的事吗？\p"
	.string "哦，感觉真是太美好了！\p"
	.string "我很高兴能和你分享\n"
	.string "我的一些幸福。\p"
	.string "好了，我得走了。\n"
	.string "拜拜！$"

MatchCall_PersonalizedText30::
	.string "{CHN}我是…{STR_VAR_1}。\n"
	.string "人们称我为专家。\p"
	.string "但有一件事我知道。\n"
	.string "我无法仅凭自己\l"
	.string "的力量成为专家。\p"
	.string "只有借助宝可梦的力量，\n"
	.string "训练家才能成为专家。\p"
	.string "哼！我想我说了\n"
	.string "一些深奥的话！\p"
	.string "我心情很好地告辞了！$"

MatchCall_PersonalizedText31::
	.string "{CHN}我是{STR_VAR_1}。\n"
	.string "很高兴和你聊天！\p"
	.string "我泡在这个温泉浴缸里\n"
	.string "感觉神清气爽。\p"
	.string "自从我们见面后，我一直在和\n"
	.string "年轻的训练家对战，但你仍是\l"
	.string "其中最棒的。\p"
	.string "我想你老了以后\n"
	.string "会成为专家的！哦呵呵呵…$"

MatchCall_PersonalizedText32::
	.string "{CHN}耶！我是{STR_VAR_1}！\n"
	.string "怎么样？\p"
	.string "可能是我的错觉，但当我\n"
	.string "赢得对战时，我的短裤好像\l"
	.string "感觉，嗯，更好了。材质上。\p"
	.string "我这么说是什么意思？\n"
	.string "有点难以解释，但是…\l"
	.string "我该怎么说呢…\l"
	.string "我的短裤感觉更丝滑了！\p"
	.string "而当我和你对战时，{PLAYER}{KUN}，\n"
	.string "我的短裤感觉又黏又粗。\p"
	.string "… … … … … …\n"
	.string "你不会真的相信吧？\l"
	.string "嘿嘿嘿，就这些！拜拜！$"

MatchCall_PersonalizedText33::
	.string "{CHN}啊哈！\n"
	.string "{STR_VAR_1}在此！\p"
	.string "一如既往，我在疯狂地\n"
	.string "钓鱼！\p"
	.string "除了海和河，还有\n"
	.string "其他地方可以钓鱼吗？\p"
	.string "我有种强烈的冲动，想在\n"
	.string "几乎任何地方钓鱼！\p"
	.string "哦，天哪，糟糕！\n"
	.string "我的线缠住了！\p"
	.string "我得走了！\n"
	.string "给我找些新钓点吧！$"

MatchCall_PersonalizedText34::
	.string "{CHN}嘿，你好！我是{STR_VAR_1}。\n"
	.string "你过得随意吗？\p"
	.string "你知道，从小到大，\n"
	.string "我一直很平和，对吧？\p"
	.string "我从来不太喜欢\n"
	.string "紧张或急躁。\p"
	.string "但你知道吗，\n"
	.string "我现在是个三项运动员。\p"
	.string "你永远不知道生活会\n"
	.string "把你带向何方，如果你明白我的意思。\p"
	.string "你现在是个训练家，但谁知道\n"
	.string "未来会怎样，嗯？\p"
	.string "想象自己成为老师，\n"
	.string "或者艺术家。很酷，对吧？\p"
	.string "但是，嘿，放轻松。随意点。\n"
	.string "回见。$"

MatchCall_PersonalizedText35::
	.string "{CHN}我是{STR_VAR_1}！\n"
	.string "我正在骑自行车。\p"
	.string "我喜欢游泳和跑步，\n"
	.string "但骑自行车是我的最爱！\p"
	.string "它让我的全身感觉\n"
	.string "仿佛与风融为一体。\p"
	.string "它让我兴奋得\n"
	.string "像在飞一样！\p"
	.string "好！今天，我要刷新\n"
	.string "自行车道的纪录！\p"
	.string "你也应该来挑战！\n"
	.string "再见！$"

MatchCall_PersonalizedText36::
	.string "{CHN}哟，我是{STR_VAR_1}！我正\n"
	.string "在三项全能比赛中！\p"
	.string "但是，嘿，我总有时间\n"
	.string "聊聊天！\p"
	.string "和宝可梦一起锻炼感觉\n"
	.string "真不错！\p"
	.string "不用言语交流，我们就能同步，\n"
	.string "仿佛共享一颗心。\p"
	.string "真令人振奋！\p"
	.string "喘…边跑边聊…\n"
	.string "我快不行了…\l"
	.string "喘…得…走了…$"

MatchCall_PersonalizedText37::
	.string "{CHN}嗨，我是{STR_VAR_1}。\n"
	.string "如果你想提高耐力，\l"
	.string "高原训练是关键！\p"
	.string "试着在山顶上跑步。\n"
	.string "你很快就会气喘吁吁！\p"
	.string "我也缺氧了！\n"
	.string "再见！$"

MatchCall_PersonalizedText38::
	.string "{CHN}哦，你好，我是{STR_VAR_1}。\p"
	.string "我一直在游泳，但似乎\n"
	.string "还是到不了彩幽市。\p"
	.string "也许我一直在原地转圈。\p"
	.string "不，不，那不可能。\n"
	.string "哇哈哈哈。\l"
	.string "保重！$"

MatchCall_PersonalizedText39::
	.string "{CHN}嘿，我是{STR_VAR_1}…\n"
	.string "哎呀！\p"
	.string "哗啦！\p"
	.string "咕噜咕噜咕噜咕噜…\p"
	.string "哗啦！\p"
	.string "呼哧呼哧！呼哧呼哧！\p"
	.string "嘿！抱歉！\n"
	.string "我刚涂了防晒油。\p"
	.string "所以我的宝可梦导航器滑\n"
	.string "从我手中掉进了水里！\p"
	.string "但是，天哪，得佛的宝可梦导航器真\n"
	.string "结实。泡了水也没事！\p"
	.string "总之，我在忙日光浴，\n"
	.string "下次再聊吧。$"

MatchCall_PersonalizedText40::
	.string "{CHN}你好，我是{STR_VAR_1}。\p"
	.string "三项全能三个项目中，\n"
	.string "我最喜欢游泳。\p"
	.string "但如果我在海里待太久，\n"
	.string "不会变得皱巴巴的吗？\p"
	.string "哦，三项全能真是一项残酷的\n"
	.string "人类耐力测试！拜拜！$"

MatchCall_PersonalizedText41::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你的宝可梦怎么样？\p"
	.string "我的龙宝可梦似乎\n"
	.string "处于巅峰状态。先再见了。$"

MatchCall_PersonalizedText42::
	.string "{CHN}我是{STR_VAR_1}。\p"
	.string "我的{STR_VAR_2}比\n"
	.string "上次更强了。\p"
	.string "我不会再输给你了。\n"
	.string "你等着下次吧！\p"
	.string "回见！$"

MatchCall_PersonalizedText43::
	.string "{CHN}我是{STR_VAR_1}。\p"
	.string "我一直在继续\n"
	.string "隐身术的修行。\p"
	.string "但我太成功了。\n"
	.string "没人能找到我。\l"
	.string "我的成功让我孤独…\p"
	.string "如烟般消散！\n"
	.string "再会！$"

MatchCall_PersonalizedText44::
	.string "{CHN}我是{STR_VAR_1}。\n"
	.string "自我们相遇后，我一直坚持训练。\p"
	.string "我的{STR_VAR_2}变得\n"
	.string "相当强了。\p"
	.string "在海滩上训练很有效，\n"
	.string "和我想的一样。拜拜！$"

MatchCall_PersonalizedText45::
	.string "{CHN}你好吗？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我不知道这些讨厌的火山灰\n"
	.string "什么时候才会停？\p"
	.string "如果积得太深，会盖住\n"
	.string "我阳伞上的花纹…\p"
	.string "约好再见面吧！$"

MatchCall_PersonalizedText46::
	.string "{CHN}嗨，我是{STR_VAR_1}。\p"
	.string "你知道吗？在海里比在泳池\n"
	.string "里更容易漂浮。\p"
	.string "只要静静地躺着，你的身体\n"
	.string "就会自己浮起来。\p"
	.string "但如果浮得太久，\n"
	.string "小心别被冲得\l"
	.string "太远。\p"
	.string "…我到底在哪儿？\n"
	.string "我得走了！$"

MatchCall_PersonalizedText47::
	.string "{CHN}哦，{PLAYER}{KUN}，你好！\n"
	.string "我是{STR_VAR_1}。\l"
	.string "我现在在山上。\p"
	.string "但地面太颠簸了。\n"
	.string "我没法在这里搭帐篷…\p"
	.string "哦，我有了一个绝妙的主意！\p"
	.string "也许我能让我的宝可梦\n"
	.string "把这里的地面压平！\p"
	.string "我要试试那个！\n"
	.string "拜拜！$"

MatchCall_PersonalizedText48::
	.string "{CHN}哦，嗨，嗨，我是{STR_VAR_1}！\p"
	.string "我和莉芙一起培育宝可梦！\n"
	.string "我们非常努力！\p"
	.string "如果我们更努力，能成为\n"
	.string "第一名吗？拜拜！$"

MatchCall_PersonalizedText49::
	.string "{CHN}我是{STR_VAR_1}！\p"
	.string "我是个水手，但我现在\n"
	.string "不在船上。\p"
	.string "这让我想知道——\n"
	.string "陆地上的水手该叫什么？\p"
	.string "这就是我一边凝视着海浪\n"
	.string "一边思考的问题。\p"
	.string "好，下次见！$"

MatchCall_PersonalizedText50::
	.string "{CHN}我是{STR_VAR_1}。\n"
	.string "怎么样？捉到更多宝可梦了吗？\p"
	.string "如果你捉到了新宝可梦，\n"
	.string "一定要来给我看看。\p"
	.string "我不会发牢骚的，真的。\n"
	.string "我会等你的。再见。$"

MatchCall_PersonalizedText51::
	.string "{CHN}我是{STR_VAR_1}。\p"
	.string "你有没有以最佳方式\n"
	.string "培育你的宝可梦？\p"
	.string "我所在的地方空气清新。\n"
	.string "这是培育\l"
	.string "宝可梦的完美环境。\p"
	.string "如果你想专心培育\n"
	.string "宝可梦，你应该来\l"
	.string "{STR_VAR_2}。保重。$"

MatchCall_PersonalizedText52::
	.string "{CHN}嗨，我是{STR_VAR_1}。\p"
	.string "我给了我的{STR_VAR_2}一个宝可方块。\n"
	.string "它似乎非常喜欢。\p"
	.string "看来宝可梦对宝可方块也有\n"
	.string "自己的喜好。\p"
	.string "我觉得这很迷人。\n"
	.string "请多保重。$"

MatchCall_PersonalizedText53::
	.string "{CHN}我是{STR_VAR_1}。\p"
	.string "如果你和宝可梦合作，\n"
	.string "在野外也能过得很舒适。\p"
	.string "每个人都应该意识到这一点，\n"
	.string "并更多地与宝可梦合作。\p"
	.string "那就理想了。\n"
	.string "我真的这么认为。\p"
	.string "我觉得你走在正确的道路上！\n"
	.string "回头见！$"

MatchCall_PersonalizedText54::
	.string "{CHN}嗨，我是{STR_VAR_1}。你知道，\n"
	.string "那个时刻准备的训练家！\p"
	.string "{PLAYER}{KUN}，你的道具够用吗？\n"
	.string "你的宝可梦准备好行动了吗？\p"
	.string "时刻保持一切完美\n"
	.string "是让你的旅程\l"
	.string "持续下去的秘诀。\p"
	.string "我得去检查我自己的\n"
	.string "补给了！保持警惕！$"

MatchCall_PersonalizedText55::
	.string "{CHN}我是{STR_VAR_1}！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "{STR_VAR_2}是一条非常繁忙的\n"
	.string "干道，所以我每天被各种\l"
	.string "训练家挑战。\p"
	.string "今天，我赢了五场输\n"
	.string "了三场！\p"
	.string "你今天怎么样？\n"
	.string "下次告诉我，好吗？$"

MatchCall_PersonalizedText56::
	.string "{CHN}是我，{STR_VAR_1}。\p"
	.string "我很受欢迎，因为\n"
	.string "我有很多虫宝可梦，对吧？\p"
	.string "嗯，我今天带了一堆我最喜欢的\n"
	.string "虫子去学校。\p"
	.string "我喜欢的那个女孩哭了！\n"
	.string "想笑就笑吧。\p"
	.string "我得试着教她\n"
	.string "虫宝可梦的魅力所在。\p"
	.string "抽泣…\n"
	.string "再见！$"

MatchCall_PersonalizedText57::
	.string "{CHN}哈！哈！哈！哈！\p"
	.string "嗨！我是{STR_VAR_1}！哈！哈！\p"
	.string "试着聊天…\n"
	.string "一边爬山…\l"
	.string "真是剧烈运动… 哈！哈！\p"
	.string "呃！呜…\n"
	.string "更陡了…\l"
	.string "我们…下次再聊…\l"
	.string "哈！哈！哈！$"

MatchCall_PersonalizedText58::
	.string "{CHN}哦，嗨！\p"
	.string "我还在和琪拉一起\n"
	.string "寻找宝藏！\p"
	.string "也许这里根本\n"
	.string "就没有宝藏…\p"
	.string "但重要的是\n"
	.string "我和琪拉一起寻找。\p"
	.string "哦，嘿，琪拉！\n"
	.string "你…你为什么生气？\p"
	.string "我没有不理你，亲爱的！\n"
	.string "你是我的唯一！\p"
	.string "…{PLAYER}，我得走了，拜拜！$"

MatchCall_PersonalizedText59::
	.string "{CHN}我是{STR_VAR_1}！\p"
	.string "我又去武斗镇的道馆\n"
	.string "训练了。\p"
	.string "道馆馆主藤树似乎\n"
	.string "变强了。\p"
	.string "说是被狂野的浪潮\n"
	.string "锻炼得更坚韧了…\p"
	.string "但他还是一如既往的酷。\n"
	.string "女士们都崇拜他！\l"
	.string "老实说，这让我嫉妒。\p"
	.string "我想…他的朋友希巴\n"
	.string "是不是和藤树一样？\p"
	.string "你知道的，那种满身汗或臭味，\n"
	.string "还爱叫人\l"
	.string "“大浪”之类的。\p"
	.string "但是，嘿，这种嫉妒\n"
	.string "不太得体，对吧？\p"
	.string "忘掉这次聊天吧，\n"
	.string "怎么样？再见！$"

MatchCall_PersonalizedText60::
	.string "{CHN}很高兴能和像你\n"
	.string "这样年轻的训练家聊天。\p"
	.string "我想无论你到了什么年纪，\n"
	.string "都会继续享受宝可梦。\p"
	.string "如果你也有像我们\n"
	.string "这样的搭档，不是很好吗？\p"
	.string "当然，{PLAYER}{KUN}，你已经\n"
	.string "享受着宝可梦的信任\l"
	.string "和陪伴了。\p"
	.string "你已具备长久而\n"
	.string "持久关系的潜质！\p"
	.string "哈哈哈！\n"
	.string "永远不要气馁！$"

MatchCall_PersonalizedText61::
	.string "{CHN}嗨，我是{STR_VAR_1}！\n"
	.string "我们刚赢了一场对战！\p"
	.string "我们不常赢，但对手是个\n"
	.string "很酷的游泳训练家。\p"
	.string "我姐姐气坏了！\p"
	.string "她想装弱来\n"
	.string "给人留下印象！\p"
	.string "无论输赢，\n"
	.string "她总是训我！\p"
	.string "{PLAYER}{KUN}，你下次能\n"
	.string "跟她说几句吗？\p"
	.string "好，再见！$"

MatchCall_PersonalizedText62::
	.string "{CHN}我是{STR_VAR_1}，是的。\n"
	.string "我昨天出海了。\p"
	.string "我一直希望能找到\n"
	.string "新的遗迹来探索。\p"
	.string "但潮水似乎\n"
	.string "把我带回了起点。\p"
	.string "我对战也很弱…\n"
	.string "尽管嘲笑我吧…\l"
	.string "但我不会放弃。\p"
	.string "我发现新遗迹的\n"
	.string "日子总会到来！\p"
	.string "这就是我要说的！\n"
	.string "再会！$"

MatchCall_PersonalizedText63::
	.string "{CHN}啊哈！\n"
	.string "是我，{STR_VAR_1}！\l"
	.string "我现在在108号水路上！\l"
	.string "也就是说，还是老地方！\p"
	.string "今天，一位华丽的游泳训练家\n"
	.string "从我身边游过！\p"
	.string "所以我大喊一声吓她！\p"
	.string "她狠狠瞪了我一眼！\p"
	.string "这是来自108号水路的报道！\n"
	.string "由{STR_VAR_1}为你播报！$"

MatchCall_PersonalizedText64::
	.string "{CHN}我是{STR_VAR_1}！\p"
	.string "我有点忙，但我想\n"
	.string "我应该告诉你我今天又\l"
	.string "打败了五个训练家。\p"
	.string "如果我保持这个速度，\n"
	.string "下次也许能打败你。\p"
	.string "我想我们会成为好对手，\n"
	.string "你和我。再见了！$"

MatchCall_BattleFrontierStreakText1::
	.string "{CHN}嗨！我是{STR_VAR_1}。\n"
	.string "我听到消息了！\p"
	.string "他们说你在\n"
	.string "{STR_VAR_2}表现出色。\p"
	.string "太厉害了，{STR_VAR_3}连胜？\n"
	.string "再见！$"

MatchCall_BattleFrontierStreakText2::
	.string "{CHN}你好，我是{STR_VAR_1}！\n"
	.string "我听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}赢得了{STR_VAR_3}\n"
	.string "场连胜。\p"
	.string "真了不起！我也应该\n"
	.string "更努力！再见！$"

MatchCall_BattleFrontierStreakText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "我听说你在\n"
	.string "{STR_VAR_2}大杀四方！\p"
	.string "{STR_VAR_3}场连胜…\n"
	.string "那可是个大纪录，对吧？\p"
	.string "我也得加把劲了！\n"
	.string "回头见！$"

MatchCall_BattleFrontierStreakText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。怎么样？\p"
	.string "有传言说你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}场\l"
	.string "连胜。\p"
	.string "我也得加把劲了。\n"
	.string "再见！$"

MatchCall_BattleFrontierStreakText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}\n"
	.string "并连续赢了{STR_VAR_3}场？\l"
	.string "真了不起！\p"
	.string "我得再多培养我的宝可梦了。\n"
	.string "回头见！$"

MatchCall_BattleFrontierStreakText6::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。你好吗？\p"
	.string "顺便说一下，我听说你\n"
	.string "在{STR_VAR_2}取得了{STR_VAR_3}连胜\l"
	.string "的壮举。\p"
	.string "这激励我\n"
	.string "专注于培育队伍。$"

MatchCall_BattleFrontierStreakText7::
	.string "{CHN}…呃，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}…\p"
	.string "哦，对，你去了\n"
	.string "{STR_VAR_2}，对吧？\p"
	.string "而且你连续赢了{STR_VAR_3}场。\p"
	.string "哦，那里有只稀有宝可梦！\n"
	.string "我得走了！$"

MatchCall_BattleFrontierStreakText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切都好。\p"
	.string "哦，你确实如此。我听说\n"
	.string "你在{STR_VAR_2}连续赢了{STR_VAR_3}场\l"
	.string "对战。\p"
	.string "太厉害了！\n"
	.string "希望你继续成功。$"

MatchCall_BattleFrontierStreakText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "我听说了！你在{STR_VAR_2}的\n"
	.string "{STR_VAR_3}连胜！\p"
	.string "太酷了！\n"
	.string "我也得更努力！$"

MatchCall_BattleFrontierStreakText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}连续赢了\n"
	.string "{STR_VAR_3}场？\p"
	.string "这成就相当了不起。\n"
	.string "我得更努力了。$"

MatchCall_BattleFrontierStreakText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你是\n"
	.string "{STR_VAR_2}的恐怖存在？\p"
	.string "你赢了，多少，{STR_VAR_3}场\n"
	.string "连胜？\p"
	.string "你真厉害。\n"
	.string "我想知道我能赢多少场？$"

MatchCall_BattleFrontierStreakText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "有人传话给我关于你的事。\n"
	.string "说你在叫{STR_VAR_2}的地方\l"
	.string "连续赢了{STR_VAR_3}场？\p"
	.string "那故事真了不起。\n"
	.string "再见！$"

MatchCall_BattleFrontierStreakText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "希望你一切都好。\p"
	.string "他们说你在{STR_VAR_2}连续\n"
	.string "赢了{STR_VAR_3}场。\p"
	.string "我真佩服你的精力！\n"
	.string "拜拜。$"

MatchCall_BattleFrontierStreakText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你的事了！\n"
	.string "你不是刚在{STR_VAR_2}连续\l"
	.string "赢了{STR_VAR_3}场吗？\p"
	.string "你真是个榜样！\n"
	.string "拜拜！$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "{CHN}嗨！我是{STR_VAR_1}。\n"
	.string "我听到消息了！\p"
	.string "他们说你在\n"
	.string "{STR_VAR_2}表现出色。\p"
	.string "太厉害了——{STR_VAR_3}连胜？\n"
	.string "再见！$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "{CHN}你好，我是{STR_VAR_1}！\n"
	.string "我听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}赢得了{STR_VAR_3}\n"
	.string "场连胜。\p"
	.string "真了不起！我也应该\n"
	.string "更努力！再见！$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "我听说你在\n"
	.string "{STR_VAR_2}大杀四方！\p"
	.string "{STR_VAR_3}场连胜…\n"
	.string "那可是个大纪录，对吧？\p"
	.string "我也得加把劲了！\n"
	.string "回头见！$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。怎么样？\p"
	.string "有传言说你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}场\l"
	.string "连胜。\p"
	.string "我也得加把劲了。\n"
	.string "再见！$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}\n"
	.string "并连续赢了{STR_VAR_3}场？\l"
	.string "真了不起！\p"
	.string "我吗？我觉得我有所进步。\n"
	.string "回头见！$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。你好吗？\p"
	.string "顺便说一下，我听说你\n"
	.string "在{STR_VAR_2}取得了{STR_VAR_3}连胜\l"
	.string "的壮举。\p"
	.string "我也得更努力了！\n"
	.string "回头见！$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "{CHN}…呃，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}…\p"
	.string "哦，对，你去了\n"
	.string "{STR_VAR_2}，对吧？\p"
	.string "而且你连续赢了{STR_VAR_3}场。\p"
	.string "哦，那里有只稀有宝可梦！\n"
	.string "我得走了！$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切都好。\p"
	.string "哦，你确实如此。我听说\n"
	.string "你在{STR_VAR_2}连续赢了{STR_VAR_3}场\l"
	.string "对战。\p"
	.string "太厉害了！\n"
	.string "我也得培养我的宝可梦了！$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "我听说了！你在{STR_VAR_2}的\n"
	.string "{STR_VAR_3}连胜！\p"
	.string "太酷了！\n"
	.string "我也得更努力！$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好…\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}连续赢了\n"
	.string "{STR_VAR_3}场？\p"
	.string "这成就相当了不起。\n"
	.string "我得更努力了。$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你是\n"
	.string "{STR_VAR_2}的恐怖存在？\p"
	.string "你赢了，多少，{STR_VAR_3}场\n"
	.string "连胜？\p"
	.string "你真厉害。\n"
	.string "我想知道我能赢多少场？$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "有人传话给我关于你的事。\n"
	.string "说你在叫{STR_VAR_2}的地方\l"
	.string "连续赢了{STR_VAR_3}场？\p"
	.string "那故事真了不起。\n"
	.string "再见！$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "希望你一切都好。\p"
	.string "他们说你在{STR_VAR_2}连续\n"
	.string "赢了{STR_VAR_3}场。\p"
	.string "我真佩服你的精力！\n"
	.string "拜拜。$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "我听说你的事了！\p"
	.string "你不是刚在{STR_VAR_2}连续\n"
	.string "赢了{STR_VAR_3}场吗？\p"
	.string "你真是个榜样！\n"
	.string "拜拜！$"

MatchCall_BattleDomeText1::
	.string "{CHN}嗨！{PLAYER}？\n"
	.string "你好，我是{STR_VAR_1}！\l"
	.string "我听到消息了！\p"
	.string "你成了{STR_VAR_2}\n"
	.string "{STR_VAR_3}次的冠军？\p"
	.string "太厉害了！我得做得更好！\n"
	.string "再见！$"

MatchCall_BattleDomeText2::
	.string "{CHN}你好，我是{STR_VAR_1}！\n"
	.string "我听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}赢得了\n"
	.string "{STR_VAR_3}次冠军。\p"
	.string "太棒了！我不知道能不能\n"
	.string "成为冠军呢？$"

MatchCall_BattleDomeText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "最近怎么样？\p"
	.string "我听说你在{STR_VAR_2}赢得了{STR_VAR_3}次\n"
	.string "冠军！\p"
	.string "下次再多赢一次！\n"
	.string "回头见！$"

MatchCall_BattleDomeText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "成了{STR_VAR_3}次冠军。\p"
	.string "听起来你很努力。\n"
	.string "我会努力跟上的！$"

MatchCall_BattleDomeText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "直接赢了{STR_VAR_3}次。\p"
	.string "我也得加把劲了！\n"
	.string "回头见！$"

MatchCall_BattleDomeText6::
	.string "{CHN}嘿，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。你好吗？\p"
	.string "顺便说一下，我听说你成了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}次\l"
	.string "冠军。\p"
	.string "我得在你甩得更远之前\n"
	.string "好好培育宝可梦。$"

MatchCall_BattleDomeText7::
	.string "{CHN}{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你去了{STR_VAR_2}\n"
	.string "并成了{STR_VAR_3}次冠军？\p"
	.string "真不错。顺便问问，你最近\n"
	.string "有捉到稀有宝可梦吗？\p"
	.string "哦，是这样啊。\n"
	.string "好，拜拜。$"

MatchCall_BattleDomeText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切都好。\l"
	.string "哦，你确实如此。\p"
	.string "我听说你在{STR_VAR_2}赢得了\n"
	.string "{STR_VAR_3}次冠军。\p"
	.string "我必须像你一样培育宝可梦。\n"
	.string "再见啦。$"

MatchCall_BattleDomeText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "我听说了！你在{STR_VAR_2}\n"
	.string "拿了{STR_VAR_3}次冠军！\p"
	.string "太酷了！\n"
	.string "我也得更努力！$"

MatchCall_BattleDomeText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}连续赢了\n"
	.string "{STR_VAR_3}次？\p"
	.string "这成就相当了不起。\n"
	.string "我得更努力了。$"

MatchCall_BattleDomeText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你是\n"
	.string "{STR_VAR_2}的恐怖存在？\p"
	.string "你赢了，多少，现在\n"
	.string "{STR_VAR_3}次了？\p"
	.string "我想知道我是否能\n"
	.string "成为冠军？\p"
	.string "…几乎不可能？\n"
	.string "好吧，再见！$"

MatchCall_BattleDomeText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "你在叫{STR_VAR_2}的地方\n"
	.string "赢了{STR_VAR_3}次冠军？\p"
	.string "那故事真了不起。\n"
	.string "再见！$"

MatchCall_BattleDomeText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "希望你一切都好。\p"
	.string "他们说你在{STR_VAR_2}赢了\n"
	.string "{STR_VAR_3}次冠军？\p"
	.string "我真佩服你的精力！\n"
	.string "拜拜。$"

MatchCall_BattleDomeText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "我听说你的事了！\p"
	.string "你不是在{STR_VAR_2}赢了\n"
	.string "{STR_VAR_3}次冠军吗？\p"
	.string "你真是个榜样！\n"
	.string "再见啦！$"

MatchCall_BattlePikeText1::
	.string "{CHN}嗨！{PLAYER}？\n"
	.string "你好，我是{STR_VAR_1}！\l"
	.string "我听到消息了！\p"
	.string "你在{STR_VAR_2}通过了\n"
	.string "{STR_VAR_3}个房间！\p"
	.string "太厉害了！\n"
	.string "再见！$"

MatchCall_BattlePikeText2::
	.string "{CHN}你好，我是{STR_VAR_1}！\n"
	.string "我听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}通过了\n"
	.string "{STR_VAR_3}个房间。\p"
	.string "我得更努力了！\n"
	.string "拜拜！$"

MatchCall_BattlePikeText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "最近怎么样？\p"
	.string "我听说你在{STR_VAR_2}通过了{STR_VAR_3}个\n"
	.string "房间！\p"
	.string "下次试着做得更好！\n"
	.string "回头见！$"

MatchCall_BattlePikeText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}冲过了{STR_VAR_3}个\n"
	.string "房间。\p"
	.string "我得训练宝可梦\n"
	.string "努力跟上！$"

MatchCall_BattlePikeText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}通过了{STR_VAR_3}个\n"
	.string "房间。\p"
	.string "我也得加把劲了！\n"
	.string "回头见！$"

MatchCall_BattlePikeText6::
	.string "{CHN}嘿，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。你好吗？\p"
	.string "顺便说一下，我听说你通过了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}个房间。\p"
	.string "我得在你甩得更远之前\n"
	.string "好好培育宝可梦。$"

MatchCall_BattlePikeText7::
	.string "{CHN}{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你去了{STR_VAR_2}\n"
	.string "并通过了{STR_VAR_3}个房间？\p"
	.string "真厉害。\p"
	.string "哦，那里有只稀有宝可梦！\n"
	.string "好，拜拜。$"

MatchCall_BattlePikeText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切都好。\l"
	.string "哦，你确实如此。\p"
	.string "我听说你通过了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}个房间。\p"
	.string "真了不起！\n"
	.string "我必须像你一样培育宝可梦。\l"
	.string "再见啦。$"

MatchCall_BattlePikeText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "我听说了！你通过了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}个房间！\p"
	.string "太酷了！\n"
	.string "我也得更努力！$"

MatchCall_BattlePikeText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你通过了{STR_VAR_2}的\n"
	.string "{STR_VAR_3}个房间？\p"
	.string "这成就相当了不起。\n"
	.string "我得更努力了。$"

MatchCall_BattlePikeText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你是\n"
	.string "{STR_VAR_2}的恐怖存在？\p"
	.string "你通过了，多少，{STR_VAR_3}个房间？\n"
	.string "那应该算点什么。\p"
	.string "我想知道我是否能\n"
	.string "成为冠军？\p"
	.string "…几乎不可能？\n"
	.string "好吧，再见！$"

MatchCall_BattlePikeText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "你在叫{STR_VAR_2}的地方\n"
	.string "通过了{STR_VAR_3}个房间？\p"
	.string "那故事真了不起。\n"
	.string "再见！$"

MatchCall_BattlePikeText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "希望你一切都好。\p"
	.string "他们说你在{STR_VAR_2}通过了\n"
	.string "{STR_VAR_3}个房间？\p"
	.string "我真佩服你的精力！\n"
	.string "拜拜。$"

MatchCall_BattlePikeText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "我听说你的事了！\p"
	.string "你不是在{STR_VAR_2}通过了\n"
	.string "{STR_VAR_3}个房间吗？\p"
	.string "你真是个榜样！\n"
	.string "再见啦！$"

MatchCall_BattlePyramidText1::
	.string "{CHN}嗨！{PLAYER}？\n"
	.string "你好，我是{STR_VAR_1}！\l"
	.string "我听到消息了！\p"
	.string "你在{STR_VAR_2}里爬了\n"
	.string "{STR_VAR_3}层，对吧？\p"
	.string "太厉害了！\n"
	.string "我也该去挑战一下。$"

MatchCall_BattlePyramidText2::
	.string "{CHN}你好，我是{STR_VAR_1}！\n"
	.string "我听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}通过了\n"
	.string "{STR_VAR_3}层。\p"
	.string "哇，太棒了！\n"
	.string "我也得培育宝可梦了！$"

MatchCall_BattlePyramidText3::
	.string "{CHN}嘿，{PLAYER}！\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "最近怎么样？\p"
	.string "我听说你在{STR_VAR_2}爬了{STR_VAR_3}层！\n"
	.string "\p"
	.string "下次试着做得更好！\n"
	.string "回头见！$"

MatchCall_BattlePyramidText4::
	.string "{CHN}嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}爬了\n"
	.string "{STR_VAR_3}层。\p"
	.string "我得努力跟上！$"

MatchCall_BattlePyramidText5::
	.string "{CHN}嗨呀，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}爬了\n"
	.string "{STR_VAR_3}层。\p"
	.string "我也得加把劲了！\n"
	.string "回头见！$"

MatchCall_BattlePyramidText6::
	.string "{CHN}嘿，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。你好吗？\p"
	.string "顺便说一下，我听说你通过了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}层。\p"
	.string "我得在你甩得更远之前\n"
	.string "好好培育宝可梦。$"

MatchCall_BattlePyramidText7::
	.string "{CHN}{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你去了{STR_VAR_2}\n"
	.string "并爬上了{STR_VAR_3}层？\p"
	.string "不错。那里有稀有宝可梦\n"
	.string "吗？\p"
	.string "没有，是吗？\n"
	.string "好，拜拜。$"

MatchCall_BattlePyramidText8::
	.string "{CHN}哦，{PLAYER}{KUN}，你好吗？\n"
	.string "我是{STR_VAR_1}。\l"
	.string "希望你一切都好。\l"
	.string "哦，你确实如此。\p"
	.string "我听说你通过了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}层。\p"
	.string "真了不起！\n"
	.string "我必须像你一样培育宝可梦。\l"
	.string "再见啦。$"

MatchCall_BattlePyramidText9::
	.string "{CHN}哦，{PLAYER}{KUN}，你好啊！\n"
	.string "我是{STR_VAR_1}！\p"
	.string "我听说了！你通过了\n"
	.string "{STR_VAR_2}的{STR_VAR_3}层！\p"
	.string "太酷了！\n"
	.string "我也得更努力！$"

MatchCall_BattlePyramidText10::
	.string "{CHN}哦，{PLAYER}{KUN}，你好。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}里爬了\n"
	.string "{STR_VAR_3}层？\p"
	.string "这成就相当了不起。\n"
	.string "我得更努力了。$"

MatchCall_BattlePyramidText11::
	.string "{CHN}啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你是\n"
	.string "{STR_VAR_2}的恐怖存在？\p"
	.string "你爬上了，多少，{STR_VAR_3}层？\n"
	.string "那应该算点什么。\p"
	.string "我想知道我是否能\n"
	.string "成为冠军？\p"
	.string "…几乎不可能？\n"
	.string "好吧，再见！$"

MatchCall_BattlePyramidText12::
	.string "{CHN}你好，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "你在叫{STR_VAR_2}的地方\n"
	.string "通过了{STR_VAR_3}层？\p"
	.string "那故事真了不起。\n"
	.string "再见！$"

MatchCall_BattlePyramidText13::
	.string "{CHN}啊，你好，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}！\l"
	.string "希望你一切都好。\p"
	.string "他们说你在{STR_VAR_2}爬了\n"
	.string "{STR_VAR_3}层？\p"
	.string "我真佩服你的精力！\n"
	.string "拜拜。$"

MatchCall_BattlePyramidText14::
	.string "{CHN}哦，嗨，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\l"
	.string "我听说你的事了！\p"
	.string "你不是在{STR_VAR_2}通过了\n"
	.string "{STR_VAR_3}层吗？\p"
	.string "你真是个榜样！\n"
	.string "再见啦！$"

MatchCall_Text_Mom1::
	.string "{CHN}妈妈：你爸爸和你…\n"
	.string "大家都被宝可梦迷住了。\p"
	.string "宝可梦的魅力是什么呢？\p"
	.string "我吗？\n"
	.string "我喜欢帮我做\l"
	.string "日常家务的宝可梦。$"

MatchCall_Text_Mom2::
	.string "{CHN}妈妈：嗨，{PLAYER}！\n"
	.string "你爸爸一直把自己关在\l"
	.string "橙华道馆里。\p"
	.string "他偶尔会回家。\n"
	.string "但吃饱了就回道馆去了，\l"
	.string "吃尽所有能吃的东西。\p"
	.string "我猜输给你\n"
	.string "对他的自尊是个不小的打击！$"

MatchCall_Text_Mom3::
	.string "{CHN}妈妈：{PLAYER}…\n"
	.string "别担心我和家里。\p"
	.string "把那双跑步鞋穿到\n"
	.string "破为止，亲爱的！$"

MatchCall_Text_Roxanne1::
	.string "{CHN}杜鹃：哦，你好，{PLAYER}！\p"
	.string "自我们相遇后，我一直\n"
	.string "在努力重新训练。\p"
	.string "我还需要一些时间\n"
	.string "才能重新开放道馆。\p"
	.string "但当我准备好时，请来我的道馆\n"
	.string "再战一场！$"

MatchCall_Text_Roxanne2::
	.string "{CHN}杜鹃：是{PLAYER}吗？\n"
	.string "恭喜你！\l"
	.string "我一直在听人说起你！\p"
	.string "至于我，我还需要一些时间\n"
	.string "才能重新开放道馆。\p"
	.string "但当我准备好时，请来我的道馆\n"
	.string "再战一场！$"

MatchCall_Text_Roxanne3::
	.string "{CHN}杜鹃：{PLAYER}！\n"
	.string "我的道馆准备好了！\p"
	.string "请随时来\n"
	.string "卡那兹市！$"

MatchCall_Text_Roxanne4::
	.string "{CHN}杜鹃：在卡那兹道馆，\n"
	.string "我们曾对战过这件事，{PLAYER}，\l"
	.string "是一种骄傲。$"

MatchCall_Text_Brawly1::
	.string "{CHN}藤树：嘿，{PLAYER}{KUN}！\p"
	.string "我从我们的对战中\n"
	.string "学到了很多。\p"
	.string "我打算重新训练，\n"
	.string "然后重新开放道馆。\p"
	.string "还需要一些时间\n"
	.string "我才能重新运营道馆。\p"
	.string "但如果我能重新开放道馆，\n"
	.string "我希望你再来挑战我们。$"

MatchCall_Text_Brawly2::
	.string "{CHN}藤树：嘿，{PLAYER}{KUN}！\n"
	.string "恭喜你！\p"
	.string "关于你壮举的消息\n"
	.string "随着潮风传来了！\p"
	.string "看来我需要再\n"
	.string "多训练一些。\p"
	.string "还需要一些时间\n"
	.string "我才能重新运营道馆。\p"
	.string "但如果我能重新开放道馆，\n"
	.string "我希望你再来挑战我们。$"

MatchCall_Text_Brawly3::
	.string "{CHN}藤树：嘿，{PLAYER}{KUN}！\n"
	.string "我的道馆已经准备好了！\p"
	.string "随时回武斗镇\n"
	.string "再来挑战！$"

MatchCall_Text_Brawly4::
	.string "{CHN}藤树：{PLAYER}{KUN}，我觉得\n"
	.string "和你对战永远不会腻！$"

MatchCall_Text_Wattson1::
	.string "{CHN}铁旋：哦，是你啊！\p"
	.string "你走后，我一直\n"
	.string "从零开始重新训练。\p"
	.string "我得说还需要一点点\n"
	.string "时间才能重新开放道馆。\p"
	.string "你得等到那时候了！\n"
	.string "哇哈哈哈哈！$"

MatchCall_Text_Wattson2::
	.string "{CHN}铁旋：哇哈哈哈哈！\p"
	.string "你真做到了，对吧？\n"
	.string "我一直在听到你的消息！\p"
	.string "看来我还需要再\n"
	.string "训练一些。\p"
	.string "我得说还需要一点点\n"
	.string "时间才能重新开放道馆。\p"
	.string "你得等到那时候了！\n"
	.string "哇哈哈哈哈！$"

MatchCall_Text_Wattson3::
	.string "{CHN}铁旋：哦，是你啊！\n"
	.string "我的道馆准备好了！\p"
	.string "随时来紫堇市！\n"
	.string "哇哈哈哈哈！$"

MatchCall_Text_Wattson4::
	.string "{CHN}铁旋：哇哈哈哈！\p"
	.string "和你的对战总是\n"
	.string "充满惊人的力量！$"

MatchCall_Text_Flannery1::
	.string "{CHN}亚莎：{PLAYER}…\p"
	.string "我们对战时，我清楚地认识\n"
	.string "到自己有多么不成熟。\p"
	.string "但我还没完！\p"
	.string "我要重新训练并\n"
	.string "重新开放道馆。\p"
	.string "到时候，{PLAYER}，\n"
	.string "请再来挑战我们。$"

MatchCall_Text_Flannery2::
	.string "{CHN}亚莎：你好，{PLAYER}？\n"
	.string "恭喜你！\p"
	.string "你成功的消息\n"
	.string "像火山的 heat 一样传到了这里！\p"
	.string "我们的训练在这里\n"
	.string "进展得很顺利。\p"
	.string "道馆准备好时，一个标记会\n"
	.string "出现在\l"
	.string "对战寻呼列表中我名字旁边。$"

MatchCall_Text_Flannery3::
	.string "{CHN}亚莎：哦，{PLAYER}？\n"
	.string "我们的道馆准备好了！\p"
	.string "来釜炎镇泡个温泉\n"
	.string "顺便挑战一下！$"

MatchCall_Text_Flannery4::
	.string "{CHN}亚莎：{PLAYER}…\n"
	.string "我肯定你每次\l"
	.string "训练都在进步。$"

MatchCall_Text_Winona1::
	.string "{CHN}娜琪：你好，{PLAYER}！\p"
	.string "多亏了我们的对战，我认识\n"
	.string "到了自己的弱点！\p"
	.string "当我重新开放道馆时，我不会\n"
	.string "再败下阵来！$"

MatchCall_Text_Winona2::
	.string "{CHN}娜琪：你做到了，{PLAYER}！\p"
	.string "关于新冠军的消息\n"
	.string "已经传到了茵郁市！\p"
	.string "但是…下次我们对战时，\n"
	.string "结果不会一样了。$"

MatchCall_Text_Winona3::
	.string "{CHN}娜琪：是{PLAYER}吗？\n"
	.string "我们的道馆重新开放了！\p"
	.string "我们在茵郁市等你！$"

MatchCall_Text_Winona4::
	.string "{CHN}娜琪：{PLAYER}…\n"
	.string "虽然我输了，但我的翅膀\l"
	.string "永远不会折断。\p"
	.string "是的，就像你\n"
	.string "从未放弃梦想一样。$"

MatchCall_Text_TateLiza1::
	.string "{CHN}枫：哦！你是…\n"
	.string "南：{PLAYER}！\p"
	.string "枫：我们在重新训练…\n"
	.string "南：为了重新开放我们的道馆！\p"
	.string "枫：当我们的道馆准备好时…\n"
	.string "南：当我们的道馆准备好时…\p"
	.string "枫：我们名字旁会出现标记…\n"
	.string "南：在对战寻呼列表上。$"

MatchCall_Text_TateLiza2::
	.string "{CHN}枫：{PLAYER}，恭喜你！\n"
	.string "南：{PLAYER}，恭喜你！\p"
	.string "枫：我们两个…\n"
	.string "南：还在训练中！\p"
	.string "枫：我们还需要一些时间，但是…\n"
	.string "南：当我们的道馆准备好时…\p"
	.string "枫：我们名字旁会出现标记…\n"
	.string "南：在对战寻呼列表上。$"

MatchCall_Text_TateLiza3::
	.string "{CHN}枫：{PLAYER}！\n"
	.string "南：{PLAYER}！\p"
	.string "枫：我们的道馆准备好了！\n"
	.string "南：我们的道馆准备好了！\p"
	.string "枫：请来…\n"
	.string "南：随时来绿岭市！$"

MatchCall_Text_TateLiza4::
	.string "{CHN}枫：{PLAYER}，我们的那场对战…\n"
	.string "南：是宝贵的经验。\p"
	.string "枫：如果…\n"
	.string "南：能再和大家对战就好了！$"

MatchCall_Text_Juan1::
	.string "{CHN}亚当：嗯…\n"
	.string "{PLAYER}{KUN}…是吧？\p"
	.string "我们的对战——它让我\n"
	.string "想起了我第一次\l"
	.string "遇到米可利的时候。\p"
	.string "也许你是个天才，\n"
	.string "有一天可能超越米可利！$"

MatchCall_Text_Juan2::
	.string "{CHN}亚当：呼呼…{PLAYER}{KUN}…\n"
	.string "你终于实现了你的目标。\p"
	.string "我识人的眼光\n"
	.string "没有看错…\p"
	.string "希望能再有机会见到\n"
	.string "你，因为你已经登上了\l"
	.string "力量和荣耀的巅峰。$"

MatchCall_Text_Juan3::
	.string "{CHN}亚当：呵呵…{PLAYER}{KUN}…\p"
	.string "我们的琉璃道馆终于\n"
	.string "重新开放了。\p"
	.string "如果你想见我，\n"
	.string "随时欢迎来访。$"

MatchCall_Text_Juan4::
	.string "{CHN}亚当：{PLAYER}{KUN}…\p"
	.string "如同最优美的乐曲，我们\n"
	.string "共同进行的对战在我心中\l"
	.string "激荡出灵感的和弦…\p"
	.string "当我闭上眼睛，我看到\n"
	.string "你随着旋律翱翔的画面…$"

MatchCall_Text_Sidney::
	.string "{CHN}花月：哟，{PLAYER}！\p"
	.string "如果你想再和我对战，\n"
	.string "随时回来\l"
	.string "宝可梦联盟就好。\p"
	.string "我会一直在这里！\n"
	.string "我会等你的！$"

MatchCall_Text_Phoebe::
	.string "{CHN}芙蓉：嗨，{PLAYER}！\p"
	.string "要不要什么时候\n"
	.string "再回来这里？\p"
	.string "我想看看你和你的\n"
	.string "宝可梦之间的\l"
	.string "羁绊有多深了。$"

MatchCall_Text_Glacia::
	.string "{CHN}波妮：你好，{PLAYER}。\p"
	.string "我相信你没有对\n"
	.string "自己的力量自满吧？\p"
	.string "如果你觉得需要让你\n"
	.string "火热的心情稍微冷却一下，请来\l"
	.string "宝可梦联盟…$"

MatchCall_Text_Drake::
	.string "{CHN}源治：那个声音…{PLAYER}，是你吗？\n"
	.string "你听起来不错…\p"
	.string "我知道现在有一个叫\n"
	.string "对战开拓区的地方\l"
	.string "在考验训练家\l"
	.string "的技术。\p"
	.string "但是，如果你想要真正的\n"
	.string "对战，没有什么能替代\l"
	.string "宝可梦联盟！\p"
	.string "你同意吗，{PLAYER}？$"

MatchCall_Text_Wallace::
	.string "{CHN}米可利：你好，{PLAYER}{KUN}。\n"
	.string "你见过大吾吗？\p"
	.string "他…\n"
	.string "实际上非常厉害。\p"
	.string "但是，他是个很少\n"
	.string "对战的怪人。\p"
	.string "他宁愿去寻找\n"
	.string "稀有的石头。\p"
	.string "我确信他现在正在某个洞穴或\n"
	.string "崎岖的山里挖掘。\p"
	.string "但稀有的石头到底是什么？\n"
	.string "我能想到的只有陨石…$"

MatchCall_Text_MayRayquazaCall:
	.string "{CHN}… … … … … …\n"
	.string "… … … … … 嘟！\p"
	.string "小遥：嗨，{PLAYER}{KUN}！\p"
	.string "我刚才在花蕊镇\n"
	.string "附近。\p"
	.string "我看到一只巨大的绿色宝可梦\n"
	.string "在天空中高飞。\p"
	.string "我…\n"
	.string "我从没见过那样的东西。\p"
	.string "我想知道那是什么。\n"
	.string "这也许是个重大发现？\p"
	.string "… … … … … …\n"
	.string "… … … … … 咔嗒！$"

MatchCall_Text_BrendanRayquazaCall:
	.string "{CHN}… … … … … …\n"
	.string "… … … … … 嘟！\p"
	.string "佑树：嘿，{PLAYER}！\n"
	.string "我刚才在花蕊镇。\p"
	.string "我看到这只巨大的绿色宝可梦\n"
	.string "飞过天空。\p"
	.string "我从没见过\n"
	.string "那么惊人的东西。\p"
	.string "真希望你能看到，\n"
	.string "{PLAYER}。\p"
	.string "… … … … … …\n"
	.string "… … … … … 咔嗒！$"

MatchCall_Text_May1::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\p"
	.string "布莱利先生作为水手退休了，\n"
	.string "但我还是有时看到他和他的\l"
	.string "宠物皮可在海上。\p"
	.string "他一定还是热爱大海。$"

MatchCall_Text_May2::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\p"
	.string "你知道像橙华和武斗这样的\n"
	.string "小镇都有道馆吗？\p"
	.string "不知为什么，大港口\n"
	.string "凯那市却没有道馆。\p"
	.string "等他们终于在那里建道馆时，\n"
	.string "我应该申请当馆主。$"

MatchCall_Text_May3::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\p"
	.string "你还记得卡那兹市\n"
	.string "一个叫碎岩大叔的人吗？\l"
	.string "他在那里有栋房子，记得吗？\p"
	.string "嗯，我发现他的弟弟\n"
	.string "住在紫堇市。\p"
	.string "你能猜到他的名字吗？\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "碎岩大叔！$"

MatchCall_Text_May4::
	.string "{CHN}小遥：{PLAYER}{KUN}？\p"
	.string "卡绿隧道…\n"
	.string "他们这么命名是因为它\l"
	.string "连接卡那兹和绿荫镇。$"

MatchCall_Text_May5::
	.string "{CHN}小遥：{PLAYER}{KUN}，你好吗？\p"
	.string "我现在在111号道路。\p"
	.string "我要去一位老太太\n"
	.string "家休息。\p"
	.string "她就住在\n"
	.string "沙漠的北边。$"

MatchCall_Text_May6::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\p"
	.string "你知道沙漠里的\n"
	.string "海市蜃楼塔吗？\p"
	.string "他们说，像海市蜃楼一样，它\n"
	.string "会神秘地出现和消失。\p"
	.string "我真希望能看到它。$"

MatchCall_Text_May7::
	.string "{CHN}小遥：{PLAYER}{KUN}，呀呼！\n"
	.string "我现在在119号道路。\p"
	.string "这里有一条大河，\n"
	.string "经常下雨。\p"
	.string "我被淋湿了！$"

MatchCall_Text_May8::
	.string "{CHN}小遥：{PLAYER}{KUN}，嗨。\p"
	.string "送火山是对已结束生命\n"
	.string "的宝可梦的纪念。\p"
	.string "也许正因为如此，它\n"
	.string "里有很多幽灵属性的宝可梦！$"

MatchCall_Text_May9::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\p"
	.string "我正想去釜炎镇\n"
	.string "泡温泉。\p"
	.string "但在路上，凹凸山道附近，\n"
	.string "我遇到了一些看起来不怀好意的\l"
	.string "家伙。气氛很紧张！$"

MatchCall_Text_May10::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\n"
	.string "你看新闻了吗？\p"
	.string "他们说史藤船长在潜艇探险中\n"
	.string "发现了\l"
	.string "海底洞窟。$"

MatchCall_Text_May11::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\n"
	.string "你不觉得很棒吗？\p"
	.string "即使你没有船，\n"
	.string "你也可以使用\l"
	.string "宝可梦的招式渡海。\p"
	.string "你知道还有更多吗？\p"
	.string "有一种宝可梦招式可以\n"
	.string "让你潜到海底。$"

MatchCall_Text_May12::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\n"
	.string "希望一切顺利！\p"
	.string "你有没有在海上发现\n"
	.string "去另一边的路被挡住了？\l"
	.string "\p"
	.string "试着深潜到水下并\n"
	.string "沿着海沟前进。\p"
	.string "当你到达另一边时，\n"
	.string "浮上水面。简单！$"

MatchCall_Text_May13::
	.string "{CHN}小遥：嗨，{PLAYER}{KUN}！\p"
	.string "怎么样？\n"
	.string "你在填写宝可梦图鉴吗？\p"
	.string "我听到一个传闻说有\n"
	.string "超古代宝可梦存在。\l"
	.string "而且有三只！\p"
	.string "我连一只都想看看…$"

MatchCall_Text_May14::
	.string "{CHN}小遥：{PLAYER}{KUN}！\n"
	.string "我听到传闻了！\p"
	.string "你打败了琉璃道馆\n"
	.string "馆主？\p"
	.string "那你离目标\n"
	.string "不远了，对吧？$"

MatchCall_Text_May15::
	.string "{CHN}小遥：丰缘没有一个训练家\n"
	.string "不知道你是\l"
	.string "谁，{PLAYER}{KUN}！\p"
	.string "当我告诉人们我和你是朋友时，\n"
	.string "{PLAYER}{KUN}，他们都\l"
	.string "很惊讶！$"

MatchCall_Text_Brendan1::
	.string "{CHN}佑树：嘿，{PLAYER}！\p"
	.string "布莱利先生作为水手退休了，\n"
	.string "但我还是有时看到他和他的\l"
	.string "宠物皮可在海上。\p"
	.string "我想他一定还是\n"
	.string "热爱大海。$"

MatchCall_Text_Brendan2::
	.string "{CHN}佑树：嘿，{PLAYER}！\p"
	.string "我不明白为什么像橙华和武斗这样的\n"
	.string "小镇都有道馆。\p"
	.string "我的意思是，大港口\n"
	.string "凯那市却没有道馆。\p"
	.string "等他们终于在那里建道馆时，\n"
	.string "我应该申请当馆主。$"

MatchCall_Text_Brendan3::
	.string "{CHN}佑树：哟，{PLAYER}！\p"
	.string "你还记得卡那兹市\n"
	.string "一个叫碎岩大叔的人吗？\l"
	.string "他在那里有栋房子，对吧？\p"
	.string "嗯，原来他的弟弟\n"
	.string "住在紫堇市。\p"
	.string "你能猜到他的名字吗？\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "碎岩大叔！$"

MatchCall_Text_Brendan4::
	.string "{CHN}佑树：这个声音…{PLAYER}？\p"
	.string "他们给卡绿隧道起这个名字\n"
	.string "是因为它连接卡那兹和\l"
	.string "绿荫镇。\p"
	.string "你知道吗？$"

MatchCall_Text_Brendan5::
	.string "{CHN}佑树：{PLAYER}，怎么样？\p"
	.string "嘿，我现在在111号道路。\p"
	.string "我要去沙漠北边\n"
	.string "一位老太太家休息。\p"
	.string "如果你在附近，你也\n"
	.string "应该去拜访她。$"

MatchCall_Text_Brendan6::
	.string "{CHN}佑树：嘿，{PLAYER}！\p"
	.string "你知道沙漠里的\n"
	.string "海市蜃楼塔吗？\p"
	.string "他们说，像海市蜃楼一样，它\n"
	.string "只在某些时候才能看到。\p"
	.string "我想看看那个！$"

MatchCall_Text_Brendan7::
	.string "{CHN}佑树：这位是谁？哦，{PLAYER}？\n"
	.string "猜猜怎么着？我现在在119号道路。\p"
	.string "这里有一条大河，\n"
	.string "而且一直下雨。\p"
	.string "我被淋透了！$"

MatchCall_Text_Brendan8::
	.string "{CHN}佑树：{PLAYER}！\p"
	.string "送火山是对已结束生命\n"
	.string "的宝可梦的纪念。\p"
	.string "那可能就是为什么它\n"
	.string "里有很多幽灵属性的宝可梦！$"

MatchCall_Text_Brendan9::
	.string "{CHN}佑树：嘿，{PLAYER}。\p"
	.string "我正要回釜炎镇\n"
	.string "泡温泉。\p"
	.string "但在凹凸山道附近，我遇到了\n"
	.string "一些凶神恶煞的家伙。\p"
	.string "那些家伙…\n"
	.string "我想他们是火焰队。$"

MatchCall_Text_Brendan10::
	.string "{CHN}佑树：嗨，{PLAYER}！\n"
	.string "你看新闻了吗？\p"
	.string "他们说史藤船长在潜艇探险中\n"
	.string "发现了\l"
	.string "海底洞窟。$"

MatchCall_Text_Brendan11::
	.string "{CHN}佑树：嘿，{PLAYER}！\n"
	.string "你不觉得很厉害吗？\p"
	.string "即使你没有船，\n"
	.string "你也可以使用\l"
	.string "宝可梦的招式渡海。\p"
	.string "而且，有一种招式可以让你\n"
	.string "潜到海底。\p"
	.string "天哪，宝可梦什么都能做！$"

MatchCall_Text_Brendan12::
	.string "{CHN}佑树：嘿，{PLAYER}！\n"
	.string "你还好吗？\p"
	.string "有没有在海上发现\n"
	.string "去另一边的路被挡住了？\p"
	.string "试着深潜到水下并\n"
	.string "沿着海底的海沟前进。\p"
	.string "当你到达另一边时，\n"
	.string "浮上水面。简单！$"

MatchCall_Text_Brendan13::
	.string "{CHN}佑树：嘿，{PLAYER}！\p"
	.string "怎么样？宝可梦图鉴\n"
	.string "填写得顺利吗？\p"
	.string "我听到一个传闻说有\n"
	.string "超古代宝可梦存在。\l"
	.string "而且不只是一只——三只！\p"
	.string "我连一只都想捉到…$"

MatchCall_Text_Brendan14::
	.string "{CHN}佑树：{PLAYER}！\n"
	.string "我听到传闻了！\p"
	.string "你打败了琉璃道馆\n"
	.string "馆主？太棒了！\p"
	.string "你离目标越来越近了！$"

MatchCall_Text_Brendan15::
	.string "{CHN}佑树：丰缘没有一个训练家\n"
	.string "不知道你是\l"
	.string "谁，{PLAYER}！\p"
	.string "当我告诉人们我和你是朋友时，\n"
	.string "{PLAYER}，他们都挺\l"
	.string "嫉妒的！$"

MatchCall_Text_Wally1::
	.string "{CHN}路比：哦，{PLAYER}！\p"
	.string "我越来越健康，\n"
	.string "身体也越来越强壮了。\p"
	.string "我希望我能很快成为像你\n"
	.string "一样的训练家，{PLAYER}！$"

MatchCall_Text_Wally2::
	.string "{CHN}路比：{PLAYER}，你好！\p"
	.string "卡绿隧道开通后，\n"
	.string "婉达一直很开心！$"

MatchCall_Text_Wally3::
	.string "{CHN}路比：哦，{PLAYER}！\p"
	.string "我…我没告诉任何人就\n"
	.string "离开了绿荫镇的叔叔家。\p"
	.string "不知道他是不是生我的气了…\p"
	.string "{PLAYER}，你理解\n"
	.string "我的感受，对吧？$"

MatchCall_Text_Wally4::
	.string "{CHN}路比：{PLAYER}？\n"
	.string "是我，路比！\p"
	.string "训练家的世界真了不起！\p"
	.string "当我和宝可梦在一起时，\n"
	.string "各种各样的人都会和我打招呼！\p"
	.string "就好像每个人都在\n"
	.string "通过宝可梦联系在一起！$"

MatchCall_Text_Wally5::
	.string "{CHN}路比：{PLAYER}？太棒了！\n"
	.string "我们一起捉的那只拉鲁鲁丝？\l"
	.string "它进化了，{PLAYER}！\p"
	.string "也许我有天赋…\p"
	.string "哦，但我不该这么\n"
	.string "自大！\p"
	.string "毕竟，应该被表扬的\n"
	.string "是宝可梦！$"

MatchCall_Text_Wally6::
	.string "{CHN}… … … … … …\n"
	.string "… … … … … …\p"
	.string "路比似乎不在\n"
	.string "宝可梦导航器的服务区…$"

MatchCall_Text_Wally7::
	.string "{CHN}路比：哦，{PLAYER}！\p"
	.string "在遇到你之前，我几乎\n"
	.string "从未离开过家…\p"
	.string "但现在，我和\n"
	.string "我自己的宝可梦一起冒险…\p"
	.string "{PLAYER}…\n"
	.string "谢谢你…$"

MatchCall_Text_Scott1::
	.string "{CHN}水木：嘿，{PLAYER}{KUN}！\p"
	.string "你知道宝可梦可以在\n"
	.string "任何地方找到吗？\p"
	.string "比如山里、海里、\n"
	.string "任何地方的高草丛里？\p"
	.string "就像宝可梦一样，你也可以在\n"
	.string "任何地方找到训练家。\p"
	.string "所以，我也得\n"
	.string "到处赶路。忙，忙！$"

MatchCall_Text_Scott2::
	.string "{CHN}水木：我现在在119号道路。\n"
	.string "这里训练家遍地都是！\p"
	.string "而且似乎到处都是\n"
	.string "高高的草丛。\p"
	.string "在这里穿短裤走路\n"
	.string "让我浑身痒痒！$"

MatchCall_Text_Scott3::
	.string "{CHN}水木：嗨，嗨，{PLAYER}{KUN}！\p"
	.string "你有机会爬过\n"
	.string "送火山吗？\p"
	.string "那个地方是对已逝\n"
	.string "宝可梦的纪念。\p"
	.string "它是每个训练家\n"
	.string "都应该爬到山顶一次的地方。$"

MatchCall_Text_Scott4::
	.string "{CHN}水木：嗨，{PLAYER}{KUN}！\p"
	.string "我一直听到这些奇怪的\n"
	.string "团伙在捣乱的消息。\p"
	.string "火焰队和水舰队，\n"
	.string "好像是这样叫的。\p"
	.string "我想他们之中应该有一些\n"
	.string "厉害的训练家。\p"
	.string "…但如果是暴徒的话…$"

MatchCall_Text_Scott5::
	.string "{CHN}水木：哦，嗨，{PLAYER}{KUN}。\p"
	.string "海底会不会有\n"
	.string "厉害的训练家呢？\p"
	.string "我没法亲自去确认。\n"
	.string "一来我不会游泳。\l"
	.string "而且我不培育宝可梦…$"

MatchCall_Text_Scott6::
	.string "{CHN}水木：嗨，嗨，{PLAYER}{KUN}！\p"
	.string "你知道当你收集了所有\n"
	.string "道馆徽章后就可以挑战\l"
	.string "宝可梦联盟吗？\p"
	.string "以你的才能，成为\n"
	.string "冠军不是梦想。\p"
	.string "但你知道吗？\n"
	.string "还有一个更好的地方。\p"
	.string "不过，目前\n"
	.string "我只能说到这里。\p"
	.string "这是你可以期待\n"
	.string "的事情。\p"
	.string "当你赢得宝可梦联盟\n"
	.string "进入名人堂之后！\l"
	.string "$"

MatchCall_Text_Scott7::
	.string "{CHN}… … … … … …\n"
	.string "… … … … … …\p"
	.string "水木似乎不在\n"
	.string "宝可梦导航器的服务区…$"

MatchCall_Text_Norman1::
	.string "{CHN}爸爸：在卡那兹市，有个人\n"
	.string "有着碎岩大叔这个\l"
	.string "奇怪名字。\p"
	.string "如果你在附近，应该\n"
	.string "去拜访他一下。$"

MatchCall_Text_Norman2::
	.string "{CHN}爸爸：嗯…一点一点地，但也很\n"
	.string "确实地，你变强了，\l"
	.string "{PLAYER}。\p"
	.string "你越强，就飞得\n"
	.string "越远越高，离开妈妈\l"
	.string "和我…\p"
	.string "这种感觉很难解释。$"

MatchCall_Text_Norman3::
	.string "{CHN}爸爸：我明白了…\n"
	.string "你已经收集了四个道馆徽章…\p"
	.string "现在躲不掉了。\n"
	.string "我们会像约定好的那样对战。\p"
	.string "随时来吧。\n"
	.string "我们都在等你！$"

MatchCall_Text_Norman4::
	.string "{CHN}爸爸：{PLAYER}！你最好偶尔\n"
	.string "去看看妈妈。\p"
	.string "我会留在这里\n"
	.string "加倍训练。\p"
	.string "对战之道深奥\n"
	.string "而无情！$"

MatchCall_Text_Norman5::
	.string "{CHN}爸爸：哦，嗨，{PLAYER}！\p"
	.string "什么？熔岩徽章？\n"
	.string "我不知道那是什么。\p"
	.string "但既然叫这个名字，可能\n"
	.string "和火山有什么关系！$"

MatchCall_Text_Norman6::
	.string "{CHN}爸爸：嘿呀！哈啊！嘟啊！\p"
	.string "…哦？{PLAYER}！\p"
	.string "你正好碰到我\n"
	.string "在训练宝可梦！$"

MatchCall_Text_Norman7::
	.string "{CHN}爸爸：{PLAYER}！\p"
	.string "谁能想到你会成为\n"
	.string "宝可梦联盟冠军…\p"
	.string "好！\n"
	.string "我不会落后的！$"

MatchCall_Text_Norman8::
	.string "{CHN}爸爸：嗯？{PLAYER}？\n"
	.string "来得正好！\p"
	.string "这次，我要挑战\n"
	.string "你对战。\p"
	.string "我在橙华道馆等你。\n"
	.string "随时接受我的挑战！$"

MatchCall_Text_Norman9::
	.string "{CHN}爸爸：…你让我惊讶，{PLAYER}。\n"
	.string "你还能飞多高呢？$"

MatchCall_Text_Steven1::
	.string "{CHN}大吾：嗨，{PLAYER}{KUN}！\p"
	.string "你去过\n"
	.string "紫堇市了吗？\p"
	.string "你应该去自行车店\n"
	.string "买辆音速自行车。\p"
	.string "然后，试着彻底探索\n"
	.string "石之洞窟。\p"
	.string "你可能会在那里\n"
	.string "有新发现。$"

MatchCall_Text_Steven2::
	.string "{CHN}大吾：嗨，{PLAYER}{KUN}！\p"
	.string "我到目前为止遇到了\n"
	.string "很多不同的训练家。\p"
	.string "但你是独一无二的。\n"
	.string "你不像任何人。$"

MatchCall_Text_Steven3::
	.string "{CHN}大吾：嗨，{PLAYER}{KUN}！\p"
	.string "当你和宝可梦一起冒险时，\n"
	.string "你在想什么？\p"
	.string "你把它们当作强大的\n"
	.string "伙伴吗？\p"
	.string "还是把它们当作有趣的\n"
	.string "同伴？\p"
	.string "根据你的想法，你冒险\n"
	.string "的意义也会改变。$"

MatchCall_Text_Steven4::
	.string "{CHN}大吾：喂？\n"
	.string "{PLAYER}{KUN}？\p"
	.string "我在宇宙中心遇到了\n"
	.string "一些麻烦。\p"
	.string "抱歉，我现在不能说话。\n"
	.string "拜拜！$"

MatchCall_Text_Steven5::
	.string "{CHN}大吾：哦！\n"
	.string "{PLAYER}{KUN}！\p"
	.string "不需要说话了。\n"
	.string "说话的时间已经过了。\p"
	.string "你要相信自己\n"
	.string "做正确的事。$"

MatchCall_Text_Steven6::
	.string "{CHN}… … … … … …\p"
	.string "大吾似乎没有接到\n"
	.string "电话…$"

MatchCall_Text_Steven7::
	.string "{CHN}大吾：{PLAYER}{KUN}…恭喜你\n"
	.string "进入名人堂。\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "希望我们能\n"
	.string "在某个地方再见！$"

MatchCall_Text_BirchRegisterCall:
	.string "{CHN}小田卷博士：哦，{PLAYER}{KUN}！\n"
	.string "我已经听说过你的事了！\p"
	.string "看来你的宝可梦导航器\n"
	.string "升级了对战寻呼功能。\p"
	.string "好，我也该注册了！\p"
	.string "这样，即使你在\n"
	.string "野外，我也能查看\l"
	.string "你的宝可梦图鉴。\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "{CHN}已将小田卷博士\n"
	.string "注册到宝可梦导航器中。$"

MatchCall_Text_UnusedProfBirch:
	.string "{CHN}小田卷博士：同时拥有\n"
	.string "宝可梦图鉴和宝可梦导航器，\l"
	.string "研究宝可梦就更有趣了，对吧？$"

MatchCall_Text_MrStone1::
	.string "{CHN}斯通先生：哦？{PLAYER}{KUN}！\p"
	.string "既然你打给我了，宝可梦导航器\n"
	.string "一定没问题！\p"
	.string "其他人也会被注册，\n"
	.string "所以试着也打给他们！\p"
	.string "好！好！\n"
	.string "你看起来很高兴！\p"
	.string "嗯…\n"
	.string "我怎么知道的？\p"
	.string "因为我正从办公室\n"
	.string "窗户看着你！\p"
	.string "哇哈哈哈！\n"
	.string "再见！$"

MatchCall_Text_MrStone2::
	.string "{CHN}斯通先生：哦？{PLAYER}{KUN}！\p"
	.string "怎么了？你是不是忘了\n"
	.string "我那个小差事？\p"
	.string "我需要你把我的信\n"
	.string "送到武斗镇给大吾。\p"
	.string "之后，把我们的包裹送到\n"
	.string "凯那市给史藤船长。\p"
	.string "你记得吧？\p"
	.string "好了，身为一个忙碌的总裁，\n"
	.string "我得走了！拜拜！$"

MatchCall_Text_MrStone3::
	.string "{CHN}斯通先生：哦！{PLAYER}{KUN}！\p"
	.string "啊，你见到大吾了！\n"
	.string "那我得奖励你！\p"
	.string "当你再到卡那兹市时，\n"
	.string "来我办公室找我。\p"
	.string "我会等你的！$"

MatchCall_Text_MrStone4::
	.string "{CHN}斯通先生：哦！{PLAYER}{KUN}！\p"
	.string "你知道卡绿隧道\n"
	.string "是得佛公司挖的吗？\p"
	.string "但我们停工了，\n"
	.string "为了保护那个地区的宝可梦。\p"
	.string "这不用说也知道。\p"
	.string "让宝可梦安宁地生活\n"
	.string "比我们自己的\l"
	.string "方便更重要。$"

MatchCall_Text_MrStone5::
	.string "{CHN}斯通先生：你好，你好，{PLAYER}{KUN}！\p"
	.string "我从橙华市的人那里听说\n"
	.string "你是千里的孩子！\p"
	.string "难怪你这么能干！$"

MatchCall_Text_MrStone6::
	.string "{CHN}斯通先生：什么？\p"
	.string "你和你爸爸对战\n"
	.string "还打败了他？\p"
	.string "太惊人了！\p"
	.string "我没想到我结交了\n"
	.string "这么特别的人！哇哈哈！$"

MatchCall_Text_MrStone7::
	.string "{CHN}喂！\n"
	.string "这里是得佛公司…\l"
	.string "哦，你好，{PLAYER}！\p"
	.string "我们的总裁刚才还在，\n"
	.string "但他出去了。\p"
	.string "我们的总裁很忙，但你也\n"
	.string "一样忙呢，{PLAYER}。$"

MatchCall_Text_MrStone8::
	.string "{CHN}…嗯？…什么？\p"
	.string "固拉…是？…顿？\p"
	.string "信号不好…\n"
	.string "…听不清…\p"
	.string "滋滋滋…$"

MatchCall_Text_MrStone9::
	.string "{CHN}…嗯？…什么？\p"
	.string "海底…是？…洞窟…？\p"
	.string "信号不好…\n"
	.string "…听不清…\p"
	.string "滋滋滋…$"

MatchCall_Text_MrStone10::
	.string "{CHN}斯通先生：{PLAYER}{KUN}！是我！\p"
	.string "你显然卷入了各种\n"
	.string "事情，但我很忙，\l"
	.string "完全不知道具体是什么！\p"
	.string "不过，我敦促你走\n"
	.string "你相信的路。\p"
	.string "我会一直支持你！\n"
	.string "保重！$"

MatchCall_Text_MrStone11::
	.string "{CHN}斯通先生：… … … … … …\n"
	.string "是{PLAYER}{KUN}吗？\p"
	.string "你的声音充满自信，\n"
	.string "我一时没认出来！\p"
	.string "嗯！你一定要来\n"
	.string "得佛公司走走！$"