@ Only contains the text for the Mauville Man named Giddy. The Rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "{CHN} 太漂亮了！$"

GiddyText_SoDarling::
	.string "{CHN} 太可爱了！$"

GiddyText_SoRelaxed::
	.string "{CHN} 太轻松了！$"

GiddyText_SoSunny::
	.string "{CHN} 太阳光了！$"

GiddyText_SoDesirable::
	.string "{CHN} 太令人向往了！$"

GiddyText_SoExciting::
	.string "{CHN} 太刺激了！$"

GiddyText_SoAmusing::
	.string "{CHN} 太有趣了！$"

GiddyText_SoMagical::
	.string "{CHN} 太神奇了！$"

GiddyText_Is::
	.string "{CHN} 是$"

GiddyText_DontYouAgree::
	.string "{CHN}\n"
	.string "你不觉得吗？$"

GiddyText_ISoWantToGoOnAVacation::
	.string "{CHN}我好想去度假啊。\n"
	.string "你知道有什么好地方吗？$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "{CHN}我买了120色的蜡笔！\n"
	.string "你不觉得很棒吗？$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "{CHN}要是我们能乘着\n"
	.string "泡泡飘走，那该多好啊？$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "{CHN}当你在沙滩上写字，\n"
	.string "它们会被冲走。这让我很难过。$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "{CHN}海底是什么样子的？\n"
	.string "我真想去一次！$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "{CHN}当你看到夕阳时，\n"
	.string "会不会想回家？$"

GiddyText_LyingBackInTheGreenGrass::
	.string "{CHN}躺在绿草地上……\n"
	.string "哦，真是太棒了！$"

GiddyText_SecretBasesAreSoWonderful::
	.string "{CHN}秘密基地真是太棒了！\n"
	.string "你能感受到那种兴奋吗？$"
