MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "{CHN}这个招式只能学习\n"
	.string "一次。可以吗？$"

MoveTutor_Text_SwaggerTeach:
	.string "{CHN}嘿！我的宝可梦超厉害！\n"
	.string "比任何宝可梦都酷！\p"
	.string "我正迈着虚张声势的步伐\n"
	.string "大摇大摆地走着，结果被董事长\l"
	.string "狠狠训了一顿。\p"
	.string "那让我再也不敢虚张声势了。\p"
	.string "如果您愿意，我可以教\n"
	.string "您的宝可梦虚张声势招式。$"

MoveTutor_Text_SwaggerDeclined:
	.string "{CHN}什么，不行吗？您就不能\n"
	.string "有点干劲吗？$"

MoveTutor_Text_SwaggerWhichMon:
	.string "{CHN}好的，哪只宝可梦想要\n"
	.string "学习虚张声势呢？$"

MoveTutor_Text_SwaggerTaught:
	.string "{CHN}从今以后我会好好夸奖我的宝可梦，\n"
	.string "不再虚张声势了。$"

MoveTutor_Text_RolloutTeach:
	.string "{CHN}您知道吗，从这里朝那个方向\n"
	.string "可以走很远很远\l"
	.string "而不用改变方向？\p"
	.string "我甚至可以滚着\n"
	.string "过去。\p"
	.string "您觉得您的宝可梦\n"
	.string "也会想滚吗？\p"
	.string "如果您愿意的话，\n"
	.string "我可以教它滚动招式。$"

MoveTutor_Text_RolloutDeclined:
	.string "{CHN}您不必害羞。\n"
	.string "一起滚吧！$"

MoveTutor_Text_RolloutWhichMon:
	.string "{CHN}嘿嘿，没问题！要是\n"
	.string "宝可梦长得像我那就太好了。$"

MoveTutor_Text_RolloutTaught:
	.string "{CHN}在草地上滚来滚去让我\n"
	.string "很快乐。来吧，一起滚！$"

MoveTutor_Text_FuryCutterTeach:
	.string "{CHN}有一种招式连续使用\n"
	.string "就会变得越来越强。\p"
	.string "它是虫属性招式，\n"
	.string "酷得不得了。\p"
	.string "它叫做连斩。\n"
	.string "要让我教给某只宝可梦吗？$"

MoveTutor_Text_FuryCutterDeclined:
	.string "{CHN}我们好像合不来。$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "{CHN}耶！\n"
	.string "告诉我应该教哪只宝可梦。$"

MoveTutor_Text_FuryCutterTaught:
	.string "{CHN}看着招式是否连续命中\n"
	.string "让我好兴奋！$"

MoveTutor_MimicTeach:
	.string "{CHN}啊，年轻人！\p"
	.string "我也是年轻人，但我模仿\n"
	.string "这个镇上老人们的\l"
	.string "风格和说话方式。\p"
	.string "您说呢，年轻人？\n"
	.string "如果我提议教\l"
	.string "模仿招式，您会同意吗？$"

MoveTutor_MimicDeclined:
	.string "{CHN}哦，讨厌！我想教\n"
	.string "您的宝可梦模仿呢！$"

MoveTutor_Text_MimicWhichMon:
	.string "{CHN}呼哦！那我就教吧！\n"
	.string "让我看看您想让我教\l"
	.string "哪只宝可梦。$"

MoveTutor_Text_MimicTaught:
	.string "{CHN}模仿是很有深度的招式。\p"
	.string "您能否像我一样\n"
	.string "完美地使用它……？$"

MoveTutor_Text_MetronomeTeach:
	.string "{CHN}我想要各种各样的东西！\n"
	.string "但是我的零花钱都用光了……\p"
	.string "要是有一个咒语，\n"
	.string "摇一摇手指就能\l"
	.string "变出钱来，那该多好？\p"
	.string "如果您愿意，我可以教您的宝可梦\n"
	.string "摇手指招式。\p"
	.string "钱不会变出来，但您的宝可梦\n"
	.string "会摇手指。怎么样？$"

MoveTutor_Text_MetronomeDeclined:
	.string "{CHN}好吧。如果您改变主意，\n"
	.string "我就在这里。$"

MoveTutor_Text_MetronomeWhichMon:
	.string "{CHN}好的！我来教！\n"
	.string "应该教哪只宝可梦呢？$"

MoveTutor_Text_MetronomeTaught:
	.string "{CHN}当宝可梦像节拍器一样\n"
	.string "摇动手指时，各种\l"
	.string "好事就会发生。\p"
	.string "要是我们也能\n"
	.string "使用它，那该多好？$"

MoveTutor_Text_SleepTalkTeach:
	.string "{CHN}哼！我老婆靠\n"
	.string "觉醒力量来保持清醒。\p"
	.string "她应该像我一样打个盹，\n"
	.string "说梦话。\p"
	.string "我可以教您的宝可梦\n"
	.string "说梦话。有兴趣吗？$"

MoveTutor_Text_SleepTalkDeclined:
	.string "{CHN}哦，行，行。您也想用\n"
	.string "觉醒力量保持清醒……$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "{CHN}啊，懂事的孩子！\n"
	.string "应该教哪只宝可梦呢？$"

MoveTutor_Text_SleepTalkTaught:
	.string "{CHN}我老婆的硬币戏法\n"
	.string "我一次都没学会。\p"
	.string "要是我在说梦话时\n"
	.string "能学会就好了……$"

MoveTutor_Text_SubstituteTeach:
	.string "{CHN}当我从屋顶上\n"
	.string "眺望广阔的世界……\p"
	.string "我在想，要是不止一个我，\n"
	.string "那该多好，\l"
	.string "这样我就能享受各种人生。\p"
	.string "当然这不可能。\n"
	.string "咯咯……\p"
	.string "我知道了！您有没有兴趣\n"
	.string "让宝可梦学习替身呢？$"

MoveTutor_Text_SubstituteDeclined:
	.string "{CHN}哦，不要吗？\p"
	.string "宝可梦可以用它\n"
	.string "制造自己的分身哦。$"

MoveTutor_Text_SubstituteWhichMon:
	.string "{CHN}咯咯……\n"
	.string "您想让我教哪只\l"
	.string "宝可梦替身呢？$"

MoveTutor_Text_SubstituteTaught:
	.string "{CHN}我们人类应该尽情\n"
	.string "享受自己的人生！\p"
	.string "我希望您也能那样！$"

MoveTutor_Text_DynamicPunchTeach:
	.string "{CHN}我再也受不了了！\p"
	.string "完全没希望了！\p"
	.string "我是格斗属性训练家，\n"
	.string "所以无论我怎么努力，\l"
	.string "都无法在绿岭道馆获胜！\p"
	.string "啊！打！打！打！\n"
	.string "打！打！打！\p"
	.string "什么，别那样看着我！\n"
	.string "我只是在打地面！\p"
	.string "还是说您想让我教您的\n"
	.string "宝可梦爆裂拳？$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "{CHN}可恶！您居然也取笑我？\n"
	.string "打！打！打！$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "{CHN}什么？您要？您真是好人！\n"
	.string "应该教哪只宝可梦呢？$"

MoveTutor_Text_DynamicPunchTaught:
	.string "{CHN}我希望您用爆裂拳\n"
	.string "在绿岭道馆获胜！$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "{CHN}唉……\p"
	.string "琉璃市的道馆馆主\n"
	.string "真是令人爱慕。\p"
	.string "但这也意味着我有\n"
	.string "很多情敌。\p"
	.string "他有着舍身冲撞般的魅力。\n"
	.string "我连他的目光都吸引不了。\p"
	.string "拜托，让我教您的宝可梦\n"
	.string "舍身冲撞招式吧！$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "{CHN}哦……\n"
	.string "连您也拒绝我……$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "{CHN}好的，应该教哪只宝可梦\n"
	.string "舍身冲撞呢？$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "{CHN}我不再为爱而活！\n"
	.string "我要变得坚强！$"

MoveTutor_Text_ExplosionTeach:
	.string "{CHN}我不打算永远\n"
	.string "待在这种乡下地方一事无成。\p"
	.string "您看着吧，我要去城里\n"
	.string "大出风头。\p"
	.string "说真的，我要引发\n"
	.string "一场人气的大爆炸！\p"
	.string "如果您听到了，我很乐意\n"
	.string "教您的宝可梦大爆炸！$"

MoveTutor_Text_ExplosionDeclined:
	.string "{CHN}啊！您拒绝我\n"
	.string "是因为我住在乡下吗？$"

MoveTutor_Text_ExplosionWhichMon:
	.string "{CHN}好！就来大爆炸！\n"
	.string "哪只宝可梦想爆炸呢？$"

MoveTutor_Text_ExplosionTaught:
	.string "{CHN}长久以来，我教宝可梦\n"
	.string "如何使用大爆炸，但我自己\l"
	.string "却还没引爆自己的大爆炸……\p"
	.string "也许是因为内心深处，\n"
	.string "我宁愿留在这里……$"
