gText_ObtainedTheItem::
	.string "{CHN}获得了{STR_VAR_2}！$"

gText_TheBagIsFull::
	.string "{CHN}背包已满…$"

gText_PutItemInPocket::
	.string "{CHN}{PLAYER}将{STR_VAR_2}\n"
	.string "放进了{STR_VAR_3}口袋。$"

gText_PlayerFoundOneItem::
	.string "{CHN}{PLAYER}找到了一个{STR_VAR_2}！$"

gText_TooBadBagIsFull::
	.string "{CHN}真可惜！\n"
	.string "背包已满…$"

gText_PlayerPutItemInBag::
	.string "{CHN}{PLAYER}将{STR_VAR_2}\n"
	.string "放进了背包。$"

gText_ObtainedTheDecor::
	.string "{CHN}获得了{STR_VAR_2}！$"

gText_NoRoomLeftForAnother::
	.string "{CHN}真可惜！没有空间再放\n"
	.string "另一个{STR_VAR_2}了…$"

gText_TheDecorWasTransferredToThePC::
	.string "{CHN}{STR_VAR_2}被传送到\n"
	.string "电脑。$"
