gText_PkmnTransferredSomeonesPC::
	.string "{CHN}{STR_VAR_2}被传送到\n"
	.string "某人的电脑。\p"
	.string "它被放入了\n"
	.string "盒子“{STR_VAR_1}。”$"

gText_PkmnTransferredLanettesPC::
	.string "{CHN}{STR_VAR_2}被传送到\n"
	.string "莉莉的电脑。\p"
	.string "它被放入了\n"
	.string "盒子“{STR_VAR_1}。”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{CHN}某人电脑上的\n"
	.string "盒子“{STR_VAR_3}”已满。\p"
	.string "{STR_VAR_2}被传送到\n"
	.string "盒子“{STR_VAR_1}。”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "{CHN}莉莉电脑上的\n"
	.string "盒子“{STR_VAR_3}”已满。\p"
	.string "{STR_VAR_2}被传送到\n"
	.string "盒子“{STR_VAR_1}。”$"

gText_NoMoreRoomForPokemon::
	.string "{CHN}没有更多空间放置宝可梦了！\p"
	.string "宝可梦盒子已满，\n"
	.string "无法再接受更多！$"

gText_NicknameThisPokemon::
	.string "{CHN}要给这只\n"
	.string "{STR_VAR_1}起个昵称吗？$"
