gText_WouldYouLikeToRestYourPkmn::
	.string "{CHN}你好，欢迎来到\n"
	.string "宝可梦中心。\p"
	.string "我们会让您的疲惫宝可梦\n"
	.string "恢复到完全健康。\p"
	.string "要让您的宝可梦休息吗？$"

gText_IllTakeYourPkmn::
	.string "{CHN}好的，我会收下您的宝可梦\n"
	.string "几秒钟。$"

gText_RestoredPkmnToFullHealth::
	.string "{CHN}感谢您的等待。\p"
	.string "我们已经让您的宝可梦\n"
	.string "恢复到完全健康。$"

gText_WeHopeToSeeYouAgain::
	.string "{CHN}期待再次见到您！$"

gText_WelcomeCutShort::
	.string "{CHN}你好，欢迎来到\n"
	.string "宝可梦中心。\p"
	.string "我们会让您的疲惫宝可梦\n"
	.string "恢复到完全健康。\p"
	.string "您想要……$"

gText_NoticesGoldCard::
	.string "{CHN}那……那张卡……\n"
	.string "难道是……金卡？！\p"
	.string "哦，金色多么耀眼！\n"
	.string "四颗星星似乎在闪闪发光！\p"
	.string "我见过几位持有\n"
	.string "银卡的训练家，但是，{PLAYER}，\l"
	.string "您是我见过的第一位\l"
	.string "持有金卡的训练家！\p"
	.string "好的，{PLAYER}，请允许我\n"
	.string "荣幸地让您的宝可梦休息！$"

gText_YouWantTheUsual::
	.string "{CHN}很高兴见到您，{PLAYER}！\n"
	.string "您想要照旧，对吗？$"

gText_IllTakeYourPkmn2::
	.string "{CHN}好的，我会收下您的宝可梦\n"
	.string "几秒钟。$"

gText_ThankYouForWaiting::
	.string "{CHN}感谢您的等待。$"

gText_WeHopeToSeeYouAgain2::
	.string "{CHN}期待再次见到您！$"
