gBirchDexRatingText_AreYouCurious::
	.string "{CHN}小田卷博士：啊，{PLAYER}{KUN}！\p"
	.string "你对自己的宝可梦图鉴\n"
	.string "进展情况感到好奇吗？$"

gBirchDexRatingText_Cancel::
	.string "{CHN}嗯？哦，你还没抓到足够的\n"
	.string "宝可梦，还不足以让人一看。$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "{CHN}嗯嗯……\p"
	.string "那么，你已经见过{STR_VAR_1}只宝可梦，\n"
	.string "并且抓到了{STR_VAR_2}只宝可梦……$"

gBirchDexRatingText_LessThan10::
	.string "{CHN}多去草丛里走走，\n"
	.string "更仔细地寻找宝可梦吧。$"

gBirchDexRatingText_LessThan20::
	.string "{CHN}我想你已经掌握了窍门。\n"
	.string "但是，从这里开始会变得更难。$"

gBirchDexRatingText_LessThan30::
	.string "{CHN}有些宝可梦只会出现在\n"
	.string "特定的区域。\l"
	.string "你必须要有耐心。$"

gBirchDexRatingText_LessThan40::
	.string "{CHN}嗯，数量还可以再多一些，\n"
	.string "但这看起来越来越像\l"
	.string "一本宝可梦图鉴了。$"

gBirchDexRatingText_LessThan50::
	.string "{CHN}进展得相当不错。\n"
	.string "继续努力。$"

gBirchDexRatingText_LessThan60::
	.string "{CHN}你有在用钓竿吗？\n"
	.string "海里有许多宝可梦。$"

gBirchDexRatingText_LessThan70::
	.string "{CHN}除了抓宝可梦之外，\n"
	.string "要不要也让它们进化呢？$"

gBirchDexRatingText_LessThan80::
	.string "{CHN}这将会是一本了不起的\n"
	.string "宝可梦图鉴。\l"
	.string "我有这种预感。$"

gBirchDexRatingText_LessThan90::
	.string "{CHN}你已经收集了这么多……\n"
	.string "你的才能真是非凡！$"

gBirchDexRatingText_LessThan100::
	.string "{CHN}你去过野生原野区吗？\p"
	.string "我听说那里有一些宝可梦\n"
	.string "只能在那个地方抓到。$"

gBirchDexRatingText_LessThan110::
	.string "{CHN}你终于达到了\n"
	.string "100种的标记。\p"
	.string "这是一本令人赞叹的宝可梦图鉴！$"

gBirchDexRatingText_LessThan120::
	.string "{CHN}也许有些宝可梦\n"
	.string "可以使用碎岩找到。$"

gBirchDexRatingText_LessThan130::
	.string "{CHN}通过和其他人交换，\n"
	.string "你应该能再获得一些宝可梦。$"

gBirchDexRatingText_LessThan140::
	.string "{CHN}我听说有些宝可梦\n"
	.string "在完全爱上自己的\l"
	.string "训练家时会进化。$"

gBirchDexRatingText_LessThan150::
	.string "{CHN}我没想到丰缘地区\n"
	.string "竟然有这么多种\l"
	.string "宝可梦。$"

gBirchDexRatingText_LessThan160::
	.string "{CHN}偶尔，有些宝可梦会\n"
	.string "像爆发一样大量出现。\p"
	.string "不要错过这样的机会。$"

gBirchDexRatingText_LessThan170::
	.string "{CHN}通过翻阅你的宝可梦图鉴，\n"
	.string "可以很好地了解丰缘地区的\l"
	.string "宝可梦。$"

gBirchDexRatingText_LessThan180::
	.string "{CHN}我觉得你已经够资格成为\n"
	.string "一名宝可梦博士了，而且还是位\l"
	.string "优秀的博士！$"

gBirchDexRatingText_LessThan190::
	.string "{CHN}拥有这么完整的宝可梦图鉴，\n"
	.string "你已经是这方面的真正专家了！$"

gBirchDexRatingText_LessThan200::
	.string "{CHN}你已经非常接近完成\n"
	.string "这本宝可梦图鉴了。\l"
	.string "我能感觉得到！$"

gBirchDexRatingText_DexCompleted::
	.string "{CHN}恭喜你！\n"
	.string "你的宝可梦图鉴已经完成了！$"

gBirchDexRatingText_OnANationwideBasis::
	.string "{CHN}嗯嗯……\n"
	.string "在全国范围内……\p"
	.string "你已经见过{STR_VAR_1}只宝可梦，\n"
	.string "并且抓到了{STR_VAR_2}只宝可梦……$"
