Questionnaire_Text_FillOut::
	.string "{CHN}这里有一份问卷。\n"
	.string "您想填写吗？$"

Questionnaire_Text_ThankYou::
	.string "{CHN}感谢您抽出时间\n"
	.string "填写我们的问卷。\p"
	.string "您的反馈将作为\n"
	.string "今后的参考。$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "{CHN}哦，您好！\n"
	.string "您知道那些词？\p"
	.string "那就意味着您一定知道\n"
	.string "神秘礼物。\p"
	.string "从现在起，您应该可以\n"
	.string "接收神秘礼物了！$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "{CHN}保存游戏后，您就可以\n"
	.string "使用神秘礼物了。$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "{CHN}哦，您好！\n"
	.string "您知道那些词？\p"
	.string "那就意味着您一定知道\n"
	.string "神秘事件。$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "{CHN}保存游戏后，您就可以\n"
	.string "使用神秘事件了。$"

MysteryGift_Text_TheresATicketForYou::
	.string "{CHN}感谢您使用神秘\n"
	.string "事件系统。\p"
	.string "您一定是{PLAYER}吧。\n"
	.string "这里有一张给您的票。$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "{CHN}它似乎是用来在\n"
	.string "水静市港口使用的。\p"
	.string "何不试一试，看看\n"
	.string "是怎么回事呢？$"
