	.align 2
gText_ConfirmSave::
	.string "{CHN}要保存游戏吗？$"

gText_AlreadySavedFile::
	.string "{CHN}已经存在保存文件。\n"
	.string "要覆盖它吗？$"

gText_SavingDontTurnOff::
	.string "{CHN}保存中…\n"
	.string "请勿关闭电源。$"

gText_PlayerSavedGame::
	.string "{CHN}{PLAYER}保存了游戏。$"

gText_DifferentSaveFile::
	.string "{CHN}警告！\p"
	.string "已经存在另一个游戏文件。\n"
	.string "如果现在保存，另一个文件的\n"
	.string "冒险，包括道具和\l"
	.string "宝可梦，将全部丢失。\p"
	.string "确定要现在保存\n"
	.string "并覆盖另一个保存文件吗？$"

gText_SaveError::
	.string "{CHN}保存错误。\p"
	.string "请更换\n"
	.string "备份记忆体。$"

gText_SavingDontTurnOffPower::
	.string "{CHN}保存中…\n"
	.string "请勿关闭电源。$"
