SecretBase_Text_Trainer0Intro:
	.string "{CHN}你已经做好秘密基地了吗？\p"
	.string "我到处走遍了，\n"
	.string "才选择了这个地方。\p"
	.string "既然你已经来了，\n"
	.string "要不要来对战一场？$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "{CHN}好！\n"
	.string "我们上吧！$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "{CHN}咦？\n"
	.string "哦，你现在不行吗……$"

SecretBase_Text_Trainer0Defeated::
	.string "{CHN}哇啊！你太强了！\n"
	.string "关于我输了这件事……请保密！$"

SecretBase_Text_Trainer0PostBattle:
	.string "{CHN}你觉得我的秘密基地怎么样？\n"
	.string "明天再来找我玩吧。$"

SecretBase_Text_Trainer0PreChampion:
	.string "{CHN}你已经做好秘密基地了吗？\p"
	.string "我到处走遍了，\n"
	.string "才选择了这个地方。\p"
	.string "请随便逛逛！$"

SecretBase_Text_Trainer5Intro:
	.string "{CHN}有很多地方\n"
	.string "都可以做秘密基地。\p"
	.string "但我最喜欢这个地点。\n"
	.string "你不觉得不错吗？\p"
	.string "哦，你想来对战吗？$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "{CHN}好，开始吧！$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "{CHN}哦……\n"
	.string "好吧，下次再说。$"

SecretBase_Text_Trainer5Defeated::
	.string "{CHN}嗯……我们输了……\n"
	.string "但是不要告诉任何人！\l"
	.string "这是机密！$"

SecretBase_Text_Trainer5PostBattle:
	.string "{CHN}如果你再来这附近，\n"
	.string "希望你能来找我。$"

SecretBase_Text_Trainer5PreChampion:
	.string "{CHN}有很多地方都可以做\n"
	.string "秘密基地。\p"
	.string "但我最喜欢这个地点。\n"
	.string "你不觉得不错吗？$"

SecretBase_Text_Trainer1Intro:
	.string "{CHN}这是个热门的地点。\n"
	.string "总是有人占着。\p"
	.string "哦！你也在想\n"
	.string "占据这个地点吗？\p"
	.string "这样吧，如果你能打败我，\n"
	.string "这个地点就归你了。$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "{CHN}好！\n"
	.string "我要守护我的秘密基地！$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "{CHN}咦？是这样吗？\n"
	.string "你对这个地点没兴趣吗？$"

SecretBase_Text_Trainer1Defeated::
	.string "{CHN}我撑不住了！\n"
	.string "我认输！$"

SecretBase_Text_Trainer1PostBattle:
	.string "{CHN}好吧，等我哪天搬走，\n"
	.string "这里就是你的了！$"

SecretBase_Text_Trainer1PreChampion:
	.string "{CHN}这是个热门的地点。\n"
	.string "总是有人占着。\p"
	.string "我等了很长时间才有空位。\n"
	.string "终于轮到我用了！$"

SecretBase_Text_Trainer6Intro:
	.string "{CHN}欢迎来到我的宝可梦实验室。\p"
	.string "我在这里秘密地进行\n"
	.string "对战的研究。\p"
	.string "你想看看我有多强吗？$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "{CHN}我要全力以赴！$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "{CHN}哦。\n"
	.string "那下次吧！$"

SecretBase_Text_Trainer6Defeated::
	.string "{CHN}嗯……我还有很多要学的。\n"
	.string "我得再多研究研究。$"

SecretBase_Text_Trainer6PostBattle:
	.string "{CHN}谢谢你和我对战。\n"
	.string "明天请再来。$"

SecretBase_Text_Trainer6PreChampion:
	.string "{CHN}欢迎来到我的宝可梦实验室。\p"
	.string "我在这里秘密地进行\n"
	.string "对战的研究。$"

SecretBase_Text_Trainer2Intro:
	.string "{CHN}大宅子虽然不错，但我更喜欢\n"
	.string "这种地方。\p"
	.string "我喜欢这里，因为会有各种各样的人\n"
	.string "来找我玩。\p"
	.string "那么，要不要来对战一场？$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "{CHN}就该这样！$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "{CHN}等你准备好了，叫我一声！$"

SecretBase_Text_Trainer2Defeated::
	.string "{CHN}啊！输了！\n"
	.string "不过对战还是很有趣的！$"

SecretBase_Text_Trainer2PostBattle:
	.string "{CHN}嗯，总之，我应该去买些\n"
	.string "装饰品和家具。\p"
	.string "我想让我的秘密基地成为\n"
	.string "其他人也能享受的地方。$"

SecretBase_Text_Trainer2PreChampion:
	.string "{CHN}大宅子虽然不错，但我更喜欢\n"
	.string "这种地方。\p"
	.string "我喜欢这里，因为会有各种各样的人\n"
	.string "来找我玩。$"

SecretBase_Text_Trainer7Intro:
	.string "{CHN}我就是喜欢购买装饰品\n"
	.string "和家具。\p"
	.string "我也同样喜欢\n"
	.string "培养宝可梦。\p"
	.string "如果你愿意的话，能和我的宝可梦\n"
	.string "对战一场吗？$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "{CHN}谢谢你。\n"
	.string "我们开始吧？$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "{CHN}哦。\n"
	.string "真令人失望……$"

SecretBase_Text_Trainer7Defeated::
	.string "{CHN}我认输……$"

SecretBase_Text_Trainer7PostBattle:
	.string "{CHN}刚才真有趣！\n"
	.string "我应该去享受购物了。$"

SecretBase_Text_Trainer7PreChampion:
	.string "{CHN}我就是喜欢购买装饰品\n"
	.string "和家具。\p"
	.string "我也同样喜欢\n"
	.string "培养宝可梦。$"

SecretBase_Text_Trainer3Intro:
	.string "{CHN}有些人把秘密基地建在\n"
	.string "很难找到的地方。\l"
	.string "他们是想躲起来吗？\p"
	.string "不过既然你找到了我，\n"
	.string "要不要来对战一场？$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "{CHN}我可不会轻易认输！$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "{CHN}哦……你大概是找这个地方\n"
	.string "找累了吧？$"

SecretBase_Text_Trainer3Defeated::
	.string "{CHN}我输了……$"

SecretBase_Text_Trainer3PostBattle:
	.string "{CHN}你的秘密基地在哪里？\n"
	.string "我应该去那里拜访你。$"

SecretBase_Text_Trainer3PreChampion:
	.string "{CHN}有些人把秘密基地建在\n"
	.string "很难找到的地方。\l"
	.string "他们是想躲起来吗？$"

SecretBase_Text_Trainer8Intro:
	.string "{CHN}有人告诉我，可以通过几种方式\n"
	.string "获得装饰品。\p"
	.string "我们应该比一比，看谁能弄到\n"
	.string "更漂亮的装饰品和家具！\p"
	.string "顺便一提，要来对战吗？$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "{CHN}这是我的秘密基地。\n"
	.string "我不能输！$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "{CHN}我随时都可以和你对战。$"

SecretBase_Text_Trainer8Defeated::
	.string "{CHN}咦？\n"
	.string "我刚才输了吗？$"

SecretBase_Text_Trainer8PostBattle:
	.string "{CHN}收集装饰品我可不会输。\n"
	.string "再来玩啊！$"

SecretBase_Text_Trainer8PreChampion:
	.string "{CHN}有人告诉我，可以通过几种方式\n"
	.string "获得装饰品。\p"
	.string "我们应该比一比，看谁能弄到\n"
	.string "更漂亮的装饰品和家具！$"

SecretBase_Text_Trainer4Intro:
	.string "{CHN}我找到了一个喜欢的地方，\n"
	.string "用我最爱的装饰品布置了一番。\p"
	.string "我培养我最喜欢的宝可梦，\n"
	.string "和它一起变强。\p"
	.string "这就是我做的事。\n"
	.string "要和我对战吗？$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "{CHN}让我看看你的本事！$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "{CHN}看来你也有提不起劲的时候。$"

SecretBase_Text_Trainer4Defeated::
	.string "{CHN}我现在完全清楚你的本事了。$"

SecretBase_Text_Trainer4PostBattle:
	.string "{CHN}我们都能变得更强。\n"
	.string "继续努力吧！$"

SecretBase_Text_Trainer4PreChampion:
	.string "{CHN}我找到了一个喜欢的地方，\n"
	.string "用我最爱的装饰品布置了一番。\p"
	.string "我培养我最喜欢的宝可梦，\n"
	.string "和它一起变强。\p"
	.string "每一天都是美好的一天。$"

SecretBase_Text_Trainer9Intro:
	.string "{CHN}通过人们拥有的装饰品种类\n"
	.string "和摆放方式，\l"
	.string "你可以了解到他们的品味\l"
	.string "和感觉。\p"
	.string "你觉得我的品味如何？\n"
	.string "你无言以对吗？\p"
	.string "想看看我在对战方面的品味吗？$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "{CHN}绝不留手！$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "{CHN}我随时乐意展示我的风格。$"

SecretBase_Text_Trainer9Defeated::
	.string "{CHN}你真是天赋异禀！\n"
	.string "你的力量似乎无穷无尽……$"

SecretBase_Text_Trainer9PostBattle:
	.string "{CHN}你觉得我的风格如何？\n"
	.string "我会继续磨练它！$"

SecretBase_Text_Trainer9PreChampion:
	.string "{CHN}通过人们拥有的装饰品种类\n"
	.string "和摆放方式，\l"
	.string "你可以了解到他们的品味\l"
	.string "和感觉。\p"
	.string "你觉得我的品味如何？\n"
	.string "你无言以对吗？$"
