ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "{CHN}你打算深入\n"
	.string "那里吗？\p"
	.string "能不能帮我带些\n"
	.string "浅滩盐和浅滩贝壳回来？\p"
	.string "如果你能带材料给我，\n"
	.string "我可以给你做点好东西。$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "{CHN}如果你各带四份浅滩盐和浅滩贝壳给我，\l"
	.string "我可以给你做一个贝壳铃铛……\p"
	.string "你每天都能拿到那些材料。$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "{CHN}哦，嘿！浅滩盐和浅滩贝壳！\n"
	.string "而且数量也够了！\p"
	.string "你想让我用它们\n"
	.string "给你做一个贝壳铃铛吗？$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "{CHN}那么，好嘞！我马上给你\n"
	.string "做一个贝壳铃铛。\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "好啦！完成！$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "{CHN}让宝可梦带着它吧。\n"
	.string "它一定会喜欢的，这是肯定的。\p"
	.string "哎呀，贝壳铃铛的声音……\n"
	.string "简直是太美妙了！\p"
	.string "你每天都能拿到材料，\n"
	.string "所以我还能再给你做。$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "{CHN}哦……是这样啊……\n"
	.string "我本想做一个贝壳铃铛的……$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "{CHN}如果我给你做的话，\n"
	.string "你的包里没有空间放。\p"
	.string "你应该腾出空间\n"
	.string "再回来拿贝壳铃铛。$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "{CHN}这里原本有些浅滩盐。\n"
	.string "但是，现在已经什么都没有了。$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "{CHN}这里原本有个浅滩贝壳。\n"
	.string "但是，现在已经什么都没有了。$"
