Route102_Text_CalvinIntro:
	.string "{CHN}既然你带着宝可梦，\n"
	.string "那你就是正式的宝可梦训练家了！\l"
	.string "你不能拒绝我的挑战！$"

Route102_Text_CalvinDefeated:
	.string "{CHN}啊，我输了……\n"
	.string "我应该多训练一下的……$"

Route102_Text_CalvinPostBattle:
	.string "{CHN}听着，你。如果你很强，\n"
	.string "你应该早点告诉我！$"

Route102_Text_CalvinRegister:
	.string "{CHN}自从上次见到你，\n"
	.string "我就一直在努力训练。\p"
	.string "我想再和你对战一次，能\n"
	.string "把我登记到你的宝可梦导航器里吗？$"

Route102_Text_CalvinRegisterShort:
	.string "{CHN}我想再和你对战一次，能\n"
	.string "把我登记到你的宝可梦导航器里吗？$"

Route102_Text_CalvinRematchIntro:
	.string "{CHN}自从输给你之后，我拼命地\n"
	.string "训练了我的宝可梦。\l"
	.string "你不能拒绝我的挑战！$"

Route102_Text_CalvinRematchDefeated:
	.string "{CHN}啊，我输了……\n"
	.string "我的训练方法不对吗？$"

Route102_Text_CalvinRematchPostBattle:
	.string "{CHN}如果你要变得更强，\n"
	.string "我也会变得更强。$"

Route102_Text_AllenIntro:
	.string "{CHN}你刚成为训练家吗？\n"
	.string "我们都是新手！$"

Route102_Text_AllenDefeated:
	.string "{CHN}我叫住你是因为我以为\n"
	.string "我能赢你……$"

Route102_Text_AllenPostBattle:
	.string "{CHN}我一次都没赢过……\n"
	.string "真希望我能快点赢……$"

Route102_Text_RickIntro:
	.string "{CHN}哈哈！我们对上眼了！\n"
	.string "我要用我的虫属性宝可梦挑战你！$"

Route102_Text_RickDefeated:
	.string "{CHN}哎哟！完蛋了！$"

Route102_Text_RickPostBattle:
	.string "{CHN}如果和训练家对上眼，\n"
	.string "就必须挑战！这是规矩！$"

Route102_Text_TianaIntro:
	.string "{CHN}我要一直赢下去，\n"
	.string "成为最棒的训练家。\p"
	.string "帮我更进一步吧！$"

Route102_Text_TianaDefeated:
	.string "{CHN}结果倒是让你更进一步了……$"

Route102_Text_TianaPostBattle:
	.string "{CHN}为了继续赢下去，我发现\n"
	.string "我得捕捉更多的宝可梦。$"

Route103_Text_DaisyIntro:
	.string "{CHN}你感受到我们那\n"
	.string "安抚灵魂的香气了吗？$"

Route103_Text_DaisyDefeated:
	.string "{CHN}你没有被我们的香气迷惑……$"

Route103_Text_DaisyPostBattle:
	.string "{CHN}芳香疗法是一种用香气\n"
	.string "进行心理疗愈的方法。$"

Route103_Text_AmyIntro:
	.string "{CHN}AMY：我是AMY。\n"
	.string "这是我妹妹LIV。\l"
	.string "我们一起对战！$"

Route103_Text_AmyDefeated:
	.string "{CHN}AMY：哎呀，我们输了。$"

Route103_Text_AmyPostBattle:
	.string "{CHN}AMY：和两个训练家\n"
	.string "对战的时候，需要考虑\l"
	.string "各种各样的事情。$"

Route103_Text_AmyNotEnoughPokemon:
	.string "{CHN}AMY：哎呀，你只带着\n"
	.string "一只宝可梦。\l"
	.string "这样可不能和我们对战。$"

Route103_Text_LivIntro:
	.string "{CHN}LIV：我们作为一个\n"
	.string "团队一起对战。$"

Route103_Text_LivDefeated:
	.string "{CHN}LIV：哦，我们输了，姐姐……$"

Route103_Text_LivPostBattle:
	.string "{CHN}LIV：我们配合得天衣无缝，\n"
	.string "我和我姐姐……\p"
	.string "但我们还是输了……$"

Route103_Text_AmyLivRegister:
	.string "{CHN}LIV：真的，我们要强得多……\n"
	.string "是真的！下次让你见识见识！$"

Route103_Text_LivNotEnoughPokemon:
	.string "{CHN}LIV：如果你想和我们对战，\n"
	.string "必须带两只宝可梦！\l"
	.string "不带的话可不公平！$"

Route103_Text_AmyRematchIntro:
	.string "{CHN}AMY：我是AMY。\n"
	.string "这是我妹妹LIV。\l"
	.string "我们一起对战！$"

Route103_Text_AmyRematchDefeated:
	.string "{CHN}AMY：啊，呜！\n"
	.string "我们又赢不了……$"

Route103_Text_AmyRematchPostBattle:
	.string "{CHN}AMY：和两个训练家\n"
	.string "对战的时候，需要考虑\l"
	.string "各种各样的事情。$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "{CHN}AMY：哎呀，你只带着\n"
	.string "一只宝可梦。\l"
	.string "这样可不能和我们对战。$"

Route103_Text_LivRematchIntro:
	.string "{CHN}LIV：我们作为一个\n"
	.string "团队一起对战。$"

Route103_Text_LivRematchDefeated:
	.string "{CHN}LIV：啊啊，我们又输了……\n"
	.string "姐姐……$"

Route103_Text_LivRematchPostBattle:
	.string "{CHN}LIV：我们配合得天衣无缝，\n"
	.string "我和我姐姐……\p"
	.string "但为什么我们又输了呢？$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "{CHN}LIV：如果你想和我们对战，\n"
	.string "必须带两只宝可梦！\l"
	.string "不带的话可不公平！$"

Route103_Text_AndrewIntro:
	.string "{CHN}啊！我的鱼线全缠在一起了！\n"
	.string "我越来越烦躁了！\l"
	.string "够了！跟我对战！$"

Route103_Text_AndrewDefeated:
	.string "{CHN}啊！输了！\n"
	.string "我更烦了！$"

Route103_Text_AndrewPostBattle:
	.string "{CHN}啊，我还在冒火……\n"
	.string "吼吼吼……$"

Route103_Text_MiguelIntro:
	.string "{CHN}我的宝可梦可爱极了！\n"
	.string "别害羞，我让你看看！$"

Route103_Text_MiguelDefeated:
	.string "{CHN}哦，天哪！\n"
	.string "我亲爱的宝可梦！$"

Route103_Text_MiguelPostBattle:
	.string "{CHN}我那可爱的宝可梦\n"
	.string "即使昏倒了也很迷人！$"

Route103_Text_MiguelRegister:
	.string "{CHN}我会让你再来看看\n"
	.string "我那可爱的宝可梦的！$"

Route103_Text_MiguelRematchIntro:
	.string "{CHN}嗨，你！我那可爱极了的\n"
	.string "宝可梦变得更迷人了！$"

Route103_Text_MiguelRematchDefeated:
	.string "{CHN}哦！\n"
	.string "我亲爱的宝可梦！$"

Route103_Text_MiguelRematchPostBattle:
	.string "{CHN}和它相处的时间越久，\n"
	.string "我的宝可梦就越可爱。$"

Route103_Text_PeteIntro:
	.string "{CHN}这种距离……\n"
	.string "你游过去就行了！$"

Route103_Text_PeteDefeated:
	.string "{CHN}哦，你游得真好！$"

Route103_Text_PetePostBattle:
	.string "{CHN}哦，我明白你的想法\n"
	.string "了。\p"
	.string "如果我有一只那么可靠的宝可梦，\n"
	.string "我也想冲浪！$"

Route103_Text_IsabelleIntro:
	.string "{CHN}看路啊！\n"
	.string "我们要撞上了！$"

Route103_Text_IsabelleDefeated:
	.string "{CHN}呻吟……$"

Route103_Text_IsabellePostBattle:
	.string "{CHN}我不太会游泳，所以在练习……\n"
	.string "抱歉差点撞到你。$"

Route103_Text_RhettIntro:
	.string "{CHN}哇！\n"
	.string "你怎么钻进这么小的空间的？$"

Route103_Text_RhettDefeated:
	.string "{CHN}哇！\n"
	.string "这孩子真行！$"

Route103_Text_RhettPostBattle:
	.string "{CHN}你喜欢这样\n"
	.string "狭窄的地方吗？$"

Route103_Text_MarcosIntro:
	.string "{CHN}是我吉他的呐喊把你引来的吗？$"

Route103_Text_MarcosDefeated:
	.string "{CHN}我的独奏被毁了……$"

Route103_Text_MarcosPostBattle:
	.string "{CHN}我在人少的地方弹吉他，\n"
	.string "但聚集了很多歌迷。\p"
	.string "嘿，也许我该转职业了。$"

Route104_Text_GinaIntro:
	.string "{CHN}GINA：好，让我们用\n"
	.string "宝可梦对战吧！$"

Route104_Text_GinaDefeat:
	.string "{CHN}GINA：输了真让人难过！$"

Route104_Text_GinaPostBattle:
	.string "{CHN}GINA：你好强！\n"
	.string "我们还要多多训练！$"

Route104_Text_GinaNotEnoughMons:
	.string "{CHN}GINA：哦？只有一只宝可梦？\n"
	.string "那我们不和你对战。\p"
	.string "如果只有一只宝可梦，\n"
	.string "它会孤单的。那可不好。$"

Route104_Text_MiaIntro:
	.string "{CHN}MIA：我们是双胞胎，所以一起\n"
	.string "用宝可梦对战。$"

Route104_Text_MiaDefeat:
	.string "{CHN}MIA：我们一起对战，但\n"
	.string "都输了……$"

Route104_Text_MiaPostBattle:
	.string "{CHN}MIA：我们会更多地训练宝可梦，\n"
	.string "变得像你一样强。$"

Route104_Text_MiaNotEnoughMons:
	.string "{CHN}MIA：你想和我们对战？\p"
	.string "如果不带两只宝可梦，\n"
	.string "那可不行。\l"
	.string "我们对你来说太强了！$"

Route104_Text_IvanIntro:
	.string "{CHN}为什么要保密？\n"
	.string "我是水属性宝可梦专家！\p"
	.string "嗯？\n"
	.string "你不认识我？$"

Route104_Text_IvanDefeat:
	.string "{CHN}我觉得自己还不赖，\n"
	.string "但看来不是啊……唉……$"

Route104_Text_IvanPostBattle:
	.string "{CHN}我太沉迷钓鱼了。\n"
	.string "忘了还要培养宝可梦……$"

Route104_Text_BillyIntro:
	.string "{CHN}在沙滩上留下脚印\n"
	.string "太好玩了！$"

Route104_Text_BillyDefeat:
	.string "{CHN}哇！我的运动鞋进了沙子！\n"
	.string "全都是沙！$"

Route104_Text_BillyPostBattle:
	.string "{CHN}我想在每片沙滩\n"
	.string "都留下脚印，但它们\l"
	.string "很快就消失了……$"

Route104_Text_HaleyIntro:
	.string "{CHN}我应该……\n"
	.string "还是不应该？\p"
	.string "好吧，我决定了，我来对战！$"

Route104_Text_HaleyDefeat:
	.string "{CHN}我不该对战的……$"

Route104_Text_HaleyPostBattle:
	.string "{CHN}当你面临选择，\n"
	.string "如果让别人替你决定，\l"
	.string "无论结果如何，\l"
	.string "你都会后悔。$"

Route104_Text_HaleyRegister1:
	.string "{CHN}你很强，我该不该把你\n"
	.string "登记到我的宝可梦导航器里？\l"
	.string "也许不该……\p"
	.string "好吧，我决定了，我登记你！$"

Route104_Text_HaleyRegister2:
	.string "{CHN}你很强，我该不该把你\n"
	.string "登记到我的宝可梦导航器里？\l"
	.string "也许不该……\p"
	.string "好吧，我决定了，我登记你！$"

Route104_Text_HaleyRematchIntro:
	.string "{CHN}来吧，跟我对战吧！$"

Route104_Text_HaleyRematchDefeat:
	.string "{CHN}哦……\n"
	.string "我还以为能赢……$"

Route104_Text_HaleyPostRematch:
	.string "{CHN}对战是我自己决定的，\n"
	.string "所以我能从容地接受失败。\p"
	.string "但我对输掉还是很不甘心！$"

Route104_Text_WinstonIntro:
	.string "{CHN}哦，当然，我接受你的挑战。\n"
	.string "我很有钱。$"

Route104_Text_WinstonDefeat:
	.string "{CHN}为什么我赢不了？$"

Route104_Text_WinstonPostBattle:
	.string "{CHN}有些东西是钱买不到的。\n"
	.string "那就是宝可梦……$"

Route104_Text_WinstonRegister1:
	.string "{CHN}嗯？\n"
	.string "啊，你拿到了宝可梦导航器。\p"
	.string "我很乐意登记你。\n"
	.string "毕竟，我有的是钱。$"

Route104_Text_WinstonRegister2:
	.string "{CHN}嗯？\n"
	.string "啊，你拿到了宝可梦导航器。\p"
	.string "我很乐意登记你。\n"
	.string "毕竟，我有的是钱。$"

Route104_Text_WinstonRematchIntro:
	.string "{CHN}输给你之后，我学到了\n"
	.string "很多关于宝可梦的事。$"

Route104_Text_WinstonRematchDefeat:
	.string "{CHN}我又输了？\n"
	.string "为什么我赢不了？$"

Route104_Text_WinstonPostRematch:
	.string "{CHN}我极其富有，但似乎\n"
	.string "在宝可梦上赢不了……\p"
	.string "宝可梦的世界真深奥啊……$"

Route104_Text_CindyIntro:
	.string "{CHN}我们一定是命中注定要相遇。\n"
	.string "可以请你和我对战吗？$"

Route104_Text_CindyDefeat:
	.string "{CHN}哦，天哪！$"

Route104_Text_CindyPostBattle:
	.string "{CHN}“你好”是“再见”的开始。\n"
	.string "希望我们还能再见。$"

Route104_Text_CindyRegister1:
	.string "{CHN}你好，我们又见面了。\p"
	.string "我们似乎互相吸引。让我们\n"
	.string "互相登记到宝可梦导航器里吧。$"

Route104_Text_CindyRegister2:
	.string "{CHN}我们应该纪念一下\n"
	.string "我们互相吸引的缘分。\p"
	.string "让我们互相登记到\n"
	.string "宝可梦导航器里吧。$"

Route104_Text_CindyRematchIntro:
	.string "{CHN}你好，我们又见面了。\n"
	.string "可以请你和我对战吗？$"

Route104_Text_CindyRematchDefeat:
	.string "{CHN}哦，天哪……\n"
	.string "我已经尽力了……$"

Route104_Text_CindyPostRematch:
	.string "{CHN}“你好”是“再见”的开始。\n"
	.string "希望我们还能再见。$"

Route104_Text_DarianIntro:
	.string "{CHN}我钓到了一只很强的宝可梦！\p"
	.string "它有一种神奇的特质！\n"
	.string "它看起来确实很强，没错！$"

Route104_Text_DarianDefeat:
	.string "{CHN}什么……$"

Route104_Text_DarianPostBattle:
	.string "{CHN}嘿，鲤鱼王，你可真\n"
	.string "对不起你的名字啊，是吧？$"

Route105_Text_FosterIntro:
	.string "{CHN}这附近应该有\n"
	.string "一块神秘的岩石。\l"
	.string "你知道什么吗？$"

Route105_Text_FosterDefeated:
	.string "{CHN}我光顾着想那块石头，\n"
	.string "宝可梦却还是那么弱……$"

Route105_Text_FosterPostBattle:
	.string "{CHN}我可以盯着一块好看的石头\n"
	.string "看上好几个小时都不觉得无聊。$"

Route105_Text_LuisIntro:
	.string "{CHN}呼！看到你时我还以为\n"
	.string "有小孩溺水了。\p"
	.string "你看起来没事，那要不要\n"
	.string "来场对战？$"

Route105_Text_LuisDefeated:
	.string "{CHN}咕噜……咕噜……$"

Route105_Text_LuisPostBattle:
	.string "{CHN}如果溺水了，求救信号是\n"
	.string "朝海滩挥动一只手臂。$"

Route105_Text_DominikIntro:
	.string "{CHN}在蔚蓝的深海中游泳……\n"
	.string "感觉棒极了！$"

Route105_Text_DominikDefeated:
	.string "{CHN}我输了……\n"
	.string "现在心情变蓝了……$"

Route105_Text_DominikPostBattle:
	.string "{CHN}为什么海是蓝色的？\p"
	.string "我在凯那市的博物馆\n"
	.string "学过，但忘了。$"

Route105_Text_BeverlyIntro:
	.string "{CHN}在水里身体感觉更轻盈。\n"
	.string "好像变瘦了！$"

Route105_Text_BeverlyDefeated:
	.string "{CHN}我浮起来了……$"

Route105_Text_PostBattle:
	.string "{CHN}在水里你的体重会减少到\n"
	.string "十分之一。\p"
	.string "那我的体重就是……\n"
	.string "哎呀！我才不告诉你我的体重！$"

Route105_Text_ImaniIntro:
	.string "{CHN}蓝蓝的天空……\n"
	.string "辽阔的大海……\l"
	.string "好宁静啊……$"

Route105_Text_ImaniDefeated:
	.string "{CHN}我在偷懒的时候输了！$"

Route105_Text_ImaniPostBattle:
	.string "{CHN}我想让人说我让人感到\n"
	.string "放松。咯咯。$"

Route105_Text_AndresIntro:
	.string "{CHN}我深信大海对我们\n"
	.string "隐瞒着秘密。$"

Route105_Text_AndresDefeated:
	.string "{CHN}是的……\n"
	.string "我不擅长对战……$"

Route105_Text_AndresPostBattle:
	.string "{CHN}我确信世界上的海洋中\n"
	.string "有许多等待被发现的秘密。\p"
	.string "我打算把它们全部找到！$"

Route105_Text_AndresRegister:
	.string "{CHN}咦？我这么弱，你还愿意\n"
	.string "把我登记到你的宝可梦导航器里？$"

Route105_Text_AndresRematchIntro:
	.string "{CHN}我说过我很弱了……\n"
	.string "你确定要这么做吗？$"

Route105_Text_AndresRematchDefeated:
	.string "{CHN}是的……\n"
	.string "我就知道赢不了。$"

Route105_Text_AndresRematchPostBattle:
	.string "{CHN}我也许对战很弱，但我的\n"
	.string "探索精神不会输给任何人。\p"
	.string "我要游遍世界各地的\n"
	.string "海洋！$"

Route105_Text_JosueIntro:
	.string "{CHN}我游泳游累了。\n"
	.string "我还不太习惯。\p"
	.string "我需要一场对战来换换心情！$"

Route105_Text_JosueDefeated:
	.string "{CHN}我输了是因为在海里对战。$"

Route105_Text_JosuePostBattle:
	.string "{CHN}是啊，对我来说，天空比\n"
	.string "大海更合适。$"

Route106_Text_ElliotIntro:
	.string "{CHN}你更喜欢哪个，在海里\n"
	.string "钓鱼还是在河里？$"

Route106_Text_ElliotDefeated:
	.string "{CHN}就像深海钓鱼一样，\n"
	.string "我输得很惨！$"

Route106_Text_ElliotPostBattle:
	.string "{CHN}钓鱼是最棒的，\n"
	.string "不管在海里还是河里。\l"
	.string "你同意吧？$"

Route106_Text_ElliotRegister:
	.string "{CHN}钓鱼很棒，对战也一样。\n"
	.string "如果不介意，我们能再见面吗？$"

Route106_Text_ElliotRematchIntro:
	.string "{CHN}我钓鱼钓到了很多宝可梦。\n"
	.string "我给你看一场精彩的对战！$"

Route106_Text_ElliotRematchDefeated:
	.string "{CHN}我又输得很惨！$"

Route106_Text_ElliotRematchPostBattle:
	.string "{CHN}无论输赢，宝可梦都是最棒的！\n"
	.string "你同意吧？$"

Route106_Text_NedIntro:
	.string "{CHN}如果需要去洗手间，\n"
	.string "人们该怎么办？\p"
	.string "如果我去洗手间的时候\n"
	.string "鱼竿钓到大鱼怎么办？我不能去……$"

Route106_Text_NedDefeated:
	.string "{CHN}我输了是因为我憋着\n"
	.string "不去洗手间……$"

Route106_Text_NedPostBattle:
	.string "{CHN}哦，不！我有种预感\n"
	.string "会钓到大鱼！$"

Route106_Text_DouglasIntro:
	.string "{CHN}哈哈哈！我跑步不行，但\n"
	.string "在水里你追不到我！$"

Route106_Text_DouglasDefeated:
	.string "{CHN}我认输！$"

Route106_Text_DouglasPostBattle:
	.string "{CHN}游泳比赛我不会输……$"

Route106_Text_KylaIntro:
	.string "{CHN}大海就是我的后院。我不会\n"
	.string "因为你是小孩就手下留情！$"

Route106_Text_KylaDefeated:
	.string "{CHN}你是不是对我\n"
	.string "手下留情了？$"

Route106_Text_KylaPostBattle:
	.string "{CHN}随着波浪漂流……\n"
	.string "我喜欢这样！你要不要试试？$"

Route107_Text_DarrinIntro:
	.string "{CHN}哈欠……\p"
	.string "我一定是随波漂流的时候\n"
	.string "睡着了。$"

Route107_Text_DarrinDefeated:
	.string "{CHN}啊哈哈，我输了……\n"
	.string "我想我要小睡一下……$"

Route107_Text_DarrinPostBattle:
	.string "{CHN}在海浪中漂流摇晃——\n"
	.string "就像睡在\l"
	.string "柔软舒适的床上。$"

Route107_Text_TonyIntro:
	.string "{CHN}大海就像我的后院。\n"
	.string "来对战吧！$"

Route107_Text_TonyDefeated:
	.string "{CHN}我在主场输了……\n"
	.string "太震惊了！$"

Route107_Text_TonyPostBattle:
	.string "{CHN}我怀揣着梦想\n"
	.string "游过大海……\p"
	.string "这是一首歌！\n"
	.string "总之，我要继续游泳了。$"

Route107_Text_TonyRegister:
	.string "{CHN}你让我震惊到骨子里！\n"
	.string "好吧，为了不让你忘了我……$"

Route107_Text_TonyRematchIntro:
	.string "{CHN}在广阔的海洋中游泳，\n"
	.string "我的宝可梦变强了！$"

Route107_Text_TonyRematchDefeated:
	.string "{CHN}太震惊了！\p"
	.string "我的宝可梦变强了，但\n"
	.string "我作为训练家还是那么弱！$"

Route107_Text_TonyRematchPostBattle:
	.string "{CHN}你在对战中学到的东西\n"
	.string "会让你成为更强的训练家。\l"
	.string "海浪教会了我这一点。$"

Route107_Text_DeniseIntro:
	.string "{CHN}你知道一个叫\n"
	.string "武斗镇的小镇吗？$"

Route107_Text_DeniseDefeated:
	.string "{CHN}我讨厌这样！$"

Route107_Text_DenisePostBattle:
	.string "{CHN}武斗镇大厅里流行着\n"
	.string "一句奇怪的话。$"

Route107_Text_BethIntro:
	.string "{CHN}你想和我对战吗？\n"
	.string "好啊，我奉陪！$"

Route107_Text_BethDefeated:
	.string "{CHN}我比不上你。$"

Route107_Text_BethPostBattle:
	.string "{CHN}我觉得你会越来越强。\n"
	.string "我也要加油！$"

Route107_Text_LisaIntro:
	.string "{CHN}LISA：我们以姐弟\n"
	.string "之名挑战你！$"

Route107_Text_LisaDefeated:
	.string "{CHN}LISA：太厉害了。\n"
	.string "你的实力非同一般。$"

Route107_Text_LisaPostBattle:
	.string "{CHN}LISA：你有没有朋友\n"
	.string "愿意和你一起去海滩？$"

Route107_Text_LisaNotEnoughPokemon:
	.string "{CHN}LISA：如果想和我们对战，\n"
	.string "多带些宝可梦来。$"

Route107_Text_RayIntro:
	.string "{CHN}RAY：我们总是用宝可梦对战，\n"
	.string "我和我姐姐。\p"
	.string "我总是输，但我们能在2对2中\n"
	.string "打败你！$"

Route107_Text_RayDefeated:
	.string "{CHN}RAY：哇哦，你的等级\n"
	.string "比我们高！$"

Route107_Text_RayPostBattle:
	.string "{CHN}RAY：我姐姐把宝可梦给了我。\n"
	.string "我培养它，现在它是我的重要\l"
	.string "伙伴！$"

Route107_Text_RayNotEnoughPokemon:
	.string "{CHN}RAY：如果你想和我们对战，\n"
	.string "去多带几只宝可梦来！$"

Route107_Text_CamronIntro:
	.string "{CHN}我正在进行铁人三项，\n"
	.string "但我一点都不累！$"

Route107_Text_CamronDefeated:
	.string "{CHN}这让我精疲力竭……$"

Route107_Text_CamronPostBattle:
	.string "{CHN}之后我还有游泳和跑步\n"
	.string "要做。\p"
	.string "我没事吧？$"

Route108_Text_JeromeIntro:
	.string "{CHN}我的梦想是游遍世界七大洋！$"

Route108_Text_JeromeDefeated:
	.string "{CHN}这样下去我可游不了\n"
	.string "七大洋……$"

Route108_Text_JeromePostBattle:
	.string "{CHN}和海洋宝可梦玩耍是\n"
	.string "游泳的乐趣之一！$"

Route108_Text_MatthewIntro:
	.string "{CHN}嘿，那边！你也要去\n"
	.string "废弃船吗？$"

Route108_Text_MatthewDefeated:
	.string "{CHN}我在下沉！\n"
	.string "咕噜……咕噜……$"

Route108_Text_MatthewPostBattle:
	.string "{CHN}有些人甚至进入了那艘\n"
	.string "废弃船。$"

Route108_Text_TaraIntro:
	.string "{CHN}我那爱说谎的男朋友说我\n"
	.string "穿比基尼很好看……$"

Route108_Text_TaraDefeated:
	.string "{CHN}哦，呜！$"

Route108_Text_TaraPostBattle:
	.string "{CHN}即使是谎言，我也喜欢被夸\n"
	.string "好看……\l"
	.string "我们女生就是这么复杂……$"

Route108_Text_MissyIntro:
	.string "{CHN}我爱大海！\n"
	.string "游泳时我忘掉一切烦恼！$"

Route108_Text_MissyDefeated:
	.string "{CHN}输掉对战让我\n"
	.string "压力山大！$"

Route108_Text_MissyPostBattle:
	.string "{CHN}游泳可以消除压力！\n"
	.string "很健康！$"

Route108_Text_CoryIntro:
	.string "{CHN}我喜欢水属性宝可梦。\n"
	.string "我也喜欢其他宝可梦！$"

Route108_Text_CoryDefeated:
	.string "{CHN}哇！我输了！\n"
	.string "哇！哇！$"

Route108_Text_CoryPostBattle:
	.string "{CHN}大喊对我有好处！\n"
	.string "让我精神振奋！$"

Route108_Text_CoryRegister:
	.string "{CHN}我也喜欢强大的训练家！\n"
	.string "把我登记到你的宝可梦导航器里！$"

Route108_Text_CoryRematchIntro:
	.string "{CHN}无论输赢，我都爱在海里对战！$"

Route108_Text_CoryRematchDefeated:
	.string "{CHN}哇！我又输了！\n"
	.string "哇！哇！$"

Route108_Text_CoryRematchPostBattle:
	.string "{CHN}如果你面临挑战，\n"
	.string "试着对着大海大喊！$"

Route108_Text_CarolinaIntro:
	.string "{CHN}我为我的宝可梦感到骄傲。\n"
	.string "我们给你看一场速战！$"

Route108_Text_CarolinaDefeated:
	.string "{CHN}这一点都不可爱。$"

Route108_Text_CarolinaPostBattle:
	.string "{CHN}像这样在海里，我倒不介意\n"
	.string "穿一件粉色荷叶边泳衣……$"

Route109_Text_DavidIntro:
	.string "{CHN}嘿呀！看看我的腹肌！\n"
	.string "这就是所谓的“线条”！$"

Route109_Text_DavidDefeated:
	.string "{CHN}哎呀！\n"
	.string "搞砸了！$"

Route109_Text_DavidPostBattle:
	.string "{CHN}嘿呀！\p"
	.string "我的雕塑般腹肌和\n"
	.string "宝可梦对战没关系！$"

Route109_Text_AliceIntro:
	.string "{CHN}你做好防晒\n"
	.string "了吗？$"

Route109_Text_AliceDefeated:
	.string "{CHN}痛痛痛！$"

Route109_Text_AlicePostBattle:
	.string "{CHN}脸颊最容易晒伤！$"

Route109_Text_HueyIntro:
	.string "{CHN}我在世界各地的港口停泊过，\n"
	.string "但凯那市是最好的。$"

Route109_Text_HueyDefeated:
	.string "{CHN}你是最棒的！$"

Route109_Text_HueyPostBattle:
	.string "{CHN}最好的港口里有最强的\n"
	.string "训练家……$"

Route109_Text_EdmondIntro:
	.string "{CHN}嗝……\n"
	.string "对战？和我？$"

Route109_Text_EdmondDefeated:
	.string "{CHN}嗝……哦哦哦哦哦……\n"
	.string "嗝嗝嗝嗝……$"

Route109_Text_EdmondPostBattle:
	.string "{CHN}我平时比这强多了！\n"
	.string "只是我晕船得厉害！\p"
	.string "我是个水手，但……$"

Route109_Text_RickyIntro:
	.string "{CHN}我好渴……我想去海滨小屋\n"
	.string "喝瓶汽水……$"

Route109_Text_RickyDefeated:
	.string "{CHN}呻吟……$"

Route109_Text_RickyPostBattle:
	.string "{CHN}我饿坏了……我的游泳圈\n"
	.string "看起来像个巨大的甜甜圈……$"

Route109_Text_RickyRegister:
	.string "{CHN}等我不渴的时候，\n"
	.string "你能再和我对战吗？$"

Route109_Text_RickyRematchIntro:
	.string "{CHN}我饿了，但我还有\n"
	.string "足够的力气对战！$"

Route109_Text_RickyRematchDefeated:
	.string "{CHN}我输了……\n"
	.string "因为我饿了……$"

Route109_Text_RickyRematchPostBattle:
	.string "{CHN}在海滩上吃东西，\n"
	.string "什么都觉得更好吃。$"

Route109_Text_LolaIntro:
	.string "{CHN}海滩遮阳伞看起来不像\n"
	.string "一朵巨大的花吗？$"

Route109_Text_LolaDefeated:
	.string "{CHN}妈妈！$"

Route109_Text_LolaPostBattle:
	.string "{CHN}从天上看海滩，\n"
	.string "就像一个大花园！$"

Route109_Text_LolaRegister:
	.string "{CHN}我？\n"
	.string "我每天都在这里！$"

Route109_Text_LolaRematchIntro:
	.string "{CHN}我不会再输给你了！\n"
	.string "所以我带了游泳圈！$"

Route109_Text_LolaRematchDefeated:
	.string "{CHN}妈妈！$"

Route109_Text_LolaRematchPostBattle:
	.string "{CHN}有了游泳圈，我和我的\n"
	.string "宝可梦可爱度大增！$"

Route109_Text_AustinaIntro:
	.string "{CHN}没有游泳圈我就不会游泳，\n"
	.string "但宝可梦对战我不会输！$"

Route109_Text_AustinaDefeated:
	.string "{CHN}我输了是因为\n"
	.string "我用了游泳圈吗？$"

Route109_Text_AustinaPostBattle:
	.string "{CHN}我的游泳圈是时尚单品。\n"
	.string "不能没有它。$"

Route109_Text_GwenIntro:
	.string "{CHN}嗨，大训练家。\n"
	.string "你愿意和我对战吗？$"

Route109_Text_GwenDefeated:
	.string "{CHN}哦，你好强。$"

Route109_Text_GwenPostBattle:
	.string "{CHN}你怎么变得这么强？$"

Route109_Text_CarterIntro:
	.string "{CHN}哇哈哈！这家伙要钓\n"
	.string "大鱼了！$"

Route109_Text_CarterDefeated:
	.string "{CHN}这家伙输了一条……$"

Route109_Text_CarterPostBattle:
	.string "{CHN}这家伙觉得你是大鱼。\n"
	.string "不，你是未来的大鱼！$"

Route109_Text_PaulIntro:
	.string "{CHN}PAUL：真是扫兴。\p"
	.string "希望你别打扰我们\n"
	.string "珍贵的共处时光。$"

Route109_Text_PaulDefeated:
	.string "{CHN}PAUL：好吧，我认输。$"

Route109_Text_PaulPostBattle:
	.string "{CHN}PAUL：好吧，别告诉别人\n"
	.string "我们在这里。\l"
	.string "这是我们两人的私密世界！$"

Route109_Text_PaulNotEnoughPokemon:
	.string "{CHN}PAUL：我们深深地相爱着。\n"
	.string "所以我们让宝可梦\l"
	.string "一起对战。$"

Route109_Text_MelIntro:
	.string "{CHN}MEL：我们，嗯，深爱着彼此。\n"
	.string "我们的浪漫点燃了整个丰缘！$"

Route109_Text_MelDefeated:
	.string "{CHN}MEL：我们输了，都是我的错！\n"
	.string "PAUL会讨厌我的！$"

Route109_Text_MelPostBattle:
	.string "{CHN}MEL：嗯，PAUL，你生我的气吗？\n"
	.string "请不要生气。$"

Route109_Text_MelNotEnoughPokemon:
	.string "{CHN}MEL：我们，嗯，真心相爱着。\n"
	.string "所以我们让宝可梦\l"
	.string "一起对战。$"

Route109_Text_ChandlerIntro:
	.string "{CHN}当当！看到了吗？\n"
	.string "我的游泳圈是圆的！$"

Route109_Text_ChandlerDefeated:
	.string "{CHN}哦，哦！\n"
	.string "太可惜了！$"

Route109_Text_ChandlerPostBattle:
	.string "{CHN}我都给你看了我的圆游泳圈\n"
	.string "了……$"

Route109_Text_HaileyIntro:
	.string "{CHN}我不会游泳，所以我在\n"
	.string "假装游泳。$"

Route109_Text_HaileyDefeated:
	.string "{CHN}我就知道！\n"
	.string "我就觉得我们赢不了。$"

Route109_Text_HaileyPostBattle:
	.string "{CHN}等我学会游泳，\n"
	.string "我的宝可梦也会变强。$"

Route109_Text_ElijahIntro:
	.string "{CHN}对于像我这样强壮的家伙，\n"
	.string "这种宝可梦最合适了！$"

Route109_Text_ElijahDefeated:
	.string "{CHN}即使输了我也很酷，对吧？$"

Route109_Text_ElijahPostBattle:
	.string "{CHN}对于像我这样强壮的家伙，\n"
	.string "港口是最合适的场景！\p"
	.string "我想我要去凯那市了。$"

Route110_Text_JacobIntro:
	.string "{CHN}哇！小心点！\n"
	.string "看来你还不太习惯自行车比赛。$"

Route110_Text_JacobDefeated:
	.string "{CHN}哇！\n"
	.string "我的刹车失灵了！$"

Route110_Text_JacobPostBattle:
	.string "{CHN}爆胎和刹车问题可能\n"
	.string "造成严重伤害！\l"
	.string "检查你的自行车有没有问题！$"

Route110_Text_AnthonyIntro:
	.string "{CHN}哟，你！\n"
	.string "你能跟上我的速度吗？$"

Route110_Text_AnthonyDefeated:
	.string "{CHN}人仰马翻！$"

Route110_Text_AnthonyPostBattle:
	.string "{CHN}光靠速度赢不了宝可梦对战。\n"
	.string "我得重新考虑一下……$"

Route110_Text_BenjaminIntro:
	.string "{CHN}自行车骑得快也别慌！$"

Route110_Text_BenjaminDefeated:
	.string "{CHN}我不该在宝可梦\n"
	.string "对战时慌张……$"

Route110_Text_BenjaminPostBattle:
	.string "{CHN}没必要慌张和紧张。\n"
	.string "放轻松。时间多的是。$"

Route110_Text_BenjaminRegister:
	.string "{CHN}我会继续不紧不慢地前行。\n"
	.string "想对战的话就叫我。$"

Route110_Text_BenjaminRematchIntro:
	.string "{CHN}你是不是骑得有点太快了？\n"
	.string "放轻松，来对战吧。$"

Route110_Text_BenjaminRematchDefeated:
	.string "{CHN}我没慌，但还是输了……$"

Route110_Text_BenjaminRematchPostBattle:
	.string "{CHN}没必要慌张和紧张。\n"
	.string "放轻松。时间多的是。$"

Route110_Text_AbigailIntro:
	.string "{CHN}铁人三项极其艰难。\p"
	.string "你必须完成游泳、\n"
	.string "自行车和跑步三个项目。$"

Route110_Text_AbigailDefeated:
	.string "{CHN}宝可梦对战也很难！$"

Route110_Text_AbigailPostBattle:
	.string "{CHN}我累坏了，需要休息。\n"
	.string "适当休息很重要。$"

Route110_Text_AbigailRegister:
	.string "{CHN}你知道吗，我喜欢你！\n"
	.string "让我们在自行车道上再战吧。$"

Route110_Text_AbigailRematchIntro:
	.string "{CHN}边骑车边对战\n"
	.string "不是很酷吗？$"

Route110_Text_AbigailRematchDefeated:
	.string "{CHN}哇……\n"
	.string "你怎么这么强？$"

Route110_Text_AbigailRematchPostBattle:
	.string "{CHN}你在追求记录吗？\p"
	.string "如果我耽误了你，对不起！$"

Route110_Text_JasmineIntro:
	.string "{CHN}我一直不停地骑。\n"
	.string "我的大腿硬得像石头！$"

Route110_Text_JasmineDefeated:
	.string "{CHN}我担心肌肉抽筋……$"

Route110_Text_JasminePostBattle:
	.string "{CHN}哦，你有道馆徽章？\n"
	.string "难怪你这么强！$"

Route110_Text_EdwardIntro:
	.string "{CHN}我预见到了你的意图！\n"
	.string "我不可能输！$"

Route110_Text_EdwardDefeated:
	.string "{CHN}我没能预见到自己的失败！$"

Route110_Text_EdwardPostBattle:
	.string "{CHN}我看到你的未来……\p"
	.string "嗯……\n"
	.string "我看到一道闪光……$"

Route110_Text_JaclynIntro:
	.string "{CHN}啊哈哈哈！\n"
	.string "我要用奇迹让你眼花缭乱！$"

Route110_Text_JaclynDefeated:
	.string "{CHN}我奇迹般地输了！$"

Route110_Text_JaclynPostBattle:
	.string "{CHN}你赢只是因为那是个\n"
	.string "奇迹！是的，奇迹！\l"
	.string "别以为你能一直赢！$"

Route110_Text_EdwinIntro:
	.string "{CHN}能让我看看你的宝可梦吗？\n"
	.string "就看一眼，好吗？$"

Route110_Text_EdwinDefeated:
	.string "{CHN}我想完成\n"
	.string "我的收藏……$"

Route110_Text_EdwinPostBattle:
	.string "{CHN}当我看到不认识的宝可梦，\n"
	.string "作为收藏家的热情就被点燃了！$"

Route110_Text_EdwinRegister:
	.string "{CHN}我也喜欢收集对战寻呼\n"
	.string "的登记……$"

Route110_Text_EdwinRematchIntro:
	.string "{CHN}嗨，你抓到新宝可梦了吗？\p"
	.string "能让我看看你的宝可梦吗？\n"
	.string "就看一眼，好吗？$"

Route110_Text_EdwinRematchDefeated:
	.string "{CHN}你的宝可梦……\n"
	.string "我好羡慕。$"

Route110_Text_EdwinRematchPostBattle:
	.string "{CHN}哦，我好想把所有稀有宝可梦\n"
	.string "都变成我的！$"

Route110_Text_DaleIntro:
	.string "{CHN}嘿！\n"
	.string "别那样偷偷溜到我背后！$"

Route110_Text_DaleDefeated:
	.string "{CHN}我输了！\n"
	.string "可恶！$"

Route110_Text_DalePostBattle:
	.string "{CHN}钓鱼全靠专注。\n"
	.string "你得盯着浮标。$"

Route110_Text_IsabelIntro:
	.string "{CHN}啊哈哈哈！为了展示\n"
	.string "我可爱的宝可梦，我哪儿都去。$"

Route110_Text_IsabelDefeated:
	.string "{CHN}哦，天哪，这可不行。$"

Route110_Text_IsabelPostBattle:
	.string "{CHN}与其对战，也许我该去\n"
	.string "宝可梦俱乐部展示我的宝可梦。$"

Route110_Text_IsabelRegister:
	.string "{CHN}那还不够展示\n"
	.string "我的宝可梦。\p"
	.string "我要让你成为我的忠实观众，\n"
	.string "尽可能多地来！$"

Route110_Text_IsabelRematchIntro:
	.string "{CHN}啊哈哈哈！我很乐意\n"
	.string "随时展示我的宝可梦！$"

Route110_Text_IsabelRematchDefeated:
	.string "{CHN}哦，天哪，这可不行。$"

Route110_Text_IsabelRematchPostBattle:
	.string "{CHN}我觉得我永远都\n"
	.string "无法停止展示我的宝可梦。\p"
	.string "但我也喜欢对战！$"

Route110_Text_TimmyIntro:
	.string "{CHN}我在这一带的草丛里\n"
	.string "发现了一些酷酷的宝可梦！$"

Route110_Text_TimmyDefeated:
	.string "{CHN}光酷可赢不了……$"

Route110_Text_TimmyPostBattle:
	.string "{CHN}用刚抓到的宝可梦\n"
	.string "对战很难。$"

Route110_Text_AlyssaIntro:
	.string "{CHN}我从自行车道上摔下来了……\p"
	.string "我要用对战来\n"
	.string "克服我的尴尬！$"

Route110_Text_AlyssaDefeated:
	.string "{CHN}哎呀！\n"
	.string "结果我输了！$"

Route110_Text_AlyssaPostBattle:
	.string "{CHN}摔倒……输掉……\n"
	.string "这对我来说太丢脸了！$"

Route110_Text_JosephIntro:
	.string "{CHN}好！全速前进！跟不上节奏\n"
	.string "就被甩开！$"

Route110_Text_JosephDefeated:
	.string "{CHN}你倒是跟上节奏了……$"

Route110_Text_JosephPostBattle:
	.string "{CHN}这不会打倒我！\n"
	.string "输让我变成了更好的男人！$"

Route110_Text_KalebIntro:
	.string "{CHN}当可爱的宝可梦互相帮助……\n"
	.string "你见不到更可爱的场景了！$"

Route110_Text_KalebDefeated:
	.string "{CHN}你没有同情心和怜悯心吗？$"

Route110_Text_KalebPostBattle:
	.string "{CHN}好了，好了，你们已经尽力了，\n"
	.string "我的小可爱们。$"

Route111_Text_DrewIntro:
	.string "{CHN}哦，嘿！那副护目镜很适合你。\n"
	.string "但我觉得我戴更好看。\p"
	.string "让我们用对战来决定谁戴\n"
	.string "更好看吧！$"

Route111_Text_DrewDefeat:
	.string "{CHN}因为护目镜我看不清\n"
	.string "两边的情况。$"

Route111_Text_DrewPostBattle:
	.string "{CHN}护目镜让人能在\n"
	.string "沙暴中前行。\l"
	.string "我很高兴！$"

Route111_Text_HeidiIntro:
	.string "{CHN}我在沙漠里野餐。\p"
	.string "总能遇到训练家，\n"
	.string "所以这里也能享受对战！$"

Route111_Text_HeidiDefeat:
	.string "{CHN}哦！你太过分了！$"

Route111_Text_HeidiPostBattle:
	.string "{CHN}在沙暴中对战时，\n"
	.string "小心你的宝可梦的HP。\p"
	.string "如果不注意，\n"
	.string "它可能会昏倒！$"

Route111_Text_BeauIntro:
	.string "{CHN}戴着这副护目镜让我\n"
	.string "觉得自己像超级英雄。\l"
	.string "现在没人能打败我！$"

Route111_Text_BeauDefeat:
	.string "{CHN}光靠精神赢不了……$"

Route111_Text_BeauPostBattle:
	.string "{CHN}总有一天我要成为真正的英雄。\n"
	.string "我要更努力地让\l"
	.string "我和我的宝可梦变强。$"

Route111_Text_BeckyIntro:
	.string "{CHN}我听说沙漠里\n"
	.string "能找到化石。会在哪呢？$"

Route111_Text_BeckyDefeat:
	.string "{CHN}我差一点……$"

Route111_Text_BeckyPostBattle:
	.string "{CHN}如果能在沙漠里找到化石，\n"
	.string "那这里以前一定是海。$"

Route111_Text_DustyIntro:
	.string "{CHN}三十年来我一直在寻找\n"
	.string "古代遗迹！\l"
	.string "有人要挑战我吗？$"

Route111_Text_DustyDefeat:
	.string "{CHN}我寻找遗迹，\n"
	.string "却没寻找强大的宝可梦。$"

Route111_Text_DustyPostBattle:
	.string "{CHN}三十年来我一直在寻找\n"
	.string "古代遗迹！\p"
	.string "不对，等等，是四十年？\n"
	.string "到底是多少来着？$"

Route111_Text_DustyRegister:
	.string "{CHN}我没有在寻找\n"
	.string "强大的宝可梦。\p"
	.string "但不知为何，我很喜欢\n"
	.string "宝可梦导航器。$"

Route111_Text_DustyRematchIntro:
	.string "{CHN}三十年来我一直在寻找\n"
	.string "古代遗迹！\p"
	.string "不对，等等，是四十年？\n"
	.string "总之，有人要挑战我吗？$"

Route111_Text_DustyRematchDefeat:
	.string "{CHN}我没找到遗迹，也没找到\n"
	.string "强大的宝可梦……$"

Route111_Text_DustyPostRematch:
	.string "{CHN}三十年来我一直在寻找\n"
	.string "古代遗迹！\p"
	.string "不对，等等，我寻找了\n"
	.string "四十年？\p"
	.string "嗯……甚至可能是五十年……\n"
	.string "我到底干了多久了？$"

Route111_Text_TravisIntro:
	.string "{CHN}我精力充沛！\n"
	.string "我的宝可梦也精神抖擞！$"

Route111_Text_TravisDefeat:
	.string "{CHN}我的宝可梦没精神了……$"

Route111_Text_TravisPostBattle:
	.string "{CHN}当我看到精力充沛的训练家，\n"
	.string "忍不住多看几眼。$"

Route111_Text_IreneIntro:
	.string "{CHN}我不知道你要去哪，\n"
	.string "但你想对战吗？$"

Route111_Text_IreneDefeat:
	.string "{CHN}哦，你强得讨厌！$"

Route111_Text_IrenePostBattle:
	.string "{CHN}我想去烟囱山，\n"
	.string "但这里的风景\l"
	.string "也很不错。$"

Route111_Text_DaisukeIntro:
	.string "{CHN}为了锻炼自己，我挑战\n"
	.string "所有遇到的人！$"

Route111_Text_DaisukeDefeat:
	.string "{CHN}叔叔！我认输！$"

Route111_Text_DaisukePostBattle:
	.string "{CHN}我只能继续训练，\n"
	.string "直到能打败像你这样\l"
	.string "强大的训练家。$"

Route111_Text_WiltonIntro:
	.string "{CHN}让我看看你把宝可梦\n"
	.string "锻炼得怎么样了。$"

Route111_Text_WiltonDefeat:
	.string "{CHN}我明白了，你把它们锻炼得\n"
	.string "相当不错。$"

Route111_Text_WiltonPostBattle:
	.string "{CHN}宝可梦和训练家通过\n"
	.string "对战学到很多。\p"
	.string "重要的是即使输了也绝不放弃。$"

Route111_Text_WiltonRegister:
	.string "{CHN}从你的训练方式中\n"
	.string "可以学到很多。\p"
	.string "如果方便的话，\n"
	.string "我请求再战一场。$"

Route111_Text_WiltonRematchIntro:
	.string "{CHN}我们在这里训练，\n"
	.string "把水平提升到新的高度。\l"
	.string "留下来和我们一起训练吧！$"

Route111_Text_WiltonRematchDefeat:
	.string "{CHN}哦，你不错！$"

Route111_Text_WiltonPostRematch:
	.string "{CHN}既然你这么强，你应该\n"
	.string "以宝可梦联盟为目标。$"

Route111_Text_BrookeIntro:
	.string "{CHN}哦，你的宝可梦看起来像是\n"
	.string "认真的角色。\l"
	.string "我必须请你出战。$"

Route111_Text_BrookeDefeat:
	.string "{CHN}它们不只是看起来强，\n"
	.string "它们是真的强！$"

Route111_Text_BrookePostBattle:
	.string "{CHN}我以为我在勤奋地培养宝可梦，\n"
	.string "但哦不，还有很多\l"
	.string "要做的事。$"

Route111_Text_BrookeRegister:
	.string "{CHN}我希望能和\n"
	.string "更多像你这样的强者成为朋友！$"

Route111_Text_BrookeRematchIntro:
	.string "{CHN}你可以让宝可梦变强或\n"
	.string "变弱，取决于你教的\l"
	.string "招式。\p"
	.string "你的宝可梦\n"
	.string "会什么招式？$"

Route111_Text_BrookeRematchDefeat:
	.string "{CHN}你教了它们好招式！$"

Route111_Text_BrookePostRematch:
	.string "{CHN}也许我该阻止宝可梦进化，\n"
	.string "直到它们学会\l"
	.string "更好的招式……$"

Route111_Text_CeliaIntro:
	.string "{CHN}我不该来这种\n"
	.string "地方野餐的！$"

Route111_Text_CeliaDefeat:
	.string "{CHN}啊！\n"
	.string "我真不该来！$"

Route111_Text_CeliaPostBattle:
	.string "{CHN}在这样的大风沙中，\n"
	.string "即使戴着护目镜也没法\l"
	.string "铺野餐的位置……$"

Route111_Text_BryanIntro:
	.string "{CHN}你有多强？\n"
	.string "让我们揭开这个秘密！$"

Route111_Text_BryanDefeat:
	.string "{CHN}哦！你的实力！\n"
	.string "被神秘笼罩着！$"

Route111_Text_BryanPostBattle:
	.string "{CHN}这片沙漠在\n"
	.string "流沙中隐藏着谜团！$"

Route111_Text_BrandenIntro:
	.string "{CHN}如果你能输的话，\n"
	.string "我分你一点我的三明治。$"

Route111_Text_BrandenDefeat:
	.string "{CHN}啧！我以为一个三明治\n"
	.string "就够了当贿赂……$"

Route111_Text_BrandenPostBattle:
	.string "{CHN}我的沙丘鼠最爱\n"
	.string "吃我的三明治了。$"

Route111_Text_TyronIntro:
	.string "{CHN}这是我最喜欢的宝可梦！$"

Route111_Text_TyronDefeat:
	.string "{CHN}等等！\n"
	.string "你看清我的宝可梦了吗？$"

Route111_Text_TyronPostBattle:
	.string "{CHN}对战时，我以展示\n"
	.string "我的宝可梦为乐。\p"
	.string "我猜每个人对战时\n"
	.string "都有这种感觉！$"

Route111_Text_CelinaIntro:
	.string "{CHN}教我怎么给我的生活\n"
	.string "增添点刺激吧。$"

Route111_Text_CelinaDefeat:
	.string "{CHN}哦……我的天……\n"
	.string "刺激过头了。$"

Route111_Text_CelinaPostBattle:
	.string "{CHN}我的心还在怦怦跳。\n"
	.string "你真是个出色的训练家。$"

Route111_Text_HaydenIntro:
	.string "{CHN}像我这样饥肠辘辘的时候，\n"
	.string "可没有怜悯的余地！$"

Route111_Text_HaydenDefeat:
	.string "{CHN}呻吟……$"

Route111_Text_HaydenPostBattle:
	.string "{CHN}我的肚子在咕咕叫！\n"
	.string "也许我可以烤些树果……$"

Route111_Text_BiancaIntro:
	.string "{CHN}你从卡那兹市来吗？\n"
	.string "那你应该精力充沛！$"

Route111_Text_BiancaDefeat:
	.string "{CHN}哦啦啦！\n"
	.string "这可真够受的！$"

Route111_Text_BiancaPostBattle:
	.string "{CHN}这条路……\n"
	.string "你还有很长的路要走。$"

Route112_Text_BriceIntro:
	.string "{CHN}哈哈哈哈！\n"
	.string "来场对战怎么样？\l"
	.string "你和我！\l"
	.string "哈哈哈哈！$"

Route112_Text_BriceDefeat:
	.string "{CHN}我输了！\n"
	.string "哈哈哈哈！$"

Route112_Text_BricePostBattle:
	.string "{CHN}哈哈哈哈哈！有东西飞进我鼻子了！\n"
	.string "哈哈哈哈哈——阿嚏！$"

Route112_Text_TrentIntro:
	.string "{CHN}我的腿因为在山里上下跋涉\n"
	.string "而变得结实。\p"
	.string "它们可不会轻易打颤，\n"
	.string "朋友！$"

Route112_Text_TrentDefeat:
	.string "{CHN}哎哟！我的腿抽筋了！$"

Route112_Text_TrentPostBattle:
	.string "{CHN}试试远足，我是说真正地\n"
	.string "在山路上跋涉，\l"
	.string "背着几十斤重的背包。\p"
	.string "那样，我的朋友，\n"
	.string "会让你的身体非常结实。$"

Route112_Text_TrentRegister:
	.string "{CHN}哎哟，我的腿抽筋了。\n"
	.string "你能从我的背包里拿些\l"
	.string "绷带给我吗？\p"
	.string "不，那是我的宝可梦导航器！\n"
	.string "哦，好吧，我登记你。$"

Route112_Text_TrentRematchIntro:
	.string "{CHN}我一直在远足保持健壮。\n"
	.string "我的力量绰绰有余！$"

Route112_Text_TrentRematchDefeat:
	.string "{CHN}我在力量上被压倒了？$"

Route112_Text_TrentRematchPostBattle:
	.string "{CHN}我听说烟囱山顶有一些\n"
	.string "非常厉害的训练家。\p"
	.string "我打算上去挑战\n"
	.string "他们！$"

Route112_Text_LarryIntro:
	.string "{CHN}我很强。\n"
	.string "输了我也不会哭。$"

Route112_Text_LarryDefeat:
	.string "{CHN}哇啊啊！$"

Route112_Text_LarryPostBattle:
	.string "{CHN}我不是因为想妈妈才哭的！\n"
	.string "抽泣……$"

Route112_Text_CarolIntro:
	.string "{CHN}出去野餐的时候，\n"
	.string "就是要唱歌呀！\l"
	.string "来吧，和我一起唱！$"

Route112_Text_CarolDefeat:
	.string "{CHN}哦，你好强！$"

Route112_Text_CarolPostBattle:
	.string "{CHN}不管你唱歌或宝可梦行不行，\n"
	.string "都没关系。\p"
	.string "最开心的人就是赢家！$"

Route112_Text_BryantIntro:
	.string "{CHN}我在焰之小径抓到了\n"
	.string "火热的宝可梦！看看吧！$"

Route112_Text_BryantDefeat:
	.string "{CHN}真是一路颠簸！$"

Route112_Text_BryantPostBattle:
	.string "{CHN}我喜欢你对战的方式。\n"
	.string "有一种独特的风采。$"

Route112_Text_ShaylaIntro:
	.string "{CHN}哦，你真是个可爱的训练家！\n"
	.string "拜托，我需要一场浪漫的对战！\l"
	.string "我还算不赖！$"

Route112_Text_ShaylaDefeat:
	.string "{CHN}哦，你好强啊！\n"
	.string "你让我大吃一惊！$"

Route112_Text_ShaylaPostBattle:
	.string "{CHN}你现在忙吗？\n"
	.string "我在想也许我们可以\l"
	.string "马上再战一场……\l"
	.string "但如果你忙的话也没关系。$"

Route113_Text_JaylenIntro:
	.string "{CHN}你能猜到为什么\n"
	.string "这里这么凉爽吗？$"

Route113_Text_JaylenDefeat:
	.string "{CHN}咻！\n"
	.string "好臭！$"

Route113_Text_JaylenPostBattle:
	.string "{CHN}火山灰遮住了阳光，\n"
	.string "所以不会很热。\p"
	.string "那对我很好——我受不了热！$"

Route113_Text_DillonIntro:
	.string "{CHN}火山的喷发证明\n"
	.string "地球是活的。$"

Route113_Text_DillonDefeat:
	.string "{CHN}你真是强得离谱！$"

Route113_Text_DillonPostBattle:
	.string "{CHN}哎哟！哦哦！我看不见了！\n"
	.string "火山灰进了我的睫毛！\p"
	.string "懂了吗？火山灰和睫毛？\p"
	.string "好吧，那很烂，抱歉……$"

Route113_Text_MadelineIntro:
	.string "{CHN}我用这把阳伞来为\n"
	.string "我亲爱的呆火驼挡住\l"
	.string "这些脏兮兮的火山灰。$"

Route113_Text_MadelineDefeat:
	.string "{CHN}呼，呼……\n"
	.string "我累坏了……$"

Route113_Text_MadelinePostBattle:
	.string "{CHN}你非常擅长这个。\n"
	.string "我得说我印象深刻！$"

Route113_Text_MadelineRegister:
	.string "{CHN}来，躲到我的阳伞下。\n"
	.string "让我把你登记到我的宝可梦导航器里。$"

Route113_Text_MadelineRematchIntro:
	.string "{CHN}哦，你好，好久不见了吧？\n"
	.string "能邀请你对战吗？$"

Route113_Text_MadelineRematchDefeat:
	.string "{CHN}哦，太棒了！$"

Route113_Text_MadelinePostRematch:
	.string "{CHN}你依然非常擅长这个。\n"
	.string "我得说我印象深刻！$"

Route113_Text_LaoIntro:
	.string "{CHN}从火山灰中我跃出！嘿呀！\n"
	.string "我向你挑战！$"

Route113_Text_LaoDefeat:
	.string "{CHN}我荣幸地认输！$"

Route113_Text_LaoPostBattle:
	.string "{CHN}我必须精进隐身之术。\n"
	.string "告辞了。$"

Route113_Text_LaoRegister:
	.string "{CHN}呀呀！见识古老的忍者\n"
	.string "宝可梦导航器登记术！$"

Route113_Text_LaoRematchIntro:
	.string "{CHN}从火山灰中我跃出！嘿呀！\n"
	.string "我向你挑战！$"

Route113_Text_LaoRematchDefeat:
	.string "{CHN}我荣幸地认输！$"

Route113_Text_LaoPostRematch:
	.string "{CHN}我完美的隐身术\n"
	.string "败给了我不成熟的对战技术……\p"
	.string "告辞了。$"

Route113_Text_LungIntro:
	.string "{CHN}谢谢你找到我！\n"
	.string "但我们还得对战！$"

Route113_Text_LungDefeat:
	.string "{CHN}我要对你用忍术……\n"
	.string "“火山灰旋涡 cloak”！\p"
	.string "……什么？\n"
	.string "已经结束了？$"

Route113_Text_LungPostBattle:
	.string "{CHN}你知道躲藏最糟糕的是什么吗？\n"
	.string "如果没人来，会很寂寞。$"

Route113_Text_ToriIntro:
	.string "{CHN}TORI：我们两个都在收集火山灰。\n"
	.string "我们也用宝可梦对战。$"

Route113_Text_ToriDefeat:
	.string "{CHN}TORI：我们输了……好无聊，我要去\n"
	.string "多收集些火山灰。$"

Route113_Text_ToriPostBattle:
	.string "{CHN}TORI：我们有多少火山灰了？\n"
	.string "希望够换一个白色玻璃哨。$"

Route113_Text_ToriNotEnoughMons:
	.string "{CHN}TORI：我们想2对2对战。\n"
	.string "不然的话，我们会输！$"

Route113_Text_TiaIntro:
	.string "{CHN}TIA：我们两个都在收集火山灰。\n"
	.string "我们也用宝可梦对战。$"

Route113_Text_TiaDefeat:
	.string "{CHN}TIA：我们赢不了……好无聊，\n"
	.string "所以我要去多收集些火山灰。$"

Route113_Text_TiaPostBattle:
	.string "{CHN}TIA：我们有很多火山灰！\n"
	.string "我想够换一个白色玻璃哨了！$"

Route113_Text_TiaNotEnoughMons:
	.string "{CHN}TIA：我们想2对2对战。\n"
	.string "不然的话，我们赢不了！$"

Route113_Text_CobyIntro:
	.string "{CHN}哼，有了这些翅膀我可以\n"
	.string "把你弹飞！$"

Route113_Text_CobyDefeat:
	.string "{CHN}啊……什么？$"

Route113_Text_CobyPostBattle:
	.string "{CHN}被打得这么惨的时候，\n"
	.string "我都不知道该说什么……$"

Route113_Text_SophieIntro:
	.string "{CHN}这里的温暖让我昏昏欲睡。\n"
	.string "和我对战吧，好让我保持清醒。$"

Route113_Text_SophieDefeat:
	.string "{CHN}这是一场梦。\n"
	.string "我确信……$"

Route113_Text_SophiePostBattle:
	.string "{CHN}输掉让我火大……\n"
	.string "我要就在这里睡觉！\l"
	.string "呼呼！$"

Route113_Text_LawrenceIntro:
	.string "{CHN}你是不是正在\n"
	.string "收集火山灰？$"

Route113_Text_LawrenceDefeat:
	.string "{CHN}呵呵。\n"
	.string "我们输得很干脆。$"

Route113_Text_LawrencePostBattle:
	.string "{CHN}我也该躲在火山灰下面。$"

Route113_Text_WyattIntro:
	.string "{CHN}你……你想和我对战？\n"
	.string "即使我的宝可梦是刚抓的？$"

Route113_Text_WyattDefeat:
	.string "{CHN}你……你赢了就这么开心？\n"
	.string "即使对手只是我？$"

Route113_Text_WyattPostBattle:
	.string "{CHN}哦，现在你想对输家\n"
	.string "说句话了？\p"
	.string "你可真酷啊。\n"
	.string "哼！$"

Route114_Text_LennyIntro:
	.string "{CHN}哟嘞嘿呼！\p"
	.string "…… ……\p"
	.string "你应该喊\n"
	.string "“哟嘞嘿呼”因为这里\l"
	.string "没有回音！$"

Route114_Text_LennyDefeat:
	.string "{CHN}哟嘞嘿呼！$"

Route114_Text_LennyPostBattle:
	.string "{CHN}我还是个小鬼的时候，\n"
	.string "相信有人模仿我并喊\l"
	.string "回“哟嘞嘿呼”。$"

Route114_Text_LucasIntro:
	.string "{CHN}如果没准备好，\n"
	.string "就不该上山！$"

Route114_Text_LucasDefeat:
	.string "{CHN}大山是无情的……$"

Route114_Text_LucasPostBattle:
	.string "{CHN}冬天的大山会因暴风雪\n"
	.string "和雪崩变得致命。$"

Route114_Text_ShaneIntro:
	.string "{CHN}露营真好玩！可以钓鱼、烤\n"
	.string "棉花糖，还可以讲鬼故事！\p"
	.string "但最棒的是宝可梦\n"
	.string "对战！$"

Route114_Text_ShaneDefeat:
	.string "{CHN}太强了！$"

Route114_Text_ShanePostBattle:
	.string "{CHN}我觉得能和宝可梦一起\n"
	.string "露营真是太好了。$"

Route114_Text_NancyIntro:
	.string "{CHN}饭后我需要运动。\n"
	.string "来对战吧！$"

Route114_Text_NancyDefeat:
	.string "{CHN}哦，不！$"

Route114_Text_NancyPostBattle:
	.string "{CHN}我刚吃了一顿美味的饭菜。\n"
	.string "我困了……$"

Route114_Text_SteveIntro:
	.string "{CHN}呜呼呼呼呼……\n"
	.string "想和我的宝可梦对战吗？$"

Route114_Text_SteveDefeat:
	.string "{CHN}我……我的宝可梦……$"

Route114_Text_StevePostBattle:
	.string "{CHN}一个全是疙瘩和硬块的大身体，\n"
	.string "巨大的角，和凶猛的獠牙……\p"
	.string "呜呼呼呼……\n"
	.string "我真希望有那样的宝可梦……$"

Route114_Text_SteveRegister:
	.string "{CHN}别忘了你对我做了什么！\n"
	.string "我会让你忘不掉的！$"

Route114_Text_SteveRematchIntro:
	.string "{CHN}呜呼呼呼呼……\n"
	.string "来吧，和我的宝可梦对战……$"

Route114_Text_SteveRematchDefeat:
	.string "{CHN}能见到你的宝可梦\n"
	.string "我真幸运……$"

Route114_Text_StevePostRematch:
	.string "{CHN}呜呼呼呼呼……\p"
	.string "看到宝可梦对战，我就\n"
	.string "浑身颤抖……$"

Route114_Text_BernieIntro:
	.string "{CHN}生篝火的时候，\n"
	.string "确保手边有水。$"

Route114_Text_BernieDefeat:
	.string "{CHN}谢谢你浇灭我的火！$"

Route114_Text_BerniePostBattle:
	.string "{CHN}在森林里真的要小心\n"
	.string "任何形式的火。\p"
	.string "千万别低估\n"
	.string "火的力量。$"

Route114_Text_BernieRegister:
	.string "{CHN}你点燃了我的斗志。\n"
	.string "让我们互相登记吧！$"

Route114_Text_BernieRematchIntro:
	.string "{CHN}你学会生篝火时\n"
	.string "手边备水了吗？$"

Route114_Text_BernieRematchDefeat:
	.string "{CHN}我想我在燃起之前\n"
	.string "就被浇灭了。$"

Route114_Text_BerniePostRematch:
	.string "{CHN}在森林里真的要小心\n"
	.string "任何形式的火。\p"
	.string "千万别低估\n"
	.string "火的力量。$"

Route114_Text_ClaudeIntro:
	.string "{CHN}如果是钓鱼，你根本\n"
	.string "不是我的对手。\l"
	.string "所以，放马过来吧！$"

Route114_Text_ClaudeDefeat:
	.string "{CHN}如果是钓鱼，我就赢了……$"

Route114_Text_ClaudePostBattle:
	.string "{CHN}我想去流星瀑布\n"
	.string "碰碰运气钓大鱼。\p"
	.string "那里肯定有什么。\n"
	.string "我就是知道。$"

Route114_Text_NolanIntro:
	.string "{CHN}我喜欢钓鱼。但我也喜欢\n"
	.string "对战！\p"
	.string "谁挑战我，我都奉陪，\n"
	.string "即使我在钓鱼。$"

Route114_Text_NolanDefeat:
	.string "{CHN}我喜欢对战，但这\n"
	.string "不代表我擅长……$"

Route114_Text_NolanPostBattle:
	.string "{CHN}这次我一定行！\p"
	.string "我总是这么想，所以我离不开\n"
	.string "钓鱼和宝可梦。$"

Route114_Text_TyraIntro:
	.string "{CHN}TYRA：好啊。\n"
	.string "我正好有心情。\l"
	.string "我教你一点关于宝可梦的事。$"

Route114_Text_TyraDefeat:
	.string "{CHN}TYRA：多惊人的对战风格！$"

Route114_Text_TyraPostBattle:
	.string "{CHN}TYRA：我正在教我的学妹IVY\n"
	.string "关于宝可梦的事。$"

Route114_Text_TyraNotEnoughMons:
	.string "{CHN}TYRA：咯咯……\n"
	.string "如果你想和我们对战，只有一只\l"
	.string "宝可梦可不够！$"

Route114_Text_IvyIntro:
	.string "{CHN}IVY：谁教你的宝可梦知识？$"

Route114_Text_IvyDefeat:
	.string "{CHN}IVY：多惊人的对战风格！$"

Route114_Text_IvyPostBattle:
	.string "{CHN}IVY：我开始训练宝可梦\n"
	.string "是因为TYRA，我的学长，\l"
	.string "教了我！$"

Route114_Text_IvyNotEnoughMons:
	.string "{CHN}IVY：你只有一只宝可梦吗？\n"
	.string "我想它一定很寂寞。$"

Route114_Text_KaiIntro:
	.string "{CHN}我钓到了一条大鱼！\n"
	.string "超大的，我告诉你！$"

Route114_Text_KaiDefeat:
	.string "{CHN}那是怎么回事？\n"
	.string "我的在尺寸上输了吗？$"

Route114_Text_KaiPostBattle:
	.string "{CHN}好！\n"
	.string "我要去钓一条更大的！$"

Route114_Text_CharlotteIntro:
	.string "{CHN}我！\n"
	.string "我不只是有一张漂亮脸蛋！$"

Route114_Text_CharlotteDefeat:
	.string "{CHN}那一点都不可爱！$"

Route114_Text_CharlottePostBattle:
	.string "{CHN}我不想要只是\n"
	.string "可爱的宝可梦。\p"
	.string "我喜爱有一两个怪癖的\n"
	.string "可爱宝可梦！$"

Route114_Text_AngelinaIntro:
	.string "{CHN}你的宝可梦进化了\n"
	.string "很多吗？$"

Route114_Text_AngelinaDefeat:
	.string "{CHN}哦，我明白了。\n"
	.string "很高兴知道。$"

Route114_Text_AngelinaPostBattle:
	.string "{CHN}有些宝可梦进化时变化很大，\n"
	.string "令人吃惊！$"

Route115_Text_TimothyIntro:
	.string "{CHN}嗯……\n"
	.string "你看起来挺能干的……\l"
	.string "让我陪你一战！$"

Route115_Text_TimothyDefeat:
	.string "{CHN}你比我想象的\n"
	.string "强多了！$"

Route115_Text_TimothyPostBattle:
	.string "{CHN}没有天生的天才。\n"
	.string "一切全靠努力！\l"
	.string "这就是我的信念……$"

Route115_Text_TimothyRegister:
	.string "{CHN}嗯……这么惨的失败\n"
	.string "已经是遥远的记忆了。\p"
	.string "如果可以的话，我希望能\n"
	.string "再有机会对战。$"

Route115_Text_TimothyRematchIntro:
	.string "{CHN}嗯……一如既往，你的敏捷\n"
	.string "不言自明。\l"
	.string "来吧，陪我战一场！$"

Route115_Text_TimothyRematchDefeat:
	.string "{CHN}一如既往地强！$"

Route115_Text_TimothyPostRematch:
	.string "{CHN}一切全靠努力！\p"
	.string "我输了是因为我\n"
	.string "努力得不够！$"

Route115_Text_KoichiIntro:
	.string "{CHN}你！\p"
	.string "我的腕力！\p"
	.string "要求对战！$"

Route115_Text_KoichiDefeat:
	.string "{CHN}哎哟哎哟哎哟！$"

Route115_Text_KoichiPostBattle:
	.string "{CHN}我的腕力战队！\p"
	.string "只要它们追求力量，我就\n"
	.string "会和它们一起变强！$"

Route115_Text_NobIntro:
	.string "{CHN}我最强的技能是用额头\n"
	.string "碎砖头！$"

Route115_Text_NobDefeat:
	.string "{CHN}哇啊啊啊！\n"
	.string "我的头裂了！$"

Route115_Text_NobPostBattle:
	.string "{CHN}我一直在教我的宝可梦空手道。\p"
	.string "看来它们会比我\n"
	.string "强得多。我很期待。$"

Route115_Text_NobRegister:
	.string "{CHN}你让我印象深刻！等我重新\n"
	.string "训练后再来一战！$"

Route115_Text_NobRematchIntro:
	.string "{CHN}你打败我们之后，我们努力训练\n"
	.string "提升了技能。\l"
	.string "来吧，再战一场！$"

Route115_Text_NobRematchDefeat:
	.string "{CHN}哇啊啊！\n"
	.string "我们又输了！$"

Route115_Text_NobPostRematch:
	.string "{CHN}我的宝可梦会变强的！\n"
	.string "我要加倍训练！$"

Route115_Text_CyndyIntro:
	.string "{CHN}这片海滩是我秘密的训练场！\n"
	.string "别来捣乱！$"

Route115_Text_CyndyDefeat:
	.string "{CHN}我训练得不够！$"

Route115_Text_CyndyPostBattle:
	.string "{CHN}沙子能起缓冲作用，减少冲击\n"
	.string "防止受伤。\l"
	.string "这里是训练的绝佳地点。$"

Route115_Text_CyndyRegister:
	.string "{CHN}好吧，你可以来这里。\n"
	.string "作为交换，我想再和你对战。$"

Route115_Text_CyndyRematchIntro:
	.string "{CHN}好，开战吧！$"

Route115_Text_CyndyRematchDefeat:
	.string "{CHN}我能对战，但我的宝可梦……$"

Route115_Text_CyndyPostRematch:
	.string "{CHN}即使输了，我还是能从中\n"
	.string "获得一些乐趣。\l"
	.string "一定是因为我热爱宝可梦。$"

Route115_Text_HectorIntro:
	.string "{CHN}我有一只稀有的宝可梦！\n"
	.string "要我给你看看吗？$"

Route115_Text_HectorDefeat:
	.string "{CHN}你……\n"
	.string "你想要我的宝可梦，对吧？$"

Route115_Text_HectorPostBattle:
	.string "{CHN}我有这只稀有的宝可梦。\n"
	.string "这足以让我满足。$"

Route115_Text_KyraIntro:
	.string "{CHN}我要边跑边对战！\n"
	.string "尽量跟上我！$"

Route115_Text_KyraDefeat:
	.string "{CHN}喘，喘……$"

Route115_Text_KyraPostBattle:
	.string "{CHN}我犯了个错误，\n"
	.string "边跑边对战！\p"
	.string "我该跑一圈冷静一下……$"

Route115_Text_JaidenIntro:
	.string "{CHN}看招！\n"
	.string "超级宝可梦忍者攻击！$"

Route115_Text_JaidenDefeat:
	.string "{CHN}哇啊！\n"
	.string "我们的策略失败了！$"

Route115_Text_JaidenPostBattle:
	.string "{CHN}但我的宝可梦很超级，\n"
	.string "对吧？$"

Route115_Text_HeleneIntro:
	.string "{CHN}我的宝可梦有黑带级别的\n"
	.string "实力！$"

Route115_Text_HeleneDefeat:
	.string "{CHN}这太丢脸了！$"

Route115_Text_HelenePostBattle:
	.string "{CHN}我很少遇到比我更强的人……\p"
	.string "我明白了！\n"
	.string "你是道馆馆主，对吧？$"

Route115_Text_AlixIntro:
	.string "{CHN}我们对上眼了！\n"
	.string "现在跑不掉了！$"

Route115_Text_AlixDefeat:
	.string "{CHN}嘎！\n"
	.string "不错！$"

Route115_Text_AlixPostBattle:
	.string "{CHN}哦，好吧。\n"
	.string "我想我要瞬间回家。$"

Route115_Text_MarleneIntro:
	.string "{CHN}你打扰了我冥想……\n"
	.string "你要受到惩罚。$"

Route115_Text_MarleneDefeat:
	.string "{CHN}你打断了我的集中！$"

Route115_Text_MarlenePostBattle:
	.string "{CHN}我在和我的宝可梦一起冥想。\n"
	.string "但这地方不太安宁……$"

Route116_Text_ClarkIntro:
	.string "{CHN}如果隧道不通，\n"
	.string "那我就翻过山顶。$"

Route116_Text_ClarkDefeat:
	.string "{CHN}喘……喘……\n"
	.string "输了让我累了……$"

Route116_Text_ClarkPostBattle:
	.string "{CHN}没有隧道也没什么大不了。\n"
	.string "对登山客来说，山就是路！$"

Route116_Text_JoeyIntro:
	.string "{CHN}我的宝可梦最棒了！\n"
	.string "看看吧！$"

Route116_Text_JoeyDefeat:
	.string "{CHN}哎哟！擦伤了！\n"
	.string "我得贴个创可贴！$"

Route116_Text_JoeyPostBattle:
	.string "{CHN}创可贴是坚韧的标志！\n"
	.string "我又多了一个！$"

Route116_Text_JoseIntro:
	.string "{CHN}我的虫属性宝可梦很强！\n"
	.string "来对战吧！$"

Route116_Text_JoseDefeat:
	.string "{CHN}我输了！\n"
	.string "我以为我能赢你！$"

Route116_Text_JosePostBattle:
	.string "{CHN}虫属性宝可梦进化快。\n"
	.string "所以它们也很快变强。$"

Route116_Text_JaniceIntro:
	.string "{CHN}让我教教你我的\n"
	.string "可爱宝可梦有多强！$"

Route116_Text_JaniceDefeat:
	.string "{CHN}你比我高出一筹……$"

Route116_Text_JanicePostBattle:
	.string "{CHN}兼具可爱和力量的\n"
	.string "宝可梦，那才是理想。$"

Route116_Text_JerryIntro:
	.string "{CHN}我们在训练家学校学了\n"
	.string "各种东西。\p"
	.string "我想实地试试看！$"

Route116_Text_JerryDefeat:
	.string "{CHN}我在学校偷懒了……\n"
	.string "所以才输了。$"

Route116_Text_JerryPostBattle:
	.string "{CHN}我得回训练家学校\n"
	.string "重修一些课程。\l"
	.string "不的话，杜鹃会发火的。$"

Route116_Text_JerryRegister1:
	.string "{CHN}我在训练家学校学到\n"
	.string "宝可梦导航器可以登记训练家。\p"
	.string "我不太明白那是什么意思，\n"
	.string "所以能让我试试吗？$"

Route116_Text_JerryRegister2:
	.string "{CHN}我在训练家学校学到\n"
	.string "宝可梦导航器可以登记训练家。\p"
	.string "我不太明白那是什么意思，\n"
	.string "所以能让我试试吗？$"

Route116_Text_JerryRematchIntro:
	.string "{CHN}我一直在训练家学校\n"
	.string "认真学习。\l"
	.string "我不会像上次那样输了。$"

Route116_Text_JerryRematchDefeat:
	.string "{CHN}嗯？\n"
	.string "我明明很用功了。$"

Route116_Text_JerryPostRematch:
	.string "{CHN}我得回训练家学校\n"
	.string "重修一些课程。\l"
	.string "不的话，杜鹃会发火的。$"

Route116_Text_KarenIntro:
	.string "{CHN}我在学校学习，回家的路上\n"
	.string "也在学习！$"

Route116_Text_KarenDefeat:
	.string "{CHN}我震惊了——我输了？$"

Route116_Text_KarenPostBattle:
	.string "{CHN}啊啊，这样下去我永远也成不了\n"
	.string "像杜鹃那样优雅的训练家！$"

Route116_Text_KarenRegister1:
	.string "{CHN}哦，哇！那不是宝可梦导航器吗？\n"
	.string "我也有一台！请登记我！$"

Route116_Text_KarenRegister2:
	.string "{CHN}哦，哇！那不是宝可梦导航器吗？\n"
	.string "我也有一台！请登记我！$"

Route116_Text_KarenRematchIntro:
	.string "{CHN}自从见到你后我学了\n"
	.string "很多东西。你必须看看我的成果！$"

Route116_Text_KarenRematchDefeat:
	.string "{CHN}我震惊了。\n"
	.string "我又输了？$"

Route116_Text_KarenPostRematch:
	.string "{CHN}你打败过杜鹃？\n"
	.string "那我就赢不了你。暂时不行。$"

Route116_Text_SarahIntro:
	.string "{CHN}告诉你，我在任何事上从未\n"
	.string "输给过任何人。$"

Route116_Text_SarahDefeat:
	.string "{CHN}哦，天哪。\n"
	.string "这对我来说是全新的体验。$"

Route116_Text_SarahPostBattle:
	.string "{CHN}我的奢华生活让我拥有了一切\n"
	.string "我能想要的。\p"
	.string "然而，在宝可梦方面，\n"
	.string "我的财富毫无意义。$"

Route116_Text_DawsonIntro:
	.string "{CHN}当你看到我宝可梦华丽的毛发，\n"
	.string "它们的美会让你\l"
	.string "无法抵抗！$"

Route116_Text_DawsonDefeat:
	.string "{CHN}哦，宝贝，别这样！$"

Route116_Text_DawsonPostBattle:
	.string "{CHN}哦，不不不！\n"
	.string "你弄乱了我宝可梦的毛！\l"
	.string "你也毁了我的发型！\l"
	.string "我得现在就打电话给我的造型师！$"

Route116_Text_DevanIntro:
	.string "{CHN}我们要让你大吃一惊！$"

Route116_Text_DevanDefeat:
	.string "{CHN}哎呀呀！\n"
	.string "根本不是一个级别的！$"

Route116_Text_DevanPostBattle:
	.string "{CHN}我应该试试不同的宝可梦\n"
	.string "属性，那才是我应该做的。$"

Route116_Text_JohnsonIntro:
	.string "{CHN}前面是死路。\n"
	.string "我无聊了，能对战吗？$"

Route116_Text_JohnsonDefeat:
	.string "{CHN}虽然输了但很有趣。$"

Route116_Text_JohnsonPostBattle:
	.string "{CHN}想留在这里\n"
	.string "陪我吗？$"

Route117_Text_IsaacIntro:
	.string "{CHN}听着，能让你和我\n"
	.string "培养的宝可梦对战吗？$"

Route117_Text_IsaacDefeat:
	.string "{CHN}你培养得真好……$"

Route117_Text_IsaacPostBattle:
	.string "{CHN}宝可梦不全是力量。\p"
	.string "打磨独特的个性\n"
	.string "也是享受宝可梦的\l"
	.string "另一种方式。$"

Route117_Text_IsaacRegister:
	.string "{CHN}我要加倍训练。\n"
	.string "你能来看看我们吗？$"

Route117_Text_IsaacRematchIntro:
	.string "{CHN}我培养的宝可梦\n"
	.string "看起来不错，和以前一样。$"

Route117_Text_IsaacRematchDefeat:
	.string "{CHN}你知道怎么正确培养。\n"
	.string "你可能有寄宿处的技巧……$"

Route117_Text_IsaacPostRematch:
	.string "{CHN}你的宝可梦成长得很好！\n"
	.string "你应该让它们参加选拔赛。$"

Route117_Text_LydiaIntro:
	.string "{CHN}请允许我评估你是否\n"
	.string "正确地培养了宝可梦。$"

Route117_Text_LydiaDefeat:
	.string "{CHN}是的，它们成长得很好。$"

Route117_Text_LydiaPostBattle:
	.string "{CHN}试着更多地关注宝可梦的性格\n"
	.string "特征来培养。$"

Route117_Text_LydiaRegister:
	.string "{CHN}很高兴遇到像你这样出色的训练家。\n"
	.string "希望能再见到你。$"

Route117_Text_LydiaRematchIntro:
	.string "{CHN}请允许我重新评估你是否\n"
	.string "正确地培养了宝可梦。$"

Route117_Text_LydiaRematchDefeat:
	.string "{CHN}它们成长得令人钦佩。$"

Route117_Text_LydiaPostRematch:
	.string "{CHN}宝可梦似乎喜欢不同种类的\n"
	.string "{POKEBLOCK}S，取决于它们的性格。$"

Route117_Text_DylanIntro:
	.string "{CHN}我正在进行铁人三项，但，\n"
	.string "无所谓，来对战吧！$"

Route117_Text_DylanDefeat:
	.string "{CHN}我没力气了！$"

Route117_Text_DylanPostBattle:
	.string "{CHN}我可能搞砸了……\p"
	.string "那场对战中我可能\n"
	.string "掉到了最后……$"

Route117_Text_DylanRegister:
	.string "{CHN}宝可梦也得强吗？\n"
	.string "我想请你训练我！$"

Route117_Text_DylanRematchIntro:
	.string "{CHN}我正处在铁人三项中间，\n"
	.string "但我遥遥领先。\l"
	.string "让我们速战速决！$"

Route117_Text_DylanRematchDefeat:
	.string "{CHN}我又没力气了！$"

Route117_Text_DylanPostRematch:
	.string "{CHN}我游泳和自行车都是第一，\n"
	.string "但宝可梦我还不太\l"
	.string "自信。$"

Route117_Text_MariaIntro:
	.string "{CHN}我用宝可梦进行铁人三项训练，\n"
	.string "所以我对速度相当自信。$"

Route117_Text_MariaDefeat:
	.string "{CHN}看来我需要\n"
	.string "多练习。$"

Route117_Text_MariaPostBattle:
	.string "{CHN}只有坚持训练\n"
	.string "才有意义。\p"
	.string "好！我要恢复训练！\n"
	.string "明天！$"

Route117_Text_MariaRegister:
	.string "{CHN}你看起来在正确地训练……\n"
	.string "如果你愿意，我以后再和你对战！$"

Route117_Text_MariaRematchIntro:
	.string "{CHN}你在坚持训练吗？\n"
	.string "我可是！\l"
	.string "让我给你看看证据！$"

Route117_Text_MariaRematchDefeat:
	.string "{CHN}看来我需要\n"
	.string "多练习。$"

Route117_Text_MariaPostRematch:
	.string "{CHN}我明天恢复训练。\n"
	.string "改天再对战吧！$"

Route117_Text_DerekIntro:
	.string "{CHN}曾经是捕虫少年！\n"
	.string "现在是虫迷狂人！\p"
	.string "但我对宝可梦的爱\n"
	.string "从未改变！$"

Route117_Text_DerekDefeat:
	.string "{CHN}我的无能也\n"
	.string "没有改变……$"

Route117_Text_DerekPostBattle:
	.string "{CHN}我只是追随内心，现在\n"
	.string "他们叫我虫迷狂人……\p"
	.string "不过，我是虫属性宝可梦的专家，\n"
	.string "所以他们叫我\l"
	.string "虫迷狂人也很自然。$"

Route117_Text_AnnaIntro:
	.string "{CHN}ANNA：我和我漂亮的学妹\n"
	.string "搭档在一起。我得表现好！$"

Route117_Text_AnnaDefeat:
	.string "{CHN}ANNA：我和我漂亮的学妹\n"
	.string "搭档在一起！让我赢吧！$"

Route117_Text_AnnaPostBattle:
	.string "{CHN}ANNA：你的宝可梦有一些好的\n"
	.string "组合。\p"
	.string "我说你仅次于我们！$"

Route117_Text_AnnaAndMegRegister:
	.string "{CHN}ANNA：我们不能就这么算了！\n"
	.string "你会回来的，对吧？$"

Route117_Text_AnnaNotEnoughMons:
	.string "{CHN}ANNA：如果你想和我们对战，\n"
	.string "带两只宝可梦来。$"

Route117_Text_MegIntro:
	.string "{CHN}MEG：我要和我超棒的\n"
	.string "学长搭档一起打败你！$"

Route117_Text_MegDefeat:
	.string "{CHN}MEG：哦，不！\n"
	.string "对不起，ANNA！我拖了后腿……$"

Route117_Text_MegPostBattle:
	.string "{CHN}MEG：我拖累了ANNA……\n"
	.string "如果没有，她就赢了！$"

Route117_Text_MegNotEnoughMons:
	.string "{CHN}MEG：你只有一只宝可梦吗？\n"
	.string "那我们不能和你对战。\p"
	.string "我们想2对2对战。$"

Route117_Text_AnnaRematchIntro:
	.string "{CHN}ANNA：我不能在学妹\n"
	.string "面前一直输，对吧？$"

Route117_Text_AnnaRematchDefeat:
	.string "{CHN}ANNA：我找不到感觉。$"

Route117_Text_AnnaPostRematch:
	.string "{CHN}ANNA：你的宝可梦有一些好的\n"
	.string "组合。\p"
	.string "我说你仅次于我们！$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "{CHN}ANNA：如果你想和我们对战，\n"
	.string "带两只宝可梦来。$"

Route117_Text_MegRematchIntro:
	.string "{CHN}MEG：我要和我的\n"
	.string "学长搭档一起，这次一定要赢！$"

Route117_Text_MegRematchDefeat:
	.string "{CHN}MEG：太强了！$"

Route117_Text_MegPostRematch:
	.string "{CHN}MEG：我和我的\n"
	.string "学长搭档一起对战，但输了……\p"
	.string "真让人泄气……$"

Route117_Text_MegRematchNotEnoughMons:
	.string "{CHN}MEG：你只有一只宝可梦吗？\n"
	.string "那我们不能和你对战。\p"
	.string "我们想2对2对战。$"

Route117_Text_MelinaIntro:
	.string "{CHN}不是很棒吗？一边看着\n"
	.string "漂亮的花一边对战？$"

Route117_Text_MelinaDefeat:
	.string "{CHN}哦，相当了不起！$"

Route117_Text_MelinaPostBattle:
	.string "{CHN}一边看着花一边\n"
	.string "慢跑感觉太棒了。$"

Route117_Text_BrandiIntro:
	.string "{CHN}让我展示隐藏在\n"
	.string "超能力宝可梦中的力量！$"

Route117_Text_BrandiDefeat:
	.string "{CHN}惊人！$"

Route117_Text_BrandiPostBattle:
	.string "{CHN}超能力宝可梦很复杂。\n"
	.string "你应该试着抓一些。$"

Route117_Text_AishaIntro:
	.string "{CHN}专注于取得胜利。\n"
	.string "这就是我的对战方式！$"

Route117_Text_AishaDefeat:
	.string "{CHN}我不会浪费时间生气——\n"
	.string "我宁愿去训练。$"

Route117_Text_AishaPostBattle:
	.string "{CHN}我觉得如果你担心输，\n"
	.string "就更容易输。$"

Route118_Text_RoseIntro:
	.string "{CHN}花的香气有一种神奇的力量。\n"
	.string "它净化我们的身心。$"

Route118_Text_RoseDefeat:
	.string "{CHN}哦，天哪。\n"
	.string "我好像输了。$"

Route118_Text_RosePostBattle:
	.string "{CHN}花，宝可梦……\n"
	.string "我喜欢一切闻起来香的东西。\p"
	.string "臭的东西……\n"
	.string "我敬谢不敏。$"

Route118_Text_RoseRegister:
	.string "{CHN}嗅嗅……那气味——是宝可梦导航器！\n"
	.string "我们必须互相登记！$"

Route118_Text_RoseRematchIntro:
	.string "{CHN}你是被\n"
	.string "甜美的香气引来的吗？$"

Route118_Text_RoseRematchDefeat:
	.string "{CHN}香气的力量……\n"
	.string "似乎没什么用。$"

Route118_Text_RosePostRematch:
	.string "{CHN}如果正确使用甜香，\n"
	.string "宝可梦会被它吸引。$"

Route118_Text_PerryIntro:
	.string "{CHN}在天空中优雅飞翔的\n"
	.string "鸟宝可梦……它们最棒了！$"

Route118_Text_PerryDefeat:
	.string "{CHN}呃……\n"
	.string "我坠机了……$"

Route118_Text_PerryPostBattle:
	.string "{CHN}你的宝可梦很棒。\n"
	.string "我得更好地训练我的。$"

Route118_Text_ChesterIntro:
	.string "{CHN}起飞吧！\n"
	.string "我的鸟宝可梦！$"

Route118_Text_ChesterDefeat:
	.string "{CHN}它们确实起飞了……$"

Route118_Text_ChesterPostBattle:
	.string "{CHN}如果它们更强，就能飞得\n"
	.string "更自由……$"

Route118_Text_BarnyIntro:
	.string "{CHN}我是钓鱼大师，也是训练家。\n"
	.string "我在培养我钓到的宝可梦。$"

Route118_Text_BarnyDefeat:
	.string "{CHN}我以为我训练得\n"
	.string "还不错……$"

Route118_Text_BarnyPostBattle:
	.string "{CHN}边钓鱼边训练宝可梦\n"
	.string "赢不了……\p"
	.string "我是不是半吊子？$"

Route118_Text_WadeIntro:
	.string "{CHN}对钓鱼大师来说，装备是关键。\p"
	.string "但对训练家来说，关键要素\n"
	.string "是宝可梦和心，当然！$"

Route118_Text_WadeDefeat:
	.string "{CHN}我在心上被击败了？$"

Route118_Text_WadePostBattle:
	.string "{CHN}想想看，钓鱼是钓鱼大师\n"
	.string "和宝可梦之间的战斗。$"

Route118_Text_DaltonIntro:
	.string "{CHN}让我的旋律震撼你的灵魂！$"

Route118_Text_DaltonDefeat:
	.string "{CHN}啦啦啦……$"

Route118_Text_DaltonPostBattle:
	.string "{CHN}电吉他不总是\n"
	.string "那么吵的……\p"
	.string "它可以弹奏出\n"
	.string "激动人心的旋律……$"

Route118_Text_DaltonRegister:
	.string "{CHN}当我谱写出更好的旋律时，\n"
	.string "你一定要来听，好吗？$"

Route118_Text_DaltonRematchIntro:
	.string "{CHN}来自我和宝可梦的旋律……\n"
	.string "让它传到你的灵魂深处。$"

Route118_Text_DaltonRematchDefeat:
	.string "{CHN}啦啦啦……$"

Route118_Text_DaltonPostRematch:
	.string "{CHN}我演奏时，我的情感应该通过\n"
	.string "电吉他传达到你心里……$"

Route118_Text_DeandreIntro:
	.string "{CHN}上，上，上！\n"
	.string "宝可梦1、2、3！$"

Route118_Text_DeandreDefeat:
	.string "{CHN}回来，宝可梦！你没事吧？\n"
	.string "宝可梦1、2、3？！$"

Route118_Text_DeandrePostBattle:
	.string "{CHN}我有一支宝可梦\n"
	.string "战队，不是很酷吗？\p"
	.string "你可以学我——我不介意！$"

Route119_Text_BrentIntro:
	.string "{CHN}我们是模仿圈！\n"
	.string "我们模仿你做的事！$"

Route119_Text_BrentDefeat:
	.string "{CHN}哎呀！\n"
	.string "我输了！$"

Route119_Text_BrentPostBattle:
	.string "{CHN}模仿有什么好的？\p"
	.string "呼呼呼……\n"
	.string "你永远不会明白……$"

Route119_Text_DonaldIntro:
	.string "{CHN}终于见面了！\n"
	.string "我的虫属性宝可梦会陪你对战！$"

Route119_Text_DonaldDefeat:
	.string "{CHN}希望我们没见过面……$"

Route119_Text_DonaldPostBattle:
	.string "{CHN}我想多模仿你。\n"
	.string "你能快点走吗？$"

Route119_Text_TaylorIntro:
	.string "{CHN}你向前迈一步，我们也向前迈一步。\p"
	.string "你向右转，我们也向右转……$"

Route119_Text_TaylorDefeat:
	.string "{CHN}但如果你赢，我就输……$"

Route119_Text_TaylorPostBattle:
	.string "{CHN}我无法模仿你赢得比赛。\n"
	.string "那是不可能的……\l"
	.string "真让我火大……$"

Route119_Text_DougIntro:
	.string "{CHN}嗯，你终于逮到我了！\n"
	.string "还是你在躲我？$"

Route119_Text_DougDefeat:
	.string "{CHN}哇，那场对战真精彩！$"

Route119_Text_DougPostBattle:
	.string "{CHN}我们是模仿圈！\n"
	.string "希望你喜欢我们的表演。$"

Route119_Text_GregIntro:
	.string "{CHN}你不知道我是谁，对吧？\p"
	.string "但，我也不知道你。\n"
	.string "所以，我们对战吧！$"

Route119_Text_GregDefeat:
	.string "{CHN}你挺强的！$"

Route119_Text_GregPostBattle:
	.string "{CHN}在你离开之前，我们会\n"
	.string "继续模仿你的一举一动。$"

Route119_Text_KentIntro:
	.string "{CHN}模仿圈是由喜欢模仿的人\n"
	.string "组成的。\p"
	.string "对战从我们相遇的那一刻开始！$"

Route119_Text_KentDefeat:
	.string "{CHN}我认输！$"

Route119_Text_KentPostBattle:
	.string "{CHN}你不加入我们的模仿圈吗？$"

Route119_Text_JacksonIntro:
	.string "{CHN}谁有生存的知识和\n"
	.string "技术？\p"
	.string "宝可梦护林员，那就是谁！$"

Route119_Text_JacksonDefeat:
	.string "{CHN}我的宝可梦\n"
	.string "知识不够……$"

Route119_Text_JacksonPostBattle:
	.string "{CHN}摆脱文明的束缚，\n"
	.string "唤醒内心的野性精神！\p"
	.string "那是我们的愿景。$"

Route119_Text_JacksonRegister:
	.string "{CHN}希望你能和我再战一场，\n"
	.string "不要嘲笑我的无知。$"

Route119_Text_JacksonRematchIntro:
	.string "{CHN}我要通过与宝可梦在一起\n"
	.string "来重拾我的野性精神。$"

Route119_Text_JacksonRematchDefeat:
	.string "{CHN}你还是那么强！$"

Route119_Text_JacksonPostRematch:
	.string "{CHN}相信你的宝可梦。\n"
	.string "相信你自己。\p"
	.string "道路会向你展现。$"

Route119_Text_CatherineIntro:
	.string "{CHN}哦？看看你。\p"
	.string "作为一个冒险的人，\n"
	.string "你行装也太轻了。$"

Route119_Text_CatherineDefeat:
	.string "{CHN}不准备好的时候\n"
	.string "就会出意外！$"

Route119_Text_CatherinePostBattle:
	.string "{CHN}你行装轻便但拥有\n"
	.string "所需的一切。\p"
	.string "你在身心上\n"
	.string "也都准备充分。$"

Route119_Text_CatherineRegister:
	.string "{CHN}你有宝可梦导航器吗？\n"
	.string "它是任何训练家的必备工具。\p"
	.string "哦，你有！\n"
	.string "那让我们互相登记吧！$"

Route119_Text_CatherineRematchIntro:
	.string "{CHN}你和宝可梦的\n"
	.string "旅程怎么样？$"

Route119_Text_CatherineRematchDefeat:
	.string "{CHN}我还缺少什么……$"

Route119_Text_CatherinePostRematch:
	.string "{CHN}就像你作为训练家\n"
	.string "依赖你的宝可梦一样，你的宝可梦\l"
	.string "也依赖你。$"

Route119_Text_HughIntro:
	.string "{CHN}广阔的天空蕴含着无限的希望！\p"
	.string "没有什么比飞翔的\n"
	.string "快感更棒了！$"

Route119_Text_HughDefeat:
	.string "{CHN}彻底完蛋！$"

Route119_Text_HughPostBattle:
	.string "{CHN}我的鸟宝可梦让我的\n"
	.string "飞行梦想成真了！$"

Route119_Text_PhilIntro:
	.string "{CHN}我要让你见识我和\n"
	.string "我的鸟宝可梦的真正潜力！$"

Route119_Text_PhilDefeat:
	.string "{CHN}我们缺乏潜力……$"

Route119_Text_PhilPostBattle:
	.string "{CHN}从小时候起，我就一直\n"
	.string "仰慕鸟宝可梦……$"

Route119_Text_YasuIntro:
	.string "{CHN}潜藏于阴影中，\n"
	.string "活在黑暗中……那是我的命运。\p"
	.string "我出现向你挑战！$"

Route119_Text_YasuDefeat:
	.string "{CHN}我认输！$"

Route119_Text_YasuPostBattle:
	.string "{CHN}战败者悄然\n"
	.string "退回阴影之中。\l"
	.string "那也是命运……$"

Route119_Text_TakashiIntro:
	.string "{CHN}如果你不警惕，\n"
	.string "就要吃苦头了！$"

Route119_Text_TakashiDefeat:
	.string "{CHN}你出乎意料地强！$"

Route119_Text_TakashiPostBattle:
	.string "{CHN}我的突袭以\n"
	.string "失败告终……$"

Route119_Text_HideoIntro:
	.string "{CHN}藏树于林！$"

Route119_Text_HideoDefeat:
	.string "{CHN}我向你低头。$"

Route119_Text_HideoPostBattle:
	.string "{CHN}藏树于林！\n"
	.string "藏宝可梦于宝可梦！\p"
	.string "这没有什么\n"
	.string "深层含义。$"

Route119_Text_ChrisIntro:
	.string "{CHN}你跟我说话了……\n"
	.string "所以你想挑战我！\p"
	.string "好！我要试试我冲浪时\n"
	.string "抓到的宝可梦！$"

Route119_Text_ChrisDefeat:
	.string "{CHN}我完全不知道\n"
	.string "怎么才能赢。$"

Route119_Text_ChrisPostBattle:
	.string "{CHN}在我的宝可梦上冲浪……\p"
	.string "然后在它背上钓鱼……\p"
	.string "那是一种难以言喻的奢华时刻！$"

Route119_Text_FabianIntro:
	.string "{CHN}给我一个强力和弦！\n"
	.string "胜利属于我！\l"
	.string "这是我们的闪耀时刻，哦，耶！$"

Route119_Text_FabianDefeat:
	.string "{CHN}你让我知道了谁才是老大！\n"
	.string "我们只能接受失败，哦，不！$"

Route119_Text_FabianPostBattle:
	.string "{CHN}再给我一个强力和弦！\n"
	.string "别烦我！\l"
	.string "你的胜利需要赎罪！$"

Route119_Text_DaytonIntro:
	.string "{CHN}呵呵呵！\n"
	.string "我喜欢小鬼训练家！\l"
	.string "来好好打一场吧！$"

Route119_Text_DaytonDefeat:
	.string "{CHN}你真了不起！\n"
	.string "呵呵呵！$"

Route119_Text_DaytonPostBattle:
	.string "{CHN}呵呵呵！\n"
	.string "我要试着学习\l"
	.string "像你这样的小鬼训练家的活力！$"

Route119_Text_RachelIntro:
	.string "{CHN}无论何时何地，\n"
	.string "我总是手不离阳伞。$"

Route119_Text_RachelDefeat:
	.string "{CHN}哦，可是……\n"
	.string "那不公平。$"

Route119_Text_RachelPostBattle:
	.string "{CHN}你问我的阳伞重不重？\n"
	.string "你的包装的杂物比我\l"
	.string "随身带的还多。$"

Route120_Text_ColinIntro:
	.string "{CHN}你有什么招式能\n"
	.string "打中飞行的宝可梦吗？$"

Route120_Text_ColinDefeat:
	.string "{CHN}你飞到我上面去了！$"

Route120_Text_ColinPostBattle:
	.string "{CHN}飞翔这个招式很方便，\n"
	.string "你不觉得吗？\p"
	.string "宝可梦飞行时，\n"
	.string "几乎没有招式能打中它。$"

Route120_Text_RobertIntro:
	.string "{CHN}我的宝可梦很强！\n"
	.string "你的呢？$"

Route120_Text_RobertDefeat:
	.string "{CHN}你的宝可梦更强……$"

Route120_Text_RobertPostBattle:
	.string "{CHN}稳步成长的宝可梦\n"
	.string "才靠得住。$"

Route120_Text_RobertRegister:
	.string "{CHN}你可以指望变得更强。\n"
	.string "我想把你登记到我的宝可梦导航器里！$"

Route120_Text_RobertRematchIntro:
	.string "{CHN}稳步成长的宝可梦\n"
	.string "才靠得住。$"

Route120_Text_RobertRematchDefeat:
	.string "{CHN}你的宝可梦真的强。$"

Route120_Text_RobertPostRematch:
	.string "{CHN}我的宝可梦在变强。\n"
	.string "我也得变强。$"

Route120_Text_LorenzoIntro:
	.string "{CHN}我要检查你的宝可梦\n"
	.string "看它们是否适合户外。$"

Route120_Text_LorenzoDefeat:
	.string "{CHN}有那么强的宝可梦，\n"
	.string "你不需要救援！$"

Route120_Text_LorenzoPostBattle:
	.string "{CHN}带着宝可梦随心所欲地\n"
	.string "旅行……\l"
	.string "那就是作为训练家的乐趣。$"

Route120_Text_JennaIntro:
	.string "{CHN}你的体能怎么样？\n"
	.string "如果体能不行，在危急时刻\l"
	.string "可能会很困难。$"

Route120_Text_JennaDefeat:
	.string "{CHN}我很健壮，但……$"

Route120_Text_JennaPostBattle:
	.string "{CHN}体能训练是我的日常。\n"
	.string "我总是和宝可梦一起跑步。$"

Route120_Text_JeffreyIntro:
	.string "{CHN}…… …… …… …… …… ……\n"
	.string "…… …… …… …… …… …\l"
	.string "想对战吗？$"

Route120_Text_JeffreyDefeat:
	.string "{CHN}输了……$"

Route120_Text_JeffreyPostBattle:
	.string "{CHN}…… …… …… …… …… ……\n"
	.string "…… …… …… …… …… …\l"
	.string "我会更努力……$"

Route120_Text_JeffreyRegister:
	.string "{CHN}…… …… …… …… …… ……\n"
	.string "…… …… …… …… …… …\l"
	.string "你有宝可梦导航器吗……？$"

Route120_Text_JeffreyRematchIntro:
	.string "{CHN}…… …… …… …… …… ……\n"
	.string "…… …… …… …… …… …\l"
	.string "想再对战吗？$"

Route120_Text_JeffreyRematchDefeat:
	.string "{CHN}…… …… …… …… …… ……\n"
	.string "我又输了……$"

Route120_Text_JeffreyPostRematch:
	.string "{CHN}…… …… …… …… …… ……\n"
	.string "…… …… …… …… …… …\l"
	.string "我会更努力……\l"
	.string "为了我珍贵的虫属性宝可梦……$"

Route120_Text_JenniferIntro:
	.string "{CHN}宝可梦有许多特性。\n"
	.string "如果你想成为一流的\l"
	.string "训练家，就去了解它们。$"

Route120_Text_JenniferDefeat:
	.string "{CHN}你显然在思考。$"

Route120_Text_JenniferPostBattle:
	.string "{CHN}宝可梦的特性\n"
	.string "会改变对战风格。$"

Route120_Text_ChipIntro:
	.string "{CHN}你可能是谁？\p"
	.string "你是在寻找传说中的\n"
	.string "古代遗迹吗？\l"
	.string "据传可能存在的那些？$"

Route120_Text_ChipDefeat:
	.string "{CHN}多么丢脸的挫败……$"

Route120_Text_ChipPostBattle:
	.string "{CHN}那块巨大的岩石……我愿意\n"
	.string "相信它可能确实包含\l"
	.string "古代遗迹。但我看不到入口。$"

Route120_Text_ClarissaIntro:
	.string "{CHN}为什么我带着这把阳伞？\p"
	.string "如果你能赢我，我就告诉你。$"

Route120_Text_ClarissaDefeat:
	.string "{CHN}阳伞挡不住宝可梦\n"
	.string "的攻击……$"

Route120_Text_ClarissaPostBattle:
	.string "{CHN}我觉得强烈的阳光\n"
	.string "对我的宝可梦不好。\l"
	.string "所以我用阳伞为它们遮阳。$"

Route120_Text_AngelicaIntro:
	.string "{CHN}我、宝可梦，还有我的阳伞……\p"
	.string "如果缺少任何一个，\n"
	.string "美丽的画面就被破坏了。$"

Route120_Text_AngelicaDefeat:
	.string "{CHN}你完全破坏了我的美丽……$"

Route120_Text_AngelicaPostBattle:
	.string "{CHN}阳伞一点也不适合你。\p"
	.string "哎呀，像这样的东西\n"
	.string "只会碍你的事。$"

Route120_Text_KeigoIntro:
	.string "{CHN}我要模仿宝可梦的动作\n"
	.string "创造新的忍术。$"

Route120_Text_KeigoDefeat:
	.string "{CHN}新忍术的创造\n"
	.string "还只是遥远的梦……$"

Route120_Text_KeigoPostBattle:
	.string "{CHN}也许我该拜\n"
	.string "一位忍者师傅为师。$"

Route120_Text_RileyIntro:
	.string "{CHN}我们忍者用伪装斗篷\n"
	.string "隐藏自己。\l"
	.string "我打赌你不知道我在哪！$"

Route120_Text_RileyDefeat:
	.string "{CHN}我输了！\n"
	.string "我应该把我的羞耻也伪装起来！$"

Route120_Text_RileyPostBattle:
	.string "{CHN}我们的伪装斗篷都是\n"
	.string "手工制作的。$"

Route120_Text_CallieIntro:
	.string "{CHN}如果不注意，\n"
	.string "可能会受伤！$"

Route120_Text_CallieDefeat:
	.string "{CHN}哎哟！\n"
	.string "受伤的是我。$"

Route120_Text_CalliePostBattle:
	.string "{CHN}我在想……我应该让宝可梦进化吗？\n"
	.string "不过它们现在的样子很可爱。$"

Route120_Text_LeonelIntro:
	.string "{CHN}你队伍里的宝可梦……\n"
	.string "你有不同的属性吗？$"

Route120_Text_LeonelDefeat:
	.string "{CHN}我见识了你的方针！$"

Route120_Text_LeonelPostBattle:
	.string "{CHN}我觉得你用最喜欢的宝可梦\n"
	.string "就能这么强，真了不起。$"

Route121_Text_VanessaIntro:
	.string "{CHN}你愿意和我可爱的\n"
	.string "宝可梦玩玩吗？$"

Route121_Text_VanessaDefeat:
	.string "{CHN}我不是这个意思！$"

Route121_Text_VanessaPostBattle:
	.string "{CHN}我要去茵郁市的选拔赛。\p"
	.string "我的宝可梦应该\n"
	.string "横扫大师级没问题。$"

Route121_Text_WalterIntro:
	.string "{CHN}带着我的宝可梦，我走遍了\n"
	.string "世界的四角。\p"
	.string "你可以说我对自己\n"
	.string "的能力颇有信心。$"

Route121_Text_WalterDefeat:
	.string "{CHN}啊，打得漂亮。$"

Route121_Text_WalterPostBattle:
	.string "{CHN}我想再和宝可梦一起\n"
	.string "环游世界一次。$"

Route121_Text_WalterRegister:
	.string "{CHN}你的宝可梦技艺卓越。\n"
	.string "请允许我作为纪念登记你。$"

Route121_Text_WalterRematchIntro:
	.string "{CHN}带着我的宝可梦，我走遍了\n"
	.string "世界的四角。\p"
	.string "你可以说我对自己\n"
	.string "的能力颇有信心。$"

Route121_Text_WalterRematchDefeat:
	.string "{CHN}啊，打得漂亮。$"

Route121_Text_WalterPostRematch:
	.string "{CHN}你和你的宝可梦……\p"
	.string "你们一起的实力\n"
	.string "即使在海外也算强。$"

Route121_Text_TammyIntro:
	.string "{CHN}这个世界上有超越我们\n"
	.string "理解的力量……$"

Route121_Text_TammyDefeat:
	.string "{CHN}我输了……$"

Route121_Text_TammyPostBattle:
	.string "{CHN}送火山……\n"
	.string "那里有一股神秘的\l"
	.string "力量在起作用……$"

Route121_Text_KateIntro:
	.string "{CHN}KATE：在一起，我们无所畏惧！\n"
	.string "我们要展示我们有多强！$"

Route121_Text_KateDefeat:
	.string "{CHN}KATE：我在学妹\n"
	.string "面前丢脸了……$"

Route121_Text_KatePostBattle:
	.string "{CHN}KATE：当有人依赖我时，\n"
	.string "我就有股想在\l"
	.string "他们面前耍帅的冲动……$"

Route121_Text_KateNotEnoughMons:
	.string "{CHN}KATE：如果你只有一只宝可梦，\n"
	.string "我们不能和你对战。\p"
	.string "那会变成欺负人。$"

Route121_Text_JoyIntro:
	.string "{CHN}JOY：在一起，我们无所畏惧！\n"
	.string "我们要展示我们有多强！$"

Route121_Text_JoyDefeat:
	.string "{CHN}JOY：请原谅我，KATE！$"

Route121_Text_JoyPostBattle:
	.string "{CHN}JOY：呵呵，我得和KATE，\n"
	.string "我的学长，再训练了。$"

Route121_Text_JoyNotEnoughMons:
	.string "{CHN}JOY：你要挑战我们的话\n"
	.string "至少需要两只宝可梦！$"

Route121_Text_JessicaIntro:
	.string "{CHN}站住！好好看看我珍贵的\n"
	.string "宝可梦！$"

Route121_Text_JessicaDefeat:
	.string "{CHN}哦，你怎么敢！\n"
	.string "别那么认真！$"

Route121_Text_JessicaPostBattle:
	.string "{CHN}也许我去野生原野区\n"
	.string "多抓些宝可梦。$"

Route121_Text_JessicaRegister:
	.string "{CHN}这次我对你手下留情了！\n"
	.string "下次可不会了！$"

Route121_Text_JessicaRematchIntro:
	.string "{CHN}我珍贵的宝可梦长大了！\n"
	.string "好好看看！$"

Route121_Text_JessicaRematchDefeat:
	.string "{CHN}哦，你怎么敢！\n"
	.string "你还是不留情！$"

Route121_Text_JessicaPostRematch:
	.string "{CHN}也许我去野生原野区\n"
	.string "多抓些宝可梦。$"

Route121_Text_CristinIntro:
	.string "{CHN}我有这个习惯。\n"
	.string "每天打败五个训练家。\l"
	.string "猜猜看？你是第五个！$"

Route121_Text_CristinDefeat:
	.string "{CHN}不！\n"
	.string "你太过分了！$"

Route121_Text_CristinPostBattle:
	.string "{CHN}没想到这么容易就输了……\n"
	.string "下次我会赢的！$"

Route121_Text_CristinRegister:
	.string "{CHN}那是彻底的羞辱！\n"
	.string "我不会忘了你……\l"
	.string "交出你的宝可梦导航器！$"

Route121_Text_CristinRematchIntro:
	.string "{CHN}我有这个新习惯。\n"
	.string "每天打败十个训练家。\l"
	.string "猜猜看？你是第十个！$"

Route121_Text_CristinRematchDefeat:
	.string "{CHN}等等！太过分了！\n"
	.string "我要求再战！$"

Route121_Text_CristinPostRematch:
	.string "{CHN}我就是赢不了的对手……\n"
	.string "抽泣……\l"
	.string "我不敢相信这是真的……$"

Route121_Text_CaleIntro:
	.string "{CHN}你没看到我拿着\n"
	.string "这么多东西吗？\p"
	.string "尽管如此，你\n"
	.string "还是要对战吗？$"

Route121_Text_CaleDefeat:
	.string "{CHN}我当然输了！\n"
	.string "我两只手都拿着东西！$"

Route121_Text_CalePostBattle:
	.string "{CHN}我在茵郁百货大楼\n"
	.string "买了太多东西。\p"
	.string "就在前面那条路。\n"
	.string "我真希望有你那样的包。$"

Route121_Text_MylesIntro:
	.string "{CHN}我最喜欢看\n"
	.string "别人的宝可梦了！$"

Route121_Text_MylesDefeat:
	.string "{CHN}超级棒！$"

Route121_Text_MylesPostBattle:
	.string "{CHN}你的宝可梦真棒！\n"
	.string "你是怎么培养的？$"

Route121_Text_PatIntro:
	.string "{CHN}我想让所有人都看到\n"
	.string "我培养的宝可梦！$"

Route121_Text_PatDefeat:
	.string "{CHN}哇！\n"
	.string "太精彩了！$"

Route121_Text_PatPostBattle:
	.string "{CHN}我用同样的爱和关怀培养\n"
	.string "每一只宝可梦——我不偏心。$"

Route121_Text_MarcelIntro:
	.string "{CHN}我的宝可梦从未尝过败绩！\n"
	.string "下次赢了，我就让它们\l"
	.string "参加选拔赛。$"

Route121_Text_MarcelDefeat:
	.string "{CHN}哦，这是怎么回事？$"

Route121_Text_MarcelPostBattle:
	.string "{CHN}在参加任何选拔赛之前，\n"
	.string "我可能得多训练一下我的队伍。$"

Route123_Text_WendyIntro:
	.string "{CHN}想测测你有多强吗？\n"
	.string "让我来当测试！$"

Route123_Text_WendyDefeat:
	.string "{CHN}你出色地通过了！$"

Route123_Text_WendyPostBattle:
	.string "{CHN}连我都能打败……\n"
	.string "你的实力令人惊叹！$"

Route123_Text_BraxtonIntro:
	.string "{CHN}你好像收集了\n"
	.string "很多道馆徽章。\p"
	.string "让我看看你是否真的配得上\n"
	.string "那些徽章！$"

Route123_Text_BraxtonDefeat:
	.string "{CHN}哦，你配得上，没错！$"

Route123_Text_BraxtonPostBattle:
	.string "{CHN}那场对战你没让\n"
	.string "你的徽章丢脸！$"

Route123_Text_VioletIntro:
	.string "{CHN}他们说美好的时光充满了\n"
	.string "美好的香气。$"

Route123_Text_VioletDefeat:
	.string "{CHN}哦……\n"
	.string "我闻到了痛苦的苦涩气息……$"

Route123_Text_VioletPostBattle:
	.string "{CHN}树果大师的花园充满了\n"
	.string "令人振奋的香气。$"

Route123_Text_CameronIntro:
	.string "{CHN}超能力者靠的是意志力。\p"
	.string "我让自己不输给\n"
	.string "任何人。那让我变强！$"

Route123_Text_CameronDefeat:
	.string "{CHN}我感到悲伤……$"

Route123_Text_CameronPostBattle:
	.string "{CHN}超能力者靠的是意志力。\n"
	.string "我以为我不会输给你……$"

Route123_Text_CameronRegister:
	.string "{CHN}我感应到了！\n"
	.string "你和我还会再战！\l"
	.string "虽然我不知道我会不会赢……\p"
	.string "让我看看你的宝可梦导航器。$"

Route123_Text_CameronRematchIntro:
	.string "{CHN}我说服自己不会再\n"
	.string "输了。那让我变强！$"

Route123_Text_CameronRematchDefeat:
	.string "{CHN}我感到悲伤……$"

Route123_Text_CameronPostRematch:
	.string "{CHN}我该去送火山修炼……\n"
	.string "这样下去我永远赢不了你……$"

Route123_Text_JackiIntro:
	.string "{CHN}如果你的宝可梦\n"
	.string "觉醒了超能力，别太高兴。\p"
	.string "你需要磨练那些力量\n"
	.string "才能让它们真正有用。$"

Route123_Text_JackiDefeat:
	.string "{CHN}压倒性的！$"

Route123_Text_JackiPostBattle:
	.string "{CHN}我们都有超能力。\n"
	.string "只是我们忘了怎么使用。$"

Route123_Text_JackiRegister:
	.string "{CHN}我想再和你对战。\n"
	.string "可以吗？$"

Route123_Text_JackiRematchIntro:
	.string "{CHN}你觉醒了\n"
	.string "内在的超能力吗？$"

Route123_Text_JackiRematchDefeat:
	.string "{CHN}惊人！$"

Route123_Text_JackiPostRematch:
	.string "{CHN}你和宝可梦的力量……\n"
	.string "那也可能是一种超能力。$"

Route123_Text_MiuIntro:
	.string "{CHN}MIU：你好，训练家。希望你的\n"
	.string "宝可梦输了不会哭。$"

Route123_Text_MiuDefeat:
	.string "{CHN}MIU：哎呀，我们输了。$"

Route123_Text_MiuPostBattle:
	.string "{CHN}MIU：训练家，你的宝可梦\n"
	.string "很强，因为你们是朋友。$"

Route123_Text_MiuNotEnoughMons:
	.string "{CHN}MIU：如果你\n"
	.string "没有两只宝可梦，对战就没意思了。$"

Route123_Text_YukiIntro:
	.string "{CHN}YUKI：好！\n"
	.string "我们要打败训练家的宝可梦！$"

Route123_Text_YukiDefeat:
	.string "{CHN}YUKI：哎呀，我们输了。$"

Route123_Text_YukiPostBattle:
	.string "{CHN}YUKI：你怎么这么强？\n"
	.string "我们以前从未输过。$"

Route123_Text_YukiNotEnoughMons:
	.string "{CHN}YUKI：如果你\n"
	.string "没有两只宝可梦，对战就没意思了。$"

Route123_Text_KindraIntro:
	.string "{CHN}送火山……\n"
	.string "宝可梦灵魂安息之地……\l"
	.string "你的宝可梦会安息吗？$"

Route123_Text_KindraDefeat:
	.string "{CHN}活力四溢……$"

Route123_Text_KindraPostBattle:
	.string "{CHN}送火山……\n"
	.string "宝可梦灵魂安息之地……\p"
	.string "那里一定充满了\n"
	.string "安抚灵魂的力量……$"

Route123_Text_FernandoIntro:
	.string "{CHN}我要在弹奏这首曲子时\n"
	.string "让你眼花缭乱！$"

Route123_Text_FernandoDefeat:
	.string "{CHN}嘿，等等！\n"
	.string "我还在弹前奏呢！$"

Route123_Text_FernandoPostBattle:
	.string "{CHN}你稳如磐石。\n"
	.string "我想为你写一首曲子。$"

Route123_Text_FernandoRegister:
	.string "{CHN}下次，把耳朵借给我\n"
	.string "听完整首曲子，好吗？$"

Route123_Text_FernandoRematchIntro:
	.string "{CHN}今天就是我要做到的日子！\n"
	.string "我要在我唱完歌之前\l"
	.string "让你眼花缭乱！$"

Route123_Text_FernandoRematchDefeat:
	.string "{CHN}嘿，等等！\n"
	.string "我还没到副歌呢！$"

Route123_Text_FernandoPostRematch:
	.string "{CHN}我以为你会被我的曲子\n"
	.string "迷住而输掉。$"

Route123_Text_DavisIntro:
	.string "{CHN}这是我超棒的虫属性宝可梦！\n"
	.string "我哥哥给我的。$"

Route123_Text_DavisDefeat:
	.string "{CHN}哇啊啊！\n"
	.string "你这个坏蛋！$"

Route123_Text_DavisPostBattle:
	.string "{CHN}别告诉我哥哥我输了。\n"
	.string "你要保密！$"

Route123_Text_JazmynIntro:
	.string "{CHN}打败明显很强的人\n"
	.string "会让我信心大增！$"

Route123_Text_JazmynDefeat:
	.string "{CHN}我的信心没了……$"

Route123_Text_JazmynPostBattle:
	.string "{CHN}他们说不能以貌取人。\p"
	.string "但通常，\n"
	.string "外表不会说谎……$"

Route123_Text_FrederickIntro:
	.string "{CHN}你好，孩子！\n"
	.string "能占用你一些时间吗？$"

Route123_Text_FrederickDefeat:
	.string "{CHN}啊，一个能力很强的孩子！\n"
	.string "让我为你的零花钱做点贡献。$"

Route123_Text_FrederickPostBattle:
	.string "{CHN}为你的零花钱做贡献？\n"
	.string "奖金还不够吗？$"

Route123_Text_AlbertoIntro:
	.string "{CHN}我得告诉你，鸟宝可梦\n"
	.string "是我的挚爱！\p"
	.string "鸟很酷！\n"
	.string "它们是最棒的！$"

Route123_Text_AlbertoDefeat:
	.string "{CHN}即使输了，鸟宝可梦还是很酷！$"

Route123_Text_AlbertoPostBattle:
	.string "{CHN}我收集对战中散落的\n"
	.string "鸟宝可梦羽毛。\p"
	.string "我要用\n"
	.string "鸟宝可梦羽毛做一顶帽子。$"

Route123_Text_EdIntro:
	.string "{CHN}周围没有训练家时，\n"
	.string "我让我的宝可梦互相对战。\l"
	.string "我在一旁观看。$"

Route123_Text_EdDefeat:
	.string "{CHN}我有点喜欢你的宝可梦。$"

Route123_Text_EdPostBattle:
	.string "{CHN}嘿嘿，我要偷走你的对战点子！\n"
	.string "我想那会让我变得更强。$"

Route123_Text_JonasIntro:
	.string "{CHN}我埋伏着，一个训练家\n"
	.string "掉进了我的陷阱！$"

Route123_Text_JonasDefeat:
	.string "{CHN}如果你不输，我怎么\n"
	.string "愉快地玩忍者？$"

Route123_Text_JonasPostBattle:
	.string "{CHN}下次我要埋伏一个\n"
	.string "看起来更弱的训练家。$"

Route123_Text_KayleyIntro:
	.string "{CHN}我刚买了这把阳伞。\n"
	.string "我的可爱度应该增加了三分之一！$"

Route123_Text_KayleyDefeat:
	.string "{CHN}你比我强了大约\n"
	.string "五倍！$"

Route123_Text_KayleyPostBattle:
	.string "{CHN}有效地使用配饰是\n"
	.string "时尚魅力的秘密。$"

Route124_Text_SpencerIntro:
	.string "{CHN}嘿，你在海上迷路了吗？\p"
	.string "如果你能打败我的宝可梦，\n"
	.string "我可以给你当向导。$"

Route124_Text_SpencerDefeat:
	.string "{CHN}我在对战中迷失了方向！$"

Route124_Text_SpencerPostBattle:
	.string "{CHN}很多人在海上迷失方向。\p"
	.string "如果你是那种人，\n"
	.string "你应该看看宝可梦导航器的地图。$"

Route124_Text_RolandIntro:
	.string "{CHN}嗯！你骑着宝可梦\n"
	.string "而不是自己游泳……\p"
	.string "我好羡慕！$"

Route124_Text_RolandDefeat:
	.string "{CHN}哦！\n"
	.string "我不行了……$"

Route124_Text_RolandPostBattle:
	.string "{CHN}我冷得发抖……\n"
	.string "我在水里待太久了……\p"
	.string "我真希望能像你一样骑宝可梦……$"

Route124_Text_JennyIntro:
	.string "{CHN}像这样在海里漂浮，\n"
	.string "宝可梦会过来玩。$"

Route124_Text_JennyDefeat:
	.string "{CHN}哦，可恶。\n"
	.string "我输了。$"

Route124_Text_JennyPostBattle:
	.string "{CHN}游泳的时候，我发现有些\n"
	.string "宝可梦会攻击，有些只观看。\p"
	.string "我猜宝可梦也有\n"
	.string "各自的性格。$"

Route124_Text_JennyRegister:
	.string "{CHN}只是一时兴起，也许我会让\n"
	.string "你把我登记到你的宝可梦导航器里。$"

Route124_Text_JennyRematchIntro:
	.string "{CHN}像这样在海里漂浮，\n"
	.string "训练家会来挑战你！$"

Route124_Text_JennyRematchDefeat:
	.string "{CHN}奇怪……\n"
	.string "我又输了……$"

Route124_Text_JennyPostRematch:
	.string "{CHN}这和任何事都没关系，\n"
	.string "但也许我会去陷阱屋看看。$"

Route124_Text_GraceIntro:
	.string "{CHN}我游腻了……\n"
	.string "来场对战怎么样？$"

Route124_Text_GraceDefeat:
	.string "{CHN}我不知道你\n"
	.string "这么强！$"

Route124_Text_GracePostBattle:
	.string "{CHN}你付出的所有努力\n"
	.string "一定让你变得这么强。$"

Route124_Text_ChadIntro:
	.string "{CHN}呼呼呼呼……我深潜到水下\n"
	.string "是为了深藏身份。\l"
	.string "探索深渊是我的强项！$"

Route124_Text_ChadDefeat:
	.string "{CHN}咕噜，咕噜，咕噜……\n"
	.string "我在下沉……$"

Route124_Text_ChadPostBattle:
	.string "{CHN}我有可靠消息说\n"
	.string "这附近有潜水点。\p"
	.string "这让我很想再\n"
	.string "潜入深处……$"

Route124_Text_LilaIntro:
	.string "{CHN}LILA：唉……\p"
	.string "我在海里，但谁跟我在一起？\n"
	.string "我弟弟！\p"
	.string "对战吧，这样我就不用\n"
	.string "想那些了！$"

Route124_Text_LilaDefeat:
	.string "{CHN}LILA：ROY！都怪你我们输了！\n"
	.string "回去有你受的！$"

Route124_Text_LilaPostBattle:
	.string "{CHN}LILA：唉……\p"
	.string "如果我身边不是弟弟，\n"
	.string "而是一个好男朋友就好了……$"

Route124_Text_LilaNotEnoughMons:
	.string "{CHN}LILA：你打算和我们对战？\n"
	.string "没有两只宝可梦可不行。$"

Route124_Text_RoyIntro:
	.string "{CHN}ROY：我姐姐的宝可梦很强！\p"
	.string "输了可别哭！$"

Route124_Text_RoyDefeat:
	.string "{CHN}ROY：哎呀……\n"
	.string "姐姐要骂我了……$"

Route124_Text_RoyPostBattle:
	.string "{CHN}ROY：我姐姐生气的\n"
	.string "时候很可怕。\p"
	.string "所以她才没有\n"
	.string "男朋友。$"

Route124_Text_LilaRoyRegister:
	.string "{CHN}ROY：你还会和我们对战吗？\n"
	.string "但下次手下留情，好吗？$"

Route124_Text_RoyNotEnoughMons:
	.string "{CHN}ROY：你想和我们对战？\n"
	.string "那带两只宝可梦来。$"

Route124_Text_LilaRematchIntro:
	.string "{CHN}LILA：唉……\p"
	.string "我在海里，但谁跟我在一起？\n"
	.string "我弟弟！\p"
	.string "哦，嗨，好久不见。对战吧，\n"
	.string "这样我就不用想那些了！$"

Route124_Text_LilaRematchDefeat:
	.string "{CHN}LILA：ROY！\n"
	.string "又怪你我们输了！\p"
	.string "回去要加练了！$"

Route124_Text_LilaPostRematch:
	.string "{CHN}LILA：唉……\p"
	.string "如果我有个好男朋友，我们就能\n"
	.string "用绝妙的组合打败任何人……$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "{CHN}LILA：你打算和我们对战？\n"
	.string "没有两只宝可梦可不行。$"

Route124_Text_RoyRematchIntro:
	.string "{CHN}ROY：如果我们输了，我会挨骂的。\n"
	.string "我要全力以赴！$"

Route124_Text_RoyRematchDefeat:
	.string "{CHN}ROY：糟了……\n"
	.string "姐姐又要骂我了。$"

Route124_Text_RoyPostRematch:
	.string "{CHN}ROY：我姐姐生起气来\n"
	.string "真的很可怕。\p"
	.string "她待会儿肯定要让我和宝可梦\n"
	.string "拼命训练……$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "{CHN}ROY：你想和我们对战？\n"
	.string "那就带两只宝可梦来。$"

Route124_Text_DeclanIntro:
	.string "{CHN}我独自一人在这辽阔美丽的\n"
	.string "大海上游泳。\p"
	.string "没有别的词能形容了。\n"
	.string "这真是可悲！$"

Route124_Text_DeclanDefeat:
	.string "{CHN}我心情变蓝了。\n"
	.string "蓝得像天空一样……$"

Route124_Text_DeclanPostBattle:
	.string "{CHN}我应该去和女游泳训练家\n"
	.string "搭讪，邀请她们一起长游。$"

Route124_Text_IsabellaIntro:
	.string "{CHN}我才不会输给\n"
	.string "什么冲浪训练家。$"

Route124_Text_IsabellaDefeat:
	.string "{CHN}我只是汗流到眼睛里了！\n"
	.string "我才没有哭！$"

Route124_Text_IsabellaPostBattle:
	.string "{CHN}在这附近可以找到\n"
	.string "颜色漂亮的碎片。$"

Route125_Text_NolenIntro:
	.string "{CHN}我听到你靠近的声音，\n"
	.string "就在这里等你了！$"

Route125_Text_NolenDefeat:
	.string "{CHN}我认输！$"

Route125_Text_NolenPostBattle:
	.string "{CHN}声音在水中传播的速度\n"
	.string "比在空气中快。$"

Route125_Text_StanIntro:
	.string "{CHN}嘿，那边！\n"
	.string "看看我帅气的宝可梦！$"

Route125_Text_StanDefeat:
	.string "{CHN}我扑腾失败了……$"

Route125_Text_StanPostBattle:
	.string "{CHN}我被墨海马的迷人所吸引，\n"
	.string "所以也开始游泳了。$"

Route125_Text_TanyaIntro:
	.string "{CHN}我游累了。\n"
	.string "你要不要和我对战？$"

Route125_Text_TanyaDefeat:
	.string "{CHN}你太强了！$"

Route125_Text_TanyaPostBattle:
	.string "{CHN}呼……\n"
	.string "往哪边走才能到暮水镇？$"

Route125_Text_SharonIntro:
	.string "{CHN}你想不想和我培育的\n"
	.string "水属性宝可梦对战？$"

Route125_Text_SharonDefeat:
	.string "{CHN}输了……$"

Route125_Text_SharonPostBattle:
	.string "{CHN}你的实力……你是真的厉害。\n"
	.string "我服了！$"

Route125_Text_ErnestIntro:
	.string "{CHN}啊哈！我是个强壮的水手！\n"
	.string "我闯荡过世界各地的海洋！$"

Route125_Text_ErnestDefeat:
	.string "{CHN}吼吼吼！\n"
	.string "我赢不了！$"

Route125_Text_ErnestPostBattle:
	.string "{CHN}浅滩洞穴里的潮水\n"
	.string "会涨落。\p"
	.string "顺便说一句，从涨潮到退潮大约\n"
	.string "需要六个小时。你知道吗？$"

Route125_Text_ErnestRegister:
	.string "{CHN}把我登记到你的宝可梦导航器里，\n"
	.string "我会告诉你一些好事。$"

Route125_Text_ErnestRematchIntro:
	.string "{CHN}是时候找你报仇了！\n"
	.string "来吧，我们对战！$"

Route125_Text_ErnestRematchDefeat:
	.string "{CHN}我赢不了！\n"
	.string "我完全赢不了！$"

Route125_Text_ErnestRematchPostBattle:
	.string "{CHN}浅滩洞穴……\p"
	.string "有些地方能去，有些地方不能去，\n"
	.string "取决于潮水的涨落。\p"
	.string "顺便说一句，从涨潮到退潮大约\n"
	.string "需要六个小时。别忘了！$"

Route125_Text_KimIntro:
	.string "{CHN}KIM：浅滩洞穴里住着一个\n"
	.string "有趣的老爷爷。别人告诉我的。\l"
	.string "你也要去看他吗？$"

Route125_Text_KimDefeat:
	.string "{CHN}KIM：我还以为我们会赢。$"

Route125_Text_KimPostBattle:
	.string "{CHN}KIM：浅滩洞穴里住着一个\n"
	.string "有趣的老爷爷，对吧？\p"
	.string "IRIS，我们一起去看他吧！$"

Route125_Text_KimNotEnoughMons:
	.string "{CHN}KIM：不行不行不行！你需要两只宝可梦，\n"
	.string "不然可不行！$"

Route125_Text_IrisIntro:
	.string "{CHN}IRIS：KIM，你能告诉我\n"
	.string "我们在这里找什么吗？$"

Route125_Text_IrisDefeat:
	.string "{CHN}IRIS：哦，我们差一点就赢了。$"

Route125_Text_IrisPostBattle:
	.string "{CHN}IRIS：KIM，我们真的要进\n"
	.string "浅滩洞穴吗？\l"
	.string "我们会全身湿透的。$"

Route125_Text_IrisNotEnoughMons:
	.string "{CHN}IRIS：哦，我们绝对不能\n"
	.string "做那种二对一的对战。$"

Route125_Text_PresleyIntro:
	.string "{CHN}我这个捕鸟大叔为什么会\n"
	.string "跑到海上来？$"

Route125_Text_PresleyDefeat:
	.string "{CHN}好吧。\n"
	.string "我告诉你我为什么在这里。$"

Route125_Text_PresleyPostBattle:
	.string "{CHN}我把一封信装进瓶子，\n"
	.string "放到了海里。\p"
	.string "我相信一定会有个女游泳训练家\n"
	.string "捡到它！$"

Route125_Text_AuronIntro:
	.string "{CHN}嘿！是你往海里\n"
	.string "扔垃圾吗？$"

Route125_Text_AuronDefeat:
	.string "{CHN}哦，不是你往海里\n"
	.string "扔垃圾啊。$"

Route125_Text_AuronPostBattle:
	.string "{CHN}我刚才在海浪里看到一个\n"
	.string "碍眼的瓶子在漂。\p"
	.string "竟然有人污染大海，\n"
	.string "真让我生气！$"

Route126_Text_BarryIntro:
	.string "{CHN}游泳是全身运动！\n"
	.string "你会变得健壮！$"

Route126_Text_BarryDefeat:
	.string "{CHN}我承认！\n"
	.string "你赢了！$"

Route126_Text_BarryPostBattle:
	.string "{CHN}多亏了我每天游泳……\n"
	.string "看！好好欣赏这身肌肉！$"

Route126_Text_DeanIntro:
	.string "{CHN}这座高耸的白色岩石山\n"
	.string "就是琉璃市。$"

Route126_Text_DeanDefeat:
	.string "{CHN}我就这样被打败了？$"

Route126_Text_DeanPostBattle:
	.string "{CHN}我找不到琉璃市的\n"
	.string "入口。它会在哪里呢？$"

Route126_Text_NikkiIntro:
	.string "{CHN}呵呵呵呵！\n"
	.string "我是人鱼！$"

Route126_Text_NikkiDefeat:
	.string "{CHN}我的幻想像泡泡一样破灭了！\n"
	.string "咕噜，咕噜，咕噜……$"

Route126_Text_NikkiPostBattle:
	.string "{CHN}你把我打败了……我想\n"
	.string "在绝望的波浪中消失……$"

Route126_Text_BrendaIntro:
	.string "{CHN}你好，小家伙！\n"
	.string "想和我对战吗？$"

Route126_Text_BrendaDefeat:
	.string "{CHN}哦，不——！$"

Route126_Text_BrendaPostBattle:
	.string "{CHN}我喜欢像这样在大海里\n"
	.string "和宝可梦嬉戏！$"

Route126_Text_PabloIntro:
	.string "{CHN}看看这健美的身材！\n"
	.string "我比空手道王还要结实！$"

Route126_Text_PabloDefeat:
	.string "{CHN}哎呀！太强了！\n"
	.string "不错！真不错！$"

Route126_Text_PabloPostBattle:
	.string "{CHN}输给你激发了我的感官！\n"
	.string "我会更努力地训练自己和宝可梦！$"

Route126_Text_PabloRegister:
	.string "{CHN}没错，你真不错！\n"
	.string "我想多了解了解你！$"

Route126_Text_PabloRematchIntro:
	.string "{CHN}看看这美丽的身材！\n"
	.string "我比游泳训练家还要健美！$"

Route126_Text_PabloRematchDefeat:
	.string "{CHN}哎呀！真的太强了！\n"
	.string "不错！真不错！$"

Route126_Text_PabloPostRematch:
	.string "{CHN}我会更加努力地训练！\n"
	.string "你是个好动力！\l"
	.string "你一定要再来啊！$"

Route126_Text_LeonardoIntro:
	.string "{CHN}去年我还不会游泳，\n"
	.string "但现在我已经是个不错的游泳训练家了。\p"
	.string "我觉得我现在什么都能做到了。$"

Route126_Text_LeonardoDefeat:
	.string "{CHN}唉，贪心\n"
	.string "对我一点帮助都没有。$"

Route126_Text_LeonardoPostBattle:
	.string "{CHN}只要练习，\n"
	.string "你就会变得更厉害。\p"
	.string "你还年轻——不要害怕\n"
	.string "尝试各种各样的事情！$"

Route126_Text_IsobelIntro:
	.string "{CHN}如果海水进了鼻子，\n"
	.string "是不是感觉很难受？$"

Route126_Text_IsobelDefeat:
	.string "{CHN}啊！你这家伙……\n"
	.string "咕噜！$"

Route126_Text_IsobelPostBattle:
	.string "{CHN}哦，我呛到水了！\n"
	.string "好苦！好咸！！$"

Route126_Text_SiennaIntro:
	.string "{CHN}我要倾注全部心血\n"
	.string "投入这一战！$"

Route126_Text_SiennaDefeat:
	.string "{CHN}你的心血更多！$"

Route126_Text_SiennaPostBattle:
	.string "{CHN}我现在需要冷静一下……\n"
	.string "我想去潜个水。$"

Route127_Text_CamdenIntro:
	.string "{CHN}我从你脸上看得出来。\n"
	.string "你想挑战我。$"

Route127_Text_CamdenDefeat:
	.string "{CHN}哇哇哇哇哇……$"

Route127_Text_CamdenPostBattle:
	.string "{CHN}一场精彩的对战让我\n"
	.string "感到神清气爽、心平气和。$"

Route127_Text_DonnyIntro:
	.string "{CHN}你有没有那种\n"
	.string "就是不想输给他的对手？$"

Route127_Text_DonnyDefeat:
	.string "{CHN}啊啊啊！\n"
	.string "我最讨厌输了！$"

Route127_Text_DonnyPostBattle:
	.string "{CHN}有了对手，你不就会觉得\n"
	.string "必须不断变强吗？$"

Route127_Text_JonahIntro:
	.string "{CHN}通过钓鱼，我达到了\n"
	.string "一种心如止水的境界……\p"
	.string "请允许我展示一下……$"

Route127_Text_JonahDefeat:
	.string "{CHN}虽然我输了，\n"
	.string "但我的心依然平静……$"

Route127_Text_JonahPostBattle:
	.string "{CHN}钓不到鱼也无所谓。\n"
	.string "鱼线依然在水里……$"

Route127_Text_HenryIntro:
	.string "{CHN}哎呀！别告诉我我钓到了\n"
	.string "一只冲浪的宝可梦？$"

Route127_Text_HenryDefeat:
	.string "{CHN}我跟不上！$"

Route127_Text_HenryPostBattle:
	.string "{CHN}如果钓上你那只强壮的\n"
	.string "宝可梦，我可就头疼了！$"

Route127_Text_RogerIntro:
	.string "{CHN}嘿！这是一场宝可梦迷\n"
	.string "和钓鱼迷的对决！$"

Route127_Text_RogerDefeat:
	.string "{CHN}不！我的鱼线全缠在一起了！\n"
	.string "完蛋了！$"

Route127_Text_RogerPostBattle:
	.string "{CHN}我的鱼线在跳舞！\n"
	.string "缠线探戈！哈哈，乱成一团！$"

Route127_Text_AidanIntro:
	.string "{CHN}鸟宝可梦视力极佳。\n"
	.string "它们能从高处发现猎物。$"

Route127_Text_AidanDefeat:
	.string "{CHN}呼……我认输。$"

Route127_Text_AidanPostBattle:
	.string "{CHN}这附近的海里有很多\n"
	.string "潜水点。\p"
	.string "从天空很容易发现它们，\n"
	.string "因为颜色比较深。$"

Route127_Text_KojiIntro:
	.string "{CHN}光脚跑步吧。\n"
	.string "那样能锻炼你的脚底！$"

Route127_Text_KojiDefeat:
	.string "{CHN}哎哟！\n"
	.string "我脚趾甲里卡了颗石子！$"

Route127_Text_KojiPostBattle:
	.string "{CHN}光脚感觉很棒。\n"
	.string "不过你的跑步鞋也很酷。$"

Route127_Text_KojiRegister:
	.string "{CHN}这就是我对待打败我的人的方式！\n"
	.string "希望我们还能再来一次。$"

Route127_Text_KojiRematchIntro:
	.string "{CHN}我每天还是光脚跑步。\n"
	.string "我的脚底很结实！$"

Route127_Text_KojiRematchDefeat:
	.string "{CHN}哎哟！\n"
	.string "石子硌到脚心了！$"

Route127_Text_KojiPostRematch:
	.string "{CHN}要不要光脚走一会儿？\n"
	.string "好让我试试你的跑步鞋？$"

Route127_Text_AthenaIntro:
	.string "{CHN}我们应该来一场\n"
	.string "慢节奏、有条不紊的对战。$"

Route127_Text_AthenaDefeat:
	.string "{CHN}你都没给我机会\n"
	.string "制定策略。$"

Route127_Text_AthenaPostBattle:
	.string "{CHN}当我被蓝色的大海和天空\n"
	.string "包围时，感觉时间都慢了下来。$"

Route128_Text_IsaiahIntro:
	.string "{CHN}彩幽市还很\n"
	.string "远……$"

Route128_Text_IsaiahDefeat:
	.string "{CHN}我的首胜也似乎\n"
	.string "很遥远……$"

Route128_Text_IsaiahPostBattle:
	.string "{CHN}我的一生都在输，\n"
	.string "但我绝不会放弃！$"

Route128_Text_IsaiahRegister:
	.string "{CHN}我知道我现在不行，但我相信\n"
	.string "我最终能赢。\p"
	.string "请把我登记到你的宝可梦导航器里。$"

Route128_Text_IsaiahRematchIntro:
	.string "{CHN}我状态还不错。我会继续\n"
	.string "游向彩幽市。$"

Route128_Text_IsaiahRematchDefeat:
	.string "{CHN}我还没尝过胜利的滋味……$"

Route128_Text_IsaiahPostRematch:
	.string "{CHN}我最终会到达彩幽市，\n"
	.string "在那里我最终能赢……$"

Route128_Text_KatelynIntro:
	.string "{CHN}铁人三项要先游泳、骑车，\n"
	.string "然后跑马拉松。\p"
	.string "这是一项由三个项目组成的\n"
	.string "艰苦比赛。$"

Route128_Text_KatelynDefeat:
	.string "{CHN}宝可梦对战也很艰苦……$"

Route128_Text_KatelynPostBattle:
	.string "{CHN}接下来我得骑车，但是……\n"
	.string "我快撑不住了……$"

Route128_Text_KatelynRegister:
	.string "{CHN}好吧，我也得尽力而为。\n"
	.string "希望以后能再战一场。$"

Route128_Text_KatelynRematchIntro:
	.string "{CHN}铁人三项很长。但我想成为\n"
	.string "宝可梦冠军的道路也是\l"
	.string "漫长而艰辛的。$"

Route128_Text_KatelynRematchDefeat:
	.string "{CHN}宝可梦对战真是\n"
	.string "严酷无情……$"

Route128_Text_KatelynPostRematch:
	.string "{CHN}你应该认真考虑一下\n"
	.string "冠军之路上的挑战。$"

Route128_Text_AlexaIntro:
	.string "{CHN}我们一直在努力挑战\n"
	.string "宝可梦联盟……\p"
	.string "现在可不能输！$"

Route128_Text_AlexaDefeat:
	.string "{CHN}哦！\n"
	.string "怎么会这样？！$"

Route128_Text_AlexaPostBattle:
	.string "{CHN}我付出了那么多才到这里，\n"
	.string "我不会因为一次挫折就放弃。$"

Route128_Text_RubenIntro:
	.string "{CHN}没有比我更强的训练家了！$"

Route128_Text_RubenDefeat:
	.string "{CHN}这不可能！$"

Route128_Text_RubenPostBattle:
	.string "{CHN}可能没有比你更强的\n"
	.string "训练家了！$"

Route128_Text_WayneIntro:
	.string "{CHN}我想去彩幽市，所以我\n"
	.string "抓了一只会攀登瀑布的\l"
	.string "宝可梦。$"

Route128_Text_WayneDefeat:
	.string "{CHN}我心情跌落谷底！$"

Route128_Text_WaynePostBattle:
	.string "{CHN}啊，糟糕！\p"
	.string "我的宝可梦会攀登瀑布，\n"
	.string "但我没有琉璃市的道馆徽章！$"

Route128_Text_HarrisonIntro:
	.string "{CHN}你看起来相当厉害。\n"
	.string "我不知道能不能赢？$"

Route128_Text_HarrisonDefeat:
	.string "{CHN}哎哟！\n"
	.string "看来赢是不可能的了。$"

Route128_Text_HarrisonPostBattle:
	.string "{CHN}彩幽市附近到处\n"
	.string "都是厉害的训练家。\p"
	.string "你觉得我是不是\n"
	.string "不自量力？$"

Route128_Text_CarleeIntro:
	.string "{CHN}这个地区的阳光\n"
	.string "似乎更毒辣。$"

Route128_Text_CarleeDefeat:
	.string "{CHN}阳光太刺眼，\n"
	.string "我看不太清楚。$"

Route128_Text_CarleePostBattle:
	.string "{CHN}我该回去了。\n"
	.string "我得重新涂防晒霜。$"

Route129_Text_ChaseIntro:
	.string "{CHN}这是我第一次参加铁人三项。\n"
	.string "我紧张得不行！$"

Route129_Text_ChaseDefeat:
	.string "{CHN}哇啊啊啊！\n"
	.string "我没能赢！$"

Route129_Text_ChasePostBattle:
	.string "{CHN}如果我一直紧张，\n"
	.string "就没法全力以赴了。$"

Route129_Text_AllisonIntro:
	.string "{CHN}我正在参加铁人三项，\n"
	.string "不过，好吧，要不要对战？$"

Route129_Text_AllisonDefeat:
	.string "{CHN}我本以为会赢的！$"

Route129_Text_AllisonPostBattle:
	.string "{CHN}你知道铁人三项最棒的地方\n"
	.string "是什么吗？\p"
	.string "就是在大自然中\n"
	.string "测试自己力量和耐力的\l"
	.string "极限！$"

Route129_Text_ReedIntro:
	.string "{CHN}嘿，嘿！\n"
	.string "我们开始吧！$"

Route129_Text_ReedDefeat:
	.string "{CHN}完了，我输了。\n"
	.string "就这样，结束！$"

Route129_Text_ReedPostBattle:
	.string "{CHN}输家什么都没有。\n"
	.string "我该回家了。$"

Route129_Text_TishaIntro:
	.string "{CHN}急什么？\n"
	.string "我们慢慢来。$"

Route129_Text_TishaDefeat:
	.string "{CHN}哎呀。\n"
	.string "我还想再放松一会儿……$"

Route129_Text_TishaPostBattle:
	.string "{CHN}你不喜欢匆忙时\n"
	.string "犯错吗？\p"
	.string "所以我才尽量\n"
	.string "慢慢地做事。$"

Route129_Text_ClarenceIntro:
	.string "{CHN}冲浪不像看起来那么简单，\n"
	.string "对吧？$"

Route129_Text_ClarenceDefeat:
	.string "{CHN}赢可真不容易。$"

Route129_Text_ClarencePostBattle:
	.string "{CHN}你目标是宝可梦联盟？\n"
	.string "继续努力！$"

Route130_Text_RodneyIntro:
	.string "{CHN}真意外！没想到\n"
	.string "会在海上遇到训练家。\p"
	.string "我们应该对战一下！$"

Route130_Text_RodneyDefeat:
	.string "{CHN}这孩子真厉害……$"

Route130_Text_RodneyPostBattle:
	.string "{CHN}你的眼神有一种经历过\n"
	.string "严酷挑战并获胜的人才有的\l"
	.string "神采。很适合你！$"

Route130_Text_KatieIntro:
	.string "{CHN}在深蓝的大海中，\n"
	.string "我破碎的蓝色心灵在\l"
	.string "波浪中找到慰藉。$"

Route130_Text_KatieDefeat:
	.string "{CHN}就像辽阔的蓝色大海，\n"
	.string "宝可梦的世界也有着\l"
	.string "难以置信的深度。$"

Route130_Text_KatiePostBattle:
	.string "{CHN}世界各地的孩子们\n"
	.string "都梦想有一天能成为\l"
	.string "宝可梦冠军。$"

Route130_Text_SantiagoIntro:
	.string "{CHN}像这样漂浮在广阔的大海上……\n"
	.string "真宁静。$"

Route130_Text_SantiagoDefeat:
	.string "{CHN}我不该这么悠闲！$"

Route130_Text_SantiagoPostBattle:
	.string "{CHN}像这样游泳和对战……\n"
	.string "我是个幸福的男人……$"

Route131_Text_RichardIntro:
	.string "{CHN}海里满是宝可梦。\n"
	.string "我跟你说，游泳可不容易。$"

Route131_Text_RichardDefeat:
	.string "{CHN}训练家培育的宝可梦\n"
	.string "真的很强……$"

Route131_Text_RichardPostBattle:
	.string "{CHN}呼……呼……\n"
	.string "我累坏了……\p"
	.string "去的时候轻松。难的是\n"
	.string "回来的时候。\p"
	.string "我还有力气\n"
	.string "回去吗？$"

Route131_Text_HermanIntro:
	.string "{CHN}海……海……海……\n"
	.string "满眼都是海！\l"
	.string "我对海都厌烦了！$"

Route131_Text_HermanDefeat:
	.string "{CHN}呸！$"

Route131_Text_HermanPostBattle:
	.string "{CHN}我对海厌倦，却不得不游。\p"
	.string "我天生就是个游泳健将！\n"
	.string "就是这样。$"

Route131_Text_SusieIntro:
	.string "{CHN}嗨，小甜心，等等！\n"
	.string "我们俩该对战一下！$"

Route131_Text_SusieDefeat:
	.string "{CHN}别看你那样，\n"
	.string "你还真厉害！$"

Route131_Text_SusiePostBattle:
	.string "{CHN}你看到那边那个抱怨\n"
	.string "厌倦大海的家伙了吗？\p"
	.string "那都是嘴上说说。\n"
	.string "他其实爱海爱得无可救药！$"

Route131_Text_KaraIntro:
	.string "{CHN}为什么男人这么喜欢泳衣？\p"
	.string "他们全都盯着我看！$"

Route131_Text_KaraDefeat:
	.string "{CHN}我力不从心！$"

Route131_Text_KaraPostBattle:
	.string "{CHN}也许不是我的泳衣\n"
	.string "让男人盯着我看。一定是我的美貌！$"

Route131_Text_ReliIntro:
	.string "{CHN}RELI：我们会以兄妹身份\n"
	.string "联手挑战你！$"

Route131_Text_ReliDefeat:
	.string "{CHN}RELI：即使我们联手，\n"
	.string "也赢不了……$"

Route131_Text_ReliPostBattle:
	.string "{CHN}RELI：凯那吉镇的人从\n"
	.string "出生起就与大海和宝可梦\l"
	.string "相伴。$"

Route131_Text_ReliNotEnoughMons:
	.string "{CHN}RELI：你没有两只宝可梦？\n"
	.string "那我们就没法好好对战了。$"

Route131_Text_IanIntro:
	.string "{CHN}IAN：我和姐姐\n"
	.string "一起全力以赴！$"

Route131_Text_IanDefeat:
	.string "{CHN}IAN：我和姐姐尽了全力，\n"
	.string "但还是赢不了……$"

Route131_Text_IanPostBattle:
	.string "{CHN}IAN：你知道凯那吉镇是\n"
	.string "一座漂浮的小镇吧？\p"
	.string "所以，哪里有海，\n"
	.string "哪里就是凯那吉镇的一部分！$"

Route131_Text_IanNotEnoughMons:
	.string "{CHN}IAN：如果你有两只宝可梦，\n"
	.string "我们就和你对战！$"

Route131_Text_TaliaIntro:
	.string "{CHN}如果你能打败我，我就告诉你\n"
	.string "一些重要的信息！$"

Route131_Text_TaliaDefeat:
	.string "{CHN}哦？\n"
	.string "我输了吗？$"

Route131_Text_TaliaPostBattle:
	.string "{CHN}附近有个奇怪的地方。\n"
	.string "那里有一座巨大的塔。\l"
	.string "你为什么不去看看？$"

Route131_Text_KevinIntro:
	.string "{CHN}凯那吉镇的人\n"
	.string "都很平和。\p"
	.string "他们从不生气。\n"
	.string "我也是如此。$"

Route131_Text_KevinDefeat:
	.string "{CHN}哎呀！$"

Route131_Text_KevinPostBattle:
	.string "{CHN}啧！……哦，等等。\n"
	.string "我没生气。真的！\p"
	.string "不过，哇，你真强！\n"
	.string "哈哈哈！$"

Route132_Text_GilbertIntro:
	.string "{CHN}我小时候总是感冒，\n"
	.string "但开始游泳后身体完全变好了。$"

Route132_Text_GilbertDefeat:
	.string "{CHN}我渴望更强的力量……$"

Route132_Text_GilbertPostBattle:
	.string "{CHN}训练家们走遍原野和\n"
	.string "山脉，所以他们身体也一定很好。$"

Route132_Text_DanaIntro:
	.string "{CHN}我尽量不在水流\n"
	.string "太急的地方游泳。$"

Route132_Text_DanaDefeat:
	.string "{CHN}哦，不要啊！$"

Route132_Text_DanaPostBattle:
	.string "{CHN}如果被冲走了，\n"
	.string "我就完全不知道自己在哪了……$"

Route132_Text_RonaldIntro:
	.string "{CHN}输还是赢，不试\n"
	.string "怎么知道！$"

Route132_Text_RonaldDefeat:
	.string "{CHN}哇啊！\n"
	.string "我沉到失败了！$"

Route132_Text_RonaldPostBattle:
	.string "{CHN}我从不在知道会赢的时候对战。\n"
	.string "我喜欢在胜负一线之间\l"
	.string "进行对战！$"

Route132_Text_KiyoIntro:
	.string "{CHN}我一天24小时都在思考宝可梦。\n"
	.string "你怎么可能打败我？$"

Route132_Text_KiyoDefeat:
	.string "{CHN}我输了。\n"
	.string "我认输。$"

Route132_Text_KiyoPostBattle:
	.string "{CHN}呃……\n"
	.string "你是个宝可梦狂热者吧？\p"
	.string "你一定也是一天24小时\n"
	.string "都在思考宝可梦吧？$"

Route132_Text_MakaylaIntro:
	.string "{CHN}我总是和丈夫在一起，\n"
	.string "但即使没有他我也能赢。$"

Route132_Text_MakaylaDefeat:
	.string "{CHN}哦，看来我还不够强。$"

Route132_Text_MakaylaPostBattle:
	.string "{CHN}那边那个年轻人看起来\n"
	.string "就像我丈夫年轻时一样。\p"
	.string "看得我脸红！$"

Route132_Text_JonathanIntro:
	.string "{CHN}有人一直在盯着我看。\n"
	.string "是你吗？$"

Route132_Text_JonathanDefeat:
	.string "{CHN}哇！\n"
	.string "你确实很强！$"

Route132_Text_JonathanPostBattle:
	.string "{CHN}我总觉得\n"
	.string "有人在看着我。\p"
	.string "我无法集中精力！$"

Route132_Text_PaxtonIntro:
	.string "{CHN}我妻子去哪了呢？\n"
	.string "我总是和她在一起。\l"
	.string "不知道我一个人能不能赢。$"

Route132_Text_PaxtonDefeat:
	.string "{CHN}唉，看来我果然\n"
	.string "一个人赢不了。$"

Route132_Text_PaxtonPostBattle:
	.string "{CHN}我妻子一定在找我。\n"
	.string "我得赶紧去找她。$"

Route132_Text_DarcyIntro:
	.string "{CHN}我喜欢一个人在这里训练。\n"
	.string "这些人都来真是糟糕！$"

Route132_Text_DarcyDefeat:
	.string "{CHN}好吧！我不再抱怨\n"
	.string "别人在这里了。$"

Route132_Text_DarcyPostBattle:
	.string "{CHN}我想我可以和那个\n"
	.string "老大爷组队，挑战另一支队伍。$"

Route133_Text_FranklinIntro:
	.string "{CHN}你也是被水流冲到这里的吗？\n"
	.string "这一定是缘分。\l"
	.string "我们对战吧！$"

Route133_Text_FranklinDefeat:
	.string "{CHN}强！\n"
	.string "太强了！$"

Route133_Text_FranklinPostBattle:
	.string "{CHN}像你这么强的训练家\n"
	.string "竟然会漂到这里……\l"
	.string "我一定倒霉透顶……$"

Route133_Text_DebraIntro:
	.string "{CHN}我过着悲惨痛苦的一生……\n"
	.string "我被抛弃了，\l"
	.string "漂流到了这里……$"

Route133_Text_DebraDefeat:
	.string "{CHN}又输了……$"

Route133_Text_DebraPostBattle:
	.string "{CHN}漂泊的一生……\n"
	.string "我不想再这样了！$"

Route133_Text_LindaIntro:
	.string "{CHN}欢迎！\n"
	.string "我一直在等你！$"

Route133_Text_LindaDefeat:
	.string "{CHN}不！求你！$"

Route133_Text_LindaPostBattle:
	.string "{CHN}一个强大的小孩训练家……\n"
	.string "真烦人！$"

Route133_Text_WarrenIntro:
	.string "{CHN}我想像其他人一样赢，但我\n"
	.string "不会像其他人那样培育宝可梦。$"

Route133_Text_WarrenDefeat:
	.string "{CHN}可恶！\n"
	.string "我的方法还是太松懈了！$"

Route133_Text_WarrenPostBattle:
	.string "{CHN}按自己的方式做事比\n"
	.string "随波逐流要有趣得多。\l"
	.string "这不是明摆着的嘛！$"

Route133_Text_BeckIntro:
	.string "{CHN}我带着我的\n"
	.string "鸟宝可梦大老远来到这里。$"

Route133_Text_BeckDefeat:
	.string "{CHN}你……\n"
	.string "你帅呆了！$"

Route133_Text_BeckPostBattle:
	.string "{CHN}我想回茵郁市，\n"
	.string "但我也渐渐喜欢上这里了。$"

Route133_Text_MollieIntro:
	.string "{CHN}我大概对战过几千次了。\n"
	.string "都数不清了。$"

Route133_Text_MollieDefeat:
	.string "{CHN}我可能已经输了几千次了，\n"
	.string "但失败还是让人心痛。$"

Route133_Text_MolliePostBattle:
	.string "{CHN}继续努力吧，年轻人。这样你\n"
	.string "就能变得像我和我丈夫一样。$"

Route133_Text_ConorIntro:
	.string "{CHN}年轻人太容易随波逐流。\n"
	.string "他们没有方向。$"

Route133_Text_ConorDefeat:
	.string "{CHN}你有坚定的目标。$"

Route133_Text_ConorPostBattle:
	.string "{CHN}不要让别人带你走上歧途。\n"
	.string "长大后也不要迷失方向。$"

Route134_Text_JackIntro:
	.string "{CHN}即使是会游泳的宝可梦\n"
	.string "也会被急流冲走。$"

Route134_Text_JackDefeat:
	.string "{CHN}哎呀呀呀！$"

Route134_Text_JackPostBattle:
	.string "{CHN}我觉得宝可梦喜欢\n"
	.string "这一带湍急的水流。$"

Route134_Text_LaurelIntro:
	.string "{CHN}我的爱心鱼在找一场\n"
	.string "有趣的对战。你要加入吗？$"

Route134_Text_LaurelDefeat:
	.string "{CHN}哎呀！$"

Route134_Text_LaurelPostBattle:
	.string "{CHN}有个收藏家\n"
	.string "想要爱心鱼的鳞片。$"

Route134_Text_AlexIntro:
	.string "{CHN}好嘞！休息够了，伙计们！\n"
	.string "该对战了！$"

Route134_Text_AlexDefeat:
	.string "{CHN}又累趴了……$"

Route134_Text_AlexPostBattle:
	.string "{CHN}我的鸟宝可梦长途\n"
	.string "飞行后很快就会累……$"

Route134_Text_HitoshiIntro:
	.string "{CHN}你是宝可梦训练家。\n"
	.string "不必废话。我们对战吧。$"

Route134_Text_HitoshiDefeat:
	.string "{CHN}…… …… …… …… ……\n"
	.string "…… …… …… …… ……$"

Route134_Text_HitoshiPostBattle:
	.string "{CHN}是我挑战你，却\n"
	.string "输了。我深感羞愧……$"

Route134_Text_AaronIntro:
	.string "{CHN}这一带凶猛的潮水\n"
	.string "能让我们变得更强。$"

Route134_Text_AaronDefeat:
	.string "{CHN}我心甘情愿认输。$"

Route134_Text_AaronPostBattle:
	.string "{CHN}我们会回流星瀑布\n"
	.string "继续训练。\p"
	.string "如果你愿意，你也该去。\n"
	.string "那里绝对能让你变强！$"

Route134_Text_KelvinIntro:
	.string "{CHN}我、我们的船！\n"
	.string "被潮水冲走了！$"

Route134_Text_KelvinDefeat:
	.string "{CHN}哇哇哇哇！\n"
	.string "求求你，停下！求求你！$"

Route134_Text_KelvinPostBattle:
	.string "{CHN}如果不能冲浪，我们怎么\n"
	.string "回家？\p"
	.string "其实我知道昏倒的宝可梦\n"
	.string "也能冲浪，但感觉不太对。$"

Route134_Text_MarleyIntro:
	.string "{CHN}你的宝可梦能躲过\n"
	.string "我们闪电般的攻击吗？$"

Route134_Text_MarleyDefeat:
	.string "{CHN}我从不知道有这样的技巧！\n"
	.string "你彻底打败了我们。$"

Route134_Text_MarleyPostBattle:
	.string "{CHN}我没有失去对速度的热情。\n"
	.string "我会更努力。$"

Route134_Text_ReynaIntro:
	.string "{CHN}我的宝可梦可不会\n"
	.string "轻易被打倒！$"

Route134_Text_ReynaDefeat:
	.string "{CHN}开玩笑吧！\n"
	.string "解释一下我怎么输的！$"

Route134_Text_ReynaPostBattle:
	.string "{CHN}哈哈！\n"
	.string "你赢了，没错！\p"
	.string "我会通过挑战遇到的\n"
	.string "训练家重新爬上来！$"

Route134_Text_HudsonIntro:
	.string "{CHN}听着，你在这附近见过\n"
	.string "其他水手吗？$"

Route134_Text_HudsonDefeat:
	.string "{CHN}厉害，真厉害！$"

Route134_Text_HudsonPostBattle:
	.string "{CHN}我们的船漂到海里去了。\p"
	.string "我那伙伴是个胆小的家伙，\n"
	.string "所以我挺担心他。$"






