gTrickHouse_Mechadoll_Oddish::
	.string "{CHN}走路草$"

gTrickHouse_Mechadoll_Poochyena::
	.string "{CHN}土狼犬$"

gTrickHouse_Mechadoll_Taillow::
	.string "{CHN}傲骨燕$"

gTrickHouse_Mechadoll_Azurill::
	.string "{CHN}露力丽$"

gTrickHouse_Mechadoll_Lotad::
	.string "{CHN}莲叶童子$"

gTrickHouse_Mechadoll_Wingull::
	.string "{CHN}长翅鸥$"

gTrickHouse_Mechadoll_Dustox::
	.string "{CHN}毒粉蛾$"

gTrickHouse_Mechadoll_Zubat::
	.string "{CHN}超音蝠$"

gTrickHouse_Mechadoll_Nincada::
	.string "{CHN}土居忍士$"

gTrickHouse_Mechadoll_Ralts::
	.string "{CHN}拉鲁拉丝$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "{CHN}蛇纹熊$"

gTrickHouse_Mechadoll_Slakoth::
	.string "{CHN}懒人獭$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "{CHN}土狼犬$"

gTrickHouse_Mechadoll_Shroomish::
	.string "{CHN}蘑蘑菇$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "{CHN}蛇纹熊$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "{CHN}土狼犬$"

gTrickHouse_Mechadoll_Zubat2::
	.string "{CHN}超音蝠$"

gTrickHouse_Mechadoll_Carvanha::
	.string "{CHN}利牙鱼$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "{CHN}烧伤药$"

gTrickHouse_Mechadoll_HarborMail::
	.string "{CHN}港口邮件$"

gTrickHouse_Mechadoll_SamePrice::
	.string "{CHN}价格相同$"

gTrickHouse_Mechadoll_60Yen::
	.string "{CHN}¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "{CHN}¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "{CHN}无$"

gTrickHouse_Mechadoll_CostMore::
	.string "{CHN}价格会更高。$"

gTrickHouse_Mechadoll_CostLess::
	.string "{CHN}价格会更低。$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "{CHN}价格相同$"

gTrickHouse_Mechadoll_Male::
	.string "{CHN}雄性$"

gTrickHouse_Mechadoll_Female::
	.string "{CHN}雌性$"

gTrickHouse_Mechadoll_Neither::
	.string "{CHN}都不是$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "{CHN}老爷爷$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "{CHN}老奶奶$"

gTrickHouse_Mechadoll_SameNumber::
	.string "{CHN}数量相同$"

gTrickHouse_Mechadoll_None::
	.string "{CHN}没有$"

gTrickHouse_Mechadoll_One::
	.string "{CHN}1$"

gTrickHouse_Mechadoll_Two::
	.string "{CHN}2$"

gTrickHouse_Mechadoll_Two2::
	.string "{CHN}2$"

gTrickHouse_Mechadoll_Three::
	.string "{CHN}3$"

gTrickHouse_Mechadoll_Four::
	.string "{CHN}4$"

gTrickHouse_Mechadoll_Six::
	.string "{CHN}6$"

gTrickHouse_Mechadoll_Seven::
	.string "{CHN}7$"

gTrickHouse_Mechadoll_Eight::
	.string "{CHN}8$"

gTrickHouse_Mechadoll_Six2::
	.string "{CHN}6$"

gTrickHouse_Mechadoll_Seven2::
	.string "{CHN}7$"

gTrickHouse_Mechadoll_Eight2::
	.string "{CHN}8$"
