LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "{CHN}哦，你好！你刚才参加了宝可梦\n"
	.string "选拔赛，对吧？\l"
	.string "从你的宝可梦身上很容易看出来。\p"
	.string "我是记者。我正在做一篇关于\n"
	.string "宝可梦选拔赛的报道。\p"
	.string "如果可以的话，你愿意回答\n"
	.string "几个问题吗？$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "{CHN}哦，你愿意？\n"
	.string "谢谢你。\p"
	.string "请简要描述一下，你刚才参加的\n"
	.string "这场选拔赛是怎样的？$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "{CHN}啊，我明白了。\n"
	.string "这个评论很有启发。\p"
	.string "让人能很好地感受到\n"
	.string "这场选拔赛的氛围。\p"
	.string "我还有最后一个问题。\p"
	.string "当你听到“{STR_VAR_2}”这个词时，\n"
	.string "脑海中会浮现什么形象？$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "{CHN}我明白了！\p"
	.string "原来这就是你对“{STR_VAR_2}”\n"
	.string "这个概念的理解啊。\p"
	.string "谢谢你！\n"
	.string "你给了我不少灵感。\p"
	.string "我想我现在可以写出一篇关于\n"
	.string "宝可梦选拔赛的好报道了。\p"
	.string "也许，只是也许，这篇报道还能\n"
	.string "登上电视节目。\l"
	.string "敬请期待！$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "{CHN}哦，太可惜了……\p"
	.string "嗯，如果你遇到有趣的故事，\n"
	.string "请务必告诉我。$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "{CHN}我会期待你的下一场\n"
	.string "宝可梦选拔赛。$"

gTVBravoTrainerText00::
	.string "{CHN}好耶！\n"
	.string "这里是「训练家风采」时间！\p"
	.string "今天，我们要介绍的是\n"
	.string "{STR_VAR_1}的一只宝可梦。\p"
	.string "这只宝可梦在{STR_VAR_2}类别中\n"
	.string "获得了{STR_VAR_3}级的等级。$"

gTVBravoTrainerText01::
	.string "{CHN}请欢迎{STR_VAR_2}——\n"
	.string "一只{STR_VAR_1}！\p"
	.string "昵称{STR_VAR_2}……\p"
	.string "光是这个昵称，就散发着\n"
	.string "一种“{STR_VAR_3}”的气质！$"

gTVBravoTrainerText02::
	.string "{CHN}总之，当训练家{STR_VAR_1}\n"
	.string "带着这只宝可梦参加选拔赛时，\l"
	.string "我们设法从这位训练家口中\l"
	.string "听到了几句对这位搭档的热情评价。$"

gTVBravoTrainerText03::
	.string "{CHN}赛后当我们问及这场选拔赛时，\n"
	.string "{STR_VAR_1}咧着嘴笑，开心地\l"
	.string "回答：“{STR_VAR_2}！”\p"
	.string "嗯，毕竟{STR_VAR_1}的宝可梦在\n"
	.string "这场选拔赛中取得了第{STR_VAR_3}名。\p"
	.string "这句话完全符合{STR_VAR_1}\n"
	.string "现在的心境，我说得对吧！$"

gTVBravoTrainerText04::
	.string "{CHN}赛后当我们问及这场选拔赛时，\n"
	.string "{STR_VAR_1}带着一丝苦涩\l"
	.string "回答：“{STR_VAR_2}。”\p"
	.string "嗯，毕竟{STR_VAR_1}的宝可梦在\n"
	.string "这场选拔赛中只取得了第{STR_VAR_3}名。\p"
	.string "{STR_VAR_1}的失望之情\n"
	.string "溢于言表，我说得对吧！$"

gTVBravoTrainerText05::
	.string "{CHN}难道你不想知道\n"
	.string "{STR_VAR_1}对“{STR_VAR_2}”的理解吗？\p"
	.string "我们当然也想知道！\n"
	.string "所以我们就去问了！\p"
	.string "答案精炼如下：\n"
	.string "“{STR_VAR_3}！”\p"
	.string "这就是{STR_VAR_2}这个概念\n"
	.string "对{STR_VAR_1}的意义！$"

gTVBravoTrainerText06::
	.string "{CHN}这只{STR_VAR_1}最后使出的招式\n"
	.string "{STR_VAR_2}，\l"
	.string "完全体现了“{STR_VAR_3}”！$"

gTVBravoTrainerText07::
	.string "{CHN}好样的，{STR_VAR_1}！\n"
	.string "好样的，{STR_VAR_2}！\p"
	.string "希望{STR_VAR_1}今后\n"
	.string "能攀登更高的巅峰！\p"
	.string "今天的节目就到这里！\n"
	.string "我们下次再见！$"

gTVBravoTrainerText08::
	.string "{CHN}请欢迎这位训练家的{STR_VAR_1}！$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "{CHN}你好！你就是刚才战斗的\n"
	.string "那位训练家，对吧？\p"
	.string "我正在到处收集\n"
	.string "训练家们的采访。\p"
	.string "能否请你谈几句\n"
	.string "对战斗的感想？$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "{CHN}你愿意？真的？\n"
	.string "谢谢你！\l"
	.string "那么，呃……\p"
	.string "你今天在对战金字塔\n"
	.string "的战况如何？\p"
	.string "你对战斗满意吗？\n"
	.string "还是不太满意？$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "{CHN}哦……\n"
	.string "抱歉打扰你了。\p"
	.string "下次再来对战金字塔时，\n"
	.string "请务必接受我们的采访。$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "{CHN}当然啦！\p"
	.string "你脸上那难以掩饰的\n"
	.string "满足表情……\p"
	.string "显然你刚才经历了一场\n"
	.string "精彩的战斗。$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "{CHN}哦，我明白了……\p"
	.string "能让战斗完全按照计划进行，\n"
	.string "确实不是一件容易的事。$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "{CHN}哦，哦，我能再问一个问题吗？\p"
	.string "如果要用一句话来\n"
	.string "形容你对这场战斗的\l"
	.string "感想，你会怎么说？$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "{CHN}哦，太酷了！\p"
	.string "这句话真棒！\n"
	.string "希望你下次也能有出色表现。\p"
	.string "希望能再见到你！$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "{CHN}哦，我明白了……\p"
	.string "不过，沉默寡言也是一种\n"
	.string "帅气，不是吗？\p"
	.string "希望能再有机会\n"
	.string "听听你的想法！$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "{CHN}我会期待你的\n"
	.string "下一场战斗！$"

BravoTrainerBattleTower_Text_Intro::
	.string "{CHN}好耶！\n"
	.string "这里是「训练家风采」时间！\p"
	.string "今天，我们要介绍的是挑战了\n"
	.string "对战金字塔的{STR_VAR_1}！\p"
	.string "在这次挑战中，{STR_VAR_1}派出了\n"
	.string "一只厉害的{STR_VAR_2}。$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "{CHN}这对组合在{STR_VAR_1}赛中\n"
	.string "创下了连胜{STR_VAR_2}场的新纪录！\l"
	.string "好样的，训练家！$"

BravoTrainerBattleTower_Text_Lost::
	.string "{CHN}这对组合在第{STR_VAR_2}场\n"
	.string "输给了{STR_VAR_1}。\l"
	.string "虽败犹荣，训练家！\p"
	.string "不过，在挑战初期就遇到{STR_VAR_1}\n"
	.string "确实运气不太好。\p"
	.string "我们采访了这位训练家\n"
	.string "对与{STR_VAR_1}对战的感想。$"

BravoTrainerBattleTower_Text_Won::
	.string "{CHN}这对组合彻底击败了\n"
	.string "{STR_VAR_1}的{STR_VAR_2}，赢得了全部胜利。\l"
	.string "好样的，训练家！\p"
	.string "居然能击败{STR_VAR_1}……\n"
	.string "简直难以置信！太惊人了！\p"
	.string "我们采访了这位训练家\n"
	.string "对荣耀时刻的感想。$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "{CHN}在连胜之后，这对组合最终\n"
	.string "败给了{STR_VAR_1}的{STR_VAR_2}，\l"
	.string "这是他们最后的难关。\p"
	.string "虽败犹荣，训练家！\p"
	.string "不过，确实值得敬佩。\n"
	.string "像{STR_VAR_1}和{STR_VAR_2}这样的\l"
	.string "著名组合可不多见。\p"
	.string "我们采访了这位训练家\n"
	.string "对与这对名人组合对战的感想。$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "{CHN}这位训练家这么说：\n"
	.string "“我很满意！”\p"
	.string "这回答真是令人耳目一新？\n"
	.string "好样的，训练家！\p"
	.string "能够战斗到完全满意的程度，\n"
	.string "这难道不是太棒了吗？\p"
	.string "当我听到训练家说出这句话时，\n"
	.string "我才真正体会到那份满足：$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "{CHN}这位训练家这么说：\n"
	.string "“我不满意……”\p"
	.string "我们的训练家说出这句话时，\n"
	.string "显然有些失落。\p"
	.string "不过，想要战斗到完全满意的程度\n"
	.string "可不容易，对吧？\p"
	.string "总之，当我听到下面这句话时，\n"
	.string "我才真正体会到训练家的不满：$"

BravoTrainerBattleTower_Text_None1::
	.string "{CHN}无$"

BravoTrainerBattleTower_Text_None2::
	.string "{CHN}无$"

BravoTrainerBattleTower_Text_None3::
	.string "{CHN}无$"

BravoTrainerBattleTower_Text_None4::
	.string "{CHN}无$"

BravoTrainerBattleTower_Text_Response::
	.string "{CHN}“{STR_VAR_1}。”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "{CHN}“{STR_VAR_1}。”\n"
	.string "这不是很棒吗？\p"
	.string "我可以说，这充分表达了\n"
	.string "{STR_VAR_2}的喜悦。\p"
	.string "最后与{STR_VAR_3}的那场战斗……\n"
	.string "那确实就是所谓的\l"
	.string "“{STR_VAR_1}”！$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "{CHN}“{STR_VAR_1}。”\n"
	.string "这不是很贴切吗？\p"
	.string "最后与{STR_VAR_3}的那场战斗……\n"
	.string "除了“{STR_VAR_1}”之外，\l"
	.string "再也无法用其他词语来形容！\p"
	.string "{STR_VAR_2}的失望之情\n"
	.string "溢于言表，我说得对吧！$"

BravoTrainerBattleTower_Text_Outro::
	.string "{CHN}好样的，{STR_VAR_1}！\n"
	.string "好样的，{STR_VAR_2}！\p"
	.string "希望{STR_VAR_1}今后\n"
	.string "能攀登更高的巅峰！\p"
	.string "今天的节目就到这里！\n"
	.string "我们下次再见！$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "{CHN}哇！\p"
	.string "看得出来，你对你的\n"
	.string "{STR_VAR_1}真是宠爱有加。\p"
	.string "好，它叫{STR_VAR_2}。\p"
	.string "我能请你帮个忙吗？\p"
	.string "我是电视记者，正在做一项\n"
	.string "关于宝可梦的调查。\p"
	.string "你愿意回答几个\n"
	.string "简单的问题吗？$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "{CHN}太好了！谢谢你！\p"
	.string "好，开始吧。\n"
	.string "我只需要简短的回答，可以吗？$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "{CHN}当你第一次遇见{STR_VAR_1}时，\n"
	.string "你有什么感觉？\p"
	.string "你会如何形容\n"
	.string "当时的感受？$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "{CHN}你的{STR_VAR_1}被照顾得无微不至。\p"
	.string "如果要把比作你\n"
	.string "喜欢的东西，会是什么呢？$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "{CHN}这个问题也和你心爱的\n"
	.string "{STR_VAR_1}有关。\p"
	.string "{STR_VAR_1}身上有什么\n"
	.string "吸引了你？$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "{CHN}好，我明白了。\p"
	.string "下一个问题可能\n"
	.string "有点难回答。\p"
	.string "来了……\p"
	.string "宝可梦对你来说意味着什么？$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "{CHN}我明白了！\p"
	.string "嗯嗯……\p"
	.string "好！\n"
	.string "谢谢你帮我这个忙。\p"
	.string "和你聊天既有趣\n"
	.string "又让我学到不少。\p"
	.string "我们的采访有可能\n"
	.string "会登上电视。记得收看哦！\p"
	.string "好，就到这里。\n"
	.string "再见！$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "{CHN}哦，好的……\p"
	.string "嗯，如果你想和我聊聊\n"
	.string "关于宝可梦的事，我会在这里！$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "{CHN}我喜欢这份工作——通过采访\n"
	.string "可以了解到关于宝可梦的各种事。$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "{CHN}嗨，你看起来和你的\n"
	.string "{STR_VAR_1}感情很好。\p"
	.string "你知道吗？\n"
	.string "我是电视记者。\p"
	.string "我四处旅行，采访人们\n"
	.string "关于宝可梦的事。\p"
	.string "我在想，你愿意和我聊聊\n"
	.string "你的{STR_VAR_1}吗？$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "{CHN}哇，谢谢你！\p"
	.string "好，那么，请告诉我任何\n"
	.string "关于你的{STR_VAR_1}的事吧。$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "{CHN}哇……\n"
	.string "这个故事真有趣。\p"
	.string "你和{STR_VAR_1}的感情真好，\n"
	.string "对吧？\p"
	.string "我觉得你的故事\n"
	.string "会成为一篇很棒的电视报道。\p"
	.string "我保证会把它做成\n"
	.string "一档有趣的节目。\l"
	.string "敬请期待。\p"
	.string "好，就到这里。\n"
	.string "再见！$"

gTVFanClubOpinionsText00::
	.string "{CHN}我们是宝可梦同好会！\p"
	.string "节目开始啦！\p"
	.string "在这档节目中，我们会收集你的意见，\n"
	.string "然后由我代你大声喊出来！\l"
	.string "这节目概念是不是很棒？\p"
	.string "今天，我们带来了这篇报道，\n"
	.string "来自我们派往宝可梦同好会\l"
	.string "的记者。\p"
	.string "那么，今天的主角\n"
	.string "宝可梦爱好者是谁呢？\p"
	.string "…… …… …… …… …… …… …… …\p"
	.string "{STR_VAR_1}！\p"
	.string "让我们听听{STR_VAR_1}对\n"
	.string "{STR_VAR_2}这只{STR_VAR_3}有什么要说。\p"
	.string "然后，我会把这些爱的话语\n"
	.string "在电视上大声喊出来！\p"
	.string "嘿嘿哈！\p"
	.string "一起喊吧！$"

gTVFanClubOpinionsText01::
	.string "{CHN}我们问了{STR_VAR_1}：“当你第一次\n"
	.string "看到你的{STR_VAR_2}时，\l"
	.string "最初的想法是什么？”\p"
	.string "“{STR_VAR_3}！”\p"
	.string "耶哈！这喊得真响亮！\p"
	.string "是不是让人回想起\n"
	.string "那些逝去的岁月？$"

gTVFanClubOpinionsText02::
	.string "{CHN}我们问了{STR_VAR_1}：“如果要把\n"
	.string "你的{STR_VAR_2}比作什么，\l"
	.string "会是什么……”\p"
	.string "…… …… …… …… …… …… …\p"
	.string "“{STR_VAR_3}！”\p"
	.string "哇哦，这个想法真独特！\p"
	.string "你能真切地感受到训练家\n"
	.string "对{STR_VAR_2}\l"
	.string "的那份热烈情感。$"

gTVFanClubOpinionsText03::
	.string "{CHN}那么让我们看看……\n"
	.string "是什么吸引了{STR_VAR_1}\l"
	.string "注意到这只{STR_VAR_2}？\p"
	.string "…… …… …… …… …… …… …\p"
	.string "“{STR_VAR_3}！”\p"
	.string "哇！多么精彩的宣言！\p"
	.string "训练家对{STR_VAR_2}的爱\n"
	.string "溢于言表！$"

gTVFanClubOpinionsText04::
	.string "{CHN}嗯？哦，还有更多。\n"
	.string "让我们看看！\p"
	.string "让我想想……\p"
	.string "我们问了{STR_VAR_1}：“宝可梦\n"
	.string "对你意味着什么？”\p"
	.string "…… …… …… …… …… …\p"
	.string "“{STR_VAR_3}！”\p"
	.string "好极了！\p"
	.string "这是我今天听到的最棒的呐喊！\p"
	.string "“{STR_VAR_3}！”\p"
	.string "让人忍不住想一遍\n"
	.string "又一遍地大声喊出来！\p"
	.string "既然我们已经痛快地喊过了，\n"
	.string "也是时候说再见，期待下次了！\p"
	.string "那么，让我们最后再喊一次！\n"
	.string "大家一起……\p"
	.string "“{STR_VAR_3}！”$"

gTVFanClubText00::
	.string "{CHN}我们是宝可梦同好会！\p"
	.string "节目开始啦！\p"
	.string "今天，我们从宝可梦\n"
	.string "调查角开始。\p"
	.string "在宝可梦和训练家们编织的\n"
	.string "无数故事中，今天会有什么\l"
	.string "惊人的新剧情吸引我们？\p"
	.string "让我看看……\p"
	.string "就这个！\p"
	.string "从这封信开始！\p"
	.string "这是{STR_VAR_1}写来的信，\n"
	.string "关于一只心爱的{STR_VAR_2}。\p"
	.string "让我们看看我们的来信者\n"
	.string "能多么热情地表达对{STR_VAR_2}的爱！\l"
	.string "嗯嗯……$"

gTVFanClubText01::
	.string "{CHN}哇！\n"
	.string "真是封精彩的信！$"

gTVFanClubText02::
	.string "{CHN}我太喜欢了，所以再读一遍！$"

gTVFanClubText03::
	.string "{CHN}一封好信值得\n"
	.string "反复阅读！$"

gTVFanClubText04::
	.string "{CHN}特别是“{STR_VAR_3}”那部分，\n"
	.string "真增强了情感冲击！\p"
	.string "这是一封充满\n"
	.string "真情实感的好信！$"

gTVFanClubText05::
	.string "{CHN}尤其是“{STR_VAR_3}”那部分！\p"
	.string "我喜欢“{STR_VAR_3}”的用法！$"

gTVFanClubText06::
	.string "{CHN}顺便一提，这不重要，\n"
	.string "但“{STR_VAR_3}”是句好话。\p"
	.string "我最近在聊天时\n"
	.string "经常用“{STR_VAR_3}”。$"

gTVFanClubText07::
	.string "{CHN}如果要我给这封信打分，\n"
	.string "我会给{STR_VAR_3}分。\p"
	.string "下次，我会期待{STR_VAR_1}\n"
	.string "写出更好的信！\p"
	.string "哎呀，你看时间？\n"
	.string "是时候说再见，期待下次了！$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "{CHN}哦？\n"
	.string "你或许喜欢宝可梦？\p"
	.string "我是电视台的特派记者。\p"
	.string "我正在收集最近发生的\n"
	.string "关于宝可梦和训练家的故事。\p"
	.string "如果不介意的话，\n"
	.string "你能告诉我一些关于你自己的事吗？$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "{CHN}我正在收集最近发生的\n"
	.string "关于宝可梦和训练家的故事。\p"
	.string "如果不介意的话，\n"
	.string "你能告诉我一些关于你自己的事吗？$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "{CHN}哦，你愿意？\n"
	.string "谢谢你！\p"
	.string "那么，请告诉我你最近\n"
	.string "经历的任何有趣的\l"
	.string "与宝可梦有关的事。$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "{CHN}哦，我明白了……\p"
	.string "嗯，如果你有什么有趣的故事，\n"
	.string "请告诉我。$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "{CHN}哦，真是个振奋人心的故事！\p"
	.string "我一定会把你的故事\n"
	.string "搬上电视。\p"
	.string "应该会在某个时候播出，\n"
	.string "敬请期待。$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "{CHN}嗯……\n"
	.string "我有了一个很好的电视节目素材。\p"
	.string "得赶快写出来！$"

gTVRecentHappeningsText00::
	.string "{CHN}你好，这里是「近期见闻」时间。\p"
	.string "对于宝可梦训练家来说，每一天\n"
	.string "都是一段故事。\p"
	.string "我们想为你介绍一些\n"
	.string "这样的宝可梦故事。\p"
	.string "今天，我们带来的是\n"
	.string "训练家{STR_VAR_1}的故事。\p"
	.string "{STR_VAR_1}最近经历了什么？\n"
	.string "让我们一探究竟。\p"
	.string "让我看看……$"

gTVRecentHappeningsText01::
	.string "{CHN}是不是很有启发？\p"
	.string "这个故事清楚地展现了\n"
	.string "{STR_VAR_1}最近的经历。\l"
	.string "仿佛我们就在现场亲眼目睹一样！$"

gTVRecentHappeningsText02::
	.string "{CHN}“{STR_VAR_3}。”这\n"
	.string "为故事增添了深度。$"

gTVRecentHappeningsText03::
	.string "{CHN}“{STR_VAR_3}。”\n"
	.string "这给故事带来了现场感。\l"
	.string "让我们能想象出故事发生的场景。$"

gTVRecentHappeningsText04::
	.string "{CHN}故事中“{STR_VAR_3}”\n"
	.string "这部分非常有表现力。$"

gTVRecentHappeningsText05::
	.string "{CHN}{STR_VAR_1}讲述了一个\n"
	.string "精彩的关于宝可梦的故事。\p"
	.string "现在{STR_VAR_1}的故事也已经\n"
	.string "深深地印在了你的灵魂里。\p"
	.string "今天的节目就到这里。\n"
	.string "请下次继续收看。$"

gTVMassOutbreakText00::
	.string "{CHN}大家好！\n"
	.string "这里是宝可梦新闻时间。\p"
	.string "我们刚刚收到消息，\n"
	.string "发生了一件非常罕见的事。\p"
	.string "有报道称，在{STR_VAR_1}附近\n"
	.string "发生了{STR_VAR_2}的大量出现。\l"
	.string "\p"
	.string "{STR_VAR_2}，你或许知道，\n"
	.string "是一种稀有且\l"
	.string "难以发现的宝可梦。\p"
	.string "这看起来是个难得的机会，\n"
	.string "可以看到{STR_VAR_2}\l"
	.string "在野外的神秘爆发。\p"
	.string "以上就是宝可梦新闻的报道。$"

gTV3CheersForPokeblocksText00::
	.string "{CHN}主持人：希望大家心情愉快，\n"
	.string "「为方块欢呼3次」开始了！\p"
	.string "今天，我们要品鉴的是\n"
	.string "由{STR_VAR_1}和伙伴们制作的方块。\p"
	.string "事不宜迟，让我把它\n"
	.string "喂给我那位美食家宝可梦吞球兽。\p"
	.string "…… …… …… …… …\n"
	.string "…… …… …… …… …$"

gTV3CheersForPokeblocksText01::
	.string "{CHN}吞球兽：咕比！咕比比！\p"
	.string "主持人：评判结果是「{STR_VAR_1}」！\n"
	.string "吞球兽说味道是“{STR_VAR_2}！”\p"
	.string "非常感谢你，{STR_VAR_3}！$"

gTV3CheersForPokeblocksText02::
	.string "{CHN}{STR_VAR_1}的制作表现\n"
	.string "还有待提高。\p"
	.string "如果这位训练家能做得更好，\n"
	.string "方块的味道会更美味。$"

gTV3CheersForPokeblocksText03::
	.string "{CHN}吞球兽：咕比！咕比比！\p"
	.string "主持人：嗯……太{STR_VAR_1}了。\n"
	.string "吞球兽说味道是“{STR_VAR_2}！”\p"
	.string "看来{STR_VAR_3}的失误\n"
	.string "影响了方块的质量……$"

gTV3CheersForPokeblocksText04::
	.string "{CHN}太可惜了，{STR_VAR_1}的\n"
	.string "主导努力付诸东流。\p"
	.string "希望{STR_VAR_2}下次\n"
	.string "能有更好的表现！$"

gTV3CheersForPokeblocksText05::
	.string "{CHN}下期再见！\n"
	.string "我们的口号是「为方块欢呼3次！」$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "{CHN}嗨，你好！\p"
	.string "我是{STR_VAR_1}的超级粉丝。\n"
	.string "你对{STR_VAR_1}怎么看？$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "{CHN}我明白了，我明白了。这就是你对\n"
	.string "这位训练家的看法。$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "{CHN}你是不是已经完全忘记了\n"
	.string "{STR_VAR_1}？$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "{CHN}我是{STR_VAR_1}的超级粉丝。\n"
	.string "你对{STR_VAR_1}怎么看？$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "{CHN}如果满分是一百分，\n"
	.string "你会给{STR_VAR_1}打多少分？$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "{CHN}你是不是已经完全忘记了\n"
	.string "{STR_VAR_1}？$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "{CHN}哦，我明白了！\n"
	.string "你应该找时间去见见{STR_VAR_1}。\l"
	.string "我相信你也会成为粉丝的！$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "{CHN}我明白了，我明白了。\p"
	.string "谢谢你！\n"
	.string "这信息很有用。\p"
	.string "我会和其他{STR_VAR_1}的粉丝\n"
	.string "分享这个信息，然后一起讨论。$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "{CHN}马上就会有一档关于\n"
	.string "{STR_VAR_1}的电视特别节目。\p"
	.string "希望你收看！$"

gTVTrainerFanClubSpecialText00::
	.string "{CHN}训练家粉丝俱乐部\n"
	.string "{STR_VAR_1}特别节目！\p"
	.string "这是一档为全丰缘\n"
	.string "{STR_VAR_1}的粉丝准备的特别节目！\p"
	.string "今天，我们要问的问题是：“人们\n"
	.string "对{STR_VAR_1}有什么看法？”\p"
	.string "我们向{STR_VAR_2}\n"
	.string "这位训练家代表提出了这个问题。\p"
	.string "我们问：“用一个词，你会\n"
	.string "如何形容{STR_VAR_1}？”\p"
	.string "回答是：“{STR_VAR_3}。”\p"
	.string "向{STR_VAR_2}致敬！\n"
	.string "多么有见地的看法！\p"
	.string "“{STR_VAR_3}的{STR_VAR_1}。”\n"
	.string "听起来真不错！\p"
	.string "{STR_VAR_2}还给{STR_VAR_1}的\n"
	.string "实力打了分，从0到100。$"

gTVTrainerFanClubSpecialText01::
	.string "{CHN}分数是{STR_VAR_3}分！\n"
	.string "这确实是个很高的分数！\p"
	.string "{STR_VAR_2}显然\n"
	.string "非常敬佩{STR_VAR_1}。$"

gTVTrainerFanClubSpecialText02::
	.string "{CHN}分数是{STR_VAR_3}分！\n"
	.string "这是个相当不错的分数。\p"
	.string "{STR_VAR_2}想必把\n"
	.string "{STR_VAR_1}当作对手吧。$"

gTVTrainerFanClubSpecialText03::
	.string "{CHN}分数是{STR_VAR_3}分！\n"
	.string "这分数有点低。\p"
	.string "{STR_VAR_2}想必把\n"
	.string "{STR_VAR_1}当作跟班吧。$"

gTVTrainerFanClubSpecialText04::
	.string "{CHN}分数是{STR_VAR_3}分！\n"
	.string "这分数真糟糕。\p"
	.string "{STR_VAR_2}想必把\n"
	.string "{STR_VAR_1}当作小卒吧。$"

gTVTrainerFanClubSpecialText05::
	.string "{CHN}各位观众，就是这样！\p"
	.string "我想我们对{STR_VAR_1}\n"
	.string "都有了新的认识。\p"
	.string "最后，让我用\n"
	.string "{STR_VAR_2}的话作为结束。\p"
	.string "{STR_VAR_3}的{STR_VAR_1}！$"

gTVNameRaterText00::
	.string "{CHN}现在，是时候了……\n"
	.string "「命名评级秀」。\p"
	.string "我会根据你给宝可梦取的\n"
	.string "昵称来为它占卜。\p"
	.string "我给你的建议，\n"
	.string "都是有用的忠告。\p"
	.string "今天，我要为{STR_VAR_1}的\n"
	.string "宝可梦{STR_VAR_2}的\l"
	.string "昵称{STR_VAR_3}进行解读。\p"
	.string "嗯嗯……\p"
	.string "嗯……\n"
	.string "这个昵称……$"

gTVNameRaterText01::
	.string "{CHN}这个昵称暗示着\n"
	.string "在许多方面都有天赋。\p"
	.string "我建议这位训练家鼓起勇气，\n"
	.string "接受各种挑战。$"

gTVNameRaterText02::
	.string "{CHN}这个昵称与训练家的名字\n"
	.string "{STR_VAR_1}完美契合。\p"
	.string "这意味着你们将\n"
	.string "在恰当的时机结成良好的搭档。$"

gTVNameRaterText03::
	.string "{CHN}这个昵称适合一只\n"
	.string "独一无二的宝可梦！\p"
	.string "如果好好培养，这只宝可梦的\n"
	.string "独特性将大放异彩！$"

gTVNameRaterText04::
	.string "{CHN}这个昵称将培育\n"
	.string "宝可梦体贴和富有同情心的一面。\p"
	.string "如果好好培养，这只宝可梦\n"
	.string "将展现出真正的温情！$"

gTVNameRaterText05::
	.string "{CHN}这是个非常好的昵称，\n"
	.string "暗示着未来将大有成就。\p"
	.string "我对这只宝可梦\n"
	.string "未来的发展充满好奇。$"

gTVNameRaterText06::
	.string "{CHN}这是个好昵称，\n"
	.string "能让宝可梦健康强壮！\p"
	.string "这只宝可梦应该会\n"
	.string "保持很长时间的健壮。$"

gTVNameRaterText07::
	.string "{CHN}这是个好昵称，\n"
	.string "能让宝可梦非常活跃！\p"
	.string "我想这只宝可梦\n"
	.string "在战斗中会表现得非常出色。$"

gTVNameRaterText08::
	.string "{CHN}这是个有魅力的昵称，\n"
	.string "能让宝可梦非常迷人！\p"
	.string "我毫不怀疑这只宝可梦\n"
	.string "会在宝可梦选拔赛中大放异彩。$"

gTVNameRaterText09::
	.string "{CHN}昵称{STR_VAR_1}以\n"
	.string "字母“{STR_VAR_3}”为基础。\p"
	.string "这个字母受到第一个\n"
	.string "字母“{STR_VAR_2}”的支撑，\l"
	.string "让昵称具有稳固的存在感。$"

gTVNameRaterText10::
	.string "{CHN}昵称{STR_VAR_1}\n"
	.string "形状很美，令人愉悦。\p"
	.string "字母“{STR_VAR_2}”和“{STR_VAR_3}”\n"
	.string "的组合——那真是太棒了！$"

gTVNameRaterText11::
	.string "{CHN}昵称{STR_VAR_1}——\n"
	.string "有一种崇高的流畅感。\p"
	.string "从首字母“{STR_VAR_2}”\n"
	.string "到“{STR_VAR_3}”的流畅感尤为出色。$"

gTVNameRaterText12::
	.string "{CHN}让我们再看看其他\n"
	.string "好昵称的例子，好吗？$"

gTVNameRaterText13::
	.string "{CHN}试试这个例子。取训练家\n"
	.string "{STR_VAR_1}名字的一部分，\l"
	.string "就能得到{STR_VAR_2}{STR_VAR_3}这个好昵称。$"

gTVNameRaterText14::
	.string "{CHN}昵称{STR_VAR_2}{STR_VAR_3}\n"
	.string "也会相当不错。$"

gTVNameRaterText15::
	.string "{CHN}以宝可梦的物种名\n"
	.string "{STR_VAR_2}为基础，\l"
	.string "也可以造出{STR_VAR_1}{STR_VAR_3}这个昵称。$"

gTVNameRaterText16::
	.string "{CHN}{STR_VAR_1}{STR_VAR_3}\n"
	.string "也会是一个有效的昵称。$"

gTVNameRaterText17::
	.string "{CHN}绝对要避免的是使用\n"
	.string "其他宝可梦的物种名。\p"
	.string "例如，避免取{STR_VAR_2}的名字\n"
	.string "来造{STR_VAR_1}{STR_VAR_3}这个昵称。\l"
	.string "那是不合适的。$"

gTVNameRaterText18::
	.string "{CHN}我得说，{STR_VAR_1}是个\n"
	.string "相当不错的昵称。\p"
	.string "希望训练家今后\n"
	.string "也能继续爱护{STR_VAR_1}。\p"
	.string "今天的节目就到这里。\n"
	.string "希望我们还能再见面。$"

gTVPokemonAnglerText00::
	.string "{CHN}{STR_VAR_2}钓鱼手\p"
	.string "播音员：你好！今天，我们要学习\n"
	.string "钓{STR_VAR_2}的技巧。\p"
	.string "大师，关于钓{STR_VAR_2}，\n"
	.string "您有什么建议？\p"
	.string "大师：嗯？钓{STR_VAR_2}？\n"
	.string "嗯，让我告诉你，要有耐心，\l"
	.string "慢慢等。这就是关键。\p"
	.string "你看到那边的{STR_VAR_1}了吗？\n"
	.string "那位训练家就是个好榜样。\p"
	.string "那位训练家已经\n"
	.string "让{STR_VAR_3}只宝可梦逃走了。\p"
	.string "但{STR_VAR_1}还在那里等。绝不放弃。\n"
	.string "这就是钓{STR_VAR_2}的法则。\p"
	.string "播音员：我明白了……\p"
	.string "哦！{STR_VAR_1}终于钓到了\n"
	.string "一只难得的{STR_VAR_2}！\p"
	.string "那位训练家高兴得\n"
	.string "快要哭了！\p"
	.string "看到那兴奋的样子，\n"
	.string "我也手痒想去钓鱼了！\p"
	.string "观众朋友们，何不趁此机会\n"
	.string "去尝试一下钓{STR_VAR_2}呢？\p"
	.string "下次节目之前，祝大家\n"
	.string "钓鱼愉快，再见！$"

gTVPokemonAnglerText01::
	.string "{CHN}{STR_VAR_2}钓鱼手\p"
	.string "播音员：你好！今天，我们要学习\n"
	.string "钓{STR_VAR_2}的技巧。\p"
	.string "大师，关于钓{STR_VAR_2}，\n"
	.string "您有什么建议？\p"
	.string "大师：嗯？钓{STR_VAR_2}？\n"
	.string "嗯，让我告诉你，要用\n"
	.string "钓竿大力地甩！\p"
	.string "你看到那边的{STR_VAR_1}了吗？\n"
	.string "看到钓竿是怎么操作的了吗？\p"
	.string "那位训练家已经\n"
	.string "连续钓到了{STR_VAR_3}只。\p"
	.string "播音员：太惊人了！\n"
	.string "看起来像暴风雨一样……\p"
	.string "看到那种级别的技术，\n"
	.string "我也手痒想去钓鱼了。\p"
	.string "观众朋友们，何不趁此机会\n"
	.string "去尝试一下钓{STR_VAR_2}呢？\p"
	.string "下次节目之前，祝大家\n"
	.string "钓鱼愉快，再见！$"

gTVPokemonTodayFailedText00::
	.string "{CHN}大家好！\p"
	.string "现在是「宝可梦今日谈」时间！\p"
	.string "大姐姐：嗨！大家今天\n"
	.string "都精神抖擞吗？\p"
	.string "今天，我们要来看看{STR_VAR_1}的\n"
	.string "宝可梦{STR_VAR_2}！\p"
	.string "大哥哥：好耶！这就是我们\n"
	.string "要做的！$"

gTVPokemonTodayFailedText01::
	.string "{CHN}哦！\n"
	.string "说到{STR_VAR_1}……\p"
	.string "大姐姐，我亲眼见到了\n"
	.string "那位训练家！\p"
	.string "大姐姐：哦，你看到什么了？\p"
	.string "大哥哥：嗯，我得去一趟\n"
	.string "{STR_VAR_2}。\p"
	.string "就在那时，我碰巧遇到了\n"
	.string "{STR_VAR_1}，那位训练家正在\l"
	.string "尝试捕捉宝可梦{STR_VAR_3}，但是……$"

gTVPokemonTodayFailedText02::
	.string "{CHN}宝可梦逃走了！\p"
	.string "结果浪费了这么多\n"
	.string "精灵球：{STR_VAR_2}个！\p"
	.string "你应该看看宝可梦逃走时\n"
	.string "{STR_VAR_1}脸上\l"
	.string "那挫败的表情！$"

gTVPokemonTodayFailedText03::
	.string "{CHN}但是{STR_VAR_1}搞砸了，\n"
	.string "让宝可梦晕倒了！\p"
	.string "结果浪费了这么多\n"
	.string "精灵球：{STR_VAR_2}个！\p"
	.string "你应该看看宝可梦晕倒时\n"
	.string "{STR_VAR_1}脸上\l"
	.string "那震惊和沮丧的表情！$"

gTVPokemonTodayFailedText04::
	.string "{CHN}大姐姐：嘿，喂！\n"
	.string "那样可不好！\p"
	.string "你不应该嘲笑\n"
	.string "别人的不幸！\p"
	.string "哦，可怜的{STR_VAR_1}。\n"
	.string "太可惜了！\p"
	.string "大哥哥：说得对！\n"
	.string "抱歉我笑了。$"

gTVPokemonTodayFailedText05::
	.string "{CHN}大姐姐：噗噗噗……\p"
	.string "大哥哥：喂！\n"
	.string "你也笑了！\p"
	.string "大姐姐：啊？！\p"
	.string "我没笑！\n"
	.string "真的，我没笑！\p"
	.string "哦，可怜的{STR_VAR_1}。\n"
	.string "太可惜了！\p"
	.string "大哥哥：……$"

gTVPokemonTodayFailedText06::
	.string "{CHN}大姐姐：别闹了！\n"
	.string "让我们看看今天的宝可梦……\p"
	.string "咦？\n"
	.string "时间已经到了？\p"
	.string "哎呀！\n"
	.string "我们今天没介绍成宝可梦！\p"
	.string "大哥哥：下期再见！\p"
	.string "大姐姐：嘿，不要没有我\n"
	.string "就结束节目！$"

gTVPokemonTodaySuccessfulText00::
	.string "{CHN}大家好！\p"
	.string "现在是「宝可梦今日谈」时间！\p"
	.string "大姐姐：嗨！大家今天\n"
	.string "都精神抖擞吗？\p"
	.string "今天，我们要来看看{STR_VAR_1}的\n"
	.string "宝可梦{STR_VAR_2}！\p"
	.string "大哥哥：好耶！这就是我们\n"
	.string "要做的！$"

gTVPokemonTodaySuccessfulText01::
	.string "{CHN}大姐姐：{STR_VAR_1}给这只\n"
	.string "{STR_VAR_2}取了{STR_VAR_3}这个昵称！\p"
	.string "看来{STR_VAR_3}得到了\n"
	.string "很好的疼爱！$"

gTVPokemonTodaySuccessfulText02::
	.string "{CHN}大哥哥：训练家为了抓住它，\n"
	.string "扔了这么多精灵球：{STR_VAR_3}个！\p"
	.string "最终只用了一个{STR_VAR_2}\n"
	.string "就抓到了！$"

gTVPokemonTodaySuccessfulText03::
	.string "{CHN}大姐姐：如果那么容易抓到，\n"
	.string "那一定是命运让\l"
	.string "{STR_VAR_1}和这只{STR_VAR_2}相遇的！$"

gTVPokemonTodaySuccessfulText04::
	.string "{CHN}大姐姐：哇！太棒了！\p"
	.string "不过你知道吗，一只宝可梦\n"
	.string "如果需要花很多功夫才能抓到，\l"
	.string "训练家就会更加疼爱它！$"

gTVPokemonTodaySuccessfulText05::
	.string "{CHN}大姐姐：{STR_VAR_1}的{STR_VAR_2}\n"
	.string "是一只令人难忘的宝可梦，\l"
	.string "因为用了珍贵的先机球才抓到！\p"
	.string "大哥哥：哇！那真是太厉害了！\p"
	.string "大姐姐：{STR_VAR_1}一定\n"
	.string "非常想要那只{STR_VAR_2}！$"

gTVPokemonTodaySuccessfulText06::
	.string "{CHN}大哥哥：能给那只{STR_VAR_2}\n"
	.string "取{STR_VAR_3}这个昵称……\p"
	.string "你真的能很好地感受到\n"
	.string "{STR_VAR_1}作为训练家的品味。\p"
	.string "大姐姐：我赞同！$"

gTVPokemonTodaySuccessfulText07::
	.string "{CHN}如果是我，我会把那个昵称\n"
	.string "给像这只{STR_VAR_3}一样的宝可梦！\p"
	.string "大哥哥：哇！这说不定是新\n"
	.string "搭配的开始！$"

gTVPokemonTodaySuccessfulText08::
	.string "{CHN}{STR_VAR_2}这只{STR_VAR_1}？\n"
	.string "听起来是不是很完美？\p"
	.string "用字和其他一切——\n"
	.string "听起来都和宝可梦\l"
	.string "{STR_VAR_1}非常契合！\p"
	.string "大哥哥：嗯，说得对！$"

gTVPokemonTodaySuccessfulText09::
	.string "{CHN}据我所知，还没有训练家\n"
	.string "给自己的{STR_VAR_1}\l"
	.string "取过{STR_VAR_2}这个昵称！\p"
	.string "大哥哥：这正说明了这位训练家\n"
	.string "在取昵称方面\l"
	.string "有很棒的品味！$"

gTVPokemonTodaySuccessfulText10::
	.string "{CHN}下次我抓到宝可梦时，\n"
	.string "我应该给它取{STR_VAR_2}这个名字。\p"
	.string "大哥哥：咦？我也是！\n"
	.string "我也会用{STR_VAR_2}这个昵称！$"

gTVPokemonTodaySuccessfulText11::
	.string "{CHN}大姐姐：哦，不好！\n"
	.string "看看时间！\p"
	.string "好了，各位，今天就到这里。\n"
	.string "我们下期再见！\p"
	.string "大哥哥：记住，下次出现在\n"
	.string "聚光灯下的可能就是你的宝可梦！$"

SmartShopper_Text_Intro::
	.string "{CHN}大家好！\p"
	.string "现在是「今日精明购物」时间。\p"
	.string "记者：观众朋友们，你们好吗？\p"
	.string "今天我们来到了位于\n"
	.string "{STR_VAR_2}的一家商店。\p"
	.string "让我们来看看最近\n"
	.string "热销的商品有哪些。$"

SmartShopper_Text_ClerkNormal::
	.string "{CHN}让我们采访一下店员\n"
	.string "了解情况。\p"
	.string "你好，生意怎么样？\p"
	.string "店员：哦，我们的生意非常好。\p"
	.string "最近，{STR_VAR_2}\n"
	.string "卖得特别好。\p"
	.string "前几天，有位叫{STR_VAR_1}的训练家\n"
	.string "买了{STR_VAR_3}。$"

SmartShopper_Text_RandomComment1::
	.string "{CHN}记者：那位训练家买了\n"
	.string "{STR_VAR_3}个{STR_VAR_2}？真不少！\p"
	.string "恕我直言，{STR_VAR_1}一定是\n"
	.string "在为远行\l"
	.string "做准备。\p"
	.string "出门在外，{STR_VAR_2}\n"
	.string "可是非常重要的！$"

SmartShopper_Text_RandomComment2::
	.string "{CHN}记者：说到{STR_VAR_2}这件道具，\n"
	.string "我最近也买了{STR_VAR_3}个。\p"
	.string "毕竟，{STR_VAR_2}是件很好的道具！$"

SmartShopper_Text_RandomComment3::
	.string "{CHN}记者：{STR_VAR_2}？！\n"
	.string "而且买了{STR_VAR_3}个？！\p"
	.string "我没想到会有人\n"
	.string "买那么多。\p"
	.string "天哪，我一次只能\n"
	.string "买一两个……$"

SmartShopper_Text_RandomComment4::
	.string "{CHN}记者：有一次，我买了\n"
	.string "一大堆{STR_VAR_2}这种道具。\p"
	.string "但后来发现买太多了。\n"
	.string "我后悔了……\p"
	.string "从那以后，我只买\n"
	.string "我真正需要的……\p"
	.string "哎呀！\p"
	.string "说我的事没有意义！$"

SmartShopper_Text_SecondItem::
	.string "{CHN}店员：{STR_VAR_1}还大量购买了\n"
	.string "{STR_VAR_2}这种道具，买了{STR_VAR_3}个。\p"
	.string "记者：哦，真精明。\n"
	.string "{STR_VAR_2}也是件很好的道具。$"

SmartShopper_Text_ThirdItem::
	.string "{CHN}店员：而且，那位训练家还买了\n"
	.string "{STR_VAR_3}个{STR_VAR_2}这种道具。$"

SmartShopper_Text_DuringSale::
	.string "{CHN}店员：而且，还是在打折期间。\n"
	.string "真是精明的购物。$"

SmartShopper_Text_OutroNormal::
	.string "{CHN}记者：嗯……{STR_VAR_1}看来\n"
	.string "是个精明的买家！\p"
	.string "总计，{STR_VAR_1}购买的商品达到了……\p"
	.string "¥{STR_VAR_2}？！\n"
	.string "真是惊人的金额！\p"
	.string "哎呀！时间到了！\n"
	.string "我们下期节目再见！$"

SmartShopper_Text_IsVIP::
	.string "{CHN}店员：{STR_VAR_1}是位贵宾客户，\n"
	.string "这是毫无疑问的。$"

SmartShopper_Text_ClerkMax::
	.string "{CHN}让我们采访一下店员\n"
	.string "了解情况。\p"
	.string "你好，生意怎么样？\p"
	.string "店员：哦，我们的生意好得\n"
	.string "难以置信。几乎忙不过来。\p"
	.string "最近，有位叫{STR_VAR_1}的训练家\n"
	.string "大量购买了{STR_VAR_2}这种道具。\p"
	.string "那位训练家几乎买光了\n"
	.string "我们所有的{STR_VAR_2}库存。\p"
	.string "我做梦也没想到会有\n"
	.string "客户需要那么多{STR_VAR_2}。\l"
	.string "真是闻所未闻！\p"
	.string "记者：那大概是一百\n"
	.string "或两百个吧？\p"
	.string "店员：哦，不，远不止于此！\p"
	.string "记者：哦，天哪！\n"
	.string "{STR_VAR_1}一定是位特别的顾客！\p"
	.string "店员：{STR_VAR_1}是位贵宾客户，\n"
	.string "这是毫无疑问的。$"

SmartShopper_Text_OutroMax::
	.string "{CHN}记者：嗯……\n"
	.string "那真是太惊人了。\p"
	.string "但那位训练家为什么要买\n"
	.string "那么多呢？\p"
	.string "…… …\p"
	.string "谜团越来越深，但今天\n"
	.string "的时间已经到了。\l"
	.string "我们下期节目再见！\p"
	.string "不过，{STR_VAR_1}确实是个谜一样的人……$"

gTVWorldOfMastersText00::
	.string "{CHN}大师的世界\p"
	.string "你好，观众朋友们。\p"
	.string "也许你听说过\n"
	.string "一位叫{STR_VAR_1}的训练家。\p"
	.string "{STR_VAR_1}以捕捉宝可梦的大师\n"
	.string "而闻名。\p"
	.string "{STR_VAR_1}捕捉宝可梦的诀窍\n"
	.string "完全在于步行仔细搜寻。\p"
	.string "在某个难忘的日子里，\n"
	.string "这位训练家走了{STR_VAR_2}步。\p"
	.string "那天捕捉到的\n"
	.string "宝可梦总数达到了惊人的{STR_VAR_3}只！$"

gTVWorldOfMastersText01::
	.string "{CHN}这惊人的壮绩一定是\n"
	.string "因为训练家和\l"
	.string "{STR_VAR_1}之间的信任才得以实现。$"

gTVWorldOfMastersText02::
	.string "{CHN}大师在{STR_VAR_2}附近\n"
	.string "抓到了当天最后一只{STR_VAR_3}。\p"
	.string "那只宝可梦显然\n"
	.string "享有纪录保持者的特殊地位。\p"
	.string "有实力的训练家应该受到鼓励，\n"
	.string "去挑战这个好纪录。\p"
	.string "今天就到这里。\n"
	.string "请下次继续收看。$"

gTVTodaysRivalTrainerText00::
	.string "{CHN}今日的劲敌训练家！\p"
	.string "各位宝可梦训练家好！\n"
	.string "今天大家过得怎么样？\p"
	.string "和每一天一样，\n"
	.string "今天我们也要审视一位劲敌！$"

gTVTodaysRivalTrainerText07::
	.string "{CHN}今天的劲敌训练家是{STR_VAR_1}，\n"
	.string "现在在{STR_VAR_3}附近。\p"
	.string "{STR_VAR_1}目前已经在\n"
	.string "宝可梦图鉴中登记了{STR_VAR_2}只宝可梦。$"

gTVTodaysRivalTrainerText08::
	.string "{CHN}今天的劲敌训练家是{STR_VAR_1}，\n"
	.string "现在在一个秘密基地里。\p"
	.string "{STR_VAR_1}目前已经在\n"
	.string "宝可梦图鉴中登记了{STR_VAR_2}只宝可梦。$"

gTVTodaysRivalTrainerText09::
	.string "{CHN}今天的劲敌训练家是{STR_VAR_1}。\p"
	.string "目前，{STR_VAR_1}已经在\n"
	.string "宝可梦图鉴中登记了{STR_VAR_2}只宝可梦。$"

gTVTodaysRivalTrainerText10::
	.string "{CHN}今天的劲敌训练家是{STR_VAR_1}，\n"
	.string "现在在渡轮上。\p"
	.string "{STR_VAR_1}目前已经在\n"
	.string "宝可梦图鉴中登记了{STR_VAR_2}只宝可梦。$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "{CHN}那么，我们的劲敌有多少\n"
	.string "徽章呢？数量是{STR_VAR_1}个！$"

gTVTodaysRivalTrainerText02::
	.string "{CHN}但是我们的劲敌\n"
	.string "还没有得到任何徽章！$"

gTVTodaysRivalTrainerText03::
	.string "{CHN}我们的劲敌\n"
	.string "还没有得到任何对战开拓区的象征。$"

gTVTodaysRivalTrainerText04::
	.string "{CHN}让我们看看我们的劲敌有多少\n"
	.string "对战开拓区的象征。\p"
	.string "金色象征：{STR_VAR_1}个！\n"
	.string "银色象征：{STR_VAR_2}个！$"

gTVTodaysRivalTrainerText05::
	.string "{CHN}我们的劲敌在对战开拓区\n"
	.string "已经收集了{STR_VAR_1}个对战点数。$"

gTVTodaysRivalTrainerText06::
	.string "{CHN}那么，和{STR_VAR_1}相比，\n"
	.string "你表现如何？\p"
	.string "冒险还在继续！\p"
	.string "各位训练家！\p"
	.string "让我们一起继续前进，\n"
	.string "超越我们的劲敌！$"

TrendWatcher_Text_Intro::
	.string "{CHN}武斗潮流观察网！\p"
	.string "主持人：怎么样？\n"
	.string "我们会带来武斗\l"
	.string "最新最酷的潮流资讯。\p"
	.string "今天的嘉宾是这位老先生，\n"
	.string "他自称是武斗\l"
	.string "万事通。\p"
	.string "老先生：很高兴来到这里。\p"
	.string "主持人：我们直奔主题吧。\p"
	.string "您觉得什么正在\n"
	.string "让武斗的各位着迷？\p"
	.string "老先生：{STR_VAR_1} {STR_VAR_2}。\p"
	.string "主持人：{STR_VAR_1} {STR_VAR_2}，\n"
	.string "您说？\p"
	.string "老先生：不。\p"
	.string "{STR_VAR_1} {STR_VAR_2}\n"
	.string "根本就没流行起来。\p"
	.string "您想听听这件事吗？\p"
	.string "主持人：呃，不想。我们想知道的是\n"
	.string "现在流行什么……$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "{CHN}老先生：是来自未白镇的{STR_VAR_3}\n"
	.string "告诉我{STR_VAR_1} {STR_VAR_2}\l"
	.string "很流行的……$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "{CHN}老先生：是来自未白镇的{STR_VAR_3}\n"
	.string "告诉我{STR_VAR_1} {STR_VAR_2}\l"
	.string "很流行的……$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "{CHN}但这完全没希望。\p"
	.string "{STR_VAR_1} {STR_VAR_2}庆典！\p"
	.string "{STR_VAR_1} {STR_VAR_2}大赛！\p"
	.string "我尽我所能地教给每个人，\n"
	.string "但是……\p"
	.string "也许{STR_VAR_1}这部分\n"
	.string "就是不对……\p"
	.string "主持人：呃，打扰一下老先生，我需要\n"
	.string "听现在流行的……$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "{CHN}老先生：{STR_VAR_3}！\n"
	.string "请告诉我比{STR_VAR_1} {STR_VAR_2}\l"
	.string "更大的事！$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "{CHN}老先生：{STR_VAR_3}！\n"
	.string "请告诉我比{STR_VAR_1} {STR_VAR_2}\l"
	.string "更大的事！$"

TrendWatcher_Text_Outro::
	.string "{CHN}主持人：……呃……好了，就是这样，\n"
	.string "各位时尚的观众朋友们！\p"
	.string "{STR_VAR_1} {STR_VAR_2}……呃……\n"
	.string "在武斗根本就没流行起来！\p"
	.string "我的时间到了。下次再聊！\p"
	.string "老先生：{STR_VAR_1} {STR_VAR_2}！$"

gTVHoennTreasureInvestigatorsText00::
	.string "{CHN}丰缘宝藏调查队！\p"
	.string "嗨，各位！\n"
	.string "最近发现什么秘密道具了吗？\p"
	.string "一如既往，我们将审视\n"
	.string "来自各地的目击报告！\p"
	.string "让我们从一封信开始。\n"
	.string "信上写着：“发现了{STR_VAR_1}！”$"

gTVHoennTreasureInvestigatorsText01::
	.string "{CHN}哇，我们得好好看看这封信！\n"
	.string "让我读给你听。\p"
	.string "……亲爱的调查队，\n"
	.string "希望你一切都好。\p"
	.string "我最近在{STR_VAR_3}附近\n"
	.string "某处看到了{STR_VAR_2}。\p"
	.string "那位训练家发现了\n"
	.string "{STR_VAR_1}这件道具。真让人羡慕。\p"
	.string "……嗯，干得好，{STR_VAR_2}！\p"
	.string "观众们，让这激励你们\n"
	.string "拿起探宝器去寻找吧！\p"
	.string "我会等待大家\n"
	.string "带来的激动人心的消息！$"

gTVHoennTreasureInvestigatorsText02::
	.string "{CHN}哇，我们得好好看看这封信！\n"
	.string "让我读给你听。\p"
	.string "……亲爱的调查队，\n"
	.string "希望你一切都好。\p"
	.string "我最近在渡轮上看到了{STR_VAR_2}。\p"
	.string "那位训练家发现了\n"
	.string "{STR_VAR_1}这件道具。真让人羡慕。\p"
	.string "……嗯，干得好，{STR_VAR_2}！\p"
	.string "观众们，让这激励你们\n"
	.string "拿起探宝器去寻找吧！\p"
	.string "我会等待大家\n"
	.string "带来的激动人心的消息！$"

gTVFindThatGamerText00::
	.string "{CHN}寻找那位玩家！\p"
	.string "嘿，各位玩家！\n"
	.string "你的{STR_VAR_2}转得怎么样了？\p"
	.string "一如既往，我们将聚焦\n"
	.string "一位造访过游戏中心的\l"
	.string "稀有训练家！\p"
	.string "今天我们的头号玩家是……\n"
	.string "{STR_VAR_1}！$"

gTVFindThatGamerText01::
	.string "{CHN}{STR_VAR_1}玩了{STR_VAR_2}游戏，\n"
	.string "赢得了{STR_VAR_3}枚代币。\p"
	.string "“{STR_VAR_1}来的时候，我们得\n"
	.string "确保备足代币。”\p"
	.string "当我们的玩家在玩时，\n"
	.string "游戏中心的店员们就是这么\l"
	.string "嘀咕的！\p"
	.string "观众们，如果你去游戏中心\n"
	.string "玩{STR_VAR_2}游戏，\l"
	.string "最好像{STR_VAR_1}那样看好你的代币。\p"
	.string "这里是来自游戏中心的直播——\n"
	.string "你能感受到那份刺激！\p"
	.string "今天就到这里！$"

gTVFindThatGamerText02::
	.string "{CHN}{STR_VAR_1}玩了{STR_VAR_2}游戏，\n"
	.string "输掉了{STR_VAR_3}枚代币。\p"
	.string "“{STR_VAR_1}来的时候，我们\n"
	.string "代币的销量似乎会增加。”\p"
	.string "当我们的玩家在玩时，\n"
	.string "游戏中心的店员们就是这么说的！$"

gTVFindThatGamerText03::
	.string "{CHN}观众们，如果你去游戏中心\n"
	.string "玩{STR_VAR_2}游戏，\l"
	.string "最好像{STR_VAR_1}那样看好你的代币。\p"
	.string "这里是来自游戏中心的直播——\n"
	.string "你能感受到那份刺激！\p"
	.string "今天就到这里！$"

gTVBreakingNewsText00::
	.string "{CHN}突发新闻电视！$"

gTVBreakingNewsText01::
	.string "{CHN}{STR_VAR_1}抓到了\n"
	.string "稀有的{STR_VAR_2}！\p"
	.string "我们正在{STR_VAR_3}附近\n"
	.string "进行现场直播！\p"
	.string "{STR_VAR_1}在这里\n"
	.string "成功捕获了一只稀有的{STR_VAR_2}！$"

gTVBreakingNewsText02::
	.string "{CHN}当{STR_VAR_1}遇到稀有的\n"
	.string "{STR_VAR_2}时，训练家派出了\l"
	.string "宝可梦{STR_VAR_3}。$"

gTVBreakingNewsText03::
	.string "{CHN}在战斗中，训练家扔出的\n"
	.string "精灵球数量是{STR_VAR_1}个。\p"
	.string "最终，这只稀有的宝可梦\n"
	.string "是被最后使用的{STR_VAR_2}抓住的。$"

gTVBreakingNewsText04::
	.string "{CHN}在那一瞬间，{STR_VAR_2}\n"
	.string "回荡着{STR_VAR_1}胜利的\l"
	.string "欢呼。\p"
	.string "我得说我有点羡慕{STR_VAR_1}。\n"
	.string "我也想大声欢呼。\p"
	.string "……现场直播\n"
	.string "就在这欢乐的场面中结束！$"

gTVBreakingNewsText05::
	.string "{CHN}{STR_VAR_1}未能捕捉\n"
	.string "稀有的{STR_VAR_2}！\p"
	.string "我们正在{STR_VAR_3}附近\n"
	.string "进行现场直播！\p"
	.string "就是在这里，{STR_VAR_1}未能\n"
	.string "捕捉到稀有的{STR_VAR_2}！$"

gTVBreakingNewsText06::
	.string "{CHN}当{STR_VAR_1}遇到稀有的\n"
	.string "{STR_VAR_2}时，训练家派出了\l"
	.string "宝可梦{STR_VAR_3}。$"

gTVBreakingNewsText07::
	.string "{CHN}训练家让{STR_VAR_2}\n"
	.string "使出了{STR_VAR_1}招式。\p"
	.string "训练家无意中\n"
	.string "让稀有的宝可梦晕倒了……$"

gTVBreakingNewsText12::
	.string "{CHN}然而，{STR_VAR_1}在\n"
	.string "看到稀有的{STR_VAR_2}时慌了神。\p"
	.string "训练家慌乱中命令\n"
	.string "{STR_VAR_3}攻击。\p"
	.string "训练家无意中\n"
	.string "让稀有的宝可梦晕倒了。$"

gTVBreakingNewsText08::
	.string "{CHN}在那一瞬间，{STR_VAR_2}\n"
	.string "回荡着{STR_VAR_1}沮丧的\l"
	.string "尖叫……$"

gTVBreakingNewsText09::
	.string "{CHN}然而，{STR_VAR_1}的\n"
	.string "精灵球似乎用完了。\p"
	.string "训练家不得不\n"
	.string "中止与稀有{STR_VAR_2}的战斗。\p"
	.string "在那一瞬间，{STR_VAR_3}\n"
	.string "回荡着{STR_VAR_1}沮丧的\l"
	.string "尖叫……$"

gTVBreakingNewsText10::
	.string "{CHN}然而，{STR_VAR_2}毫无预兆地\n"
	.string "逃走了。\p"
	.string "在那一瞬间，{STR_VAR_3}\n"
	.string "回荡着{STR_VAR_1}沮丧的\l"
	.string "尖叫……$"

gTVBreakingNewsText11::
	.string "{CHN}我得说我能体会{STR_VAR_1}的感受。\n"
	.string "哎，这让我也想尖叫了。\p"
	.string "……现场直播\n"
	.string "就在这忧伤的场面中结束！$"

gTVSecretBaseVisitText00::
	.string "{CHN}大家好！\n"
	.string "又到了\l"
	.string "「秘密基地探访」的时间。\p"
	.string "今天，我们要探访的是\n"
	.string "{STR_VAR_1}的秘密基地。\p"
	.string "{STR_VAR_1}是怎么\n"
	.string "个性化布置这个秘密基地的？\p"
	.string "让我们一探究竟！\n"
	.string "…… …… …… …… …$"

gTVSecretBaseVisitText01::
	.string "{CHN}哦！\n"
	.string "太棒了！\p"
	.string "这个{STR_VAR_2}……\n"
	.string "真没想到会\l"
	.string "在这里看到！$"

gTVSecretBaseVisitText02::
	.string "{CHN}哦！\n"
	.string "太惊人了！\p"
	.string "这里一件家具\n"
	.string "或装饰品都没有！\p"
	.string "普通人可\n"
	.string "无法模仿这种大胆的宣言！\p"
	.string "简约，但却充满了，是的，\n"
	.string "充满了野性！\p"
	.string "我佩服你，{STR_VAR_1}。\n"
	.string "非你莫属！$"

gTVSecretBaseVisitText03::
	.string "{CHN}哦！我明白了！\n"
	.string "我完全明白了！\p"
	.string "这个{STR_VAR_2}在这里……\n"
	.string "传递了一个有效的信息！$"

gTVSecretBaseVisitText04::
	.string "{CHN}哦！我明白了！\n"
	.string "我完全明白了！\p"
	.string "这个空间刻意\n"
	.string "不摆放任何装饰品！\p"
	.string "传递了一个有效的信息！$"

gTVSecretBaseVisitText05::
	.string "{CHN}哇哦！\p"
	.string "{STR_VAR_2}和\n"
	.string "{STR_VAR_3}的搭配！\p"
	.string "如果有过梦幻组合的话，\n"
	.string "这就是了！$"

gTVSecretBaseVisitText06::
	.string "{CHN}哇哦！\p"
	.string "把{STR_VAR_2}放在\n"
	.string "这里……\p"
	.string "有一种存在感\n"
	.string "充满了整个秘密基地！$"

gTVSecretBaseVisitText07::
	.string "{CHN}哇哦！\p"
	.string "这里什么都没摆。\p"
	.string "这个空旷的空间\n"
	.string "对整个秘密基地都有影响。$"

gTVSecretBaseVisitText08::
	.string "{CHN}哦！\n"
	.string "{STR_VAR_1}来了！\l"
	.string "让我们挑战这位训练家！\p"
	.string "…… …… …… …… …\n"
	.string "…… …… …… …… …$"

gTVSecretBaseVisitText09::
	.string "{CHN}唉……\n"
	.string "我不得不佩服{STR_VAR_1}。\p"
	.string "那位训练家的宝可梦\n"
	.string "确实配得上冠军的称号。\p"
	.string "它们充分证明了{STR_VAR_1}作为\n"
	.string "训练家的实力。\p"
	.string "那只{STR_VAR_2}会使用\n"
	.string "{STR_VAR_3}招式……\p"
	.string "这显示了{STR_VAR_1}是\n"
	.string "怎样的一位训练家。\p"
	.string "确实，这是一堂很好的课！$"

gTVSecretBaseVisitText10::
	.string "{CHN}哎呀！\n"
	.string "我不得不佩服{STR_VAR_1}。\p"
	.string "那位训练家的宝可梦\n"
	.string "强得吓人！\p"
	.string "它们充分证明了{STR_VAR_1}作为\n"
	.string "训练家的坚韧。\p"
	.string "那只{STR_VAR_2}会使用\n"
	.string "{STR_VAR_3}招式……\p"
	.string "这显示了{STR_VAR_1}是\n"
	.string "怎样的一位训练家。\p"
	.string "确实，这是一堂很好的课！$"

gTVSecretBaseVisitText11::
	.string "{CHN}哇哦！\n"
	.string "我不得不佩服{STR_VAR_1}。\p"
	.string "那位训练家的宝可梦显然\n"
	.string "培养得很均衡。\p"
	.string "它们充分证明了{STR_VAR_1}作为\n"
	.string "训练家的周到。\p"
	.string "那只{STR_VAR_2}会使用\n"
	.string "{STR_VAR_3}招式……\p"
	.string "这显示了{STR_VAR_1}是\n"
	.string "怎样的一位训练家。\p"
	.string "确实，这是一堂很好的课！$"

gTVSecretBaseVisitText12::
	.string "{CHN}哎呀！\n"
	.string "我不得不佩服{STR_VAR_1}。\p"
	.string "那位训练家的宝可梦\n"
	.string "显示出了未来成长的巨大潜力。\p"
	.string "它们代表着{STR_VAR_1}的\n"
	.string "希望和梦想。\p"
	.string "那只{STR_VAR_2}会使用\n"
	.string "{STR_VAR_3}招式……\p"
	.string "这显示了{STR_VAR_1}是\n"
	.string "怎样的一位训练家。\p"
	.string "确实，这是一堂很好的课！$"

gTVSecretBaseVisitText13::
	.string "{CHN}我得说，这是一个多么出色的\n"
	.string "秘密基地！\p"
	.string "观众们，如果有机会，\n"
	.string "一定要去{STR_VAR_1}的秘密基地看看。\p"
	.string "下次再见，告辞了！$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "{CHN}激动人心！\n"
	.string "扣人心弦！\p"
	.string "这里是宝可梦抽奖\n"
	.string "中奖快讯！\p"
	.string "你好！我们正在凯那市\n"
	.string "百货大楼一楼的\l"
	.string "宝可梦抽奖角\l"
	.string "为你现场直播！\p"
	.string "和往常一样，今天\n"
	.string "又出现了一位幸运的训练家！\p"
	.string "那位训练家的名字是……\n"
	.string "{STR_VAR_1}！\p"
	.string "{STR_VAR_1}赢得了{STR_VAR_2}等奖，\n"
	.string "并把{STR_VAR_3}带回了家！\p"
	.string "{STR_VAR_1}！\n"
	.string "恭喜你！\p"
	.string "观众们，不要光看，\n"
	.string "也来参与吧！\p"
	.string "凯那市百货大楼\n"
	.string "全体员工期待您的再次光临！\p"
	.string "这里是来自凯那市百货大楼\n"
	.string "的现场直播，\l"
	.string "为您提供丰缘\n"
	.string "最丰富的商品选择！$"

gTVThePokemonBattleSeminarText00::
	.string "{CHN}宝可梦对战研讨会！\p"
	.string "我们通过审视战斗\n"
	.string "来从中学习经验。\p"
	.string "今天的案例是{STR_VAR_1}的\n"
	.string "战斗。\p"
	.string "{STR_VAR_1}的{STR_VAR_2}\n"
	.string "正在和一只{STR_VAR_3}战斗……$"

gTVThePokemonBattleSeminarText01::
	.string "{CHN}它对{STR_VAR_2}\n"
	.string "使出了{STR_VAR_3}招式……\p"
	.string "嗯……{STR_VAR_1}！\n"
	.string "这是错误的做法！$"

gTVThePokemonBattleSeminarText02::
	.string "{CHN}除了那个糟糕的招式，\n"
	.string "训练家的{STR_VAR_1}还会使用$"

gTVThePokemonBattleSeminarText03::
	.string "{CHN}{STR_VAR_1}、{STR_VAR_2}、\n"
	.string "和{STR_VAR_3}这些招式。$"

gTVThePokemonBattleSeminarText04::
	.string "{CHN}{STR_VAR_1}和\n"
	.string "{STR_VAR_2}这些招式。$"

gTVThePokemonBattleSeminarText05::
	.string "{CHN}{STR_VAR_2}这个招式。$"

gTVThePokemonBattleSeminarText06::
	.string "{CHN}那么，在这种情况下，训练家\n"
	.string "应该使用什么呢？\p"
	.string "…… …… …… …… …\n"
	.string "{STR_VAR_1}招式！\p"
	.string "{STR_VAR_1}招式绝对\n"
	.string "比{STR_VAR_2}更好。\p"
	.string "观众们，我劝你们从这个案例中学习，\n"
	.string "用智慧去战斗！\p"
	.string "下次再见！$"

gTVTrainerFanClubText00::
	.string "{CHN}大家一起！\n"
	.string "训练家粉丝俱乐部！\p"
	.string "主持人：大家过得怎么样？\n"
	.string "今天，我们召集了超人气\l"
	.string "训练家{STR_VAR_1}的粉丝！\p"
	.string "粉丝们：呜啊啊啊啊！\p"
	.string "粉丝们：{STR_VAR_1}！\p"
	.string "主持人：各位！\n"
	.string "你们喜欢{STR_VAR_1}吗？！\p"
	.string "粉丝们：我们爱{STR_VAR_1}！\p"
	.string "主持人：你们喜欢\n"
	.string "{STR_VAR_1}的什么？！$"

gTVTrainerFanClubText01::
	.string "{CHN}粉丝们：他们扔精灵球\n"
	.string "时的帅气动作！$"

gTVTrainerFanClubText02::
	.string "{CHN}粉丝们：他们跑步时\n"
	.string "可爱的样子！$"

gTVTrainerFanClubText03::
	.string "{CHN}粉丝们：训练家在困境中\n"
	.string "变得坚强的样子！$"

gTVTrainerFanClubText04::
	.string "{CHN}粉丝们：训练家\n"
	.string "对宝可梦的了解！$"

gTVTrainerFanClubText05::
	.string "{CHN}粉丝们：训练家\n"
	.string "对所有宝可梦的关爱！$"

gTVTrainerFanClubText06::
	.string "{CHN}粉丝们：训练家\n"
	.string "惊人的骑车技巧！$"

gTVTrainerFanClubText07::
	.string "{CHN}粉丝们：训练家\n"
	.string "买东西时的气势！$"

gTVTrainerFanClubText08::
	.string "{CHN}粉丝们：训练家给\n"
	.string "宝可梦取昵称时的迷人方式！$"

gTVTrainerFanClubText09::
	.string "{CHN}粉丝们：训练家\n"
	.string "装饰秘密基地时的巧妙风格！$"

gTVTrainerFanClubText10::
	.string "{CHN}粉丝们：训练家使用\n"
	.string "招式学习器时的大胆方式！$"

gTVTrainerFanClubText11::
	.string "{CHN}主持人：如你们所见，{STR_VAR_1}\n"
	.string "火爆极了！热得烫手！\p"
	.string "在{STR_VAR_1}的粉丝中\n"
	.string "有一句特别的口号！\p"
	.string "主持人：当我说{STR_VAR_1}，\n"
	.string "你们说……\p"
	.string "粉丝们：{STR_VAR_2}！\p"
	.string "粉丝们：{STR_VAR_3}！\p"
	.string "粉丝们：{STR_VAR_2}！\p"
	.string "粉丝们：{STR_VAR_3}！\p"
	.string "主持人：没错，当有人说\n"
	.string "“{STR_VAR_1}”时……\p"
	.string "回应应该是：\n"
	.string "“{STR_VAR_2}\n"
	.string "{STR_VAR_3}！”\p"
	.string "听起来真独特！\n"
	.string "我明白为什么大家会成为\l"
	.string "{STR_VAR_1}的粉丝了！\p"
	.string "好了，电视机前的你，加入我们吧！\n"
	.string "大家一起！\p"
	.string "主持人：当我说{STR_VAR_1}，\n"
	.string "你们说……\p"
	.string "粉丝们：{STR_VAR_2}！\p"
	.string "粉丝们：{STR_VAR_3}！\p"
	.string "粉丝们：{STR_VAR_2}！\p"
	.string "粉丝们：{STR_VAR_3}！\p"
	.string "主持人：感谢所有{STR_VAR_1}\n"
	.string "狂野粉丝的参与！\l"
	.string "节目就到这里！下次再见！\p"
	.string "主持人：当我说{STR_VAR_1}，\n"
	.string "你们说……\p"
	.string "粉丝们：{STR_VAR_2}！\p"
	.string "粉丝们：{STR_VAR_3}！$"

TVSpotTheCuties_Text_Intro::
	.string "{CHN}发现可爱宝可梦！\n"
	.string "佩戴缎带的宝可梦！\p"
	.string "你好，亲爱的观众们！\p"
	.string "我肯定你们会同意，一只佩戴着\n"
	.string "缎带的宝可梦简直是太迷人了！\p"
	.string "今天，我想和你分享\n"
	.string "我在城里散步时\l"
	.string "发现的一只可爱宝可梦。\p"
	.string "今天登场\n"
	.string "的漂亮宝可梦是{STR_VAR_1}的{STR_VAR_2}。$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "{CHN}{STR_VAR_2}佩戴的\n"
	.string "缎带数量是{STR_VAR_3}条。\p"
	.string "这充分说明了\n"
	.string "{STR_VAR_1}有多么疼爱这只宝可梦。$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{CHN}{STR_VAR_2}佩戴了惊人的\n"
	.string "{STR_VAR_3}条缎带！\p"
	.string "这充分说明了{STR_VAR_1}对\n"
	.string "这只宝可梦的用心！$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{CHN}{STR_VAR_2}佩戴了令人难以置信的\n"
	.string "{STR_VAR_3}条缎带！\p"
	.string "这显示了{STR_VAR_1}作为\n"
	.string "收藏家的全心投入！$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "{CHN}让我们仔细看看\n"
	.string "{STR_VAR_2}佩戴的众多缎带。$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "{CHN}冠军缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在进入名人堂时\n"
	.string "获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的英勇气概。\p"
	.string "{STR_VAR_2}和冠军缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonCool::
	.string "{CHN}帅气缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在赢得\n"
	.string "帅气选拔赛时获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的帅气。\p"
	.string "{STR_VAR_2}和帅气缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "{CHN}美丽缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在赢得\n"
	.string "美丽选拔赛时获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的美丽。\p"
	.string "{STR_VAR_2}和美丽缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonCute::
	.string "{CHN}可爱缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在赢得\n"
	.string "可爱选拔赛时获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的可爱。\p"
	.string "{STR_VAR_2}和可爱缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "{CHN}聪明缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在赢得\n"
	.string "聪明选拔赛时获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的聪明。\p"
	.string "{STR_VAR_2}和聪明缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonTough::
	.string "{CHN}强壮缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在赢得\n"
	.string "强壮选拔赛时获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的强壮。\p"
	.string "{STR_VAR_2}和强壮缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "{CHN}致胜缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在对战塔的\n"
	.string "战绩中获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的强大。\p"
	.string "{STR_VAR_2}和致胜缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "{CHN}胜利缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}在对战塔的\n"
	.string "战绩中获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的惊人强大。\p"
	.string "{STR_VAR_2}和胜利缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "{CHN}艺术家缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}因为成为\n"
	.string "画家的模特而获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的偶像魅力。\p"
	.string "{STR_VAR_2}和艺术家缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "{CHN}努力缎带特别\n"
	.string "引人注目。\p"
	.string "{STR_VAR_2}因为特别\n"
	.string "勤奋努力而获得了它。\p"
	.string "它确实能衬托出\n"
	.string "{STR_VAR_2}的决心。\p"
	.string "{STR_VAR_2}和努力缎带！\n"
	.string "这个组合效果绝佳！$"

TVSpotTheCuties_Text_Outro::
	.string "{CHN}……啊……\p"
	.string "缎带和宝可梦……\n"
	.string "真是天作之合！\p"
	.string "在我晕倒之前，\n"
	.string "和大家说再见了！$"

gTVPokemonNewsBattleFrontierText00::
	.string "{CHN}大家好！\n"
	.string "这里是宝可梦新闻时间。\p"
	.string "我们收到了来自\n"
	.string "对战开拓区的好消息。$"

gTVPokemonNewsBattleFrontierText01::
	.string "{CHN}训练家{STR_VAR_1}在对战塔的\n"
	.string "单打挑战赛中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText02::
	.string "{CHN}训练家{STR_VAR_1}在对战塔的\n"
	.string "双打挑战赛中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText03::
	.string "{CHN}训练家{STR_VAR_1}在对战塔的\n"
	.string "多人对战中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText04::
	.string "{CHN}训练家{STR_VAR_1}在对战塔的\n"
	.string "联机多人对战中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText05::
	.string "{CHN}训练家{STR_VAR_1}在对战巨蛋的\n"
	.string "单打锦标赛中\l"
	.string "创下了{STR_VAR_2}连胜冠军的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText06::
	.string "{CHN}训练家{STR_VAR_1}在对战巨蛋的\n"
	.string "双打锦标赛中\l"
	.string "创下了{STR_VAR_2}连胜冠军的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText07::
	.string "{CHN}训练家{STR_VAR_1}在对战工厂的\n"
	.string "宝可梦交换单打中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText08::
	.string "{CHN}训练家{STR_VAR_1}在对战工厂的\n"
	.string "宝可梦交换双打中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText09::
	.string "{CHN}训练家{STR_VAR_1}在对战管道的\n"
	.string "宝可梦选择挑战中\l"
	.string "创下了通过{STR_VAR_2}个房间的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText10::
	.string "{CHN}训练家{STR_VAR_1}在对战竞技场的\n"
	.string "淘汰锦标赛中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText11::
	.string "{CHN}训练家{STR_VAR_1}在对战宫殿的\n"
	.string "单打挑战赛中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText12::
	.string "{CHN}训练家{STR_VAR_1}在对战宫殿的\n"
	.string "双打挑战赛中\l"
	.string "创下了{STR_VAR_2}连胜的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText13::
	.string "{CHN}训练家{STR_VAR_1}在对战金字塔的\n"
	.string "宝可梦探险挑战中\l"
	.string "创下了通过{STR_VAR_2}层的新纪录。\p"
	.string "为{STR_VAR_1}欢呼！$"

gTVPokemonNewsBattleFrontierText14::
	.string "{CHN}向这三只宝可梦，{STR_VAR_1}、\n"
	.string "{STR_VAR_2}和{STR_VAR_3}！\p"
	.string "祝贺你们\n"
	.string "打破纪录的表现！$"

gTVPokemonNewsBattleFrontierText15::
	.string "{CHN}向这两只宝可梦，{STR_VAR_1}\n"
	.string "和{STR_VAR_2}！\p"
	.string "祝贺你们\n"
	.string "打破纪录的表现！$"

gTVPokemonNewsBattleFrontierText16::
	.string "{CHN}向这四只宝可梦：{STR_VAR_1}！\p"
	.string "{STR_VAR_2}！\p"
	.string "{STR_VAR_3}！$"

gTVPokemonNewsBattleFrontierText17::
	.string "{CHN}还有{STR_VAR_1}！\p"
	.string "祝贺你\n"
	.string "打破纪录的表现！$"

gTVPokemonNewsBattleFrontierText18::
	.string "{CHN}让我们期待{STR_VAR_1}和忠诚的宝可梦\n"
	.string "能创造更多\l"
	.string "纪录。\p"
	.string "以上就是宝可梦新闻的报道！$"

gTVWhatsNo1InHoennTodayText00::
	.string "{CHN}今天丰缘的第一名是谁？\n"
	.string "是的，又到了那个时间！\p"
	.string "你好，观众们！你在\n"
	.string "所做的每件事上都尽力了吗？\p"
	.string "让我们来看看今天\n"
	.string "表现最好的训练家！\p"
	.string "今天的第一名训练家不是别人，\n"
	.string "正是{STR_VAR_1}！$"

gTVWhatsNo1InHoennTodayText01::
	.string "{CHN}在一天内，{STR_VAR_1}在游戏中心\n"
	.string "转了{STR_VAR_2}次老虎机。\p"
	.string "在玩的时候，听到{STR_VAR_1}\n"
	.string "嘀咕着：“对我来说，转盘\l"
	.string "根本都不动……”\l"
	.string "是不是很有趣？$"

gTVWhatsNo1InHoennTodayText02::
	.string "{CHN}在一天内，{STR_VAR_1}在游戏中心\n"
	.string "玩了{STR_VAR_2}次\l"
	.string "轮盘游戏。\p"
	.string "在玩的时候，{STR_VAR_1}大喊：\n"
	.string "“让球来决定吧！”\p"
	.string "那位训练家目光专注，\n"
	.string "表情专注。$"

gTVWhatsNo1InHoennTodayText03::
	.string "{CHN}在一天内，{STR_VAR_1}与野生\n"
	.string "宝可梦战斗了{STR_VAR_2}次！\p"
	.string "显然，{STR_VAR_1}的宝可梦\n"
	.string "已经变得无比强大。\p"
	.string "它们似乎随时、随地、\n"
	.string "以任何方式都渴望战斗！$"

gTVWhatsNo1InHoennTodayText04::
	.string "{CHN}就在一天内，{STR_VAR_1}转了\n"
	.string "{STR_VAR_2}次树果搅拌机！\p"
	.string "到最后，连{STR_VAR_1}\n"
	.string "都似乎晕了。\p"
	.string "那位训练家摇摇晃晃，\n"
	.string "像晃晃斑一样！$"

gTVWhatsNo1InHoennTodayText05::
	.string "{CHN}就在一天内，{STR_VAR_1}种下了\n"
	.string "{STR_VAR_2}个树果！\p"
	.string "结果，{STR_VAR_1}的衣服\n"
	.string "沾满了泥土。\p"
	.string "在训练家种树果的地方，无数\n"
	.string "花朵竞相绽放。\p"
	.string "据说这些花朵能\n"
	.string "抚慰人们的情绪。$"

gTVWhatsNo1InHoennTodayText06::
	.string "{CHN}就在一天内，{STR_VAR_1}摘了\n"
	.string "{STR_VAR_2}个树果！\p"
	.string "{STR_VAR_1}的背包装满了\n"
	.string "树果，那位训练家之后\l"
	.string "连走路都困难了！$"

gTVWhatsNo1InHoennTodayText07::
	.string "{CHN}就在一天内，{STR_VAR_1}获得了\n"
	.string "{STR_VAR_2}个对战点数！\p"
	.string "后来看到{STR_VAR_1}\n"
	.string "在为是把这些对战点数\l"
	.string "换成酷酷的道具还是\l"
	.string "精美的室内装饰而苦恼。\p"
	.string "据说那位训练家在考虑时\n"
	.string "一直咧着嘴笑。$"

gTVWhatsNo1InHoennTodayText08::
	.string "{CHN}哇，真了不起！\p"
	.string "{STR_VAR_1}！\n"
	.string "你是今天的第一名训练家！\p"
	.string "观众们，从{STR_VAR_1}身上汲取力量吧！\n"
	.string "你也可以每天成为第一名！$"

TVSecretBaseSecrets_Text_Intro::
	.string "{CHN}秘密基地的秘密！\p"
	.string "训练家们在秘密基地的\n"
	.string "秘密中做什么？\p"
	.string "今天，我们要调查{STR_VAR_1}的\n"
	.string "秘密基地。\p"
	.string "哦？看来{STR_VAR_2}来\n"
	.string "拜访了。\p"
	.string "让我们窥视一下！\p"
	.string "{STR_VAR_2}会做什么呢？$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "{CHN}{STR_VAR_2}接下来会做什么？$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "{CHN}那么，{STR_VAR_2}接下来会做什么？$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "{CHN}最后，{STR_VAR_2}在离开前在{STR_VAR_1}的\n"
	.string "秘密基地里走了{STR_VAR_3}步。\l"
	.string "$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "{CHN}嗯……\p"
	.string "看来{STR_VAR_1}的秘密基地\n"
	.string "没能引起{STR_VAR_2}的兴趣……$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{CHN}{STR_VAR_2}似乎非常享受\n"
	.string "{STR_VAR_1}的秘密基地。$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{CHN}{STR_VAR_2}似乎成为了\n"
	.string "{STR_VAR_1}的\l"
	.string "秘密基地的超级粉丝。$"

TVSecretBaseSecrets_Text_Outro::
	.string "{CHN}观众们可能也想去\n"
	.string "{STR_VAR_1}的秘密基地看看。\p"
	.string "下次我们将探访另一个\n"
	.string "秘密基地！感谢收看！$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "{CHN}访客停下了！\p"
	.string "访客完全不动了！\p"
	.string "{STR_VAR_1}的秘密基地\n"
	.string "就那么无聊吗？$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "{CHN}访客停下了！\p"
	.string "访客完全不动了！\p"
	.string "是累了吗？\n"
	.string "访客是不是疲倦了？$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "{CHN}访客坐到了椅子上！\n"
	.string "访客坐下了！\p"
	.string "看那开心的表情！\p"
	.string "那把椅子一定非常舒服，\n"
	.string "才会有那样的反应！$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "{CHN}访客冲向了一个气球！\p"
	.string "它爆了！\n"
	.string "天哪，它破了！\p"
	.string "访客似乎被\n"
	.string "突如其来的声音吓到了！$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "{CHN}访客钻进了一个帐篷！\p"
	.string "访客在到处跑！\p"
	.string "天哪，访客在嬉戏！\p"
	.string "访客似乎被\n"
	.string "帐篷的大小吓到了！$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "{CHN}访客正在仔细观察\n"
	.string "一盆植物！\p"
	.string "访客有着\n"
	.string "令人惊讶的成熟品味！$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "{CHN}访客正在仔细观察\n"
	.string "一面金色之盾！\p"
	.string "访客的眼睛似乎\n"
	.string "因惊叹而发亮！$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "{CHN}访客正在仔细观察\n"
	.string "一面银色之盾！\p"
	.string "访客似乎看呆了！$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "{CHN}访客正在仔细观察\n"
	.string "一件玻璃装饰品！\p"
	.string "哦，不！\p"
	.string "访客在摸它！\p"
	.string "上面沾满了\n"
	.string "指纹……$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "{CHN}访客在看电视！\p"
	.string "看来是位电视迷！$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "{CHN}访客踩了一个泥球！\p"
	.string "访客看起来很兴奋！$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "{CHN}……哦？\p"
	.string "访客伸手\n"
	.string "到自己的背包里翻找！\p"
	.string "访客拿出了\n"
	.string "一个{STR_VAR_2}！\p"
	.string "看访客举起{STR_VAR_2}时\n"
	.string "微笑的样子！\p"
	.string "就像电视广告一样！$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "{CHN}访客抓起一个抱枕然后……$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "{CHN}……开始打它！\p"
	.string "访客是不是压力太大了？$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "{CHN}……紧紧抱住它！\p"
	.string "访客是不是因为\n"
	.string "什么而感到开心？$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "{CHN}访客正在和{STR_VAR_1}\n"
	.string "聊天！\p"
	.string "看来他们要\n"
	.string "进行一场对战！\p"
	.string "结果……\p"
	.string "是访客！\n"
	.string "访客在客场赢了！\p"
	.string "访客正在\n"
	.string "跳胜利舞！$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "{CHN}访客正在和{STR_VAR_1}\n"
	.string "聊天！\p"
	.string "看来他们要\n"
	.string "进行一场对战！\p"
	.string "结果……\p"
	.string "是{STR_VAR_1}！\n"
	.string "访客输了！\p"
	.string "访客看起来很沮丧！$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "{CHN}访客正在和{STR_VAR_1}\n"
	.string "聊天！\p"
	.string "看来他们要\n"
	.string "进行一场对战！\p"
	.string "结果……\p"
	.string "不，访客拒绝了！\p"
	.string "毕竟不会进行对战！\p"
	.string "访客是不是觉得{STR_VAR_1}\n"
	.string "没有吸引力？$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "{CHN}访客正目不转睛地\n"
	.string "盯着一张海报！\p"
	.string "海报合访客的\n"
	.string "心意吗？\p"
	.string "……但是……访客的凝视\n"
	.string "有点令人不安。$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "{CHN}访客踩到了一个音符垫！\p"
	.string "……嗯……\n"
	.string "访客作了一首有趣的曲子！$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "{CHN}访客正在和{STR_VAR_1}\n"
	.string "聊天！\p"
	.string "看来他们要\n"
	.string "进行一场对战！\p"
	.string "结果……\p"
	.string "是平局！\n"
	.string "什么都没解决！\p"
	.string "两位训练家似乎都\n"
	.string "非常失望！$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "{CHN}访客踩到了\n"
	.string "一个旋转垫！\p"
	.string "看来访客晕了！\p"
	.string "访客摇摇晃晃的！\n"
	.string "小心！$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "{CHN}访客伸手去拿\n"
	.string "一个沙之装饰品！\p"
	.string "哦！\p"
	.string "它碎了！\n"
	.string "散落了！\p"
	.string "访客看起来有些\n"
	.string "不好意思和内疚！$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "{CHN}访客正在用手指\n"
	.string "擦桌面！\p"
	.string "显然，访客无法忍受\n"
	.string "灰尘！\p"
	.string "访客对整洁\n"
	.string "有着惊人的要求！$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "{CHN}访客正盯着一块砖！\p"
	.string "也许访客在思考\n"
	.string "砖头上的东西。$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "{CHN}访客正走过\n"
	.string "实心板。\p"
	.string "访客一直低着头。\p"
	.string "访客似乎意外地\n"
	.string "胆小和谨慎！$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "{CHN}访客正目不转睛地\n"
	.string "看着栅栏！\p"
	.string "是不是有什么新陷阱的点子\n"
	.string "浮现在访客的脑海中？$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "{CHN}访客踩到了\n"
	.string "一个闪光垫！\p"
	.string "访客摆出各种\n"
	.string "姿势！\p"
	.string "访客似乎在幻想\n"
	.string "自己成为偶像！$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "{CHN}访客正目不转睛地\n"
	.string "盯着一个轮胎！\p"
	.string "访客是不是在想\n"
	.string "什么样的车会用到它？$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "{CHN}访客爬上了一个台座！\p"
	.string "访客从高处\n"
	.string "俯瞰{STR_VAR_1}的基地！\p"
	.string "然后……\p"
	.string "发出了一声咆哮！\n"
	.string "访客在咆哮！$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "{CHN}访客一头撞向了\n"
	.string "一扇易破门！\p"
	.string "访客在大笑！$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "{CHN}访客正在和玩偶说话！\p"
	.string "……有点诡异……$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "{CHN}访客正在爬\n"
	.string "滑梯的梯子！\p"
	.string "然后……\p"
	.string "访客滑了下来！\p"
	.string "看来访客玩得\n"
	.string "很开心！$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "{CHN}访客正在爬\n"
	.string "滑梯的梯子！\p"
	.string "然后……\p"
	.string "访客从梯子\n"
	.string "下去了！\p"
	.string "访客是不是突然害怕了？$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "{CHN}访客踩到了\n"
	.string "一个跳跃垫！\p"
	.string "访客跳了一下！\p"
	.string "跳了两下！\p"
	.string "成功落地！\p"
	.string "访客在鼓掌！\n"
	.string "多么精彩的独角戏！$"

gTVSafariFanClubText00::
	.string "{CHN}野生原野区粉丝俱乐部！\p"
	.string "记者：好了，伙计们！\n"
	.string "在扔沙球吗？\p"
	.string "我就在这个满是\n"
	.string "神奇宝可梦的野生原野区！\p"
	.string "让我们和这位\n"
	.string "野生原野区向导聊聊！\p"
	.string "好了，伙计，来访的训练家们\n"
	.string "看起来怎么样？$"

gTVSafariFanClubText01::
	.string "{CHN}向导：大家似乎都很\n"
	.string "投入。\p"
	.string "{STR_VAR_1}表现得尤其出色。\p"
	.string "刚才，{STR_VAR_1}抓到了\n"
	.string "{STR_VAR_2}只宝可梦。$"

gTVSafariFanClubText02::
	.string "{CHN}那位训练家很会用方块。\n"
	.string "那次用了{STR_VAR_2}，我想。$"

gTVSafariFanClubText03::
	.string "{CHN}那位训练家一个\n"
	.string "方块都没用！一个都没！\p"
	.string "真是个行家。$"

gTVSafariFanClubText04::
	.string "{CHN}记者：是这样吗？\p"
	.string "看来我们的伙计{STR_VAR_1}\n"
	.string "是位出色的野生原野区大师！\p"
	.string "向导：希望那位训练家能再来\n"
	.string "展示那精湛的技术。$"

gTVSafariFanClubText05::
	.string "{CHN}向导：似乎没人\n"
	.string "表现很好。\p"
	.string "{STR_VAR_1}运气尤其不好。\p"
	.string "刚才，那位训练家只\n"
	.string "抓到了{STR_VAR_2}只宝可梦。$"

gTVSafariFanClubText06::
	.string "{CHN}向导：似乎没人\n"
	.string "表现很好。\p"
	.string "{STR_VAR_1}运气尤其不好。\p"
	.string "刚才，那位训练家\n"
	.string "一只宝可梦都没抓到。一只都没有！$"

gTVSafariFanClubText07::
	.string "{CHN}那位训练家倒是会用方块。\n"
	.string "那次用了{STR_VAR_2}，我想。\p"
	.string "但是，哎呀，我真希望那位训练家\n"
	.string "能再熟练一些。$"

gTVSafariFanClubText08::
	.string "{CHN}我想那位训练家如果用方块的话\n"
	.string "运气会更好，\l"
	.string "但那次完全没用。$"

gTVSafariFanClubText09::
	.string "{CHN}记者：是这样吗？\p"
	.string "看来我们的伙计{STR_VAR_1}\n"
	.string "需要更多的野生原野区历练。\p"
	.string "向导：希望那位训练家\n"
	.string "能多来几次，熟练起来。$"

gTVSafariFanClubText10::
	.string "{CHN}记者：没错！\n"
	.string "面对挑战很重要！\p"
	.string "观众们，来野生原野区\n"
	.string "亲自挑战吧！\p"
	.string "下次再见！$"

ContestLiveUpdates_Text_Intro::
	.string "{CHN}「宝可梦选拔赛现场直播！」\p"
	.string "主持人：感谢收看！\p"
	.string "我们正在刚刚结束的\n"
	.string "{STR_VAR_1}会场\l"
	.string "进行现场直播。\p"
	.string "大厅里依然挤满了\n"
	.string "不愿离去的观众。\p"
	.string "观众：{STR_VAR_2}！\p"
	.string "观众：{STR_VAR_3}！\p"
	.string "主持人：如你所闻，这场选拔赛\n"
	.string "由{STR_VAR_3}的\l"
	.string "宝可梦{STR_VAR_2}获胜。\p"
	.string "观众：{STR_VAR_2}！\n"
	.string "你是最棒的！\p"
	.string "观众：{STR_VAR_3}！\n"
	.string "干得好！\p"
	.string "主持人：让我们听听粉丝们\n"
	.string "对这场选拔赛的看法。$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "{CHN}观众：那只{STR_VAR_2}在\n"
	.string "第一和第二次评审中都拿了第一！\p"
	.string "那只{STR_VAR_2}会继续赢下去的！$"

ContestLiveUpdates_Text_BetterRound2::
	.string "{CHN}观众：那只{STR_VAR_2}在\n"
	.string "第一次评审中表现不佳，\l"
	.string "但在第二次评审中大放异彩！\p"
	.string "那是一次奇迹般的逆转，\n"
	.string "为了那只{STR_VAR_2}。好耶！$"

ContestLiveUpdates_Text_EqualRounds::
	.string "{CHN}观众：那只{STR_VAR_2}在\n"
	.string "第一次和第二次评审中\l"
	.string "表现都很稳定。\p"
	.string "{STR_VAR_3}和那只{STR_VAR_2}，\n"
	.string "可不是普通的组合！$"

ContestLiveUpdates_Text_BetterRound1::
	.string "{CHN}观众：在{STR_VAR_1}方面，\n"
	.string "那只{STR_VAR_2}非常出色。\p"
	.string "不过希望下次\n"
	.string "能做出更好的评审表演。$"

ContestLiveUpdates_Text_GotNervous::
	.string "{CHN}观众：当那只{STR_VAR_2}紧张时，\n"
	.string "我忍不住\l"
	.string "为它大声加油。\p"
	.string "我想对那只\n"
	.string "{STR_VAR_2}说：“恭喜！”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "{CHN}观众：那只{STR_VAR_2}的评审表演\n"
	.string "连我都吓了一跳！\p"
	.string "{STR_VAR_2}，你太棒了！$"

ContestLiveUpdates_Text_UsedCombo::
	.string "{CHN}观众：那只{STR_VAR_2}的连击\n"
	.string "评审表演太惊人了！\p"
	.string "震撼到我了！$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "{CHN}观众：获胜的{STR_VAR_2}的\n"
	.string "评审表演让我的心怦怦直跳！$"

ContestLiveUpdates_Text_WasCool::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你真帅气！$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你真美丽！$"

ContestLiveUpdates_Text_WasCute::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你真可爱！$"

ContestLiveUpdates_Text_WasSmart::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你真聪明！$"

ContestLiveUpdates_Text_WasTough::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你真强壮！$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "{CHN}观众：获胜的{STR_VAR_2}的\n"
	.string "评审表演至今让我心跳加速！$"

ContestLiveUpdates_Text_VeryCool::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你是帅气的极致！$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你是最美丽的！$"

ContestLiveUpdates_Text_VeryCute::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你是可爱至极！$"

ContestLiveUpdates_Text_VerySmart::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你是聪明中的聪明！$"

ContestLiveUpdates_Text_VeryTough::
	.string "{CHN}{STR_VAR_2}！\n"
	.string "你是强壮中的强壮！$"

ContestLiveUpdates_Text_TookBreak::
	.string "{CHN}观众：即使当{STR_VAR_2}\n"
	.string "暂停评审表演休息时，\l"
	.string "我也无法把目光从它身上移开。\p"
	.string "我被那只{STR_VAR_2}迷住了。$"

ContestLiveUpdates_Text_GotStartled::
	.string "{CHN}观众：当{STR_VAR_2}被\n"
	.string "其他宝可梦的评审表演吓到时，\l"
	.string "我差点哭了出来。\p"
	.string "{STR_VAR_2}，你真坚强！\n"
	.string "干得好！$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "{CHN}观众：哦……\n"
	.string "那只{STR_VAR_2}的{STR_VAR_3}！\l"
	.string "{STR_VAR_2}的{STR_VAR_3}！\l"
	.string "{STR_VAR_2}的{STR_VAR_3}！\l"
	.string "怎么会这么精彩？$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "{CHN}主持人：好了，就是这样。这个地方\n"
	.string "充满了{STR_VAR_1}的粉丝！\p"
	.string "我还想提一下，另一只宝可梦，\n"
	.string "{STR_VAR_2}的{STR_VAR_3}，\l"
	.string "也吸引了我的注意。\p"
	.string "{STR_VAR_2}的{STR_VAR_3}……$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "{CHN}它因为紧张，在第二次评审中\n"
	.string "一次评审表演都没做成。\p"
	.string "下次，我希望看到这只\n"
	.string "{STR_VAR_1}至少做出一次评审表演。$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "{CHN}它在第一次和第二次\n"
	.string "评审中都垫底了。\p"
	.string "希望{STR_VAR_1}能重新训练这只\n"
	.string "{STR_VAR_2}，洗刷\l"
	.string "这次垫底的耻辱。$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "{CHN}它没能利用\n"
	.string "观众的兴奋，\l"
	.string "做出相应的评审表演。\p"
	.string "我们希望{STR_VAR_1}能学会如何\n"
	.string "感受观众的情绪，\l"
	.string "下次把他们的热情推向高潮。$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "{CHN}虽然在第一次评审中\n"
	.string "拿了第一，但它在第二次\l"
	.string "评审中的表演没能奏效。\p"
	.string "它遭受了屈辱的\n"
	.string "被逆转的失败。\p"
	.string "我敢肯定{STR_VAR_1}正在研究\n"
	.string "如何做出更有效的评审表演。$"

ContestLiveUpdates_Text_NeverExciting::
	.string "{CHN}在第二次评审中，\n"
	.string "观众从未被它的表演所打动。\p"
	.string "我们希望它能不再担心其他\n"
	.string "宝可梦，学会\l"
	.string "更多地迎合观众进行评审表演。$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "{CHN}它以微弱的差距\n"
	.string "输给了{STR_VAR_1}的{STR_VAR_2}。\p"
	.string "离胜利只有一步之遥却失败，\n"
	.string "一定很心痛。\p"
	.string "如果{STR_VAR_3}因为这个结果\n"
	.string "而哭泣，我也不会惊讶。$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "{CHN}它因为重复\n"
	.string "相同的评审表演而让评审失望。\p"
	.string "这在任何选拔赛中都是\n"
	.string "不可原谅的错误，宝可梦也付出了代价。\p"
	.string "{STR_VAR_1}应该为\n"
	.string "这次糟糕的表现感到内疚。$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{CHN}{STR_VAR_1}拼尽全力，\n"
	.string "但是……\p"
	.string "一切都白费了，最终垫底。\p"
	.string "{STR_VAR_1}应该从这次失败中学习，\n"
	.string "并把学到的知识派上用场。$"

ContestLiveUpdates_Text_Outro::
	.string "{CHN}我想用我们\n"
	.string "惯常的方式向获胜者告别来结束节目。\p"
	.string "这次是{STR_VAR_1}和\n"
	.string "那只{STR_VAR_2}！\p"
	.string "主持人：大家准备好了吗？\n"
	.string "大家一起！\p"
	.string "观众：{STR_VAR_1}！{STR_VAR_2}！\n"
	.string "恭喜你们！\l"
	.string "你们是选拔赛的获胜者！$"

gTVPokemonBattleUpdateText00::
	.string "{CHN}「宝可梦对战快讯！」\p"
	.string "为您带来宝可梦\n"
	.string "对战的最新结果！$"

gTVPokemonBattleUpdateText01::
	.string "{CHN}训练家{STR_VAR_1}和\n"
	.string "{STR_VAR_2}在一场\l"
	.string "{STR_VAR_3}对战中交锋。\p"
	.string "这场比赛以{STR_VAR_1}\n"
	.string "的胜利告终！$"

gTVPokemonBattleUpdateText02::
	.string "{CHN}在对战中，{STR_VAR_1}的\n"
	.string "{STR_VAR_2}使用{STR_VAR_3}\l"
	.string "成为了一股强大的力量！$"

gTVPokemonBattleUpdateText03::
	.string "{CHN}{STR_VAR_1}的{STR_VAR_2}表现不佳，\n"
	.string "真的很受伤。$"

gTVPokemonBattleUpdateText04::
	.string "{CHN}恭喜你的胜利，\n"
	.string "{STR_VAR_1}！\p"
	.string "至于战败的{STR_VAR_2}，\n"
	.string "希望你下次能有更好的结果！\p"
	.string "本期「宝可梦对战快讯！」\n"
	.string "就到这里。$"

gTVPokemonBattleUpdateText05::
	.string "{CHN}训练家{STR_VAR_1}和\n"
	.string "{STR_VAR_2}的队伍在一场多人对战中相遇。\p"
	.string "这场比赛以{STR_VAR_1}的队伍\n"
	.string "获胜告终。$"

gTVPokemonBattleUpdateText06::
	.string "{CHN}在对战中，{STR_VAR_1}队伍中的\n"
	.string "{STR_VAR_2}使用{STR_VAR_3}\l"
	.string "成为了一股强大的力量。$"

gTVPokemonBattleUpdateText07::
	.string "{CHN}{STR_VAR_2}队伍中{STR_VAR_3}\n"
	.string "的糟糕表现真的很受伤。\p"
	.string "恭喜你的队伍获胜，\n"
	.string "{STR_VAR_1}！\p"
	.string "至于战败的{STR_VAR_2}的队伍，\n"
	.string "希望你下次能有更好的结果！\p"
	.string "本期「宝可梦对战快讯！」\n"
	.string "就到这里。$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "{CHN}雅莉：哦！我们在这里发现了一位\n"
	.string "看起来很强的训练家！\p"
	.string "好，开机！\n"
	.string "开始采访吧。$"

GabbyAndTy_Text_GabbyIntro:
	.string "{CHN}雅莉：哦！你是{PLAYER}！嗨！\n"
	.string "还记得我们吗？\p"
	.string "能让我们看看你变强了多少吗？\n"
	.string "好，开始采访！$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "{CHN}雅莉：我的眼睛没骗我！\n"
	.string "我确实发现了一位惊人的训练家！$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "{CHN}雅莉：太厉害了！太厉害了！\n"
	.string "你是谁？！\p"
	.string "我发现你的时候，就\n"
	.string "知道会有大新闻！\p"
	.string "哦，让我解释一下。我们\n"
	.string "四处旅行，采访各种\l"
	.string "训练家。\p"
	.string "那么，你能抽出一点时间\n"
	.string "接受我们的采访吗？$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "{CHN}雅莉：“{STR_VAR_1}！”\p"
	.string "记得吗？这是上次你给我们的\n"
	.string "战斗总结台词。\p"
	.string "我永远不会忘记这样的话！$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "{CHN}上次我们对战时，你还\n"
	.string "没等我们反应过来就把我们打趴了……\p"
	.string "总之，你觉得怎么样？\n"
	.string "想再接受一次采访吗？$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "{CHN}上次我们对战时，你是不是\n"
	.string "朝我们扔了精灵球？\p"
	.string "我们惊呆了！所以我们\n"
	.string "把这件事告诉了所有人，\n"
	.string "真的是所有人！\p"
	.string "总之，你觉得怎么样？\n"
	.string "想再接受一次采访吗？$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "{CHN}上次我们对战时，你巧妙的\n"
	.string "道具技巧让我们吃了个大亏。\p"
	.string "总之，你觉得怎么样？\n"
	.string "想再接受一次采访吗？$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "{CHN}上次我们对战时，\n"
	.string "我们总算还有点面子。\p"
	.string "总之，你觉得怎么样？\n"
	.string "想再接受一次采访吗？$"

GabbyAndTy_Text_InterviewAgain:
	.string "{CHN}总之，你觉得怎么样？\n"
	.string "想再接受一次采访吗？$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "{CHN}你愿意？\n"
	.string "谢谢你！\p"
	.string "好，请你描述一下\n"
	.string "对我们这场对战的感受，\l"
	.string "但要简短有力。开始！$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "{CHN}雅莉：嗯，对！\n"
	.string "这总结太完美了！\p"
	.string "我觉得这会做成\n"
	.string "一档很棒的电视节目。\p"
	.string "有机会在电视上播出，\n"
	.string "所以记得找找看！\p"
	.string "好！\n"
	.string "我们会再见到你的！$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "{CHN}雅莉：哦……\p"
	.string "好，但不要放弃！\n"
	.string "我们会继续关注你的！$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "{CHN}雅莉：我们会继续\n"
	.string "关注你的！$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "{CHN}雅莉：哪里有宝可梦\n"
	.string "很多又很强的训练家吗？$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "{CHN}雅莉：哇，你真厉害！\p"
	.string "自从我们上次对战以来，\n"
	.string "你变强了很多——很多。\p"
	.string "我们发现你是位\n"
	.string "热门训练家，这判断没错。\p"
	.string "那么，你觉得怎么样？\n"
	.string "这次你愿意\l"
	.string "接受采访吗？$"

GabbyAndTy_Text_GabbyDefeat:
	.string "{CHN}雅莉：那是一场激烈的战斗！\n"
	.string "你都拍下来了吗？$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "{CHN}阿宏：嘿，看这里！一位\n"
	.string "看起来很强的训练家，\l"
	.string "居然在这里！\n"
	.string "摄像机开着！$"

GabbyAndTy_Text_TyIntro:
	.string "{CHN}阿宏：嘿，看这里！\n"
	.string "我记得你！\p"
	.string "这场对战我会用这台\n"
	.string "摄像机全部拍下来！$"

GabbyAndTy_Text_TyPostBattle:
	.string "{CHN}阿宏：你真是个天才！\n"
	.string "我拍到了一些精彩画面！$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "{CHN}阿宏：你只有这一只\n"
	.string "宝可梦吗？\p"
	.string "如果你有更多宝可梦，\n"
	.string "拍出来的画面会更好，但是……$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "{CHN}阿宏：没错，我们确实发现了一位\n"
	.string "热门训练家。\n"
	.string "这对我们来说是个大独家！$"

GabbyAndTy_Text_TyDefeat:
	.string "{CHN}阿宏：没错，我都拍下来了。\n"
	.string "整场对战都在摄像机里。$"

gTVInSearchOfTrainersText00::
	.string "{CHN}寻找训练家……\p"
	.string "雅莉：嗨！今天我来到了\n"
	.string "{STR_VAR_1}附近。\p"
	.string "我们正在寻找这一领域\n"
	.string "有潜力的新星。\p"
	.string "今天，我们把镜头对准了\n"
	.string "训练家{PLAYER}。\p"
	.string "这位训练家身上有\n"
	.string "某种特质引起了我们的兴趣。$"

gTVInSearchOfTrainersText01::
	.string "{CHN}我们以前和{PLAYER}对战过，\n"
	.string "我们可以证明，这位训练家\l"
	.string "确实比以前变强了。\p"
	.string "当我们发现这位训练家时，\n"
	.string "我就知道我们找到了特别的人！$"

gTVInSearchOfTrainersText02::
	.string "{CHN}判断一位训练家有多强\n"
	.string "最好的方法……\p"
	.string "嗯，最快的方法就是对战。\n"
	.string "于是我们开始了调查！\p"
	.string "…… …\p"
	.string "就这样，我们\n"
	.string "与{PLAYER}对战了。\p"
	.string "我们被完全压制，\n"
	.string "被碾压，被扔到一边！\p"
	.string "{PLAYER}强得可怕……\p"
	.string "以下是我们与\n"
	.string "这位特色训练家对战后的感想。$"

gTVInSearchOfTrainersText03::
	.string "{CHN}{STR_VAR_1}和\n"
	.string "{STR_VAR_3}的组合太神了！\p"
	.string "他们——{STR_VAR_1}和\n"
	.string "{STR_VAR_3}——在战斗中\l"
	.string "无私地互相支援的样子……\p"
	.string "那真是令人惊叹的景象！\p"
	.string "{STR_VAR_2}是训练家\n"
	.string "在我们对战中最后使用的招式。\p"
	.string "{STR_VAR_2}这个招式\n"
	.string "是{STR_VAR_1}和{STR_VAR_3}\n"
	.string "友谊的象征！$"

gTVInSearchOfTrainersText04::
	.string "{CHN}……由于这次相遇，\n"
	.string "我对自己失去了信心。\p"
	.string "我们还没来得及发动一次\n"
	.string "攻击就被打败了。\l"
	.string "哦……抽泣……\p"
	.string "尽管如此，{PLAYER}的对战\n"
	.string "还是值得一看的。\p"
	.string "我建议自信的训练家\n"
	.string "去挑战{PLAYER}。$"

gTVInSearchOfTrainersText05::
	.string "{CHN}只有一句话要说。\n"
	.string "千万不要在训练家对战中\l"
	.string "扔精灵球！\p"
	.string "{PLAYER}确实很强，但\n"
	.string "显然不懂基本规则。\p"
	.string "对我们的电视观众，我有一个请求。\p"
	.string "如果你看到{PLAYER}，\n"
	.string "请提醒这位训练家！$"

gTVInSearchOfTrainersText06::
	.string "{CHN}{PLAYER}很擅长\n"
	.string "预判对手的行动。\p"
	.string "道具使用的时机\n"
	.string "非常有效！$"

gTVInSearchOfTrainersText07::
	.string "{CHN}说实话，我以为\n"
	.string "我自己还挺厉害的。\p"
	.string "虽然我们最终输了，但我们\n"
	.string "确实有一场激烈的对抗。\p"
	.string "但如果你连我都打不过，\n"
	.string "那你还有很长的路要走，{PLAYER}！$"

gTVInSearchOfTrainersText08::
	.string "{CHN}战斗结束后，我们请{PLAYER}\n"
	.string "做一个简短的总结。\p"
	.string "训练家回答说：“{STR_VAR_1}。”\p"
	.string "{PLAYER}的宝可梦{STR_VAR_2}和\n"
	.string "{STR_VAR_3}……\l"
	.string "还有“{STR_VAR_1}”……\p"
	.string "嗯！很有深度！这句话背后\n"
	.string "有深刻的含义！\p"
	.string "不奇怪——好的训练家\n"
	.string "总能说出好的话。\p"
	.string "今天就到这里！\n"
	.string "我们下期节目再见！$"

ContestLadyShow_Text_Intro::
	.string "{CHN}「宝可梦选拔赛现场直播！」\p"
	.string "主持人：抱歉打断正常节目，\n"
	.string "感谢收看！\p"
	.string "我们正在刚刚结束的\n"
	.string "{STR_VAR_1}现场\l"
	.string "为您现场直播！\p"
	.string "观众们：?!!!!\p"
	.string "主持人：哦！看来选拔赛的\n"
	.string "参赛者们朝这边来了！\p"
	.string "我会试着为电视机前的\n"
	.string "观众们做一次即兴采访！\p"
	.string "观众们：?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "{CHN}主持人：打扰一下！\n"
	.string "感谢收看我们的现场直播！\p"
	.string "请允许我祝贺你的胜利？\p"
	.string "今天这场漂亮的胜利，\n"
	.string "关键是什么？\p"
	.string "美丽小姐：今天我和我的{STR_VAR_2}\n"
	.string "都尽了最大的努力！\p"
	.string "但如果没有大家在选拔赛前\n"
	.string "给予我们的帮助，\l"
	.string "我肯定我们做不到！\p"
	.string "主持人：你有什么特别的人\n"
	.string "想与之分享这份喜悦吗？\l"
	.string "让我们现场听听！\p"
	.string "美丽小姐：嘿，那边！\p"
	.string "{STR_VAR_3}！你在看吗？\n"
	.string "我们做到了！\l"
	.string "谢谢你！$"

ContestLadyShow_Text_Lost::
	.string "{CHN}主持人：打扰一下！\n"
	.string "感谢收看我们的现场直播！\p"
	.string "你一定对那个结果\n"
	.string "很失望吧。你有什么想说的吗？\p"
	.string "美丽小姐：太让人心碎了……\n"
	.string "我和我的{STR_VAR_2}，我们都尽力了……\p"
	.string "但我觉得我辜负了\n"
	.string "所有一直支持我们的人。\p"
	.string "主持人：虽然不想说，但这只宝可梦的\n"
	.string "色泽稍微差了点。\p"
	.string "美丽小姐：{STR_VAR_3}，对不起……\n"
	.string "下次我会做得更好，我发誓……\l"
	.string "……抽泣……哇啊啊！\p"
	.string "观众们：看到了吗？\n"
	.string "可怜的女孩！\p"
	.string "主持人：呃……哎呀……\p"
	.string "呃……今天的时间就到这里了！\n"
	.string "感谢收看！$"

ContestLadyShow_Text_LostBadly::
	.string "{CHN}主持人：打扰一下！\n"
	.string "感谢收看我们的现场直播！\p"
	.string "你的选拔赛表现怎么样？\p"
	.string "美丽小姐：什么都不顺利……\n"
	.string "不知道为什么，我的{STR_VAR_2}\l"
	.string "就是吸引不到人气。\p"
	.string "主持人：虽然不想说，但这只宝可梦的\n"
	.string "色泽稍微差了点。\p"
	.string "美丽小姐：…… …… …… …… … …\n"
	.string "……抽泣……哇啊啊！\p"
	.string "观众们：看到了吗？\n"
	.string "可怜的女孩！\p"
	.string "主持人：呃……哎呀……\p"
	.string "呃……今天的时间就到这里了！\n"
	.string "感谢收看！$"