.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "{CHN}哦？你想和老头子一起\n"
	.string "做些{POKEBLOCK}S吗？$"

BerryBlender_Text_Excellent:
	.string "{CHN}太好了！$"

BerryBlender_Text_MadeOldTimerSad:
	.string "{CHN}哦……\n"
	.string "你让老头子伤心了……$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "{CHN}你知道怎么做{POKEBLOCK}吗？$"

BerryBlender_Text_LetsBerryBlender:
	.string "{CHN}那么，我们开始吧！\p"
	.string "来用树果搅拌机吧！$"

BerryBlender_Text_ExplainBerryBlending:
	.string "{CHN}好吧，那稍微说明一下。\p"
	.string "哦，别担心，非常简单。\p"
	.string "当搅拌机的箭头转到你的标记时，\n"
	.string "只要按下A键就行。\p"
	.string "你只要这样做就好。\n"
	.string "试一下就知道有多简单了。$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "{CHN}哦？\n"
	.string "你没有树果吗？\p"
	.string "如果没有树果的话，\n"
	.string "就没法做{POKEBLOCK}S了。$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "{CHN}哎呀，那可不行啊。\p"
	.string "如果你不嫌弃剩下的，可以\n"
	.string "拿我一个树果。\p"
	.string "那样的话，我们就可以用树果搅拌机\n"
	.string "一起做{POKEBLOCK}S了。$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "{CHN}如果我还有剩下的树果，\n"
	.string "我很乐意给你一个……\p"
	.string "但是，今天我没有多余的了。\n"
	.string "我们下次再一起做吧。$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "{CHN}但是你的{POKEBLOCK}盒已经满了。\p"
	.string "你应该先用掉一些{POKEBLOCK}S，\n"
	.string "然后再来找我。$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "{CHN}但是你没有{POKEBLOCK}盒。\p"
	.string "你应该先去拿一个{POKEBLOCK}盒，\n"
	.string "然后再来找我。$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "{CHN}我们快开始搅拌吧！$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "{CHN}我会做出什么样的{POKEBLOCK}呢？\n"
	.string "好期待啊！$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "{CHN}你好啊！你想和我们一起\n"
	.string "做{POKEBLOCK}S吗？$"

BerryBlender_Text_Okay:
	.string "{CHN}好的！$"

BerryBlender_Text_ThatsTooBad:
	.string "{CHN}那太可惜了……\p"
	.string "不过，无论你什么时候\n"
	.string "想搅拌，我们都在这里！$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "{CHN}当然，你知道怎么\n"
	.string "搅拌{POKEBLOCK}S吧？$"

BerryBlender_Text_LetsBerryBlender2:
	.string "{CHN}那么，我们开始吧！\p"
	.string "来用树果搅拌机吧！$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "{CHN}好的！\n"
	.string "让我来给你说明一下！\p"
	.string "当旋转的搅拌机的箭头\n"
	.string "转到你的标记时，只要按\l"
	.string "A键就行。\p"
	.string "只需要这样做。\n"
	.string "很简单吧？$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "{CHN}哦，等一下……\n"
	.string "你没有树果。\p"
	.string "没有树果的话，\n"
	.string "就没法做{POKEBLOCK}S了……\p"
	.string "无论你什么时候拿到树果\n"
	.string "想搅拌，我们都在这里。$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "{CHN}哦，等一下……\n"
	.string "你的{POKEBLOCK}盒已经满了。\p"
	.string "你应该先用掉一些{POKEBLOCK}S，\n"
	.string "然后再回来。$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "{CHN}哦，等一下……\n"
	.string "你没有{POKEBLOCK}盒。\p"
	.string "你应该先去拿一个{POKEBLOCK}盒，\n"
	.string "然后再回来。$"

/* Unused*/
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "{CHN}哦，你好！你想和我们\n"
	.string "一起做{POKEBLOCK}S吗？$"

BerryBlender_Text_OhDear:
	.string "{CHN}哎呀！$"

BerryBlender_Text_LeftUsInShock:
	.string "{CHN}哎呀，天哪……\p"
	.string "你让我们大吃一惊！$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "{CHN}你当然知道怎么\n"
	.string "做{POKEBLOCK}S吧？$"

BerryBlender_Text_LetsBerryBlender3:
	.string "{CHN}好的，亲爱的！\n"
	.string "我们开始吧！\p"
	.string "来用树果搅拌机吧！$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "{CHN}哎呀！\p"
	.string "那我就好好给你说明一下。\p"
	.string "当搅拌机的箭头转到你的标记时，\n"
	.string "按下A键就行。\p"
	.string "只需要这样做。\n"
	.string "很简单吧？$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "{CHN}你没有树果，\n"
	.string "对吧？\p"
	.string "如果没有树果的话，\n"
	.string "就没法做{POKEBLOCK}S了。\p"
	.string "我们会一直在做{POKEBLOCK}S，\n"
	.string "等你拿到一两个树果后，\l"
	.string "我们一起做吧。$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "{CHN}看起来你的{POKEBLOCK}盒\n"
	.string "已经满了。\p"
	.string "你应该先用掉一些{POKEBLOCK}S，\n"
	.string "然后再回来。$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "{CHN}看起来你还没有\n"
	.string "{POKEBLOCK}盒。\p"
	.string "你需要先去拿一个{POKEBLOCK}盒，\n"
	.string "然后再回来。$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "{CHN}好的！今天就是我\n"
	.string "刷新搅拌机速度记录的日子！$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "{CHN}哎呀！\n"
	.string "你看起来很擅长搅拌呢。\l"
	.string "要不要加入我们？$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "{CHN}我要做出美味的{POKEBLOCK}S，\n"
	.string "让我的宝可梦变得更可爱。$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "{CHN}将和朋友们一起用树果搅拌机\n"
	.string "用树果做出{POKEBLOCK}S。\p"
	.string "在和朋友们连接之前\n"
	.string "可以保存游戏吗？$"

BerryBlender_Text_SearchingForFriends:
	.string "{CHN}正在寻找你的朋友……\n"
	.string "…… B键：取消$"

BerryBlender_Text_Player1Arrived:
	.string "{CHN}{STR_VAR_1}来了。$"

BerryBlender_Text_Player1And2Arrived:
	.string "{CHN}{STR_VAR_1}和{STR_VAR_2}来了。$"

BerryBlender_Text_AllPlayersArrived:
	.string "{CHN}{STR_VAR_1}、{STR_VAR_2}和\n"
	.string "{STR_VAR_3}来了。$"

BerryBlender_Text_NoBerriesLink:
	.string "{CHN}你没有树果。\n"
	.string "无法使用树果搅拌机。$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "{CHN}你的{POKEBLOCK}盒已经满了。\n"
	.string "无法使用树果搅拌机。$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "{CHN}你没有{POKEBLOCK}盒。\n"
	.string "无法使用树果搅拌机。$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "{CHN}我喜欢做{POKEBLOCK}S。\p"
	.string "我总是随身带着树果。$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "{CHN}如果你愿意的话，我们可以\n"
	.string "用树果搅拌机一起\l"
	.string "做些{POKEBLOCK}S。$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "{CHN}哦？\n"
	.string "你没有树果吗？\p"
	.string "哎呀，那可不行啊。\p"
	.string "如果你不嫌弃剩下的，可以\n"
	.string "拿我一个树果。$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "{CHN}我们用它一起做{POKEBLOCK}S吧，\n"
	.string "用树果搅拌机。$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "{CHN}哦？\n"
	.string "你没有树果吗？\p"
	.string "如果我还有剩下的，我很乐意\n"
	.string "给你一个……\p"
	.string "但是，今天我没有多余的了。\n"
	.string "非常抱歉。$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_BLEND_MASTER, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_2_PARTICIPANT, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_2_LEADER, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_CONTEST_LOBBY_BLENDER_3_LEADER
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_1, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_CONTEST_LOBBY_BLENDER_3_PARTICIPANT_2, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  /* number of opponents, 0 indicates Link*/
	fadescreen FADE_TO_BLACK
	removeobject 240 /* Unclear where these local IDs come from,*/
	removeobject 239 /* but presumably they'd be the 4 link players*/
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
