FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "{CHN}说起宝可梦图鉴，\n"
	.string "我想起了一件事。\p"
	.string "我在寻找稀有石头的时候，\n"
	.string "遇到了一位叫大吾的训练家。\p"
	.string "哎呀，他带着\n"
	.string "一些非常厉害的宝可梦。\p"
	.string "它们不仅稀有，\n"
	.string "而且被训练到了可怕的程度！\p"
	.string "他甚至可能比\n"
	.string "这座城市的道馆馆主还要强……$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "{CHN}你手里那个是什么？\p"
	.string "…… …… …… …… ……\p"
	.string "哦，叫宝可梦图鉴吗？\n"
	.string "真了不起！$"
