SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "{CHN}让你见识一下我从馆主亚当\n"
	.string "那里学到的精妙技巧！$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "{CHN}请原谅我，亚当……$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "{CHN}看看把所有地板砖\n"
	.string "都踩碎会怎样。$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "{CHN}你大老远跑来，但不会\n"
	.string "见到亚当的。\p"
	.string "如果你输给我，就见不到！$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "{CHN}你真厉害！\n"
	.string "我被你可爱的外表骗了！$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "{CHN}你可能足够厉害，\n"
	.string "不会被亚当一击击败。$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "{CHN}亚当指挥\n"
	.string "对战的样子……\p"
	.string "那份美丽让我\n"
	.string "成为了训练家。$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "{CHN}你的对战比我\n"
	.string "更加美丽……$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "{CHN}你对战中展现的优雅\n"
	.string "太棒了。\p"
	.string "啊……能遇到宝可梦\n"
	.string "真是太幸运了。$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "{CHN}我该教教你对战\n"
	.string "有多残酷。$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "{CHN}哦。\n"
	.string "你很强。$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "{CHN}告诉你一个好消息。\p"
	.string "如果你想见到亚当，你需要\n"
	.string "把每块地板砖都走一次。$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "{CHN}丰缘地区最高水平的\n"
	.string "宝可梦道馆……\p"
	.string "那就是琉璃道馆。$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "{CHN}你的等级真高啊！$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "{CHN}与其满足于在强大的道馆里，\n"
	.string "我觉得在其他地方修炼\l"
	.string "会让你变得更强。\l"
	.string "但最重要的是，看起来更有趣。$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "{CHN}我和亚当一起\n"
	.string "训练宝可梦。\p"
	.string "别以为我好欺负。$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "{CHN}我输了……$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "{CHN}我觉得你很有潜力。\n"
	.string "要不要留下来和我们一起训练？$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "{CHN}在冰上优雅地滑行\n"
	.string "不越线……\p"
	.string "能展现那样表现的训练家\n"
	.string "一定优雅又美丽！$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "{CHN}喂，你说什么？！$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "{CHN}这很明显，但作为训练家\n"
	.string "有多强，和你的年龄\l"
	.string "毫无关系。$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "{CHN}和宝可梦在一起的时候，\n"
	.string "时间飞逝，还没来得及说“哎呀”就过去了。$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "{CHN}哎呀！$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "{CHN}真希望我能在说“哎呀”之前\n"
	.string "就忘掉那些没希望的事。$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "{CHN}如果你愿意，\n"
	.string "我可以用很稀有的宝可梦对战。$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "{CHN}哦，好了！你好好看了\n"
	.string "我的宝可梦吗？$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "{CHN}我来这座道馆是因为亚当\n"
	.string "夸奖了我可爱的宝可梦。\p"
	.string "啊，要是我年轻时\n"
	.string "就遇到亚当就好了……$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "{CHN}咯咯……\n"
	.string "你冷酷的表情真迷人。$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "{CHN}哎呀。\n"
	.string "我对你太手下留情了。$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "{CHN}你连亚当的一根手指\n"
	.string "都碰不到吧，咯咯……$"

