LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "{CHN}这颗星球上最大的谜团，\n"
	.string "都藏在海底深处。\p"
	.string "有人这么说过，但我也不知道……$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "{CHN}在幕幕市和琉璃市之间，\n"
	.string "有一条很深的海底沟壑。\p"
	.string "反正有人是这么告诉我的。$"
